// GET /artwork.jpg — permanent redirect to the real cover art.
//
// `artwork_url` pointed at this path for the podcast's entire life, but the
// file was never created: not in git, not in R2. Every RSS item already
// published references it, and podcast clients cache feed artwork by URL, so
// the path has to keep working rather than simply moving to the PNG.
//
// 301 rather than serving the bytes here: the art is a static asset now
// (site/artwork.png, generated by scripts/make_artwork.py), and redirecting
// keeps one copy rather than two.

export async function onRequest() {
  return Response.redirect('https://podcast.mingli.world/artwork.png', 301);
}
