// Reuse the podcast's supported login/session endpoints. No credentials or signing secret here.
const ORIGIN='https://podcast.mingli.world',COOKIE='mingli_video_auth';
const common={'Cache-Control':'private, no-store','Vary':'Cookie','X-Content-Type-Options':'nosniff','Referrer-Policy':'strict-origin-when-cross-origin'};
const json=(body,status=200,extra={})=>new Response(JSON.stringify(body),{status,headers:{...common,'Content-Type':'application/json',...extra}});
const cookieToken=request=>(request.headers.get('Cookie')||'').split(';').map(x=>x.trim()).find(x=>x.startsWith(COOKIE+'='))?.slice(COOKIE.length+1);
function cookie(token,logout=false){return `${COOKIE}=${token}; Path=/; Max-Age=${logout?0:31536000}; HttpOnly; Secure; SameSite=Lax`}
const LOGIN=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Mingli Video · Sign in</title><style>body{margin:0;min-height:100dvh;display:grid;place-items:center;background:#121b31;color:#f4f7ff;font:16px system-ui}main{width:min(340px,calc(100% - 48px));padding:24px}h1{font-size:30px}p{color:#b9c5df;line-height:1.5}label{display:block;margin:20px 0 8px}input,button{box-sizing:border-box;width:100%;font:inherit;border:1px solid #455675;border-radius:10px;padding:14px;background:#1a2840;color:#f4f7ff}button{margin-top:24px;background:#8ec9ff;color:#121b31;cursor:pointer}input:focus-visible,button:focus-visible{outline:3px solid #8ec9ff;outline-offset:3px}#error{color:#ffbfd7}</style></head><body><main><h1>mingli video</h1><p>Sign in with your existing podcast credentials.</p><form method="post" action="/api/login"><label for="username">Username</label><input id="username" name="username" autocomplete="username" required><label for="password">Password</label><input id="password" name="password" type="password" autocomplete="current-password" required><button>Sign in</button></form><p id="error" role="alert">__ERROR__</p></main></body></html>`;
const login=(error='',status=200)=>new Response(LOGIN.replace('__ERROR__',error),{status,headers:{...common,'Content-Type':'text/html; charset=utf-8','Content-Security-Policy':"default-src 'none'; style-src 'unsafe-inline'; form-action 'self'; base-uri 'none'; frame-ancestors 'none'"}});
export async function authorize(token,fetcher=fetch){if(!token||!/^[a-f0-9]{64}$/.test(token))return false;try{const r=await fetcher(ORIGIN+'/',{redirect:'manual',headers:{Cookie:`mingli_auth=${token}`},signal:AbortSignal.timeout(8000)});const okay=r.status===200&&r.headers.get('Content-Type')?.includes('text/html');await r.body?.cancel();return !!okay}catch{return false}}
export async function onRequest({request,next},fetcher=fetch){const url=new URL(request.url);const path=url.pathname;
 if(path==='/api/logout'&&request.method==='POST'){return new Response(null,{status:303,headers:{...common,'Set-Cookie':cookie('',true),Location:'/login'}})}
 if(path==='/api/login'&&request.method==='POST'){
  const origin=request.headers.get('Origin');if(origin&&origin!==url.origin)return json({error:'Invalid request origin'},403);
  let body;try{body=request.headers.get('Content-Type')?.includes('application/json')?await request.json():Object.fromEntries(await request.formData())}catch{return login('Invalid request.',400)}
  if(typeof body.username!=='string'||typeof body.password!=='string'||body.username.length>100||body.password.length>256)return login('Username and password required.',400);
  try{const r=await fetcher(ORIGIN+'/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:body.username,password:body.password}),redirect:'manual',signal:AbortSignal.timeout(8000)});const token=r.headers.get('Set-Cookie')?.match(/(?:^|,\s*)mingli_auth=([a-f0-9]{64})(?:;|$)/)?.[1];await r.body?.cancel();if(r.status!==200||!token)return login('Sign-in failed. Check your podcast credentials.',401);if(!await authorize(token,fetcher))return login('Sign-in could not be verified. Try again later.',503);return new Response(null,{status:303,headers:{...common,'Set-Cookie':cookie(token),Location:'/'}})}catch{return login('Sign-in is temporarily unavailable. Try again later.',503)}
 }
 if(path==='/login'){if(await authorize(cookieToken(request),fetcher))return new Response(null,{status:302,headers:{...common,Location:'/'}});return login()}
 if(!await authorize(cookieToken(request),fetcher)){if(path==='/'||request.headers.get('Sec-Fetch-Dest')==='document')return new Response(null,{status:303,headers:{...common,Location:'/login'}});return json({error:'Sign-in required'},401)}
 const response=await next();const headers=new Headers(response.headers);for(const[k,v]of Object.entries(common))headers.set(k,v);return new Response(response.body,{status:response.status,statusText:response.statusText,headers});
}
