import json
p='site/content.json';d=json.load(open(p))
rows=[
('huang-inference-2026','Jensen Huang','NVIDIA founder and CEO','Useful intelligence per watt','NVIDIA GTC Keynote 2026','2026-03-16','Event date',['Infrastructure','Product'],'Huang frames inference around constrained power, token throughput and response speed.','Conditional outlook','If inference demand grows, system efficiency may matter as much as model capability. This is not a guaranteed market outcome.','Measure cost per successful task alongside latency and quality. Study inference serving.','https://www.youtube.com/watch?v=jw_o0xr8MWU&t=3668s','https://www.nvidia.com/gtc/session-catalog/sessions/gtc26-s81595/','Publisher automated transcript anchor 01:01:08; 01:01:08–01:02:24 discusses inference trade-offs. YouTube alignment and clip end unverified.','NVIDIA vendor keynote. Commercial incentives matter; automated transcript may contain errors.'),
('wang-feedback-2026','Alexandr Wang','Meta superintelligence lab leader; Scale AI founder at the time','The agent opportunity is the feedback loop','This is a Once-in-a-Civilization Opportunity','2026-07-29','Publisher transcript date',['Agents','Product','Data'],'Wang describes agents improving measurable outcomes through repeated feedback and coordination.','Conditional outlook','A workflow with measurable feedback may suit a bounded agent loop. Internal results do not establish workforce-replacement outcomes.','Pick one measurable workflow. Define success and failure, then compare a bounded loop against a baseline.','https://www.youtube.com/watch?v=sJ4VJWycX9M&t=1611s','https://www.ycrootaccess.com/p/alexandr-wang-building-a-frontier','Publisher chapter 26:51: The Biggest Opportunity in AI Today. Exact claim onset and clip end unverified.','Y Combinator interview with Garry Tan. Internal Meta anecdotes are not independent benchmarks. Recording day and exact video upload date unverified.'),
('amodei-adoption-2026','Dario Amodei','Anthropic CEO at the time','Capability and adoption run on different clocks','We are near the end of the exponential','2026-02-13','Publisher episode date',['Strategy','Product','Infrastructure'],'Amodei distinguishes technical capability forecasts from uncertain economic adoption and compute-investment timing.','Our interpretation','A model milestone alone is weak evidence for a revenue timeline. His capability timelines are forecasts.','Investigate procurement, integration, trust and workflow barriers before assuming benchmark gains create demand.','https://www.youtube.com/watch?v=n1E9IZfvGMA&t=2780s','https://www.dwarkesh.com/p/dario-amodei-2','Publisher chapter 46:20, compute-investment discussion. Exact short-clip boundaries unverified.','Dwarkesh challenges aggressive AI timelines and cautious compute commitments. Recording date undisclosed in inspected evidence.'),
('karpathy-autonomy-2025','Andrej Karpathy','AI researcher and educator; former Tesla AI director','Build an autonomy dial','Software Is Changing (Again)','2025-06-18','Video publication date',['Agents','Product','Learning'],'Karpathy describes powerful but fallible LLMs and partially autonomous products that keep people in the loop.','Our interpretation','A visible review loop may create dependable value. This is a design hypothesis to test, not a performance guarantee.','Prototype draft, review and execute modes. Measure review time and accepted results.','https://www.youtube.com/watch?v=LCEmiRjPEtQ&t=1102s','https://www.youtube.com/watch?v=LCEmiRjPEtQ','Official chapter 18:22: partial autonomy. Publisher description and speaker notes inspected; full transcript not inspected.','Y Combinator AI Startup School, San Francisco, June 17, 2025. Conceptual product-design talk; no exact clip range claimed.'),
('ng-concrete-2025','Andrew Ng','DeepLearning.AI and AI Fund founder','Make the idea concrete before making it fast','Building Faster with AI','2025-07-10','Video publication date',['Building','Product','Learning'],'Ng emphasizes concrete product ideas and human judgment as AI accelerates implementation.','Our interpretation','Faster building increases the value of choosing and testing the right problem. No universal productivity multiplier follows.','Write a specific user, task and success criterion before prototyping. Combine implementation with customer discovery.','https://www.youtube.com/watch?v=RNJCfif1dPY&t=292s','https://www.youtube.com/watch?v=RNJCfif1dPY','Official chapter 04:52: Concrete Ideas for Faster Execution. Description and chapters inspected; full transcript not inspected.','Startup School talk. Official video description identifies June 17, 2025 as event date. Exact clip boundaries unverified.'),
('fei-spatial-2025','Fei-Fei Li','Stanford professor and World Labs co-founder at the time','The next interface may be the physical world','Spatial Intelligence is the Next Frontier in AI','2025-07-01','Video publication date',['Robotics','Learning','World models'],'Li argues for intelligence that models the three-dimensional world, beyond language.','Conditional outlook','Spatial systems could create opportunities beyond chat. Reliability, timelines and commercial winners remain uncertain.','Explore vision, geometry and simulation. Test a narrow spatial task against real-world ground truth.','https://www.youtube.com/watch?v=_PioN-CpOP0&t=860s','https://www.youtube.com/watch?v=_PioN-CpOP0','Official chapter 14:20: Why Spatial Intelligence Is Harder Than Language. Description inspected; full transcript not inspected.','Y Combinator fireside discussion, San Francisco, June 16, 2025 according to official description. Li has a commercial interest in spatial AI.'),
('hassabis-evaluation-2025','Demis Hassabis','Google DeepMind co-founder and CEO at the time','A brilliant answer is not general intelligence','Lex Fridman Podcast #475','2025-07-23','Video publication date',['Evaluation','Product','Learning'],'Hassabis emphasizes broad, consistent capability and novel discoveries when discussing his criteria for AGI.','Our interpretation','A strong demonstration does not establish reliable performance across a whole workflow. Test gaps as well as highlights.','Build evaluations around failure modes, domain coverage and distribution shift.','https://www.youtube.com/watch?v=-HzgcbRXUK8&t=3186s','https://lexfridman.com/demis-hassabis-2-transcript','Publisher transcript anchors 53:06 and 55:14 onward. Video alignment and clip end unverified.','Personal criteria for AGI in a long interview, not a universally agreed definition. Recording date not verified.')]
new=[]
for i,(id,speaker,role,title,sourceTitle,date,dateLabel,tags,summary,lens,interp,opp,url,evidence,locator,context) in enumerate(rows):
 new.append(dict(id=id,title=title,tags=tags,summary=summary,lens=lens,interpretation=interp,opportunityLabel='Practical experiment · our suggestion',opportunity=opp,source=dict(speaker=speaker,role=role,title=sourceTitle,date=date,dateLabel=dateLabel,url=url,evidence=evidence,locator=locator,context=context),quality=dict(useful=5-i*.05,novel=4.9-i*.05,credible=4.6 if i<3 or i==6 else 4.2,influence=4.8),reviewed='2026-10-02',format='Original summary card',seconds=35))
d['cards']=new+[c for c in d['cards'] if c['id'] not in {n['id'] for n in new}];d['refresh']='Reviewed launch edition: 2026 current sources and historical context. Daily candidate discovery never auto-publishes claims.';json.dump(d,open(p,'w'),indent=2)
