import json
sources={
'gtc':dict(speaker='Jensen Huang',role='NVIDIA founder and CEO at the time',title='GTC 2024 keynote',date='2024-03-18',dateLabel='Talk date',url='https://www.nvidia.com/en-us/on-demand/session/gtc24-s62542/',evidence='https://blogs.nvidia.com/blog/2024-gtc-keynote/',context='Company keynote announcing commercial NVIDIA products. Vendor claims and projections are not independent benchmarks.',locator='Official keynote recap; section headings shown below.'),
'scale21':dict(speaker='Alexandr Wang',role='Scale AI founder and CEO at the time',title='Scale Transform: Opening Remarks',date='2021-06-21',dateLabel='Publisher posting date',url='https://learn.scale.com/public/videos/opening-remarks',evidence='https://learn.scale.com/public/videos/opening-remarks',context='Scale-hosted conference introduction. This historical forecast predates today’s models. Wang had a commercial interest in annotation services.',locator='Official publisher transcript; opening discussion of compute, data and algorithms.'),
'scale22':dict(speaker='Alexandr Wang',role='Scale AI founder and CEO at the time',title='Applying AI to Redefine Every Industry',date='2022-10-24',dateLabel='Publisher posting date',url='https://learn.scale.com/public/videos/transformx-2022-keynote-product-announcements',evidence='https://learn.scale.com/public/videos/transformx-2022-keynote-product-announcements',context='TransformX product keynote. Gist checked against the publisher summary, not a timestamped transcript. Scale promotes its own services.',locator='Official publisher summary.'),
'fei':dict(speaker='Fei-Fei Li',role='AI researcher and Stanford professor at the time',title='With spatial intelligence, AI will understand the real world',date='2024-04',dateLabel='TED2024 event month',url='https://www.ted.com/talks/fei_fei_li_with_spatial_intelligence_ai_will_understand_the_real_world',evidence='https://www.ted.com/talks/fei_fei_li_with_spatial_intelligence_ai_will_understand_the_real_world',context='TED research vision. Demonstrations do not establish general-purpose robot reliability or a deployment timeline.',locator='Official TED talk description; no timestamp asserted.')}
rows=[
('compute','gtc','Compute is a system, not just a chip',['Infrastructure','Learning'],'Huang presented Blackwell alongside networking and rack-scale systems for larger AI workloads.','Our interpretation','For builders, memory and communication can matter as much as nominal compute. Benchmark the entire serving path.','Learning experiment','Measure latency, memory use and cost per successful task before changing hardware.','The Next Generation of Accelerated Computing'),
('nim','gtc','Packaging models is product work',['Product','Infrastructure'],'Huang introduced NIM microservices to package and deploy AI models through standard APIs.','Our interpretation','Deployment interfaces can turn model capability into something a team can operate. The announcement alone proves no product fit.','Product experiment','Prototype one bounded workflow and compare integration effort with your current stack.','A New Way to Create Software'),
('robots','gtc','Simulation is a practice ground',['Robotics','Learning'],'Huang described simulated environments for robot learning and introduced tools for perception and manipulation.','Conditional outlook','If simulation transfers reliably to physical tasks, it could shorten iteration. Real-world safety still needs direct validation.','Learning experiment','Study sim-to-real failures and test one task in both environments.','Omniverse Brings AI to the Physical World / Robotics'),
('data','scale21','Better data deserves a seat at the table',['Data','Product'],'Wang argued that high-quality datasets and efficient human feedback were bottlenecks as compute and models grew.','Our interpretation','Treat dataset quality as engineering work. More data helps only when it addresses the failures you actually observe.','Career experiment','Build a small error taxonomy and show how targeted labels change held-out performance.','Transcript: high-quality datasets and annotation'),
('scaling','scale21','A scaling forecast is still a forecast',['Data','Infrastructure'],'Wang forecast growth in compute and data, with new model capabilities emerging from scale.','Conditional outlook','Scaling may improve capability, but a historical prediction does not guarantee every task improves or every business benefits.','Learning experiment','Compare a smaller and larger model on the same representative evaluation set.','Transcript: core resources and emerging capabilities'),
('adapt','scale22','Start with the workflow, then adapt the model',['Product','Data'],'The keynote summary describes pretrained models and task-specific tuning as routes for enterprises without in-house model expertise.','Our interpretation','A pretrained model can reduce the starting cost. Owning evaluation and domain context remains your team’s responsibility.','Product experiment','Choose one costly repeatable task; test the baseline before considering fine-tuning.','Publisher summary: pretrained models and tuning'),
('spatial','fei','Seeing should lead to acting',['Robotics','Learning'],'Li describes spatial intelligence as processing visual information, predicting outcomes and acting in the physical world.','Conditional outlook','If systems connect perception to reliable action, useful applications may extend beyond text. Reliability and human needs remain constraints.','Learning experiment','Try a perception task with changing viewpoints and document where the system fails.','Official TED description')]
cards=[]
for i,(id,key,title,tags,summary,lens,interpretation,ol,opportunity,locator) in enumerate(rows):
 s=sources[key].copy();s['locator']=locator
 cards.append(dict(id=id,title=title,tags=tags,summary=summary,lens=lens,interpretation=interpretation,opportunityLabel=ol,opportunity=opportunity,source=s,quality=dict(useful=4.8-i*.07,novel=4.2,credible=4.5,influence=4.5),reviewed='2026-10-02',format='Original summary card',seconds=35))
json.dump(dict(version=1,updated='2026-10-02',refresh='Curated launch edition. New sources require evidence review before publication.',cards=cards),open('site/content.json','w'),indent=2)
