"""Mock Interview: Back-of-Envelope Estimation — Single-voice think-aloud."""


def build():
    lines = []

    lines.append(("narrator", "Back-of-envelope estimation. The skill that separates candidates who hand-wave from candidates who impress. In a forty-five-minute system design interview, you'll spend roughly five minutes on estimation. But those five minutes carry disproportionate weight. If you can't estimate QPS, storage, or bandwidth, the interviewer can't tell if your architecture will actually work at scale. Today, we're going to walk through every number you need, organized around twelve real interview problems — five generic, seven from the Airwallex domain. I'll say each number out loud, explain where it comes from, and show you how to derive it from first principles when you forget. Let's start with the numbers you should have memorized before walking into any system design interview."))

    # SECTION 1: Power Numbers Reference
    lines.append(("narrator", "Section one. Power numbers you must know. These are the building blocks. Every estimation in an interview starts from one of these. Write them on the whiteboard before the interviewer even finishes the prompt. It shows preparation and gives you something to reference."))

    lines.append(("narrator", "Time first. One millisecond is a thousandth of a second. One second is a thousand milliseconds. One minute is sixty seconds, so sixty thousand milliseconds. One hour is sixty minutes, thirty-six hundred seconds, or three point six million milliseconds. One day is twenty-four hours, eighty-six thousand four hundred seconds, or roughly ten to the five seconds — specifically, eight point six four times ten to the four. One month is about two point six million seconds. One year is roughly three point one five times ten to the seven seconds — thirty-one point five million."))

    lines.append(("narrator", "Now data sizes. One byte is eight bits. One kilobyte is ten to the three bytes — roughly one thousand. One megabyte is ten to the six bytes. One gigabyte is ten to the nine bytes. One terabyte is ten to the twelve bytes. One petabyte is ten to the fifteen bytes. For quick mental math, a typical English web page is about one megabyte. A JPEG photo from a phone camera is two to five megabytes. A minute of MP3 audio is about one megabyte. A minute of compressed video is roughly fifty megabytes. A database row in a transactional system is about one kilobyte."))

    lines.append(("narrator", "Latency numbers. This is the most-asked set. L1 cache reference: about one nanosecond. L2 cache: about five nanoseconds. Main memory access: about one hundred nanoseconds. Disk seek: about ten milliseconds — that's ten million nanoseconds, or one hundred thousand times slower than memory. Read one megabyte sequentially from disk: about two milliseconds for SSD, thirty milliseconds for HDD. Read one megabyte sequentially from memory: about 250 microseconds. Network round-trip within a data center: about half a millisecond to one millisecond. Network round-trip between regions: about fifty to one hundred and fifty milliseconds — so a call from Singapore to Virginia is roughly two hundred milliseconds round-trip."))

    lines.append(("narrator", "Throughput defaults. A typical HDD can do about one hundred to two hundred I/O operations per second. An SSD can do about ten thousand to one hundred thousand IOPS. A single Redis instance can handle about one hundred thousand reads per second. A single PostgreSQL instance on good hardware can handle about five to ten thousand writes per second and fifty thousand reads per second with proper indexing. A Kafka partition can handle about ten to twenty thousand messages per second. A single gRPC service node handles about ten to fifty thousand requests per second for lightweight operations."))

    lines.append(("narrator", "One more set that trips people up: availability math. Two nines — ninety-nine percent — means about three point six five days of downtime per year. Three nines — ninety-nine point nine percent — is about eight point seven six hours per year. Four nines — ninety-nine point nine nine percent — is about fifty-two point six minutes per year. Five nines — ninety-nine point nine nine nine percent — is about five point two six minutes per year. When an interviewer says we need four nines, that means you can't have more than roughly one hour of unplanned downtime per year. That constrains your deployment strategy, your failover design, and your monitoring."))

    # SECTION 2: Generic Problems Estimation
    lines.append(("narrator", "Section two. Estimation for the five generic interview problems. These are the warm-up problems from the Airwallex interview list — URL shortener, rate limiter, notification system, distributed job scheduler, and metrics pipeline. Not necessarily finance-related, the interviewer said. But the estimation skills are identical."))

    # URL Shortener
    lines.append(("narrator", "Problem one: URL shortener. Think Bitly. First question: how many URLs? Let's estimate. Say we have one hundred million active users, and each user shortens five URLs per month. That's five hundred million new URLs per month, or roughly two hundred per second on average. Peak is maybe three to five times average, so about one thousand writes per second at peak. Reads dominate — people click short links far more often than they create them. A typical read-to-write ratio is ten to one, maybe a hundred to one for viral links. Let's call it ten thousand reads per second at peak."))

    lines.append(("narrator", "Storage: each URL mapping is about two hundred bytes — the short code, maybe seven characters, the original URL averaging two kilobytes, timestamps, user ID, click count. Let's call it five hundred bytes total per record including database overhead. Five hundred million new URLs per month times five hundred bytes is about two hundred and fifty gigabytes per month, or about three terabytes per year. Over five years, that's fifteen terabytes. Totally manageable with a sharded key-value store. Cache: we'd cache the hot URLs. If the top one percent of URLs get ninety percent of clicks, we need to cache about five million entries at five hundred bytes each, which is about two point five gigabytes. A single Redis node handles that easily."))

    lines.append(("narrator", "Bandwidth: at ten thousand reads per second, each read returns about fifty bytes — just the redirect URL plus a three-oh-two status. So reads are about five hundred kilobytes per second. Writes at one thousand per second at two kilobytes each are about two megabytes per second. Total outbound: roughly two point five megabytes per second, or about twenty megabits per second. A single network link handles this."))

    # Rate Limiter
    lines.append(("narrator", "Problem two: rate limiter. This one is all about the counter. First: how many distinct clients? Say ten million API clients. Each client has a per-second, per-minute, and per-hour rate limit. The most common pattern is a sliding window counter stored in Redis. For ten million clients with three windows each, that's thirty million Redis keys. Each key stores a counter — maybe eight bytes — plus the key name — about thirty bytes — plus Redis overhead, roughly one hundred bytes per key. Total memory: thirty million times one hundred bytes is about three gigabytes. Fits in a single Redis instance, though you'd probably shard for availability."))

    lines.append(("narrator", "Requests per second: if each client makes one hundred API calls per minute on average, that's about seventeen thousand requests per second. The rate limiter sits in the hot path, so it needs to respond in under one millisecond. A Redis GET plus INCR is about fifty microseconds in the same data center, so this is feasible. At peak, maybe five times average — eighty-five thousand checks per second. Still within a single Redis cluster's capacity."))

    lines.append(("narrator", "One subtlety: the rate limiter must be distributed. If you have ten application servers, each checking a local in-memory counter, a client could exceed the limit by hitting different servers. You need a shared store. Redis is the standard choice. Alternative: a bounded Bloom filter for approximate rate limiting at much higher scale — say, one hundred million clients — but you lose precision."))

    # Notification System
    lines.append(("narrator", "Problem three: notification system. Multiple channels — push, email, SMS. Let's estimate for a social app with fifty million daily active users. Each user receives about ten notifications per day on average, so five hundred million notifications per day. That's about six thousand notifications per second on average, with morning and evening peaks of maybe three times — eighteen thousand per second."))

    lines.append(("narrator", "Channel breakdown: push notifications are about sixty percent of total, email thirty percent, SMS ten percent. Push is cheap — Apple and Google handle the delivery, we just send the payload. Each push payload is about five hundred bytes. At eighteen thousand per second, that's about nine megabytes per second outbound to push services. Email is heavier — about ten kilobytes per message with HTML templates. At about five thousand emails per second, that's fifty megabytes per second outbound. SMS is tiny payload — about two hundred bytes — but expensive per message, so you'd use it sparingly. At about two thousand per second, that's four hundred kilobytes per second."))

    lines.append(("narrator", "Storage: each notification is about one kilobyte — recipient ID, type, content reference, delivery status, timestamps. Five hundred million per day is about five hundred gigabytes per day. You don't need to keep all of it — retain for thirty days for analytics and troubleshooting, then archive. Thirty days of hot storage is about fifteen terabytes. You'd store notification metadata in a time-series database like Cassandra or TimescaleDB for fast range queries over delivery status."))

    lines.append(("narrator", "Delivery guarantees: push and email are at-least-once — idempotency is the client's responsibility. SMS is exactly-once — you absolutely cannot send a duplicate SMS to a customer. This means the SMS pipeline needs idempotency keys and deduplication before the SMS provider. That's an important distinction the interviewer will probe."))

    # Distributed Job Scheduler
    lines.append(("narrator", "Problem four: distributed job scheduler. Think Airflow or cron at scale. How many jobs? Say one thousand tenants, each scheduling an average of one hundred jobs per day. That's one hundred thousand job executions per day. But many jobs run every minute — monitoring checks, data pipeline triggers — so let's be more precise. Say ten thousand unique job definitions, each running every five minutes on average. That's about two hundred thousand executions per day, or about two to three per second. Sounds tiny, right? But there are bursts. At the top of every hour, hundreds of jobs fire simultaneously. At midnight UTC, thousands of daily batch jobs all start at once. Peak concurrent jobs could be one thousand to two thousand."))

    lines.append(("narrator", "Storage per job execution: about five hundred bytes — job ID, schedule, parameters, start and end times, status, retry count. Two hundred thousand per day is about one hundred megabytes per day. Keep ninety days of execution history: about nine gigabytes. The job definitions themselves are larger — maybe two kilobytes each including the DAG definition and dependencies. Ten thousand definitions is about twenty megabytes. Small. The real storage concern is the job queue. If we use a message broker like Kafka or RabbitMQ, the queue holds pending jobs. Peak queue depth during a midnight burst might be five thousand jobs at five hundred bytes each — two point five megabytes. Nothing."))

    lines.append(("narrator", "The harder estimation is worker capacity. Each worker can execute maybe ten concurrent jobs depending on CPU and memory. For a thousand concurrent jobs at peak, you need about one hundred workers. But jobs vary enormously — a data pipeline job might run for hours and consume four gigabytes of RAM, while a health check runs in one second with fifty megabytes. You'd want worker pools: a large pool of cheap workers for fast jobs, and a smaller pool of beefy workers for heavy jobs. The interviewer wants to see you reason about this heterogeneity, not just divide one number by another."))

    # Metrics Pipeline
    lines.append(("narrator", "Problem five: metrics and monitoring pipeline. This is the most numbers-heavy estimation in the set. How many metrics? Say five hundred microservices, each emitting fifty distinct metrics every ten seconds. That's twenty-five thousand metric data points every ten seconds, or two thousand five hundred per second. Each data point is about one hundred bytes — metric name, labels, value, timestamp. That's about two hundred and fifty kilobytes per second of raw ingestion, or about twenty-two megabytes per second with label expansions and metadata. Over a day, that's about twenty gigabytes of raw metrics. But here's the thing: metrics are high-cardinality. If you have five hundred services each with fifty metrics and each metric has ten label combinations, that's two hundred and fifty thousand time series. Store one data point per ten seconds per series for thirty days: twenty-five hundred per second times eight hundred and sixty-four hundred seconds per day times thirty days, that's about six point five billion data points. At one hundred bytes each — that's six hundred and fifty gigabytes. Compressed with Gorilla-style encoding, about fifty to one hundred gigabytes."))

    lines.append(("narrator", "Query patterns: dashboards refresh every ten seconds, querying the last hour of data for a service. That's a range scan over about three hundred and sixty data points per metric, returning instantly. Alerting queries run every minute, scanning the last five minutes — about thirty data points per metric. Neither is heavy. The hard query is a thirty-day aggregate for a capacity planning dashboard — that scans about two point six million data points per metric. This is where downsampling matters. Store one-minute averages for data older than one hour, and one-hour averages for data older than one day. That reduces the thirty-day query from millions of points to about seven hundred and twenty hourly data points."))

    lines.append(("narrator", "One more critical number: alerting latency. If a service goes down, the on-call engineer needs to be paged within two minutes. That means the metrics pipeline must ingest, aggregate, evaluate alert rules, and fire a notification in under one hundred and twenty seconds. The ingestion-to-alert path is the most latency-sensitive part of the entire pipeline. At two thousand five hundred data points per second, even a one-second delay in the Kafka consumer creates a backlog of twenty-five hundred data points. This is why metrics pipelines use push-based ingestion — agents push to the collector, rather than pull-based scraping which adds latency."))

    # SECTION 3: Airwallex-Domain Estimation
    lines.append(("narrator", "Section three. Estimation for the seven Airwallex-domain problems. These are the problems that make or break an Airwallex interview. The interviewer expects you to know fintech-specific numbers — things like SWIFT message sizes, settlement windows, FX rate update frequencies. If you get these right, it signals domain familiarity. If you don't, it's not fatal, but you lose the confidence advantage."))

    # Distributed Wallet
    lines.append(("narrator", "Problem six: distributed wallet. Think Auticuro — Airwallex's wallet infrastructure. The core entity is a virtual account with multiple currency sub-accounts. How many accounts? Say five million merchant and consumer accounts, each holding an average of three currencies. That's fifteen million currency accounts. Each account has a balance — an integer in the smallest unit of the currency, like cents for USD, sen for JPY. The balance itself is eight bytes. The account record — account ID, owner ID, currency, balance, created timestamp, version number for optimistic locking — is about one hundred and fifty bytes. Fifteen million accounts at one hundred and fifty bytes is about two point two five gigabytes. Fits on one database shard, but you'd shard anyway for write throughput."))

    lines.append(("narrator", "Transaction volume: if each account does about two transactions per day on average — deposits, withdrawals, transfers — that's ten million transactions per day, or about one hundred and fifteen per second average. Peak at three to five times: about five hundred transactions per second. Each transaction is a ledger entry — about one hundred bytes: from account, to account, amount, currency, reference, timestamp. Ten million per day at one hundred bytes is about one gigabyte per day. Seven-year retention: two point five terabytes. Manageable with PostgreSQL on a few shards. But here's the crucial number: the wallet uses single-threaded execution per account to guarantee no concurrent modifications. If all five hundred TPS hit different accounts, no problem. But hot accounts — like the platform's settlement account or a popular merchant — could receive dozens of transactions per second. Since each account processes sequentially, the single-threaded throughput per account is limited by database write latency — about two milliseconds per transaction on SSD. That's a theoretical maximum of five hundred transactions per second per account. For most accounts, this is fine. For hot accounts, you need internal sharding — splitting one logical account into multiple physical sub-accounts that consolidate asynchronously."))

    # FX Rate Engine
    lines.append(("narrator", "Problem seven: FX rate engine. This is pure throughput estimation. How many currency pairs? Say fifty major pairs. Each pair gets rate updates from two providers every one hundred to five hundred milliseconds. Let's say each provider sends updates every two hundred milliseconds on average. Two providers times fifty pairs times five updates per second each is five hundred rate updates per second. Each update is about two hundred bytes — bid, ask, timestamp, provider ID, spread. That's about one hundred kilobytes per second of raw rate data. Small. But the rate engine has to serve these rates to thousands of clients with sub-fifty-millisecond latency."))

    lines.append(("narrator", "Read volume: if we have ten thousand active API clients each requesting rate quotes at peak — say, during a market open event — that's ten thousand quote requests per second. Each quote request reads from Redis — sub-millisecond — and writes a locked quote key with a thirty-second TTL. The quote key is about three hundred bytes — quote ID, rate, expiry, client ID. Ten thousand new quotes per second, each lasting thirty seconds, means three hundred thousand active quotes in Redis at any moment. Three hundred thousand keys at three hundred bytes each is about ninety megabytes. Redis handles this easily. But the write rate is important: ten thousand writes per second of new quotes plus about ten thousand expires per second as old quotes TTL out. That's twenty thousand Redis operations per second on quote keys alone. Still within a single Redis cluster."))

    lines.append(("narrator", "One number that surprises people: FX rate storage for audit. Regulators require you to prove what rate you quoted at any given moment. You need to store every rate update. Five hundred updates per second times eighty-six thousand seconds per day is about forty-three million updates per day at two hundred bytes each — about eight point six gigabytes per day. Over seven years, that's about twenty-two terabytes of rate data. You'd store this in a time-series database or compressed files in object storage, not in your hot path. The hot path only keeps the latest rate per pair in Redis."))

    # AI Agent Platform
    lines.append(("narrator", "Problem eight: AI agent platform. Think AgentOS — Airwallex's internal AI platform. How many agents? Say five hundred internal users, each running about three concurrent agent sessions during work hours. That's about fifteen hundred concurrent sessions. Each session makes about ten LLM API calls per minute — planning, tool execution, summarization. So fifteen hundred sessions times ten calls per minute is about fifteen thousand LLM calls per minute, or about two hundred and fifty per second. Each call has a prompt of about two kilobytes and a response of about one kilobyte. So prompt ingestion is about five hundred kilobytes per second, and response generation is about two hundred and fifty kilobytes per second."))

    lines.append(("narrator", "Cost estimation: at two hundred and fifty LLM calls per second, with each call consuming about one thousand input tokens and five hundred output tokens, that's about two hundred and fifty thousand input tokens per second and one hundred and twenty-five thousand output tokens per second. At GPT-4 pricing of about thirty dollars per million input tokens and sixty dollars per million output tokens, that's about seven dollars and fifty cents per second, or about twenty-seven thousand dollars per hour. Way too expensive. You'd use GPT-4 only for complex reasoning and GPT-3.5 or open-source models for routine tasks, cutting costs by roughly ten to twenty times. Monthly cost: maybe fifty thousand dollars. The interviewer wants to see you do this math."))

    lines.append(("narrator", "Agent execution sandbox: each agent runs in a container with about five hundred megabytes of memory and one CPU core. Fifteen hundred concurrent agents is about seven hundred and fifty gigabytes of RAM and fifteen hundred CPU cores. With oversubscription at two to one — agents are often waiting for LLM responses — that's about three hundred and seventy-five gigabytes and seven hundred and fifty cores. About twenty to thirty large VMs or a Kubernetes cluster of about forty nodes."))

    # Security Automation
    lines.append(("narrator", "Problem nine: security automation platform. CVE triage and remediation. How many CVEs? About two thousand new CVEs are published per month on average, with spikes up to five thousand. Your system ingests these from the National Vulnerability Database feed and various advisory sources. Each CVE record is about five kilobytes — description, affected products, CVSS score, references. So two thousand to five thousand per month at five kilobytes is about ten to twenty-five megabytes per month. Storage is negligible."))

    lines.append(("narrator", "The real scale is in the matching. Say your organization uses about five thousand distinct software packages across all services. For each new CVE, you need to check if any of your packages are affected. That's a reverse lookup — which of our packages match this CVE's affected product list? With a pre-built index in Elasticsearch, each check is about ten milliseconds. Two thousand checks per month is negligible load. But the automated remediation is heavier. For each affected package, you generate a patch or update recommendation. Say about five percent of CVEs affect your systems — one hundred per month. For each, you run an automated analysis that takes about thirty seconds of compute, including scanning the codebase for usage patterns. One hundred analyses per month at thirty seconds each is about fifty minutes of compute. Trivial. The interviewer is testing whether you can identify that this system is not about raw throughput — it's about correctness, coverage, and the human-in-the-loop workflow."))

    # Distributed Job Scheduler (fintech context)
    lines.append(("narrator", "Problem ten: this appeared in the generic list too, but in an Airwallex context, the job scheduler handles settlement batches, reconciliation jobs, and compliance reporting. The numbers shift. Settlement jobs run at specific cutoff times per currency — SEPA cutoff is two PM Central European Time, SWIFT has regional windows. So the peak is concentrated. Say one thousand settlement batches per day, but three hundred of them fire between one and two PM UTC. That's about five batches per second during the peak window, each submitting about ten thousand individual payments to banking partners. So the peak throughput is fifty thousand payment submissions per second through the Bank Connector layer. Each submission is about one kilobyte over the wire. That's fifty megabytes per second outbound to banks during the settlement window."))

    lines.append(("narrator", "Reconciliation runs overnight — about ten million ledger entries checked against bank statements. Each check is a database read and comparison — about one millisecond. Ten million at one millisecond each is about ten thousand seconds if sequential, or about twenty-eight minutes with a hundred parallel workers. You'd want this done by six AM local time, so you need at least fifty to one hundred workers for reconciliation."))

    # Global Treasury Network
    lines.append(("narrator", "Problem eleven: global treasury network. Multi-entity cash pooling and netting. This is a lower-volume but higher-value system. How many entities? Say two hundred legal entities across forty countries. Each entity has one to five bank accounts. Total: about six hundred bank accounts. The treasury system sweeps balances daily — reading each account balance and moving funds to optimize interest and currency exposure. Six hundred balance checks per day is trivial. But each check requires calling a bank API with about five hundred millisecond latency. If done sequentially, six hundred checks at five hundred milliseconds each is about five minutes. Acceptable. But for intraday liquidity monitoring, you'd poll every fifteen minutes. Six hundred accounts every fifteen minutes is forty checks per minute. Still trivial in terms of throughput, but the latency per check matters — you need all six hundred balances within a two-minute window to make a netting decision. So you need parallelism: about fifty concurrent connections to banks, completing six hundred checks in about six seconds per batch."))

    lines.append(("narrator", "Netting: every evening, the treasury system calculates how much each entity owes every other entity, and nets the flows to minimize the number and size of actual transfers. Two hundred entities means about twenty thousand pairwise positions. The netting algorithm is essentially a graph optimization — finding the minimum set of transfers that settles all positions. This runs once per day, takes about five to ten seconds on a modern CPU. Storage: each netting run produces about two hundred to five hundred actual transfers. At one kilobyte per transfer record, that's about five hundred kilobytes per day. Over seven years: about one point three gigabytes. Negligible."))

    # Feature Store
    lines.append(("narrator", "Problem twelve: feature store. Point-in-time features for ML models, like AirSkiff at Airwallex. How many features? Say fifty ML models, each consuming about one hundred features. With overlap, that's about five hundred distinct features. Each feature is computed from some data source — transaction history, user behavior, market data. The batch pipeline recomputes all features daily, and the streaming pipeline updates them in real time as events arrive."))

    lines.append(("narrator", "Entity count: say five million users and one million merchants. Each entity has a feature vector of five hundred features. At four bytes per float feature value, plus overhead — entity ID, timestamp — that's about two kilobytes per entity. Six million entities at two kilobytes is about twelve gigabytes for the current feature table. The point-in-time requirement means you need historical snapshots — the feature values as they were at a specific timestamp, not the current values. If you store daily snapshots for thirty days, that's thirty times twelve gigabytes equals three hundred and sixty gigabytes. With compression, about fifty to one hundred gigabytes."))

    lines.append(("narrator", "Real-time serving: ML models query the feature store during inference. A fraud detection model needs features in under fifty milliseconds. With five hundred features per request at about four bytes each, each read is about two kilobytes. If the fraud model scores one thousand transactions per second, that's about two megabytes per second of feature reads from the store. You'd cache the most recent features in Redis — twelve gigabytes fits in a small Redis cluster — and serve reads from cache with database fallback."))

    lines.append(("narrator", "The streaming update path: each transaction event updates about ten to twenty features for the transacting user and merchant. At one thousand transactions per second, that's about fifteen thousand feature updates per second. Each update modifies a few bytes in a Redis hash and asynchronously writes through to the backing database. This is well within Redis's write capacity."))

    # SECTION 4: Deriving from First Principles
    lines.append(("narrator", "Section four. When you forget a number — and you will — here's how to derive it from first principles. This is what separates true estimation skill from memorization."))

    lines.append(("narrator", "Technique one: start from users and work down. If you forget how many QPS a system handles, start with the user count. One hundred million users. What fraction use the service daily? Maybe ten to twenty percent, so ten to twenty million daily active users. How many actions per user per day? Say ten to twenty. That's one to four hundred million actions per day. Divide by eighty-six thousand seconds per day for average QPS: twelve to forty-seven per second. Multiply by three to five for peak. This gives you the right order of magnitude without memorizing any specific number."))

    lines.append(("narrator", "Technique two: the rule of seventy-two for scaling. If traffic grows twenty percent per year, how long to ten-x? Seventy-two divided by twenty is about three point six years. If it grows fifty percent per year: seventy-two divided by fifty is about one point four years. This lets you quickly reason about how long your architecture needs to last before it must scale."))

    lines.append(("narrator", "Technique three: sanity check with physical limits. If someone says their database handles one million writes per second on a single machine, be skeptical. A fast SSD does about one hundred thousand IOPS. Even with write batching — grouping one hundred writes per flush — you'd need one hundred thousand divided by one hundred equals one thousand flushes per second, each requiring an fsync. The fsync latency on a good SSD is about one millisecond. So one thousand fsyncs per second is right at the limit. Possible but barely, and you'd need a very expensive SSD array. A single PostgreSQL instance? Not a chance. This is the kind of pushback an interviewer loves to see."))

    lines.append(("narrator", "Technique four: estimate bandwidth from first principles. A single one-gigabit network link can carry about one hundred megabytes per second after protocol overhead. A ten-gigabit link: about one gigabyte per second. If your system needs to move one hundred gigabytes per day of data between services, that's about one point two megabytes per second average — a one-gigabit link is fine. But if you need to move that in a one-hour batch window, it's twenty-eight megabytes per second — still fine on a one-gigabit link, but getting closer to the ceiling. Always check against the physical limit."))

    # SECTION 5: Fintech-Specific Defaults
    lines.append(("narrator", "Section five. Fintech-specific default numbers. If you're interviewing at Airwallex, Wise, Stripe, or any fintech company, these numbers signal that you've done your homework."))

    lines.append(("narrator", "SWIFT MT103 message size: about five hundred to eight hundred bytes. SWIFT settlement time: one to five business days for cross-border. SEPA transfer: same day if submitted before cutoff, costs about zero point three five euros. Faster Payments in the UK: near-instant, under fifteen seconds, up to one million pounds. ACH in the US: one to two business days, batch processed. Card payment authorization: under two seconds, settlement one to three days later. FX rate update frequency: every one hundred to five hundred milliseconds for major pairs from providers like Reuters or FXCM. FX rate spread for institutional clients: about zero point zero one to zero point zero five percent. FX rate spread for retail: about zero point five to two percent. Idempotency key TTL: thirty seconds for consumer quotes, five minutes for B2B. Compliance screening latency: about two hundred to five hundred milliseconds per check against sanctions lists. KYC onboarding time: one to five minutes for automated checks, twenty-four to forty-eight hours if manual review is triggered."))

    lines.append(("narrator", "Payment processing costs: card networks charge about one point five to three percent per transaction. Bank transfer via SWIFT: about twenty to forty dollars per transfer. SEPA: about zero point one to zero point five euros. Local rails in emerging markets: variable, but often one to two percent. These cost numbers matter because they drive architecture decisions — if you're routing payments, you want to choose the cheapest rail that meets the speed requirement."))

    lines.append(("narrator", "Regulatory retention: transaction records must be kept for five to seven years depending on jurisdiction. Anti-money-laundering reports: suspicious activity reports must be filed within thirty days of detection. GDPR right to erasure: must respond within thirty days, but financial records are exempt — you pseudonymize, you don't delete. These constraints directly affect your data architecture."))

    # SECTION 6: Quick-Reference Cheat Sheet
    lines.append(("narrator", "Section six. The quick-reference cheat sheet. When the interviewer says go ahead and estimate, write this on the whiteboard in thirty seconds."))

    lines.append(("narrator", "Time: one day equals eight-six-four-zero-zero seconds, roughly ten to the five. One month: two point six times ten to the seven seconds. One year: three point one five times ten to the seven seconds. Data: one KB, one MB equals ten to the six bytes, one GB equals ten to the nine, one TB equals ten to the twelve. Latency: L1 cache one nanosecond, memory one hundred nanoseconds, SSD read one millisecond, disk seek ten milliseconds, intra-DC network one millisecond, cross-region one hundred milliseconds. Throughput: HDD one hundred IOPS, SSD ten thousand IOPS, Redis one hundred thousand reads per second, PostgreSQL five thousand writes per second, Kafka partition ten thousand messages per second. Availability: two nines equals three point six five days downtime per year, three nines equals eight point seven hours, four nines equals fifty-three minutes, five nines equals five minutes. Users: one hundred million total, ten to twenty million daily active, ten to twenty actions per user per day, ten to forty-seven average QPS, three to five times for peak."))

    lines.append(("narrator", "Fintech defaults: SWIFT message five hundred bytes, settlement one to five days, SEPA same-day, FX update every two hundred milliseconds, FX spread institutional zero point zero one to zero point zero five percent, retail zero point five to two percent, compliance check five hundred milliseconds, retention seven years, idempotency TTL thirty seconds consumer, five minutes B2B."))

    lines.append(("narrator", "That's your cheat sheet. Memorize it. Practice writing it in thirty seconds. When the interviewer asks for estimation, you'll start from these numbers and derive everything else. The numbers aren't the point — the process is. But having the right numbers in your head makes the process faster, more confident, and more credible."))

    lines.append(("narrator", "One last thing. The most common mistake in estimation interviews is forgetting to state your assumptions. Every number you derive should be preceded by assuming or let's say. For example: assuming one hundred million users, with twenty percent daily active, and ten actions per user per day, we get two hundred million daily actions, which at eighty-six thousand seconds per day gives us about two thousand three hundred average QPS. Multiply by five for peak: eleven thousand five hundred. If any of my assumptions are wrong, the final number changes proportionally. This is how you show the interviewer that you think in systems, not in magic numbers."))

    lines.append(("narrator", "Practice these twelve problems until the estimations feel automatic. Then, in the interview, you can spend your mental energy on architecture instead of arithmetic. That's the real advantage."))

    return lines
