"""Mock Interview: Card Authorization & Issuing Platform — Two-voice dialogue."""


def build():
    lines = []

    # SECTION 1: Requirements
    lines.append(("interviewer", "Hi, welcome. Today I'd like you to design an issuing platform for virtual and physical business cards. A merchant authorization request arrives from a card network and must be approved or declined in under one hundred fifty milliseconds. The system needs card lifecycle controls, per-card and per-employee limits, available-balance checks, authorization holds, reversals, incremental authorizations, clearing files, disputes, and network outages. Explain how you avoid approving the same available funds twice."))

    lines.append(("candidate", "Thanks. Card issuing is a real-time, high-stakes system — every millisecond counts, and approving the same funds twice means real money lost. The core challenge is the authorization hold: when a cardholder swipes, we must atomically check available balance and reserve funds, all within the network's strict timeout. Let me clarify the constraints. First, what's the card network — Visa, Mastercard, or both? And are we issuing physical cards, virtual cards, or both?"))

    lines.append(("interviewer", "Both Visa and Mastercard. Both physical and virtual cards. Virtual cards for online transactions, physical cards for in-person spending. Employees get cards with company-controlled limits."))

    lines.append(("candidate", "Second question: what's the authorization volume and the clearing volume? Authorizations are real-time and much higher than settlements, which come later in batch files."))

    lines.append(("interviewer", "About five hundred authorizations per second at peak, with spikes during business hours. Clearing files come in four times per day from each network, with about two million cleared transactions per day."))

    lines.append(("candidate", "Third question: what happens when the balance store is unavailable? Decline by default, or is stand-in approval allowed?"))

    lines.append(("interviewer", "Decline by default. However, the product team wants a strictly bounded stand-in mode for premium customers — a pre-configured offline limit per card that allows a small number of approvals when the ledger is unreachable, with later reconciliation. This is a product and risk decision, not an engineering default."))

    lines.append(("candidate", "Clear. Summary: dual-network issuing, virtual and physical cards, employee-level controls, five hundred auths per second at peak, one hundred fifty millisecond SLA, authorization holds with atomic balance reservation, decline-by-default with bounded stand-in as opt-in. Moving to architecture."))

    # SECTION 2: Architecture
    lines.append(("interviewer", "Show me the architecture."))

    lines.append(("candidate", "The authorization path must be as short as possible. Here's the flow. The card network sends an authorization request to our regional network gateway. The gateway validates the network signature, parses the message, and routes it to the authorization service. The authorization service does four things in sequence, as fast as possible. First, deduplicate by network transaction ID and message type — if we've seen this exact request before, return the cached response immediately. Second, fetch card controls — status, MCC restrictions, country limits, per-transaction and daily and monthly limits, employee policy. These are cached in a fast key-value store with version and expiry — we precompute them on card creation and update. Third, check available balance against the authorization amount — this is the critical atomic step. Fourth, write the authorization record, the hold journal, and an outbox event in one transaction, and return the decision to the network. The total path: network gateway, authorization service, card controls cache, balance store, ledger posting. No synchronous calls to slow reporting, notifications, or model training."))

    lines.append(("candidate", "The clearing path is separate and asynchronous. Clearing files arrive four times per day. A matching service matches clearing records against authorization records by network references — the network transaction ID and the authorization code. When matched, the hold is converted to a settlement: the reserved amount moves from customer reserved to partner payable, and any difference between the authorization amount and the clearing amount is handled — partial clearing releases the unused hold, incremental authorizations add to it. Unmatched presentments go to a suspense account and an investigation queue — we never guess, we investigate."))

    # SECTION 3: Deep Dive — Authorization State Machine
    lines.append(("interviewer", "Walk me through the authorization state machine in detail."))

    lines.append(("candidate", "An authorization has a clear lifecycle. State one: received. The network message arrives at our gateway. We parse it, validate the signature, and create an in-flight record keyed by network transaction ID. State two: the authorization service processes the request. It checks card controls — is the card active? Is the merchant category allowed? Is the transaction within limits? Then it atomically checks and reserves funds. If all checks pass, state becomes approved hold. If any check fails, state becomes declined, and we return the appropriate decline reason mapped to the network's reason codes."))

    lines.append(("candidate", "State three: approved hold. The funds are reserved but not yet settled. The hold has an expiry — typically seven to thirty days depending on the merchant category and network rules. If clearing doesn't arrive before expiry, we release the hold automatically and create a release event. This prevents stale holds from tying up customer funds forever."))

    lines.append(("candidate", "State four: clearing arrives. The matching service finds the authorization by network references. If the clearing amount equals the hold amount, we convert the full hold to settlement — debit reserved, credit partner payable. If the clearing amount is less — say a hotel authorized five hundred but the final bill is four hundred twenty — we release the eighty difference and settle four hundred twenty. This is partial clearing. If the clearing amount is more — an incremental authorization — we check available funds for the additional amount and either approve or decline the increment."))

    lines.append(("candidate", "State five: disputes and refunds. A cardholder disputes a charge. The dispute creates a new case, and the disputed amount moves to a disputed funds account while the case is investigated. If the dispute is resolved in the cardholder's favor, we refund — debit disputed funds, credit customer available. If resolved in the merchant's favor, we move the funds back to settled."))

    # SECTION 4: Deep Dive — Preventing Double Spend
    lines.append(("interviewer", "How do you avoid approving the same available funds twice? That's the core safety question."))

    lines.append(("candidate", "Double spend prevention has three layers. Layer one: atomic balance reservation. When we check available funds and move them to holds, it must be one atomic operation — not check then reserve, because between check and reserve, another authorization could check the same funds. We use a conditional update: update account balances set available equals available minus amount, reserved equals reserved plus amount, version equals version plus one, where account ID equals X and currency equals AUD and available greater than or equal to amount and version equals expected version. If available is insufficient or the version changed, the update affects zero rows and we decline. This is a single SQL statement in a transaction — atomic, no race condition."))

    lines.append(("candidate", "Layer two: deduplication. The card network may send the same authorization request multiple times — network retries, terminal re-sends, partial message retransmission. We deduplicate by the composite key of network transaction ID plus message type. Before processing any authorization, we check: have we already processed this exact key? If yes, return the stored response. This prevents the same swipe from creating two holds. The deduplication record persists for the authorization's lifetime — even if the network retries after our response timeout, we return the original decision, not a new one."))

    lines.append(("candidate", "Layer three: idempotent clearing matching. When clearing files arrive, we match by network references, not by amount. If the same clearing record appears in two files — which happens due to network re-sends — the matching service detects the duplicate by the clearing file ID and row number, and skips it. We never create two settlement journals for the same clearing record."))

    # SECTION 5: Failure Scenarios
    lines.append(("interviewer", "What happens when the network sends a reversal before we've responded to the original authorization?"))

    lines.append(("candidate", "This is a real scenario — network message ordering isn't guaranteed. If we receive a reversal for an authorization we haven't processed yet, we process it idempotently. We create a placeholder authorization record in received state, then immediately transition it to reversed. When the original authorization finally arrives, we find the existing record and return the original reversal response. This requires our state machine to tolerate out-of-order messages. Version rules and retry lookups make this safe — we never create a hold for an already-reversed authorization."))

    lines.append(("interviewer", "The balance store is unavailable — walk me through the stand-in mode."))

    lines.append(("candidate", "Stand-in mode is an opt-in, strictly bounded fallback for premium customers. When the balance store is unreachable — health check fails three consecutive times — and the card has stand-in enabled with a configured offline limit, the authorization service can approve transactions up to that limit without checking the real balance. The offline limit is conservative — maybe five hundred dollars total, with a maximum of three stand-in approvals per card per day. Every stand-in approval creates a stand-in journal entry in a local cache, tagged as provisional. When the balance store recovers, we replay all stand-in approvals against the real balance. If a stand-in approval would have been declined — because the real balance was insufficient — we flag it for immediate investigation and reconciliation, but we don't claw back the already-approved transaction. The loss is bounded by the offline limit times the number of cards with stand-in enabled. This is a product and risk decision, not an engineering default — the default is always decline."))

    lines.append(("interviewer", "A clearing file has a transaction with no matching authorization. What do you do?"))

    lines.append(("candidate", "We never guess. The unmatched presentment goes to a suspense account — debit suspense, credit partner payable — and an investigation case is created. Operations investigates: was the authorization in a different region? Was it authorized before our system went live? Was it a network data issue? The investigation resolves the case and either creates a proper linking or writes off the suspense entry with an approved compensating journal. The key principle: unmatched presentments are exceptions, not silent postings. They surface immediately, they're tracked, and they're resolved with audit trails."))

    # SECTION 6: Scale and Trade-offs
    lines.append(("interviewer", "How do you scale this to ten times the volume?"))

    lines.append(("candidate", "Partition by card or account. Each account's balance and holds are independent, so we shard the balance store by account ID. The authorization service is stateless — it can scale horizontally. The card controls cache is already a fast key-value store — Redis or DynamoDB — and scales by adding nodes. The bottleneck is the balance store's write throughput for atomic reservations. With partitioning by account, each partition handles only its own accounts, and we can add partitions as volume grows. The network gateway has dedicated, regional deployments with redundant network connections to Visa and Mastercard — this is infrastructure scaling, not application scaling."))

    lines.append(("candidate", "At ten times volume — five thousand authorizations per second — we need to be careful about hot accounts. A single corporate card with hundreds of concurrent authorizations becomes a partition bottleneck. The solution: sub-account striping for high-volume cards, where the card's total balance is divided across sub-accounts, and incoming authorizations are distributed across them. This is the same pattern as the wallet ledger's hot-account handling."))

    # SECTION 7: Summary with Killer Phrases
    lines.append(("candidate", "Let me close with the killer phrases for card issuing. One: atomic check-and-reserve — available balance check and hold creation must be one conditional update, not check-then-reserve. Two: deduplicate by network transaction ID plus message type — the same swipe must never create two holds. Three: authorization and clearing are distinct financial events — a hold is not settlement and must not be reported as final spend. Four: unmatched presentments go to suspense and investigation — never guess, always surface exceptions. Five: decline by default, stand-in is opt-in and bounded — the offline limit caps the loss, and stand-in approvals are replayed against real balance on recovery. Six: partition by account for scale — each account's balance is independent, so shard accordingly. Seven: stale holds expire automatically — seven to thirty days depending on merchant category, releasing tied-up customer funds. And eight: reversals before authorizations are handled by out-of-order tolerance — create placeholder, transition to reversed. The phrase to remember: atomic check-and-reserve, never check-then-reserve."))

    lines.append(("interviewer", "Walk me through a complete authorization and clearing cycle for a card payment."))

    lines.append(("candidate", "Step one: authorization. A merchant swipes an Airwallex business card at a restaurant for one hundred twenty AUD. The Visa network sends the authorization request to our regional gateway in Sydney. Gateway validates the network signature, parses the message — card number, expiry, amount, merchant category code five eight one two for restaurants. It routes to the authorization service. Step two: deduplication. The service checks: have we seen network transaction ID visa-sydney-seven-eight-nine before? No — first time. Create an in-flight record."))

    lines.append(("candidate", "Step three: card controls. The service fetches the card's control profile from cache — card is active, MCC five eight one two is allowed, Australia is in the permitted countries list, single-transaction limit is five hundred AUD, daily limit is two thousand AUD, current daily spend is three hundred AUD. All checks pass. Step four: atomic balance reservation. The service executes the conditional update: update account balances set available equals available minus one hundred twenty, reserved equals reserved plus one hundred twenty, version equals version plus one, where account ID equals this card's account, currency equals AUD, available greater than or equal to one hundred twenty, version equals seven. One row affected — success. Available was two thousand, now one thousand eight hundred eighty. Reserved was five hundred, now six hundred twenty."))

    lines.append(("candidate", "Step five: the service writes the authorization record, the hold journal, and an outbox event in one transaction. Total processing time: thirty-five milliseconds. The gateway sends the approval back to Visa, which forwards it to the restaurant's terminal. Total end-to-end: under one hundred milliseconds, well within the one hundred fifty millisecond SLA."))

    lines.append(("candidate", "Step six: clearing, two days later. Visa sends a clearing file with the settled amount — one hundred fifteen AUD, because the actual bill was slightly less than the authorized amount. The matching service finds the authorization by network references. Partial clearing: settle one hundred fifteen, release five. In one transaction: debit customer reserved one hundred fifteen, credit partner payable one hundred fifteen, debit customer reserved five, credit customer available five. The five AUD difference returns to available. The hold is fully resolved. The merchant's statement shows one hundred fifteen AUD spent at the restaurant, not one hundred twenty. The difference was never spent — it was a hold that was released. Atomic check-and-reserve, never check-then-reserve."))

    return lines
