"""Mock Interview: Real-Time Chat System like WhatsApp — Two-voice dialogue."""


def build():
    lines = []

    # SECTION 1: Requirements (~5 min)
    lines.append(("interviewer", "Hi, today I'd like you to design a real-time chat system — something like WhatsApp or Messenger. Users can send messages in 1-on-1 conversations and group chats, and they expect instant delivery. Start by clarifying the requirements."))

    lines.append(("candidate", "Thanks. A chat system is a great problem because it combines real-time communication with interesting delivery and consistency challenges. Let me start with the most fundamental question: is this a pure messaging system, or does it also include features like voice and video calls, status updates, and stories? Because those features change the architecture significantly."))

    lines.append(("interviewer", "Pure messaging for now — text messages, images, and file attachments. No voice or video."))

    lines.append(("candidate", "OK, that scopes it down. Next question: what's the scale — daily active users, messages per second at peak, and the maximum group chat size? Also, what's the expected message delivery latency — do messages need to arrive within a certain time bound?"))

    lines.append(("interviewer", "50 million DAU. Peak message rate is about 10,000 messages per second. Group chats support up to 256 members. Message delivery should feel instant — under 500 milliseconds end-to-end for online recipients."))

    lines.append(("candidate", "10K msg/sec peak with 256-member groups. That means a single group message might need to be fanned out to 256 recipients, so the internal message delivery rate could be much higher — up to 2.56M fan-out events per second in the worst case. Let me ask about the ratio of 1-on-1 to group messages, since it significantly affects the fan-out design."))

    lines.append(("interviewer", "About 60 percent 1-on-1 and 40 percent group messages. The average group size for active groups is about 8 members."))

    lines.append(("candidate", "60/40 split with average group size of 8 — that's manageable. So the average fan-out per message is about 0.6 times 1 plus 0.4 times 8, which is 3.8 recipients per message. At 10K messages per second, the internal delivery rate is about 38K deliveries per second. Much more reasonable than the worst case. A few more questions. First, do we need read receipts — showing when a message has been seen? Second, do we need online/offline status indicators? Third, what about message history — how far back can users scroll, and is there a search feature? Fourth, do we need end-to-end encryption?"))

    lines.append(("interviewer", "Read receipts are required — users see double-check marks when a message is delivered and blue checks when it's read. Online/offline and last-seen timestamps are required. Message history is stored indefinitely for 1-on-1 chats and for the lifetime of a group chat. Search within conversation history is required. End-to-end encryption is a nice-to-have — discuss the design considerations but don't implement it fully."))

    lines.append(("candidate", "Let me ask about message ordering. In a group chat, if Alice and Bob send messages at nearly the same time, different recipients might see them in different orders. Do we need a globally consistent ordering within a conversation, or is per-sender ordering sufficient?"))

    lines.append(("interviewer", "We need a globally consistent ordering within each conversation — all members of a group chat should see messages in the same order."))

    lines.append(("candidate", "Also, do we support message deletion? If Alice deletes a message, should it disappear for all recipients, or just for Alice? And what about editing messages after they've been sent?"))

    lines.append(("interviewer", "Deletion removes the message for the sender only — other recipients still see it. Editing is not required for now."))

    lines.append(("candidate", "Let me summarize. We're designing a real-time chat system at 50M DAU, 10K msg/sec peak, 1-on-1 and group chats up to 256 members, sub-500ms delivery for online users, read receipts, online status, indefinite message history, in-conversation search, and globally consistent ordering per conversation. End-to-end encryption is a consideration. Let me move to estimation."))

    # SECTION 2: Estimation (~5 min)
    lines.append(("interviewer", "Go ahead with the numbers."))

    lines.append(("candidate", "50M DAU, 10K messages per second peak. Average message rate is maybe 3K per second, giving about 260M messages per day. Average message size — text messages are small, maybe 200 bytes, but with images and files, the average might be higher. Let's say 50 percent text, 30 percent images at 200 KB, and 20 percent files at 1 MB. The average size is 0.5 times 200 plus 0.3 times 200,000 plus 0.2 times 1,000,000, which is about 260 KB per message. That seems high. Let me reconsider — most messages are text. Maybe 80 percent text, 15 percent images at 100 KB, 5 percent files at 500 KB. Average: 0.8 times 200 plus 0.15 times 100,000 plus 0.05 times 500,000 equals 40 KB per message. That's more reasonable."))

    lines.append(("candidate", "Wait, 40 KB per message times 260M messages per day is 10.4 TB per day. That's a lot of data. But we don't store the media inline — we upload images and files to object storage and include a URL in the message. The message payload is just the text and the media URL, which is maybe 500 bytes. So message metadata is 500 bytes times 260M equals 130 GB per day. The media storage is separate — about 10 TB per day in object storage. Over 5 years, message metadata is about 237 TB and media is about 18 PB. The metadata needs a database, and the media goes to object storage like S3."))

    lines.append(("candidate", "I should also consider the per-user index storage. Each user needs an index of their conversations — maybe 100 conversations per user with 100 bytes of metadata each (conversation ID, last message preview, unread count, timestamp). With 50M users, that's 500 GB. This is read-heavy — every time a user opens the app, we fetch their conversation list. We'd cache this aggressively in Redis, with the database as the source of truth. The conversation list cache is about 10 KB per user, times 50M active users equals 500 GB — too much for a single Redis cluster. We'd need a sharded Redis cluster with about 50 to 100 nodes just for conversation lists."))

    lines.append(("interviewer", "What about the connection infrastructure — how many WebSocket connections do we need?"))

    lines.append(("candidate", "With 50M DAU, not all are online simultaneously. Concurrent online users might be about 20 percent of DAU — 10M concurrent connections. Each WebSocket connection consumes about 10 to 20 KB of server memory for buffers and state. At 10M connections, that's 100 to 200 GB of memory just for connections. With connection servers holding about 100K connections each, we'd need about 100 to 200 connection servers. Each server needs about 1 to 2 GB of memory for connections, plus overhead. These are lightweight servers — they just route messages, not process them."))

    lines.append(("candidate", "The fan-out computation: at peak, 10K messages per second. For 1-on-1 chats, each message fans out to 1 recipient. For group chats, the average group size matters. If 30 percent of messages are in groups with an average size of 20, the average fan-out is 0.7 times 1 plus 0.3 times 20 equals 6.7. At 10K messages per second, the internal delivery rate is about 67K deliveries per second. In the worst case with large active groups, it could spike to 200K deliveries per second. The delivery infrastructure needs to handle this comfortably."))

    # SECTION 3: High-Level Architecture (~5 min)
    lines.append(("interviewer", "Good. Let's move to the high-level architecture."))

    lines.append(("candidate", "The architecture has five main components: Connection Servers, the Message Service, the Presence Service, the Message Storage, and the Push Notification Service. Let me walk through a message send flow."))

    lines.append(("candidate", "First, let me describe the Presence Service since it's relatively simple. The Presence Service tracks which users are online and their last-seen timestamps. When a client connects to a Connection Server, the server registers the user as online with the Presence Service — writing to a Redis key with a heartbeat TTL of 30 seconds. The client sends a heartbeat every 20 seconds to keep the key alive. If the heartbeat stops, the key expires and the user is marked as offline with the last heartbeat timestamp as the last-seen time. The Presence Service also supports last-seen queries — when Alice views Bob's profile, the app queries Bob's online status. This is a simple Redis GET with sub-millisecond latency."))

    lines.append(("candidate", "When Alice sends a message, her client establishes a WebSocket connection to one of the Connection Servers. The Connection Server is stateless in terms of message data — it just maintains the WebSocket and a mapping of user ID to connection. When Alice sends a message, the Connection Server receives it, assigns a message ID and a sequence number for the conversation, and forwards it to the Message Service. The Message Service is the core — it handles message persistence, fan-out, and delivery coordination."))

    lines.append(("candidate", "The Message Service first persists the message to the database — writing it to the conversation's message history with the sequence number. Then it determines the recipients: for a 1-on-1 chat, it's the other participant; for a group chat, it's all 256 members. For each recipient, it checks the Presence Service to see if they're online. Online recipients have their messages routed through the Connection Servers via a pub/sub mechanism. Offline recipients have their messages queued for push notification delivery. The Message Service publishes the message to a per-user channel — like a Redis pub/sub channel keyed by user ID. The Connection Server subscribed to that user's channel receives the message and pushes it over the WebSocket to the recipient's client."))

    lines.append(("interviewer", "Why use Redis pub/sub instead of having the Message Service directly send to Connection Servers?"))

    lines.append(("candidate", "Decoupling. The Message Service does not need to know which Connection Server a user is connected to. With Redis pub/sub, each Connection Server subscribes to channels for all users connected to it. When a message is published to a user's channel, the right Connection Server automatically receives it. This simplifies the Message Service — it just publishes and moves on. The alternative is a routing table that maps user IDs to Connection Server IDs, but that's extra state to maintain and a potential bottleneck. Redis pub/sub handles the routing implicitly."))

    lines.append(("candidate", "But Redis pub/sub has a problem: it's fire-and-forget. If a Connection Server is temporarily disconnected when a message is published, the message is lost. We need a fallback. When the recipient comes back online, they need to catch up on missed messages. The approach is: when a client connects, it sends the last sequence number it received. The Connection Server queries the Message Service for any messages with higher sequence numbers and delivers them. This catch-up mechanism ensures no messages are lost even with pub/sub failures."))

    lines.append(("candidate", "Actually, I want to reconsider the fan-out approach. Redis pub/sub per user works for small scale, but at 10M concurrent users, that's 10M pub/sub channels. Redis handles this, but the memory usage is significant. An alternative is to use a message queue like Kafka with per-user partitions. But Kafka partitions are expensive — 10M partitions is impractical. I think the best approach is a hybrid: use Redis pub/sub for online delivery with the catch-up fallback, and use a persistent queue only for offline users who need push notifications. This limits the persistent queue size — only offline users need queued messages, and most DAU are online at any given time."))

    lines.append(("candidate", "Let me also think about the message storage model. We need two types of storage: the conversation log for message history, and per-user indexes for efficiently fetching a user's conversations and unread counts. The conversation log is a partitioned table keyed by conversation ID, with messages stored in sequence number order. This is optimized for range scans — when a user opens a chat, we fetch the last 50 messages with a single query. The per-user index maps user ID to their conversations with metadata like last message preview, last read sequence number, and unread count. This index powers the conversation list screen that every messaging app shows when you open it."))

    # SECTION 4: Deep Dive — Message Ordering, Group Fan-out, Read Receipts (~8 min)
    lines.append(("interviewer", "Let's deep dive into message ordering. How do you guarantee globally consistent ordering within a conversation?"))

    lines.append(("candidate", "Message ordering is one of the trickiest parts. The challenge is that multiple users can send messages to the same conversation simultaneously, and these messages might arrive at the Message Service via different Connection Servers at slightly different times. We need a single, consistent sequence number for all messages in a conversation. The simplest approach: assign sequence numbers at the Message Service level using a per-conversation atomic counter. When a message arrives, we increment the counter and assign the new value as the sequence number. This guarantees a total order within each conversation. With a single counter per conversation, we can use a Redis INCR command, which is atomic and fast — under 1ms."))

    lines.append(("candidate", "But with 10K messages per second across millions of conversations, the counter approach works because counters are per-conversation, not global. A busy conversation might have 10 messages per second, and the INCR handles that easily. For extremely popular group chats — like a company-wide announcement channel with thousands of messages per second — the single counter could become a bottleneck. In that case, we could use a range-based approach: allocate a block of 100 sequence numbers at a time, use them locally, and allocate a new block when exhausted. This amortizes the Redis call."))

    lines.append(("candidate", "Wait, there's a subtlety with the sequence number approach. The sender's client generates a temporary client-side ID and sends the message. The Connection Server forwards it to the Message Service, which assigns a sequence number and persists the message. But the sender needs to see their own message immediately — they can't wait for the round-trip to the Message Service. So the client optimistically displays the message with a local sequence number. When the server-assigned sequence number comes back, the client reconciles — if the order matches, great. If not, the client reorders. This optimistic UI approach is what WhatsApp and Messenger use. The key is that the final, persistent order is always the server-assigned sequence number, and all clients eventually converge to that order."))

    lines.append(("interviewer", "How do you handle the group fan-out efficiently? Sending a message to 256 recipients is expensive."))

    lines.append(("candidate", "Group fan-out is where the architecture gets interesting. A naive approach would have the Message Service individually write a delivery record for each of the 256 recipients. That's 256 database writes per message. At 10K messages per second, that could mean 2.56M database writes per second in the worst case — too expensive. Instead, I'd use a lazy delivery model. The Message Service writes the message once to the conversation's message log, along with the list of recipients. It does NOT create individual delivery records. Instead, each recipient's Connection Server pulls new messages for that user's conversations when they connect or when notified."))

    lines.append(("candidate", "Here's the optimized flow. The Message Service writes the message to the conversation log and publishes a notification to each recipient's channel — but the notification is lightweight, just the conversation ID and the new sequence number, not the full message. When a Connection Server receives a notification for a connected user, it fetches the actual message content from the Message Service (or a cache) and delivers it over WebSocket. This way, the database write is 1 per message, not 256. The read is per recipient, but reads are cheaper and can be cached. For online users, the message is fetched once from cache. For offline users, nothing happens until they connect, at which point they catch up."))

    lines.append(("candidate", "Actually, I want to reconsider this. The lazy pull model adds an extra round-trip — the Connection Server receives the notification, then fetches the message content. This adds latency. For chat, every millisecond matters. An alternative is to include the full message content in the notification. Redis pub/sub messages can include arbitrary data. So the notification carries the full message payload, and the Connection Server can push it to the client immediately without an extra fetch. The trade-off is larger pub/sub messages — 500 bytes times 256 recipients equals 128 KB per group message. At 3K group messages per second, that's 384 MB per second of pub/sub traffic. Redis handles this easily. I'd go with the eager push model for low latency and use lazy catch-up only for newly connecting users."))

    lines.append(("interviewer", "How do read receipts work?"))

    lines.append(("candidate", "Read receipts are per-recipient per-message. When Alice opens a conversation and reads Bob's message, her client sends a read-receipt event to the Connection Server, which forwards it to the Message Service. The Message Service updates the message's read status for Alice. It then notifies Bob — the sender — that his message has been read. This notification goes through the same pub/sub channel mechanism."))

    lines.append(("candidate", "The storage challenge with read receipts is that a group message with 256 recipients has 256 read statuses. Storing these individually — one row per recipient per message — is expensive. A group chat with 1000 messages per day and 256 members generates 256,000 read-receipt records per day. At scale, this is significant. I'd use a bitmap approach: for each message, store a 256-bit bitmap where bit N represents whether member N has read the message. This compresses the read status to 32 bytes per message regardless of group size. For 1-on-1 chats, a single boolean suffices. The bitmap is updated atomically when a read receipt arrives. To show Bob how many people have read his message, we count the set bits. To show Alice which messages she hasn't read, we compare her read bitmaps against the conversation's message list."))

    lines.append(("candidate", "Wait, there's a problem with the bitmap approach. If group membership changes — someone joins or leaves — the bit positions shift. We need a mapping from bit position to member ID that's versioned per conversation. When a member joins, they're appended to the member list and get the next bit position. When a member leaves, their bit is just unused — we don't compact the bitmap. This means the bitmap grows over time as members join and leave. For a group with high churn, the bitmap could become sparse and wasteful. A more practical approach: use a separate read-receipt table with columns (message_id, user_id, read_at), and index it by message_id. For querying unread counts, we use a per-conversation per-user watermark — the sequence number of the last message the user has read. All messages with sequence numbers above the watermark are unread. This is much simpler and how most chat systems actually implement it."))

    lines.append(("interviewer", "How does the watermark-based unread count work exactly?"))

    lines.append(("candidate", "Each user has a watermark per conversation — stored as (user_id, conversation_id, last_read_seq). When a user opens a conversation and reads messages, their client sends a request to update the watermark to the highest sequence number they have seen. The unread count is simply the number of messages in the conversation with sequence numbers above the watermark. To compute this efficiently, we cache the highest sequence number per conversation in Redis. The unread count is highest_seq minus last_read_seq. This is an O(1) computation — no database scan needed. When the user opens the app, we fetch all their conversation watermarks and the current highest sequences, compute unread counts for each conversation, and return them. This is fast — under 10ms for a user with 100 conversations."))

    # SECTION 5: Failure Modes (~4 min)
    lines.append(("interviewer", "What are the most critical failure scenarios?"))

    lines.append(("candidate", "The first is a Connection Server failure. If the server handling Alice's WebSocket crashes, her connection drops. The client detects this and reconnects to a different Connection Server. During the reconnection — which takes 1 to 3 seconds — messages sent to Alice are published to her pub/sub channel but not delivered because no server is subscribed. When she reconnects, the new Connection Server subscribes to her channel, and Alice sends her last-read sequence number to catch up. The Message Service returns any messages with higher sequence numbers. No messages are lost, just delayed by the reconnection time."))

    lines.append(("candidate", "The second scenario is a Message Service failure. If the service that handles message persistence and sequence number assignment crashes, new messages can't be persisted or assigned sequence numbers. Senders see their messages as pending — the client shows a clock icon instead of a check mark. We mitigate with multiple Message Service instances behind a load balancer. If one instance crashes, others take over. The sequence number counter is in Redis, which is highly available. The database writes go to a replicated PostgreSQL cluster. The system degrades to higher latency during failover but does not lose messages."))

    lines.append(("candidate", "The third scenario is a database failure. If the message database becomes unavailable, we can't persist new messages. We have two options: reject new messages entirely, or accept them into a temporary buffer and persist later. I'd choose the buffer approach — it's better for user experience. The Message Service writes incoming messages to a Kafka topic as a durable buffer. A consumer reads from Kafka and writes to the database when it recovers. The sequence number assignment also falls back to a Kafka-based ordering mechanism. This adds complexity but prevents message loss during database outages."))

    lines.append(("candidate", "The fourth scenario is a large group chat with heavy traffic overwhelming a single point. A group with 256 active members sending messages rapidly could create a hot spot on the conversation's sequence counter and message storage. We mitigate by sharding conversations across database shards — the conversation ID determines the shard. The sequence counter is per-shard in Redis, not a single global counter. For extremely hot conversations, we might need to move them to dedicated resources, but this is rare in practice."))

    lines.append(("interviewer", "What about end-to-end encryption? You mentioned it as a consideration. What are the design implications?"))

    lines.append(("candidate", "End-to-end encryption changes the architecture significantly. With E2E encryption, the server never sees the plaintext message content. This means server-side search becomes impossible — you can't index or search messages you can't read. Group key management is complex — every time a member joins or leaves a group, all members need to re-key so that new members can't read old messages and departed members can't read new ones. The Signal Protocol handles this with a sender key distribution system, but it adds message overhead for key exchange messages. Read receipts can still work because the receipt only indicates that a message was opened, not its content. Media files are encrypted client-side with a symmetric key, which is then encrypted with the recipient's public key and sent alongside the encrypted media. The server stores encrypted blobs and can't inspect them. The main trade-off is losing server-side features: no content moderation, no intelligent search, and no server-side message formatting. For a consumer app, E2E encryption is increasingly expected. For a business messaging platform, the compliance requirements might make it impractical."))

    # SECTION 6: Scale & Debrief (~3 min)
    lines.append(("interviewer", "How does the design change at 10x scale — 500M DAU?"))

    lines.append(("candidate", "At 500M DAU, concurrent connections could hit 100M. We'd need 1000 to 2000 Connection Servers. Redis pub/sub with 100M channels is pushing its limits — Redis uses memory for each channel, even empty ones. We might need to switch to a custom pub/sub system or use a sharded Redis cluster with 50 to 100 nodes. The message database at 2.6B messages per day needs aggressive sharding — maybe 100 shards partitioned by conversation ID. Kafka for the write buffer would need 500 partitions. The push notification service also scales — more offline users means more push notifications, and APNs and FCM have rate limits that we'd need to manage carefully. We'd batch push notifications and use connection pooling to the push providers."))

    lines.append(("candidate", "At 0.1x scale — 5M DAU — the design simplifies dramatically. Maybe 10 to 20 Connection Servers. A single Redis node for pub/sub and sequence counters. A single PostgreSQL instance with read replicas for message storage. No Kafka buffer — direct database writes are fine at 300 messages per second. The Presence Service could use a simple Redis set per connection server instead of a dedicated service. But the core flow — WebSocket delivery with pub/sub, catch-up on reconnect, sequence number ordering — stays the same."))

    lines.append(("interviewer", "Let me give you feedback. Positives: excellent requirements clarification — you asked about group size, ordering semantics, read receipts, online status, and encryption unprompted. The evolution of your fan-out design from naive per-recipient writes to lazy notification-and-pull to eager push with full content showed great iteration. Your self-correction on read receipts — from bitmaps to watermarks — was strong, recognizing the membership change problem. For improvement: when discussing end-to-end encryption, you mentioned it as a consideration but didn't discuss any of the design implications — how E2E encryption affects message search, server-side processing, and group key management. Even at a high level, touching on these trade-offs would have been valuable. Also, the optimistic UI with client-side sequence numbers and server reconciliation could lead to visible reordering — you should have discussed how to minimize the visual disruption when reconciliation happens. Overall, very strong. Thanks."))

    lines.append(("candidate", "Thanks for the feedback. You're right — E2E encryption has huge implications for search (you can't search server-side if messages are encrypted), group key management (every member change requires re-keying), and read receipts (the server can't aggregate read status without seeing message content). I should have discussed at least the search and key management challenges. And for the optimistic UI, I should have mentioned that the client can use a temporary local ordering that places the user's own messages at the bottom, and only reorders if other users' messages arrive with sequence numbers between the user's sent messages. This minimizes visible jumps. Good points."))

    return lines
