"""Mock Interview: Cross-Border Payments — Two-voice dialogue."""


def build():
    lines = []

    # SECTION 1: Requirements (~5 min)
    lines.append(("interviewer", "Hi, welcome. Today I'd like you to design a cross-border payment system — something like what Wise or Airwallex provides. Merchants and individuals need to send money from one country to another, potentially converting currencies along the way. Start by clarifying the requirements."))

    lines.append(("candidate", "Thanks. Cross-border payments are a deep domain, so the requirements really matter. Let me start with the most fundamental question: are we building the full payment stack ourselves — connecting directly to banking networks — or are we a layer on top of existing payment processors and banking partners? Because the complexity is very different depending on the answer."))

    lines.append(("interviewer", "Good starting question. We're building a layer that integrates with multiple banking partners and payment networks. So we handle the merchant-facing API, FX conversion, and then route payments through partner banks via SWIFT, SEPA, Faster Payments, and local rails. We're not connecting to card networks directly."))

    lines.append(("candidate", "OK, so we're a payment gateway with our own FX capability. Next I'd want to understand scale. How many transfers per second at peak, how many currency pairs, and what regions are we operating in? Also, are we supporting both business-to-business and consumer remittance, or just one segment?"))

    lines.append(("interviewer", "We handle about 5K TPS at peak, operating in 50 countries with 30 currency pairs. We serve both B2B and consumer, though B2B is the larger segment. We need to support same-day settlement for major corridors and next-day for others."))

    lines.append(("candidate", "5K TPS is substantial. The same-day settlement requirement is important — that means we can't just batch everything overnight. Let me ask about the FX side. Do we provide FX rates ourselves, or do we source them from external providers? And do we lock rates at quote time, or do we use real-time rates at payment time?"))

    lines.append(("interviewer", "We source rates from two external providers and aggregate them. We lock the rate at quote time for a configurable window — usually 30 seconds for consumer transfers and up to 5 minutes for B2B. After that, the rate expires and the customer needs a new quote."))

    lines.append(("candidate", "Rate locking is critical — it protects us from FX risk. A few more questions. First, idempotency: if a merchant retries a transfer due to a network timeout, we absolutely cannot send the money twice. Are we requiring clients to send idempotency keys? Second, what about compliance — KYC, AML, sanctions screening? Third, what happens when a payment fails at the bank side — do we automatically retry, or do we return the failure to the client?"))

    lines.append(("interviewer", "Yes, idempotency keys are required. Compliance is mandatory — every transfer goes through sanctions screening and AML checks. For bank failures, we retry automatically for transient errors like timeouts, but we return permanent failures like account closed to the client. We never double-send."))

    lines.append(("candidate", "Let me summarize. We're building a cross-border payment gateway with 5K TPS peak, 50 countries, 30 currency pairs, FX rate locking with configurable TTLs, idempotent transfers, mandatory compliance screening, automatic retry for transient bank errors, and same-day settlement for major corridors. Let me move to estimation."))

    # SECTION 2: Estimation (~5 min)
    lines.append(("interviewer", "Go ahead with the numbers."))

    lines.append(("candidate", "So 5K TPS at peak. Average TPS is probably 1 to 2K, so roughly 100 to 170K transactions per day. Wait, let me recalculate. 5K TPS times 3600 times 24 is 432 million per day if we were at peak all day. But peak to average is usually 3 to 5x, so average is about 1 to 1.7K TPS, giving us roughly 86 to 150 million transactions per day. Let's call it 100 million transactions per day as a round number."))

    lines.append(("candidate", "Read to write ratio — merchants check payment status frequently, and dashboards poll for updates. I'd estimate about 5 to 1. So at peak, 5K writes and 25K reads per second. With caching at 80% hit rate, the database sees about 5K reads per second. Storage per transaction: we have the payment record, FX quote details, compliance check results, ledger entries, and audit logs. Maybe 1 KB per transaction all in. At 100 million per day, that's about 100 GB per day. For 7-year retention, hot storage for 90 days is 9 TB, and cold storage for the rest is about 25 TB. Manageable with sharding."))

    lines.append(("interviewer", "What about the FX rate data? That's a separate storage concern."))

    lines.append(("candidate", "Right. FX rates update every 100 to 500 milliseconds for the 30 currency pairs. Each rate update is maybe 200 bytes — bid, ask, timestamp, provider ID. At, say, 10 updates per second across all pairs, that's about 200 bytes times 10 times 86400, which is roughly 170 MB per day of raw rate data. We don't need to keep all of this — we'd aggregate to minute-level snapshots for historical analysis, which is 30 pairs times 1440 minutes times 200 bytes, about 8.6 MB per day. Over 7 years, that's about 22 GB. Negligible. The hot rates live in Redis, not the database."))

    lines.append(("interviewer", "Let's dig into storage a bit more. What exactly goes into that 1 KB per transaction?"))

    lines.append(("candidate", "Good question, let me break it down. The transfer record itself is the biggest piece — about 400 bytes. That includes the transfer ID, merchant ID, sender and beneficiary details — name, account, bank code, maybe 120 bytes each — source and target currency, amount in both currencies, FX quote ID, status, timestamps for each state transition, and the idempotency key. Then the FX quote record is about 100 bytes — the quote ID, bid and ask rates, provider, locked rate, TTL, and expiry timestamp. The compliance check result is about 150 bytes — sanctions screening hit or clear, AML risk score, screening provider, and any flag details. The ledger entries are typically 4 per transfer, each about 50 bytes — account ID, amount, currency, entry type, and reference. So that's 200 bytes. And audit logs — who initiated the transfer, IP address, timestamp, and any manual review notes — are about 150 bytes. Total, roughly 1 KB. Some transfers with complex compliance flags might be 2 KB, but 1 KB is a reasonable average."))

    lines.append(("interviewer", "What about network bandwidth for the bank API calls? That's an important cost driver."))

    lines.append(("candidate", "Absolutely. Each bank API call has a significant payload compared to our internal traffic. A SWIFT MT103 message is about 500 to 800 bytes in the raw format. Our internal request to the Bank Connector — which includes the full beneficiary details, our internal payment ID, and routing instructions — is about 1 KB. The response from the bank varies — a simple acknowledgment is maybe 200 bytes, but a full status response with settlement details can be 500 bytes. So per transfer, we're looking at roughly 2 KB of outbound and 1 KB of inbound network traffic to banking partners. At 5K TPS peak, that's about 10 MB per second outbound and 5 MB per second inbound just for bank communication. That's about 80 Mbps outbound — well within a 10 Gbps link, but it's not negligible, especially if we're sending to multiple endpoints across different regions."))

    lines.append(("candidate", "There's also the compliance screening traffic. Each sanctions screening request to an external provider like Dow Jones or Refinitiv is about 500 bytes for the query and maybe 300 bytes for the response. AML checks are similar. So add about 1.5 KB per transfer for compliance. And FX rate provider polling — we're hitting two providers every 100 to 500 milliseconds for 30 currency pairs. That's about 600 requests per second, each maybe 200 bytes in and 500 bytes out, so about 300 KB per second inbound. Small but constant."))

    lines.append(("candidate", "Adding it all up — internal API traffic, bank communication, compliance, and FX — I'd estimate about 15 MB per second outbound and 8 MB per second inbound at peak. That's roughly 120 Mbps outbound and 64 Mbps inbound. We'd want at least a 10 Gbps backbone with dedicated connections to major banking partners, which is standard for payment processors. The key concern isn't raw bandwidth but latency — a 50 millisecond round-trip to a correspondent bank directly affects our settlement time."))

    # SECTION 3: High-Level Architecture (~5 min)
    lines.append(("interviewer", "Good. Let's move to the high-level architecture."))

    lines.append(("candidate", "Here's the overall flow. The merchant calls our Transfers API with an idempotency key, source currency, target currency, amount, and beneficiary details. The API layer validates the request, checks the idempotency store, and if it's a new request, forwards it to the Transfer Orchestration Service. This service is the brain — it coordinates all the steps. First, it calls the FX Service to lock a rate and get a quote. Then it calls the Compliance Service for sanctions screening and AML checks. If both pass, it creates a pending transfer record in the database and sends the transaction to the Ledger Service for double-entry bookkeeping. Then it calls the Settlement Service, which routes the payment to the appropriate banking partner via the Bank Connector layer. The Bank Connector abstracts away the protocol differences between SWIFT, SEPA, and local rails."))

    lines.append(("interviewer", "Why use a separate orchestration service instead of having the API layer handle the flow directly?"))

    lines.append(("candidate", "The orchestration service manages the multi-step transaction lifecycle, which can take seconds to hours depending on the banking rail. If we did this in the API layer, we'd hold HTTP connections open for too long, which doesn't scale. The orchestrator is async — it receives the request, starts the flow, and returns a pending status. It uses a saga pattern to coordinate the steps. If any step fails, the saga runs compensating actions — for example, if the bank rejects the payment after we've already debited the sender, we credit the money back. Each step publishes an event to Kafka, and the orchestrator consumes these events to advance the state machine."))

    lines.append(("interviewer", "Walk me through the saga for a successful cross-border transfer."))

    lines.append(("candidate", "Sure. Step 1: validate request and check idempotency. Step 2: lock FX rate — the FX Service returns a quote ID with a 30-second TTL. Step 3: run compliance checks — sanctions screening and AML. Step 4: create transfer record with status PROCESSING and write ledger entries — debit sender's account, credit FX suspense account. Step 5: submit to bank via the Bank Connector. Step 6: bank confirms acceptance — update transfer to ACCEPTED. Step 7: bank confirms settlement — update to SETTLED, write final ledger entries — debit FX suspense, credit beneficiary account. If step 5 fails permanently, the compensating action is to reverse the ledger entries and mark the transfer as FAILED. If step 5 times out and we don't know the status, we mark it as PENDING_INVESTIGATION and the reconciliation service handles it later."))

    # SECTION 4: Deep Dive — Idempotency, Ledger, and Bank Connectors (~10 min)
    lines.append(("interviewer", "Let's deep dive into the trickiest parts. How exactly does idempotency work end-to-end?"))

    lines.append(("candidate", "The client sends an Idempotency-Key header with each request. The API layer first checks a Redis-backed idempotency cache for this key. If it's found and the status is COMPLETED, we return the stored result immediately — same HTTP status code, same response body. If the status is PROCESSING, we return 202 Accepted with a polling URL. If the key is not found, we proceed. The first database transaction does two things atomically: INSERT into the idempotency_keys table with status PROCESSING, and INSERT the transfer record with status PENDING. We use ON CONFLICT DO NOTHING on the idempotency key column, which has a unique constraint per merchant. If the INSERT returns zero rows, the key already existed, and we fall back to reading the existing result."))

    lines.append(("candidate", "The reason we split this from the rest of the saga is that we can't hold a database transaction open while calling external services like FX providers and banks. So the idempotency check and transfer creation happen in one transaction, and then the orchestrator takes over asynchronously. When the saga completes — either successfully or with a failure — we update the idempotency key's status and store the result in a second transaction. If the server crashes between the first and second transaction, the key stays in PROCESSING. A background reaper scans for keys that have been PROCESSING for more than 5 minutes and resolves them by checking the transfer status."))

    lines.append(("interviewer", "What about the double-entry ledger? How do you handle cross-currency entries?"))

    lines.append(("candidate", "This is where fintech ledgers differ from regular accounting. Each currency has its own set of ledger accounts. For a USD to AUD transfer, we can't just debit USD and credit AUD in a single entry — they're different units. Instead, we use a three-entry approach. Entry 1: debit 1000 USD from the sender's account. Entry 2: credit 1000 USD to the FX suspense account. Entry 3: debit the equivalent AUD amount from the FX suspense account. Entry 4: credit that AUD amount to the beneficiary's account. The key insight is that entries 1 and 2 balance in USD, and entries 3 and 4 balance in AUD. The FX suspense account holds both currencies temporarily, and the FX gain or loss is recorded separately as a fifth entry if the actual settlement rate differs from the quoted rate."))

    lines.append(("interviewer", "What if the settlement rate differs from the quoted rate? Who bears the difference?"))

    lines.append(("candidate", "The rate is locked at quote time, so we guarantee the customer gets exactly the quoted rate. If the actual interbank rate when we settle is different, the difference is our FX gain or loss. For example, if we quoted 1.52 AUD per USD and settled at 1.53, we make a small profit. If we settled at 1.51, we take a small loss. This is why rate locking with a short TTL is essential — the longer we hold a locked rate, the more FX risk we carry. We'd also set limits on how much the locked rate can deviate from the current market rate — if a customer tries to use a quote that's more than, say, 0.5 percent off the current rate, we reject it and require a new quote."))

    lines.append(("interviewer", "Now let's talk about the Bank Connector layer. How do you handle the fact that every bank has a different API or protocol?"))

    lines.append(("candidate", "The Bank Connector uses the adapter pattern. We define a standard internal interface with methods like submitPayment, checkStatus, and getBalance. Then we implement one adapter per banking partner or protocol. The SWIFT adapter formats messages as MT103 or MT202, the SEPA adapter generates ISO 20022 XML pain.001 messages, the Faster Payments adapter uses a REST API, and so on. Each adapter handles the bank-specific quirks — like HSBC requiring a specific header format, or Citi needing a different date format. The Bank Router sits in front of the adapters and selects the best rail based on the payment's currency, amount, urgency, and cost. For a EUR to EUR payment within the EU, SEPA is cheapest. For a USD international wire, SWIFT is the only option."))

    lines.append(("candidate", "Each adapter has its own circuit breaker. If Bank A starts timing out, the circuit breaker opens and we route payments to Bank B if there's an alternative rail. If there's no alternative, we queue the payment and retry when the circuit closes. We also implement retry with exponential backoff for transient errors — but crucially, every retry carries the same idempotency key and our internal payment ID, so the bank can deduplicate if they receive the same message twice. For SWIFT, which is a store-and-forward network, this is especially important because acknowledgements can be delayed."))

    lines.append(("interviewer", "Tell me more about the reconciliation process. You mentioned it runs daily — how exactly does it work?"))

    lines.append(("candidate", "Reconciliation is the safety net that catches everything the real-time flow misses. It runs in three layers. The first layer is real-time reconciliation — every time we receive a bank confirmation, we match it against our pending transfers. This handles the happy path and most transient failures. The second layer is periodic reconciliation, which runs every 15 minutes. It queries our database for all transfers in PROCESSING or PENDING_INVESTIGATION status that have exceeded their expected settlement window — say, 2 hours for SEPA, 4 hours for Faster Payments, 24 hours for SWIFT. For each of these, it calls the bank's status API to get the current state. If the bank says SETTLED, we update our records. If the bank says REJECTED, we trigger the compensating saga. If the bank says they have no record of the payment, we need to investigate — maybe the submission failed before reaching the bank."))

    lines.append(("candidate", "The third layer is end-of-day reconciliation, which is the most thorough. We receive a daily statement file from each banking partner — typically an MT950 or camt.053 in ISO 20022 format. This file lists every transaction the bank processed on our behalf that day, with final statuses and amounts. Our reconciliation engine parses these files and matches each entry against our ledger, using a combination of our internal payment ID, the bank's reference number, amount, currency, and date. Matching is tricky because the bank's reference might not exactly match our payment ID — we include our reference in the SWIFT message's field 71A or the SEPA end-to-end ID, and the bank echoes it back, but sometimes there are formatting differences. We use a fuzzy matching algorithm that tries exact match first, then amount-plus-currency match, then amount-plus-currency-plus-date match. Any unmatched entries on either side go into an exceptions queue for manual review."))

    lines.append(("interviewer", "And the saga compensating actions — can you walk through exactly what happens step by step when something fails at each point?"))

    lines.append(("candidate", "Sure. Let me be very specific. The saga has six forward steps, each with a compensating action. Step 1 is request validation — no compensation needed, it's purely idempotent. Step 2 is FX rate locking — the compensation is to release the locked rate so it doesn't consume our FX provider quota. We call the FX Service with a release-quote command that decrements the lock count and removes the quote from Redis. Step 3 is compliance screening — no compensation needed, it's a read-only check. Step 4 is ledger entry creation — this is the most critical compensation. We write four ledger entries: debit sender, credit FX suspense in source currency, and the corresponding entries in target currency. The compensating action writes four reversing entries — credit sender, debit FX suspense in source currency, and the mirror in target currency. Each reversing entry references the original entry ID so auditors can trace the full chain. The transfer status moves to FAILED."))

    lines.append(("candidate", "Step 5 is bank submission. This is where it gets nuanced. There are three failure modes. First, the bank rejects the payment immediately — we get an explicit rejection response. Compensation: trigger the step 4 reversing entries and mark FAILED. Second, the bank times out — we send the payment but don't get an ACK within our timeout window, say 30 seconds. This is the dangerous case because the bank might have received and processed the payment, or it might not have. We cannot blindly compensate because we might reverse the sender's money while the payment is actually settling at the bank. Instead, we mark the transfer as PENDING_INVESTIGATION and hand it to the reconciliation team. A compensating action is queued but not executed — it's held in a pending state until reconciliation determines the bank's true status. Third, the bank accepts the payment but then later rejects it during settlement — this can happen hours later for SWIFT payments. The bank sends a return message, typically an MT103 return or a camt.056 rejection. Our Bank Connector receives this and publishes a payment-rejected event. The orchestrator consumes this event and triggers the full compensation flow — reversing ledger entries, releasing the FX lock, updating the transfer to RETURNED, and notifying the merchant."))

    lines.append(("candidate", "Step 6 is settlement confirmation. If the settlement amount differs from the quoted amount — which can happen with SWIFT due to correspondent bank fees — we write an additional ledger entry for the fee difference and an FX gain or loss entry. The compensation for a failed settlement confirmation would be to initiate a recall — we submit a recall request to the bank via MT192 or camt.056, which asks the beneficiary's bank to return the funds. Recalls are not guaranteed — the beneficiary might have already withdrawn the money. So we also have a manual process where the operations team contacts the beneficiary's bank directly for high-value recalls."))

    lines.append(("interviewer", "That's a detailed breakdown. One question — how do you prevent the compensating actions themselves from failing?"))

    lines.append(("candidate", "Great question. Each compensating action is implemented as an idempotent operation with its own retry logic. The reversing ledger entries use a compensating-entry ID that's derived from the original entry ID — so if the compensation is retried, the duplicate is detected and skipped. The FX rate release is naturally idempotent — releasing an already-released quote is a no-op. For bank recalls, we track the recall status and don't re-submit if one is already in progress. The orchestrator also has a dead letter queue — if a compensating action fails after all retries, it goes to the DLQ and the operations team is alerted. The key principle is that compensating actions must be at least as reliable as the forward actions they're reversing, otherwise we end up with inconsistent state."))

    # SECTION 5: Failure Modes (~4 min)
    lines.append(("interviewer", "What are the most critical failure scenarios?"))

    lines.append(("candidate", "The scariest failure is a bank accepting a payment but the confirmation getting lost. We've debited the sender, the money is moving, but our database thinks the payment is still PENDING. The reconciliation service handles this — it runs daily and compares our ledger against bank statements. Any discrepancy triggers an investigation. For more immediate detection, we also implement active status polling — for payments that have been in PROCESSING for more than the expected settlement time, we query the bank for the current status."))

    lines.append(("candidate", "Another critical failure is the FX rate provider going down. If both providers are unavailable, we can't generate new quotes. Existing locked quotes still work because they're stored in our Redis cache, but new transfer requests would need to be rejected with a clear error. We could also implement a fallback where we use the last known rate with a wider margin — say, quote at the last rate minus 1 percent to cover our FX risk — but this is a business decision, not a technical one. The compliance service going down is also critical — we cannot process any transfers without sanctions screening, so we'd reject new requests and queue existing ones until compliance is back."))

    lines.append(("interviewer", "What about data consistency — could the ledger ever be out of balance?"))

    lines.append(("candidate", "In normal operation, no — every transfer writes all ledger entries in a single database transaction. But there are edge cases. If we shard by account and a transfer involves accounts on different shards, we need a two-phase commit or a saga. I'd design the sharding so that all accounts for a single entity — the sender, the FX suspense, and the beneficiary — are on the same shard whenever possible. For the rare cross-shard case, I'd use a saga with compensating entries. And the reconciliation service runs a balance check every hour — it sums all entries per currency and verifies the total is zero. If it's not, it generates an alert for manual investigation. This is the financial equivalent of checksum verification."))

    lines.append(("interviewer", "What about a scenario that's specific to cross-border payments — a partial SWIFT failure where a correspondent bank rejects the payment?"))

    lines.append(("candidate", "That's a really important scenario and it's more common than people think. In the SWIFT network, a payment from, say, a US bank to a Philippine bank doesn't go directly. It goes through one or more correspondent banks — maybe a US correspondent that handles the USD side and a Philippine correspondent that has access to the local clearing system. Each hop in this chain can independently fail. So our bank might successfully send the MT103 to its correspondent, the correspondent forwards it, but then the second correspondent rejects it — maybe the beneficiary's account is closed, or there's a compliance flag at the intermediary bank, or the beneficiary bank is under sanctions."))

    lines.append(("candidate", "The tricky part is timing. The rejection might come back hours or even days later as an MT103 return message. During that entire window, our system shows the payment as ACCEPTED because our direct bank partner accepted it. The first indication of a problem is the return message. When the Bank Connector receives the return, it publishes a payment-returned event. The orchestrator handles this differently from a straightforward rejection. It creates a return transfer record linked to the original, writes reversing ledger entries, and initiates a refund to the sender. But there's a complication — the correspondent bank may have deducted fees during the failed transit, so the returned amount might be less than the original amount. We need to account for this fee difference in the ledger and decide whether we or the merchant absorbs it. This is typically defined in the merchant's service agreement — but from a technical perspective, we need to handle variable return amounts in our refund logic."))

    lines.append(("candidate", "There's also the scenario where we don't receive the return message at all — SWIFT doesn't guarantee return notifications. If a payment has been in ACCEPTED status for longer than the expected settlement window and we haven't received a confirmation or a return, the reconciliation service flags it for investigation. Our bank partner can send a SWIFT MT199 inquiry to trace the payment through the chain, but this is a manual process that can take days. During this investigation period, the sender's money is in limbo — we've debited them but the beneficiary hasn't received the funds. This is one of the biggest sources of customer complaints in cross-border payments, and it's why proactive status communication to the merchant is so important — even if the status is just UNDER_INVESTIGATION, it's better than silence."))

    lines.append(("interviewer", "Good. Any other failure modes worth mentioning?"))

    lines.append(("candidate", "One more — duplicate SWIFT messages. SWIFT is a store-and-forward network, and in rare cases, a message can be delivered twice due to network retransmission. This is different from our client-side idempotency problem — this is the bank receiving the same instruction twice. We protect against this by including a unique end-to-end reference in every SWIFT message — this is the field 20 in MT103. If the correspondent bank or beneficiary bank sees a duplicate reference, they should reject the second message. But not all banks implement this correctly, so we also monitor for suspicious patterns — if we see a settlement confirmation for a transfer that already has one, we alert the operations team immediately. Double-settlement is one of the most expensive failures in payments."))

    # SECTION 6: Scale & Debrief (~3 min)
    lines.append(("interviewer", "How does the design change at 10x scale — 50K TPS?"))

    lines.append(("candidate", "At 50K TPS, the database becomes the bottleneck. We'd need more shards — maybe 20 to 30 shards partitioned by a combination of merchant ID and region. The FX rate engine needs to handle more quote requests, but since it's mostly Redis lookups, it scales horizontally. The Bank Connector layer would need more connections and potentially more banking partners for load distribution. The compliance service needs to scale for parallel screening — we'd use a worker pool that processes screenings concurrently. And the reconciliation service, which is currently a single batch job, would need to be sharded — one reconciliation worker per database shard, running independently."))

    lines.append(("candidate", "More specifically at 10x, the Kafka event bus becomes critical infrastructure. At 5K TPS, a single Kafka cluster with a few partitions per topic is fine. At 50K TPS, we need to think about partitioning strategy carefully. We'd partition the transfer-events topic by merchant ID to maintain ordering guarantees per merchant — a merchant's transfers must be processed in order. With 50K merchants, we'd want maybe 200 to 500 partitions to distribute load. Consumer groups would scale to match — instead of 5 orchestrator instances, we'd run 50 to 100. Each instance consumes from a subset of partitions. The reconciliation service at 10x also can't afford to poll every pending transfer sequentially. We'd build an index on transfer status and expected settlement time, and the reconciliation query only selects transfers past their deadline, which is a much smaller set."))

    lines.append(("candidate", "There's also the regulatory dimension at 10x. More volume means more jurisdictions — if we're operating in 100 countries instead of 50, each with different reporting requirements, the compliance pipeline becomes significantly more complex. Some countries require real-time reporting of every transaction above a threshold. Others require monthly aggregates. We'd need a regulatory rules engine that can be configured per jurisdiction, rather than hardcoding each country's rules. This is a product-level investment, not just a scaling problem."))

    lines.append(("candidate", "At 0.1x scale — 500 TPS — everything simplifies. A single PostgreSQL instance with read replicas handles the load. No sharding. Redis is a single node. The saga could be simpler — maybe just sequential API calls instead of a full event-driven orchestration. But the idempotency mechanism and the double-entry ledger stay the same because correctness doesn't scale down. Even at low volume, you can't lose a payment or double-charge a customer. The reconciliation service could run as a cron job instead of a distributed service. The Bank Connector could use a single persistent connection per partner instead of a connection pool. The FX rate cache could be a single Redis key per currency pair instead of a sharded cache. But the domain logic — the saga steps, the ledger entries, the compliance checks — is identical regardless of scale."))

    lines.append(("candidate", "One thing that does change qualitatively at 0.1x is the operations model. At 50K TPS, manual intervention for every failed payment is impossible — you'd need hundreds of operations staff. So at 10x, you invest heavily in automated exception handling, self-healing reconciliation, and clear escalation rules. At 0.1x, a small team can manually investigate every exception, which means you can tolerate less automation and more ambiguity in failure handling. This actually affects the system design — at low scale, you might intentionally leave some edge cases for manual handling rather than building complex automated resolution logic."))

    lines.append(("interviewer", "Let me give you feedback. The positives: your requirements clarification was excellent — you asked about FX rate locking, idempotency, compliance, and bank failure handling unprompted. The three-entry cross-currency ledger explanation was clear and precise. Your saga design with compensating actions shows real understanding of distributed transactions. The detailed reconciliation breakdown and the SWIFT correspondent bank failure scenario were thorough. For improvement: you could have mentioned regulatory differences across jurisdictions earlier in the requirements phase rather than leaving it for the scale discussion — different countries have different reporting requirements which affects the data model from day one. Also, when discussing network bandwidth, you didn't address how cross-region latency between our data centers and banking partners affects the architecture — a payment routed through a Singapore data center to a European bank has very different latency characteristics than one routed locally. Overall, very strong. Thanks."))

    lines.append(("candidate", "Thanks for the feedback. You're right about regulatory requirements — I should have surfaced that in the requirements section when I asked about compliance. And cross-region latency is a critical operational concern, especially for the SWIFT adapter where we're communicating with banks across the globe — we'd need region-local Bank Connector instances and smart routing to minimize latency. I'll make sure to cover those next time."))

    return lines
