"""Mock Interview: Distributed Wallet — Two-voice dialogue."""


def build():
    lines = []

    # SECTION 1: Requirements (~5 min)
    lines.append(("interviewer", "Hi, welcome. Today I'd like you to design a distributed wallet system — think Airwallex's Auticuro or a multi-currency digital wallet that businesses use to hold, send, and receive money across 130-plus currencies. The system needs to be correct above all else — you cannot lose money, you cannot create money, and you cannot double-spend. Start by clarifying the requirements."))

    lines.append(("candidate", "Thanks. A wallet system is fundamentally a ledger, and correctness is everything — I completely agree. Let me start with the most basic question: are we building per-currency wallets, meaning each user or business has a separate balance per currency? Or is it a single pooled balance with a conversion layer? Because the data model and consistency guarantees are very different."))

    lines.append(("interviewer", "Per-currency wallets. A business might hold USD, EUR, GBP, and AUD simultaneously, and each currency balance is independent. They can convert between currencies, but conversion is a separate operation."))

    lines.append(("candidate", "OK, per-currency accounts. That's important — it means we need atomic cross-currency transfers where we debit one currency and credit another, and both must happen or neither. Next question: what's the scale? How many wallets, how many transactions per second, and what's the annual volume?"))

    lines.append(("interviewer", "We're handling 10K TPS at peak, with $50 billion in annual transaction volume. We support over 130 currencies. The system needs to be available globally, and we need P99 latency under 20 milliseconds for balance operations."))

    lines.append(("candidate", "10K TPS with P99 under 20 milliseconds — that's extremely tight. A traditional database with distributed transactions won't meet that latency target. And $50 billion annual volume means even tiny bugs — a rounding error, a double-spend — could cost millions. Let me ask about the transaction model. What operations does the wallet support?"))

    lines.append(("interviewer", "The core operations are: credit — add money to a wallet, debit — remove money from a wallet, transfer — atomically move money between two wallets, which could be same-currency or cross-currency, and batch operations — update multiple wallets atomically, like paying multiple beneficiaries from a single payer in one step. We also need hold and release for reservations — think of it as putting money aside temporarily, like when you authorize a payment but don't settle it yet."))

    lines.append(("candidate", "That hold-and-release pattern is important — it sounds like a TCC pattern: Try, Confirm, Cancel. Or more precisely, Reserve, Commit, Release. A few more questions. First, idempotency: if a client sends the same transfer request twice due to a network retry, we absolutely must not execute it twice. Are clients required to provide an idempotency key? Second, what about audit — regulators and compliance teams need a complete trail of every balance change, right? Third, are we dealing with exact arithmetic? Floating point is unacceptable for money."))

    lines.append(("interviewer", "Yes to all three. Clients provide a dedup_id for exactly-once semantics. Every state change must be recorded as an immutable event for audit — we're in a regulated financial domain. And yes, we use BigDecimal or equivalent — no floating point anywhere. Even a one-cent discrepancy is a bug."))

    lines.append(("candidate", "Let me summarize. We're building a multi-currency distributed wallet with per-currency accounts, 10K TPS at peak, P99 under 20 milliseconds, $50 billion annual volume, 130-plus currencies, atomic transfers including cross-currency, batch balance operations for multi-account atomicity, a TCC-style reserve and release pattern, client-provided dedup_id for exactly-once processing, complete audit trail via event sourcing, and BigDecimal arithmetic throughout. The correctness requirements dominate — this is a system where you cannot trade correctness for performance. Let me move to estimation."))

    # SECTION 2: Estimation (~5 min)
    lines.append(("interviewer", "Go ahead with the numbers."))

    lines.append(("candidate", "So 10K TPS at peak. Assuming peak-to-average ratio of about 3x, average TPS is around 3,300. That's roughly 285 million transactions per day. Let me sanity-check the $50 billion annual figure. If average transaction size is, say, $500, then at 3,300 TPS average, we get 3,300 times 500 times 86400 times 365, which is about $55 billion. Close enough — the numbers are consistent."))

    lines.append(("candidate", "Read-to-write ratio for a wallet system is interesting. Reads — balance checks, transaction history queries, audit lookups — vastly outnumber writes. I'd estimate 5 to 1 at minimum, possibly 10 to 1 for a system with dashboards and real-time monitoring. So at peak, 10K writes and 50 to 100K reads per second. That asymmetry is actually an opportunity — we can design a write path optimized for correctness and a separate read path optimized for throughput."))

    lines.append(("interviewer", "What about per-currency accounts? How many total accounts are we talking about?"))

    lines.append(("candidate", "Good question. If we have, say, 1 million wallet holders, and each holds an average of 5 currencies, that's 5 million currency-accounts. Some businesses might hold 20 or 30 currencies, but many individuals hold just 1 or 2. The 5 average seems reasonable. Each account needs a current balance and a reserved balance for the TCC pattern. So 5 million account records — that's small enough to fit in memory on a single machine, though we'd distribute for fault tolerance."))

    lines.append(("candidate", "Now storage for events. Every state change — credit, debit, transfer, reserve, release — generates an event for the audit trail. At 10K TPS, that's 10K events per second. Each event is maybe 200 to 500 bytes — event ID, account IDs, amounts in BigDecimal, currency, operation type, dedup_id, timestamp. Call it 300 bytes average. At 10K TPS, that's 3 MB per second, about 260 GB per day. For 7-year retention for compliance, that's about 670 TB. We'd keep recent events in fast storage for queries and archive older ones to object storage. The event log is append-only, which is friendly for storage optimization — compression could reduce this by 5 to 10x."))

    lines.append(("interviewer", "And the balance snapshot storage?"))

    lines.append(("candidate", "Right. We'd periodically snapshot the current state — all 5 million account balances — so we don't need to replay the entire event log to reconstruct state. A snapshot might be taken every few minutes. Each snapshot is 5 million accounts times maybe 100 bytes per account — balance, reserved amount, currency, version number — so about 500 MB per snapshot. At a snapshot every 5 minutes, that's about 144 GB per day. But we only need the latest snapshot for recovery, plus maybe the last few for rollback. So the active storage for snapshots is small — a few GB. The event log dominates."))

    # SECTION 3: High-Level Architecture (~5 min)
    lines.append(("interviewer", "Good. Let's move to the high-level architecture."))

    lines.append(("candidate", "Here's where the design gets interesting. Given the P99 under 20 milliseconds requirement at 10K TPS, I need to think very carefully about the write path. Let me start by considering the obvious approach — and then I'll explain why it doesn't work."))

    lines.append(("candidate", "The naive approach would be: put all the accounts in a distributed database — say, CockroachDB or Spanner — and use database transactions for atomicity. A transfer from Alice to Bob would be: BEGIN TRANSACTION, check Alice's balance, debit Alice, credit Bob, COMMIT. The database handles concurrency with MVCC and distributed consensus. But here's the problem: distributed transactions involve network round-trips between nodes for the two-phase commit protocol, and at 10K TPS with P99 under 20 milliseconds, we just don't have the latency budget. Even a single Raft round-trip within a data center is 1 to 3 milliseconds, and a distributed transaction involving multiple shards could easily hit 30 to 50 milliseconds at P99. So the distributed database approach won't meet our latency target."))

    lines.append(("interviewer", "What about sharding accounts to minimize cross-shard transactions?"))

    lines.append(("candidate", "That helps with throughput but not with the fundamental latency problem. Even within a single shard, you still have concurrency control — locks, MVCC version checks, conflict resolution. And at 10K TPS on a single shard, contention is high. Wait, let me reconsider. What if I use a different concurrency model entirely? Instead of multiple threads competing for shared state with locks, what if I... process all writes through a single thread?"))

    lines.append(("interviewer", "A single thread for all writes? At 10K TPS? How would that possibly work?"))

    lines.append(("candidate", "It sounds counterintuitive, but hear me out. A single thread processing commands sequentially means zero contention, zero lock overhead, zero deadlocks. Every operation is deterministic — the same commands in the same order produce the same state. And a single thread can process way more than 10K operations per second if the operations are simple — a balance check and update in memory is nanoseconds, not milliseconds. The bottleneck isn't CPU, it's IO. So the question becomes: how do we make the state machine durable and fault-tolerant while keeping it single-threaded?"))

    lines.append(("candidate", "The answer is: we use Raft consensus. The single-threaded state machine is the Raft state machine. All writes go through the Raft leader, which appends the operation to the Raft log, replicates it to followers, and once a majority acknowledges, the operation is committed and applied to the state machine. This gives us strong consistency and fault tolerance with automatic leader election. If the leader fails, a follower becomes the new leader within about 4 seconds — that's our RTO. The key insight is: Raft handles replication and consensus, and the state machine handles business logic. They're separated."))

    lines.append(("interviewer", "And the read path?"))

    lines.append(("candidate", "This is where CQRS comes in. The write path — through the single-threaded state machine — is optimized for correctness and consistency. The read path is separate and can scale horizontally. After the state machine processes a command, it publishes state changes as events. These events are consumed by read-optimized projections — basically, denormalized views of the current state stored in a database that's optimized for queries. Reads go directly to the projection database, which can have as many replicas as we need. The write path is single-threaded and fast, the read path is multi-threaded and scalable. They're decoupled."))

    lines.append(("candidate", "Let me describe the internal thread architecture of a single node. There are 4 threads, each with a single responsibility. Thread 1 is the gRPC Handler — it receives client requests, validates them, and submits them to the Raft log. Thread 2 is the Log Consumer — it reads committed entries from the Raft log and feeds them to the state machine. Thread 3 is the State Machine — the single-threaded engine that applies commands sequentially to update balances and produce events. Thread 4 is the Message Broker — it publishes state change events to the read path and external systems. The threads communicate through SPSC — single-producer single-consumer — queues. No locks, no shared mutable state between threads. The gRPC Handler produces Raft log entries, the Log Consumer consumes them, the State Machine consumes committed entries from the Log Consumer, and the Message Broker consumes events from the State Machine. Each queue is lock-free because there's exactly one producer and one consumer."))

    lines.append(("interviewer", "Why 4 threads specifically? Why not combine some of these?"))

    lines.append(("candidate", "We could combine the Log Consumer and State Machine — they're both sequential. But separating them allows the Log Consumer to batch-fetch committed entries while the State Machine is processing the previous batch, which improves throughput. The gRPC Handler must be separate because it does network IO — we don't want network latency blocking the state machine. The Message Broker must be separate because publishing events to external systems like Kafka or the projection database can be slow and unreliable — we absolutely cannot let a slow consumer block the state machine. So 4 threads is the minimum that keeps each concern independent and prevents any one concern from blocking another."))

    # SECTION 4: Deep Dive — State Machine, Exactly-Once, and Atomic Balance Updates (~10 min)
    lines.append(("interviewer", "Let's deep dive into the core of the system — the state machine, exactly-once semantics, and atomic balance updates. How does the state machine actually work?"))

    lines.append(("candidate", "The state machine is the heart of the system. It maintains an in-memory map of all account balances — the current balance and the reserved balance for each currency-account. When a command comes in — say, a transfer of 100 USD from Alice to Bob — the state machine does three things. First, it checks the dedup_id. Every command carries a client-provided dedup_id. The state machine keeps a cache of recently seen dedup_ids. If the dedup_id is in the cache, the state machine returns the cached result — the same response it returned the first time. This is how we get exactly-once semantics. If the dedup_id is new, the state machine validates the command — does Alice have at least 100 USD available? Available means current balance minus reserved balance. If the validation fails, it returns an error and caches that error with the dedup_id, so a retry gets the same error. If validation passes, it applies the command — subtract 100 from Alice's balance, add 100 to Bob's balance — and returns success."))

    lines.append(("interviewer", "Wait. The dedup_id cache is in memory. What happens if the node crashes and the cache is lost?"))

    lines.append(("candidate", "Excellent question, and this is a subtle point. The dedup_id is not just in memory — it's also persisted in the Raft log as part of the command. When the node restarts after a crash, it replays the Raft log from the last snapshot, rebuilding both the account balances and the dedup_id cache. So even after a crash, the state machine can detect duplicates. But there's a nuance: we don't want to keep dedup_ids forever — the cache would grow unbounded. We can expire dedup_ids after, say, 24 hours, because the client should have received a response by then. If a client retries a request after 24 hours with the same dedup_id, we treat it as a new request — the risk of a duplicate execution after that window is effectively zero."))

    lines.append(("candidate", "Actually, let me be more precise about the flow. When the gRPC Handler receives a request, it doesn't immediately check the dedup_id. It wraps the request — including the dedup_id — into a Raft log entry and submits it to the Raft cluster. Only after the entry is committed and the Log Consumer feeds it to the State Machine does the dedup check happen. This means the dedup_id is checked in the same sequential order as all other operations, which is what makes it correct. If we checked the dedup_id before submitting to Raft, we'd have a race condition — two concurrent requests with the same dedup_id could both pass the check and both be submitted to Raft."))

    lines.append(("interviewer", "And the persistence — how do you atomically persist the state changes?"))

    lines.append(("candidate", "This is where RocksDB WriteBatch comes in. When the state machine applies a command, it produces a set of state changes — for a transfer, that's two balance updates and a dedup_id entry. These must be persisted atomically — all succeed or all fail. We can't have a scenario where Alice's balance is updated but Bob's isn't. So we wrap all the writes in a single RocksDB WriteBatch. WriteBatch is atomic at the RocksDB level — it's written to the write-ahead log as a single entry and applied to the memtable as a single batch. If the node crashes mid-write, recovery replays the WAL, and the batch is either fully applied or not applied at all. This gives us atomic persistence without distributed locks or two-phase commit."))

    lines.append(("interviewer", "Let me push back. Why not just use database transactions — like PostgreSQL — and let it handle atomicity?"))

    lines.append(("candidate", "That's a fair question, and I considered it. But there are several reasons. First, PostgreSQL's transaction model uses MVCC and locking, which adds overhead we don't need. Our state machine is single-threaded — there's no concurrency to manage. We don't need MVCC because only one thread ever writes. Using PostgreSQL would be paying for concurrency control we don't use. Second, PostgreSQL is a separate process — there's a network hop between the state machine and the database, adding latency to every write. RocksDB is embedded — writes are local function calls. Third, and most importantly, consistency comes from Raft, not from the database. Once a command is committed in the Raft log, it's durable and agreed upon by a majority. The RocksDB WriteBatch is just the local persistence mechanism. If we used PostgreSQL transactions, we'd have two consistency mechanisms — Raft and PostgreSQL — and we'd need to coordinate them, which adds complexity without adding safety. Now, to be fair, PostgreSQL isn't wrong — if our latency target were 100 milliseconds instead of 20, it would work fine. But for our use case, RocksDB's embedded, low-latency writes are a better fit."))

    lines.append(("interviewer", "Now tell me about the batch balance operation. How do you atomically update multiple accounts?"))

    lines.append(("candidate", "The BatchBalanceOperation is one of the most elegant parts of the design. Consider a payroll scenario: an employer pays 100 employees from a single account. Without batch operations, you'd need 100 separate transfer commands, each going through Raft consensus independently — 100 round-trips, and if the 50th fails, you've already committed 49 transfers with no easy way to roll back. With BatchBalanceOperation, we package all 100 transfers into a single Raft log entry. The state machine receives the entire batch as one command, validates all 100 transfers — does the employer have enough funds to cover all of them? — and applies all 100 balance updates in a single WriteBatch. If any transfer in the batch is invalid — say, employee 50's account is frozen — the entire batch fails. This is all-or-nothing atomicity within a single Raft entry."))

    lines.append(("candidate", "The key insight is that because the state machine is single-threaded, atomicity across multiple accounts is trivial. There's no concurrency, so there's no possibility of a partial update being observed by another operation. The 100 transfers happen at a single point in the sequence — nothing can interleave. In a multi-threaded system with locks, you'd need to lock all 101 accounts — the employer plus 100 employees — in a consistent order to avoid deadlocks, and holding 101 locks while processing 100 transfers would cause massive contention. But with a single-threaded state machine, it's just a loop over the accounts. Simple, fast, and correct."))

    lines.append(("interviewer", "What about the TCC — reserve and release — pattern? How does that work with the state machine?"))

    lines.append(("candidate", "The TCC pattern — more precisely, the Reserve and Release pattern — handles distributed transactions without distributed locks. Here's the scenario: a payment gateway wants to debit a wallet, but the downstream settlement might fail. We can't just debit immediately because if settlement fails, we'd need to credit the money back, which creates an awkward reversal on the audit trail. Instead, we do a two-phase approach. Phase 1 is Reserve: the state machine checks if the account has sufficient available balance — current balance minus already reserved — and if so, moves the amount from available to reserved. The account now has a reserved balance. Phase 2 is either Confirm or Release. If the downstream settlement succeeds, the state machine moves the amount from reserved to a debit — the reserved balance decreases and the current balance decreases. If the downstream settlement fails, Release moves the amount from reserved back to available — the reservation is cancelled. The audit trail is clean: Reserve, then either Confirm or Release. No reversals needed."))

    lines.append(("candidate", "The important thing is that Reserve and Release are separate commands in the state machine, each with their own dedup_id. The payment gateway sends a Reserve command with dedup_id R1. The state machine records the reservation with a reservation ID. Later, the payment gateway sends a Confirm or Release command with the same reservation ID and a new dedup_id R2. The state machine looks up the reservation by ID and applies the appropriate action. If the payment gateway crashes after sending the Reserve but before sending the Confirm or Release, the reservation stays in the reserved state indefinitely. We need a timeout mechanism — if a reservation is older than, say, 7 days, a background process releases it automatically. This prevents reserved funds from being locked forever."))

    lines.append(("interviewer", "One more thing — the BigDecimal arithmetic. Why is this so critical, and how does it work in the state machine?"))

    lines.append(("candidate", "Floating point is a trap in any financial system. IEEE 754 double-precision can't exactly represent 0.1 — it's stored as 0.1000000000000000055511157. In a system processing $50 billion annually, these tiny differences accumulate, and they accumulate differently depending on operation order, which means your audit trail can't reproduce the exact same numbers. That's a compliance nightmare. BigDecimal solves this by storing numbers as arbitrary-precision integers with a scale factor. Every decimal is represented exactly. Arithmetic produces exact results. Division requires a rounding mode — we'd use HALF_EVEN, the standard banker's rounding. The tradeoff is performance, but BigDecimal addition takes maybe a microsecond. We have a 20-millisecond budget. Performance is not the concern — correctness is."))

    # SECTION 5: Failure Modes (~4 min)
    lines.append(("interviewer", "What are the critical failure scenarios for this system?"))

    lines.append(("candidate", "Let me start with the most important one: leader failover. In a Raft cluster, if the leader node crashes or becomes partitioned, the remaining nodes hold an election and a new leader is elected. The RTO — recovery time objective — is about 4 seconds. During those 4 seconds, the cluster is unavailable for writes. Reads from the projection database continue to work — they just serve slightly stale data until the new leader catches up. The key concern is: can a command be lost during failover? The answer is no, as long as it was committed by Raft. A command is committed when a majority of nodes have persisted it in their Raft log. If the leader crashes after committing a command but before responding to the client, the new leader has the command in its log and the state machine will apply it. The client might time out and retry with the same dedup_id, and the state machine will return the cached result. So no command is lost, and no command is duplicated."))

    lines.append(("interviewer", "What about network partitions? Can you get split-brain?"))

    lines.append(("candidate", "This is where Raft's majority requirement is crucial. In a 5-node cluster, you need 3 nodes to form a majority. If a network partition splits the cluster into 3 and 2, the group of 3 can elect a leader and process writes. The group of 2 cannot — it doesn't have a majority. So there's only one leader at any time, which means no split-brain. But there's a subtlety: what if the old leader is in the group of 2 and doesn't realize it's been partitioned? Raft handles this through term numbers. When the group of 3 elects a new leader, it increments the term. If the old leader in the group of 2 tries to commit a new entry, the followers in the group of 2 will reject it because they see a higher term from the new leader's heartbeats — wait, no, the group of 2 can't see the new leader's heartbeats because they're partitioned. But the old leader will eventually step down because it can't communicate with a majority — it can't commit entries, and Raft leaders step down if they can't reach a majority within the election timeout. So the old leader becomes a follower, and the cluster has exactly one leader."))

    lines.append(("candidate", "There's another failure scenario worth covering: what if the state machine applies a command but the WriteBatch only partially persists — say, Alice's balance is updated but Bob's isn't? This shouldn't happen because WriteBatch is atomic, but let's say there's disk corruption. On recovery, the state machine replays the Raft log from the last snapshot, reconstructing the correct state. The Raft log is the source of truth, not RocksDB. If RocksDB is corrupted, we rebuild it by replaying the Raft log. This separation is critical — it means we can always recover to a consistent state."))

    lines.append(("interviewer", "What if the Raft log itself is corrupted?"))

    lines.append(("candidate", "Raft log entries are replicated across multiple nodes. If one node's log is corrupted, the other nodes have correct copies. When the corrupted node restarts, it discovers that its log diverges from the leader's log, and the leader overwrites the divergent entries. This is part of the Raft protocol — the leader's log is authoritative. For extra safety, we could checksum each log entry and verify checksums on read. But in practice, the replication itself provides redundancy. The only scenario where log corruption causes data loss is if a majority of nodes simultaneously corrupt their logs in the same way, which is extremely unlikely."))

    lines.append(("candidate", "There's one more failure: a slow follower. If one of the 5 nodes falls behind, Raft handles this gracefully. The leader tracks each follower's log index, and if a follower falls too far behind, the leader sends it snapshots rather than individual log entries. The follower replaces its state with the snapshot and catches up on subsequent entries. Even a node offline for hours can catch up without blocking the leader."))

    # SECTION 6: Scale & Debrief (~3 min)
    lines.append(("interviewer", "How does this design scale beyond a single Raft group? 10K TPS is within a single group's capacity, but what about 100K TPS?"))

    lines.append(("candidate", "At 100K TPS, a single Raft group becomes a bottleneck because the leader must sequence all writes. The solution is sharding — partition accounts across multiple Raft groups, each with its own leader, state machine, and RocksDB instance. Each group handles a subset of accounts, and the groups operate independently. If we have 10 Raft groups, each handles 10K TPS. Reads scale even more because the projection database is shared-nothing — we just add more replicas."))

    lines.append(("candidate", "The challenge with sharding is cross-shard transactions — a transfer from Alice on shard 1 to Bob on shard 2. Within a single Raft group, atomicity is guaranteed by the single-threaded state machine. Across groups, we need a distributed protocol. The simplest approach is a two-phase commit across the Raft group leaders. The coordinator sends a prepare to both leaders, each leader's state machine reserves the funds using the TCC pattern, and if both reserve successfully, the coordinator sends confirm to both. If either fails, the coordinator sends release to both. The key is that the TCC pattern gives us distributed atomicity without distributed locks — each shard independently reserves or releases, and the coordinator just drives the protocol. This is slower than a single-shard transfer — maybe 40 to 60 milliseconds instead of 10 — but it's still fast and, more importantly, correct."))

    lines.append(("interviewer", "How do you handle the case where the coordinator crashes during a cross-shard transaction?"))

    lines.append(("candidate", "The coordinator logs its state to a durable store before sending each phase. If it crashes after sending prepare but before sending confirm or release, a recovery process reads the coordinator log, checks the status of each participant, and drives the transaction to completion. Each participant — the Raft group leader — has the reservation in its state machine, and reservations have timeouts. So if the coordinator crashes and never sends confirm or release, the reservations eventually time out and are automatically released. This is a self-healing mechanism. The coordinator recovery is for faster resolution — we don't want to wait for the timeout if we can resolve it immediately."))

    lines.append(("candidate", "For the sharding key, I'd use a compound key: business ID plus currency. This co-locates all accounts for the same business on the same shard, so internal transfers — like moving between a business's own currency accounts — are single-shard. Only transfers between different businesses cross shard boundaries. Since the majority of wallet operations are likely intra-business, this is a huge optimization."))

    lines.append(("interviewer", "At the other end, what if you had 0.1x the scale — 1K TPS? What would you simplify?"))

    lines.append(("candidate", "At 1K TPS, a single Raft group with 3 nodes instead of 5 might be sufficient — 3 nodes is the minimum for Raft majority, and at lower throughput, the reduced fault tolerance is acceptable. The read path could use fewer replicas. The RocksDB compaction could be less aggressive. But the fundamental architecture — single-threaded state machine, Raft consensus, CQRS, event sourcing — stays the same because correctness doesn't scale down. Even at 1K TPS, you can't lose money or double-spend. The only thing I might simplify is the sharding — a single Raft group handles all accounts, so no cross-shard transactions and no 2PC. But the state machine design, the dedup_id mechanism, the WriteBatch atomicity, the TCC pattern — all of these stay because they're correctness features, not performance features."))

    # SECTION 7: End-to-End Walkthrough (~4 min)
    lines.append(("interviewer", "Let's do an end-to-end walkthrough. Trace a transfer of 200 USD from Alice to Bob, going through all 4 threads on the leader node."))

    lines.append(("candidate", "Let me trace it step by step through each thread and queue. Alice wants to transfer 200 USD to Bob. She sends a gRPC request: TransferRequest with from_account=Alice:USD, to_account=Bob:USD, amount=200, currency=USD, dedup_id=abc123. Thread 1 — the gRPC Handler — receives the request. It validates the request format — are the account IDs well-formed? Is the amount positive? Is the currency valid? It then wraps the request into a Raft log entry — a byte array containing the serialized command — and submits it to the Raft library. The submission is asynchronous — the gRPC Handler doesn't wait for the entry to be committed. Instead, it registers a callback that will be invoked when the entry is committed. The gRPC Handler then picks up the next incoming request from the network."))

    lines.append(("candidate", "Meanwhile, the Raft library replicates the log entry to the followers. It sends AppendEntries RPCs to the 4 follower nodes, each containing the log entry. The followers write the entry to their own Raft logs and reply with success. Once the leader receives acknowledgements from a majority — that's 3 out of 5 nodes including itself — the entry is committed. The Raft library notifies the Log Consumer."))

    lines.append(("candidate", "Thread 2 — the Log Consumer — is waiting on the SPSC queue from the Raft library. When the entry is committed, the Raft library pushes it to the queue. The Log Consumer reads the entry, deserializes it, and pushes the command to the SPSC queue leading to the State Machine. It might batch multiple committed entries together to amortize queue overhead."))

    lines.append(("candidate", "Thread 3 — the State Machine — picks up the command from its input queue. It processes it sequentially. Step 1: check the dedup_id. It looks up abc123 in the dedup cache. It's not found — this is a new request. Step 2: validate. It looks up Alice's USD balance — say it's 1500 USD, with 0 reserved. Available balance is 1500, which is greater than 200. Validation passes. Step 3: apply. It subtracts 200 from Alice's balance — now 1300 — and adds 200 to Bob's balance — say, from 800 to 1000. Step 4: persist. It creates a RocksDB WriteBatch with three writes: update Alice's balance to 1300, update Bob's balance to 1000, and store the dedup_id abc123 with the result. The WriteBatch is committed atomically. Step 5: produce events. The State Machine creates a TransferCompleted event containing the transfer details — from, to, amount, timestamp, new balances — and pushes it to the SPSC queue leading to the Message Broker."))

    lines.append(("candidate", "Thread 4 — the Message Broker — picks up the event. It publishes to two destinations. First, the projection database — updating the read-optimized materialized view of Alice's and Bob's balances. Second, external systems — a Kafka topic for downstream consumers like notifications, audit, and analytics. The Message Broker handles retries and backpressure without blocking the State Machine, because they're on different threads connected by an SPSC queue."))

    lines.append(("candidate", "Meanwhile, back on Thread 1, the callback fires — the Raft library signals that the entry has been committed and applied. The gRPC Handler constructs the response — TransferResponse with status=SUCCESS, from_balance=1300, to_balance=1000 — and sends it back to Alice. The entire flow takes roughly 5 to 10 milliseconds in the happy path. The State Machine processing itself is maybe 50 microseconds. The bulk of the latency is Raft consensus — waiting for a majority of nodes to acknowledge the log entry — which is 2 to 5 milliseconds within a data center. Well within our 20-millisecond P99 target."))

    lines.append(("interviewer", "And if Alice retries the same request with the same dedup_id?"))

    lines.append(("candidate", "The flow is the same up until the State Machine processing. When the State Machine checks the dedup_id abc123, it finds it in the cache with a cached result — status=SUCCESS, from_balance=1300, to_balance=1000. It returns this cached result without modifying any balances. The Message Broker publishes a DuplicateDetected event for observability, but no balance changes are made. The client gets the same response as the first time. This is exactly-once semantics — the transfer was executed once, and the retry is a transparent no-op."))

    # SECTION 8: Thinking Process & Beats (~3 min)
    lines.append(("interviewer", "Before we wrap up, I want to share my thinking process for evaluating a wallet system design — the framework I use when I approach any problem in this domain."))

    lines.append(("interviewer", "When I see a wallet or ledger problem, the first thing I look for is whether the candidate recognizes that this is fundamentally a consistency problem, not a throughput problem. Can you guarantee that money is never lost, never created, and never double-spent? Everything else is secondary. If the candidate starts by talking about Kafka and microservices, that's a red flag. They should start by talking about state, consistency, and atomicity. The single-threaded state machine is the single most important design decision, and the candidate needs to discover it organically or justify it clearly."))

    lines.append(("interviewer", "The first beat I listen for is the rejection of distributed locks. Most candidates instinctively reach for distributed locks when they see concurrent balance updates. But distributed locks have liveness problems — if a lock holder crashes, the account is frozen during the timeout. They have performance problems — every operation requires a network round-trip to acquire the lock. And they have correctness problems — what's the lock granularity? Per-account? Per-currency? A batch operation needs 100 locks, which is a deadlock risk. The candidate who recognizes these problems and concludes that locks are wrong for this domain has taken the first critical step."))

    lines.append(("interviewer", "The second beat is arriving at the single-threaded state machine. The reasoning should go: if we process all writes sequentially, we eliminate concurrency, which eliminates the need for locks, which eliminates deadlocks, which eliminates a whole class of bugs. The throughput concern — can a single thread handle 10K TPS? — resolves because the operations are simple in-memory lookups and updates. The real bottleneck is the consensus protocol, not the state machine. This is the right tradeoff: we accept that write throughput is limited by the Raft leader in exchange for absolute correctness and simplicity."))

    lines.append(("interviewer", "The third beat is the dedup_id mechanism for exactly-once semantics. This is subtle because it interacts with Raft. The dedup_id must be checked inside the state machine, not before it — checking before submitting to Raft creates a race condition. It must be persisted in the same WriteBatch as the balance updates, so a crash can't lose the dedup without also losing the balance change. And the dedup cache must be bounded — you can't keep every dedup_id forever. These details separate real understanding from hand-waving."))

    lines.append(("interviewer", "The fourth beat is WriteBatch atomicity. The candidate needs to explain why atomic persistence matters — a partial write leaves inconsistent state — and how WriteBatch solves it. The deeper point is that the Raft log is the source of truth, and RocksDB is a materialized cache. If RocksDB is corrupted, we rebuild from the Raft log. This separation of consensus from persistence is what makes the system both correct and fast."))

    lines.append(("interviewer", "Now the traps. The biggest is distributed locks, which I've covered. The second is floating-point arithmetic — doubles are fast and familiar but wrong for money. The candidate should explicitly mention BigDecimal or integer-based arithmetic. The third is the missing audit trail — a wallet that only stores current balances without history is not compliant. Event sourcing isn't optional; it's a regulatory requirement. The fourth is over-engineering the write path — at 10K TPS, the single-threaded state machine handles it easily. Optimization effort should go into the read path. The fifth is hand-waving cross-shard transactions — the TCC pattern requires careful handling of coordinator failures and reservation timeouts."))

    lines.append(("interviewer", "To summarize: identify the problem as a consistency problem, reject distributed locks, arrive at the single-threaded state machine, layer on dedup_id for exactly-once, WriteBatch for atomic persistence, Raft for consensus, CQRS for read scalability, and TCC for cross-shard atomicity. Avoid the traps — no floating point, no missing audit trail, no premature write-path optimization, no hand-waved cross-shard atomicity. That's the mental model. Thanks for the discussion — you did well covering all these beats."))

    return lines