"""Mock Interview: Distributed Cache — Two-voice dialogue."""


def build():
    lines = []

    lines.append(("interviewer", "Hi. Today I'd like you to design a distributed cache — think Redis or Memcached, but we're building our own. Start with requirements clarification."))

    lines.append(("candidate", "Thanks. A distributed cache is one of those systems that seems simple but has really subtle consistency and availability challenges. Let me ask some clarifying questions. First, what operations do we need to support? Just basic get and set, or do we need more complex operations like atomic increments, sorted sets, and pub/sub? Because the data structure support significantly affects the design."))

    lines.append(("interviewer", "Let's start with get, set, and delete as the core. We also need support for time-to-live on keys and atomic increment. Sorted sets and pub/sub are out of scope for now."))

    lines.append(("candidate", "OK, that's a simpler model. Next, what's the scale? How many nodes, how much data, and what QPS are we targeting? Also, what's the expected latency — are we talking sub-millisecond like Memcached, or is single-digit milliseconds acceptable?"))

    lines.append(("interviewer", "We need to support 1 million operations per second across a cluster of up to 100 nodes. Total data size is up to 1 terabyte. Latency should be sub-millisecond for cache hits, and we need 99.9% availability."))

    lines.append(("candidate", "1M QPS and 1 TB across 100 nodes — that's about 10 GB per node and 10K QPS per node, which is reasonable. Sub-millisecond latency means we need to keep everything in memory with no disk access on the hot path. Let me ask about consistency. In a distributed cache, when a key is updated on one node, how quickly do other nodes need to see the new value? Strong consistency would require coordination, which adds latency. Eventual consistency is faster but can serve stale reads."))

    lines.append(("interviewer", "Good question. We want strong consistency for writes — once a set operation returns successfully, subsequent gets must return the new value. But we can tolerate a brief window of stale reads if it significantly improves performance. What would you recommend?"))

    lines.append(("candidate", "For a cache, I'd recommend a primary-owner model with consistency on the owner node. Each key has a designated owner node determined by consistent hashing. Writes go to the owner and are replicated asynchronously to replica nodes. Reads from the owner are strongly consistent. Reads from replicas might be briefly stale but are much faster because they can be served from any nearby replica. This gives us sub-millisecond reads in the common case and strong consistency when it matters most. Let me also ask about eviction policy — when the cache is full, what's the eviction strategy?"))

    lines.append(("interviewer", "Support both LRU and TTL-based eviction. The client chooses per key. Let me summarize: 1M QPS, 1 TB, 100 nodes, sub-millisecond latency, owner-based consistency with async replication, LRU plus TTL eviction. Let's move to estimation."))

    lines.append(("candidate", "Sure. Let me work through the numbers. 1M QPS across 100 nodes means 10K QPS per node. At 10K QPS per node with sub-millisecond latency, each request needs to complete in under 1 millisecond, which means the entire operation — hash lookup, memory access, response serialization — must stay on the order of microseconds. A well-optimized hash table lookup in memory is about 100 to 200 nanoseconds, so we have headroom, but we need to be careful about lock contention and memory allocation overhead."))

    lines.append(("candidate", "For throughput, 1M QPS sustained means about 86.4 billion operations per day. If we assume 60% reads, 30% writes, and 10% deletes, that's 600K reads, 300K writes, and 100K deletes per second. Each operation involves a key lookup in the hash table — the key is typically 20 to 50 bytes, and values average maybe 1 KB based on typical cache workloads. So the data stored is about 1 TB as given. At 10 GB per node, each node's hash table holds roughly 10 million key-value pairs."))

    lines.append(("interviewer", "What about memory overhead? You can't just say 10 GB of data needs 10 GB of RAM."))

    lines.append(("candidate", "Right, there's significant overhead. The hash table itself has overhead — open addressing with a load factor of 0.7 means we allocate about 1.4x the space for the table entries. Each entry needs a key pointer, value pointer, TTL timestamp, and LRU list pointers — that's about 48 bytes of metadata per entry. For 10 million entries per node, that's 480 MB of metadata alone. Then there's the key and value storage — 10 million keys at 30 bytes average is 300 MB, and 10 million values at 1 KB average is 10 GB. So the total memory per node is roughly 10 GB data plus 300 MB keys plus 480 MB metadata plus 1.4 GB hash table overhead, which is about 12 GB. We'd provision 16 GB per node to leave headroom for fragmentation and temporary allocations. Across 100 nodes, that's 1.6 TB of total RAM for 1 TB of data — a 1.6x overhead ratio, which is reasonable."))

    lines.append(("candidate", "Network bandwidth is another consideration. At 1M QPS with an average request size of 50 bytes for keys and 1 KB for values, read responses consume about 600K times 1 KB which is 600 MB per second of outbound data just for reads. Write requests bring in about 300K times 1 KB which is 300 MB per second of inbound data. Including request overhead, headers, and replication traffic — each write is replicated to 2 replicas, so add 600 MB per second of internal replication traffic — the total network traffic is about 1.5 GB per second across the cluster, or 15 MB per second per node. That's about 120 Mbps per node, well within a 10 Gbps network. But the replication traffic adds up — we need to account for it in our capacity planning, especially during rebalancing when large amounts of data move between nodes."))

    lines.append(("interviewer", "Good numbers. Now let's move to the architecture."))

    lines.append(("candidate", "The core architecture uses consistent hashing to distribute keys across nodes. When a client wants to read or write a key, it hashes the key and finds the responsible node on the hash ring. We use virtual nodes — each physical node maps to, say, 100 to 200 virtual nodes on the ring — to ensure even data distribution. The client side has a smart client library that knows the cluster topology and can route requests directly to the right node, avoiding a proxy layer that would add latency."))

    lines.append(("interviewer", "Walk me through what happens when a client sets a key."))

    lines.append(("candidate", "The client library hashes the key using MurmurHash3, maps it to a position on the ring, and identifies the owner node. It then sends a SET request directly to that node over a persistent TCP connection. The owner node stores the key-value pair in its in-memory hash table, updates the LRU list, and sets the TTL timer if one was specified. It then asynchronously replicates the write to one or two replica nodes — the next nodes clockwise on the ring. The SET response is returned to the client as soon as the owner has persisted the write to its memory. The client doesn't wait for replication. This gives us sub-millisecond write latency with the trade-off that if the owner crashes before replication completes, we could lose the last few writes."))

    lines.append(("interviewer", "Now walk me through GET and DELETE with the same level of detail."))

    lines.append(("candidate", "For GET, the client hashes the key, identifies the owner node, and sends a GET request directly. The owner looks up the key in its hash table. If found, it checks the TTL — if the key has expired, it deletes it lazily, increments the expired-keys counter, and returns a cache miss. If the key is valid, it updates the LRU position — moves this key to the head of the LRU list — and returns the value. The entire operation is a hash lookup plus a list node move plus a memory copy, which should complete in under 100 microseconds on the server side. If the owner is down, the client can fall back to reading from a replica, but it gets a potentially stale value. We mark the response with a stale-read flag so the client knows."))

    lines.append(("candidate", "For DELETE, the process is similar — hash the key, send a DELETE to the owner. The owner removes the key from the hash table, removes it from the LRU list, cancels any TTL timer, and frees the memory. The delete is asynchronously replicated to replicas. One subtlety: deleting a key that doesn't exist is a no-op and returns success — we don't distinguish between deleting an existing key and deleting a non-existent one. This simplifies the client logic and avoids leaking information about what keys exist, which is a minor security consideration."))

    lines.append(("candidate", "There's also the atomic increment operation, which is more complex. INCR must be read-modify-write and must be atomic — no two clients should increment the same key concurrently and lose an update. The owner node handles this by keeping a per-key spinlock. When an INCR request arrives, the owner acquires the lock, reads the current value, parses it as an integer, adds the increment, writes back the new value, updates the LRU position, and releases the lock. Since this all happens on the owner node in memory, the lock is held for microseconds — well within our latency budget. The updated value is then asynchronously replicated. If two clients INCR the same key simultaneously, one of them will wait for the spinlock, but the wait time is negligible."))

    lines.append(("interviewer", "Is that trade-off acceptable? Losing writes in a cache?"))

    lines.append(("candidate", "It depends on what the cache is used for. If it's a pure cache — meaning all data is also in the authoritative database — then losing a cache entry is fine because it just results in a cache miss and a fallback to the database. But if clients are using the cache as a primary data store — like using Redis as a session store or rate limiter — then data loss is not acceptable. For the primary data store use case, we'd need synchronous replication — the owner waits for at least one replica to acknowledge the write before responding to the client. This adds a network round-trip to every write, maybe 0.5 to 1 millisecond within the same data center, which is still fast but not sub-millisecond. I'd make this configurable per namespace or per key."))

    lines.append(("interviewer", "Let's talk about memory management. How do you allocate and free memory for key-value pairs efficiently?"))

    lines.append(("candidate", "This is one of the most important implementation details, and it's where naive approaches fall apart. If we use malloc and free for every SET and DELETE, we'd suffer from severe memory fragmentation — after running for a while, we'd have lots of small free blocks that can't satisfy larger allocations, even though the total free memory is sufficient. This is the classic fragmentation problem that killed many early cache implementations. The solution is slab allocation, which is what Memcached uses. We pre-allocate memory in slabs — each slab is a fixed-size chunk, say 1 MB. Within each slab, all items are the same size. We have slab classes for different sizes — class 1 for items up to 64 bytes, class 2 for items up to 128 bytes, class 3 for items up to 256 bytes, and so on, doubling each time up to the maximum value size, maybe 1 MB."))

    lines.append(("candidate", "When a SET request arrives with a 300-byte value, we find the smallest slab class that fits — class 3 for 256 bytes is too small, so we use class 4 for up to 512 bytes. If there's a free slot in an existing slab of class 4, we use it. If not, we allocate a new 1 MB slab and divide it into 512-byte slots — that gives us 2048 slots per slab. When a key is deleted or evicted, its slot is returned to the slab's free list. This eliminates external fragmentation completely — we never have small unusable gaps between allocations. The trade-off is internal fragmentation — a 300-byte value uses a 512-byte slot, wasting 212 bytes. On average, the waste is about 25% of the value size because each value is placed in a slot up to 2x its size. But this is far better than the unbounded fragmentation of malloc."))

    lines.append(("interviewer", "How do you handle the case where one slab class is heavily used while another is mostly empty? Can you reassign slabs?"))

    lines.append(("candidate", "This is called slab rebalancing and it's a real operational problem. Imagine a workload where most values are small — say 80 bytes — so slab class 2 is constantly full and evicting keys, while slab class 6 for 2 KB values is mostly empty. We'd want to take a slab from class 6 and reassign it to class 2. The challenge is that the slab from class 6 contains live items — we can't just repurpose it. The rebalancer works by selecting a slab from the underutilized class, evicting all items in that slab — either by moving them to other slabs of the same class if there's room, or by simply evicting the LRU items — and then reformatting the slab for the target class. This is a background process that runs slowly to avoid disrupting foreground traffic. Redis takes a different approach — it doesn't use slabs at all, instead it uses jemalloc which handles fragmentation reasonably well for general-purpose allocation. But for a dedicated cache where we control the workload pattern, slabs are more predictable and have bounded fragmentation."))

    lines.append(("interviewer", "Now let's deep dive into the LRU implementation. How exactly do you maintain the LRU order efficiently?"))

    lines.append(("candidate", "The classic LRU implementation uses a doubly-linked list plus a hash table — the hash table maps keys to their list nodes, and the list maintains the access order. When a key is accessed, we move its node to the head of the list. When we need to evict, we remove the tail of the list. The problem with this approach in a high-throughput cache is lock contention — every access modifies the list, and a single global list with a single lock becomes a bottleneck at 10K QPS per node. Redis solved this with an approximate LRU — it doesn't maintain an exact access order. Instead, each key has a 24-bit timestamp of its last access time. When eviction is needed, Redis randomly samples 5 keys and evicts the one with the oldest timestamp. This is probabilistic — it might not evict the true LRU key — but it's very fast because there's no list manipulation and no lock contention."))

    lines.append(("candidate", "I'd use a hybrid approach. For each slab class, we maintain a separate doubly-linked list, so we have N independent LRU lists instead of one global list. This reduces contention because operations on different slab classes don't interfere. Each list is protected by its own spinlock — since list operations are just pointer swaps taking microseconds, the spinlock hold time is minimal. For even less contention, we could use a lock-free linked list, but the complexity isn't worth it given that spinlock-based lists already perform well. Within each slab class's LRU list, we maintain exact order — every access moves the key to the head. When we need to evict from a slab class because it's full, we take the tail of that class's list. This is more accurate than Redis's approximate LRU and still performs well because the contention is spread across many lists."))

    lines.append(("interviewer", "What about TTL expiry? How do you efficiently expire keys without scanning the entire dataset?"))

    lines.append(("candidate", "TTL expiry has two mechanisms — lazy expiry and active expiry. Lazy expiry is simple: when a key is accessed via GET, we check its TTL timestamp. If the current time exceeds the TTL, we delete the key and return a miss. This costs almost nothing because we're already looking at the key. But lazy expiry alone has a problem — keys that are never accessed again sit in memory forever, wasting space. So we also need active expiry. Active expiry uses a timing wheel — a circular array of slots, where each slot represents a time interval, say 100 milliseconds. When a key is SET with a TTL of 30 seconds, we calculate which slot it falls into — slot number equals expiry time modulo the wheel size — and add the key to a linked list in that slot. A background thread advances the wheel pointer every 100 milliseconds and processes all keys in the current slot, deleting expired ones. This gives us O(1) insertion and roughly O(1) per-key expiry check."))

    lines.append(("candidate", "The timing wheel approach is efficient but has a subtlety — if a massive batch of keys all expire at the same time — say, a cache warmup that set 1 million keys with a 1-hour TTL — the background thread would need to delete 1 million keys in one tick, causing a latency spike. To prevent this, the active expiry thread limits itself to processing a fixed number of keys per tick — say, 1000 — and if there are more, it spreads the remaining work across subsequent ticks. The keys that haven't been actively expired yet are still subject to lazy expiry, so they'll be cleaned up when accessed. The trade-off is that some expired keys might linger in memory for a few extra seconds, but in practice this is fine because they're taking up space that would otherwise be used for new keys, and the next SET that needs that slab slot will evict the expired key via LRU anyway."))

    lines.append(("interviewer", "Let's deep dive into consistent hashing and what happens when nodes are added or removed."))

    lines.append(("candidate", "This is where consistent hashing really matters. In a traditional hash mod N approach, if N changes — say we add a node — almost every key gets remapped, which causes a massive data shuffle. Consistent hashing minimizes this. When a node joins, it takes over the key range between its position and the previous node's position on the ring. Only the keys in that range need to move. Similarly, when a node leaves, its keys are taken over by the next node on the ring. With virtual nodes, the data movement is evenly distributed across all remaining nodes."))

    lines.append(("candidate", "The process works like this. When a new node joins, the cluster metadata is updated — the ring configuration now includes the new node's virtual nodes. The new node contacts the nodes that own the key ranges it's responsible for and requests the data for those ranges. The donor nodes stream the data to the new node. During this transfer, reads and writes for the affected keys still go to the original owner. Once the transfer is complete, the cluster metadata is updated again to redirect traffic for those key ranges to the new node. There's a brief period where both the old and new node could serve reads for the same key range, so we need a clean switchover."))

    lines.append(("interviewer", "What about node failures? If a node crashes, what happens to its data?"))

    lines.append(("candidate", "Each key has a primary owner and one or two replicas. If the primary crashes, the first replica is promoted to primary. The client library detects the failure — either through a connection error or a gossip protocol notification — and redirects requests for those keys to the new primary. The promoted replica already has a copy of the data from the async replication, so reads continue to work. The only risk is the data that was written to the old primary but not yet replicated — that data is lost. If we configured synchronous replication, there's no data loss, but higher write latency."))

    lines.append(("candidate", "After the promotion, we need to restore the replication factor. The system selects another node to be the new replica and starts copying data from the new primary. This is a background process that doesn't block foreground operations. We also need to update the cluster metadata so the client library knows about the new topology. We use a gossip protocol for this — each node periodically exchanges state information with a few random peers, and changes propagate through the cluster within a few seconds."))

    lines.append(("interviewer", "How would you handle a network partition — a split brain scenario?"))

    lines.append(("candidate", "This is one of the hardest problems. If we have a partition, both sides could accept writes for the same key, leading to conflicts. For a cache with strong consistency, we need to ensure that only one partition can accept writes for a given key. I'd use a majority quorum approach. The owner and its replicas form a replication group. Writes require acknowledgment from a majority of the group — for a group of 3, that means 2 out of 3. In a partition, only the side with the majority can accept writes. The minority side rejects writes and returns errors to clients. This is essentially the Raft consensus algorithm applied to each replication group. It adds some latency to writes but prevents split-brain conflicts."))

    lines.append(("interviewer", "What are the other failure scenarios you'd worry about?"))

    lines.append(("candidate", "Hot keys are a big concern. If one key gets disproportionate traffic — say, a viral celebrity's profile cached in our system — the owner node for that key becomes a bottleneck. We'd handle this with client-side local caching — the client library caches hot keys in process memory with a short TTL, so repeated reads don't even hit the distributed cache. We could also implement read replicas specifically for hot keys — multiple copies distributed across different nodes, with reads load-balanced across them."))

    lines.append(("candidate", "Another failure is the gossip protocol getting stuck — if the cluster metadata is inconsistent, clients might route requests to the wrong node. We'd implement a heartbeat mechanism where each node sends regular heartbeats to a monitoring service. If a node misses too many heartbeats, it's marked as suspected, and after a timeout, as confirmed down. The cluster then triggers the failover process. We'd also add a metadata version number that increments with each topology change, so clients can detect if they have stale routing information."))

    lines.append(("interviewer", "What about hot keys? You mentioned local caching, but what if we need to migrate a hot key to distribute load?"))

    lines.append(("candidate", "Hot key migration is a different problem from hot key caching. Local caching helps with read-heavy hot keys, but what about write-heavy hot keys — like a counter that's incremented on every page view? The owner node for that key becomes a bottleneck because all writes go to it. The first line of defense is client-side batching — the client library batches increments locally and sends a single INCRBY with the accumulated count every 10 to 100 milliseconds, reducing the write QPS to the owner by 10 to 100x. This is what Redis does with its pipeline feature."))

    lines.append(("candidate", "But if the key is truly hot — millions of reads per second — we need to replicate the key across multiple owner nodes. This is called hot key replication. Instead of one owner, we designate, say, 10 owners for the same key. Each owner holds a full copy. For reads, the client picks a random owner, distributing the read load. For writes, we have a problem — updating 10 owners atomically is expensive. For counters, we use a sharded counter approach — each of the 10 owners maintains a partial counter, and when the full value is needed, we read all 10 and sum them. This is an eventually consistent counter — you lose atomic increment visibility across shards, but for use cases like page view counts, eventual consistency is fine. For hot keys that need strong consistency on writes, we can't shard — we have to accept the bottleneck or use a different data structure like a CRDT that supports merge without coordination."))

    lines.append(("candidate", "The migration process itself is interesting. When the monitoring system detects a hot key — say, a key receiving more than 10x the average QPS — it triggers a migration plan. The system creates additional replicas on lightly loaded nodes, copies the current value, and starts directing a portion of read traffic to the new replicas. Write traffic still goes to the original owner, which propagates updates to the new replicas. Over a few seconds, the load is distributed. The tricky part is ensuring the replicas converge — for a sharded counter, the partial values might temporarily be inconsistent, but the system self-corrects as the partial counters accumulate new increments."))

    lines.append(("interviewer", "What happens when a node runs out of memory? The OOM scenario."))

    lines.append(("candidate", "OOM is one of the most dangerous failure modes for an in-memory cache. When a node is about to run out of memory — we track memory usage and trigger eviction at, say, 85% capacity — the LRU eviction kicks in. We evict keys from the tail of each slab class's LRU list until memory usage drops below 80%. But there's a scenario where eviction can't keep up: if the incoming write rate exceeds the eviction rate, memory fills up faster than we can evict. This can happen during a traffic spike or a cache warmup that loads a lot of new data."))

    lines.append(("candidate", "When memory reaches 95%, we enter a critical state. At this point, we have two options. The first is to reject new writes — we return a NOMEM error to clients, who then fall back to the database. Reads still work for existing keys, and deletions and evictions continue to free memory. This is the safer approach because it protects existing data and lets the system self-heal as traffic subsides. The second option is to evict more aggressively — instead of evicting only from the tail of the LRU list, we evict from a wider range, sampling more keys and evicting any that haven't been accessed recently. This is more disruptive but keeps accepting writes. I'd prefer option 1 because in a cache, rejecting a write is always safe — the worst case is a cache miss, not data loss."))

    lines.append(("candidate", "There's also the question of what happens to a single node's OOM at the cluster level. If one node is full but others have capacity, the cluster should detect this and redistribute the key ranges. The full node signals its state to the cluster coordinator, which triggers a partial rebalance — some of the full node's key ranges are migrated to nodes with available memory. This is different from a node failure — the full node is still healthy, just at capacity. The migration is lower priority and slower to avoid disrupting the cluster. We'd also want to alert the operations team, because persistent memory pressure usually indicates that the cluster is undersized for the workload and needs more nodes."))

    lines.append(("interviewer", "Good. Let me give you feedback. The positives: you identified the consistency trade-off early and proposed a reasonable owner-plus-replica model. Your explanation of consistent hashing and virtual nodes was clear, and the data transfer process during rebalancing was thorough. The hot key problem and local caching solution showed good operational awareness. The slab allocation and memory management discussion was solid, and the timing wheel for TTL expiry was a nice detail. For improvement: when discussing the Raft-based quorum approach, you added significant complexity — you should have discussed the performance implications more honestly. Raft adds a network round-trip to every write and requires a leader election during failover, which can take seconds. For a cache where sub-millisecond latency is the goal, this might not be acceptable. A simpler approach like last-write-wins with conflict resolution might be more appropriate. Also, you could have discussed the cold cache warmup problem — when the entire cluster restarts after a deployment, all keys are lost and the database gets hammered. Overall, solid work. Thanks."))

    lines.append(("candidate", "Thanks. You're right about Raft being heavy for a cache — I should have been more honest about that trade-off and proposed a lighter alternative. And memory management is definitely something I should have covered — slab allocation like Memcached uses would prevent fragmentation and keep eviction efficient. The cold cache warmup is a great point too — I'd handle that with a gradual warmup where we pre-populate the cache from the database at a controlled rate, maybe loading the top 10% of keys first based on access frequency, and letting the rest fill in via cache misses. Appreciate the feedback."))

    lines.append(("interviewer", "Before we wrap up, how does this design change at 10x scale and 0.1x scale?"))

    lines.append(("candidate", "At 10x scale — 10M QPS and 10 TB — we'd need about 1000 nodes instead of 100. The consistent hashing ring scales naturally — more nodes mean smaller key ranges per node, and rebalancing moves less data per event. But the gossip protocol becomes a concern — with 1000 nodes, gossip convergence takes longer, maybe 10 to 20 seconds instead of 2 to 3. We might need a more structured membership protocol like SWIM with suspicion mechanisms, or even a centralized metadata service like etcd that stores the ring configuration and pushes updates to clients. The smart client library also needs optimization — with 1000 nodes and 200 virtual nodes each, that's 200,000 virtual nodes on the ring. The client needs an efficient data structure to find the owner for a given hash. A sorted array with binary search is O(log N) where N is 200,000 — about 18 comparisons, which is fine. But we'd also need to handle topology updates more carefully — with 1000 nodes, failures and additions happen frequently, and the client must quickly update its routing table."))

    lines.append(("candidate", "At 10x scale, the replication traffic also becomes significant. 10M QPS with 300K writes per second — wait, let me recalculate. At 10M QPS with 30% writes, that's 3M writes per second, each replicated to 2 replicas, so 6M replication messages per second. At an average of 1 KB per value, that's 6 GB per second of internal replication traffic across the cluster. We'd need a dedicated replication network or use RDMA for intra-cluster communication to avoid competing with client traffic. Cross-data-center replication for disaster recovery adds another dimension — we'd use asynchronous batch replication to the DR site, sending batches of writes every 100 milliseconds to amortize the WAN round-trip cost."))

    lines.append(("candidate", "At 0.1x scale — 100K QPS and 100 GB — we could run on 10 nodes with 16 GB RAM each, or even 5 nodes with 32 GB each. The gossip protocol is trivially fast at this size. We might skip virtual nodes entirely — with only 5 to 10 physical nodes, the distribution is already even enough. The replica count could be reduced to 1 instead of 2 to save memory. And the client library could be simpler — maybe even a proxy-based approach where a stateless proxy routes requests, instead of requiring a smart client. The proxy adds a network hop, but at 100K QPS a single proxy instance handles it easily, and it simplifies client integration significantly. The key insight is that at low scale, simplicity beats efficiency — a proxy that adds 0.5 milliseconds of latency is fine when your SLA is sub-millisecond plus the proxy overhead, which still keeps you under 2 milliseconds."))

    lines.append(("candidate", "One thing that doesn't change at any scale is the correctness model — the slab allocator, the LRU eviction logic, the TTL expiry mechanism, and the consistency guarantees are the same whether you have 5 nodes or 1000. What changes is the operational complexity — monitoring 5 nodes is easy, monitoring 1000 requires automated alerting, capacity planning, and self-healing rebalancing. At 0.1x, a node failure is an incident that wakes up an engineer. At 10x, node failures are expected and handled automatically."))

    return lines
