"""Mock Interview: Feature Store / ML Infrastructure — Two-voice dialogue."""


def build():
    lines = []

    # SECTION 1: Requirements (~5 min)
    lines.append(("interviewer", "Hi, welcome. Today I'd like you to design a Feature Store — the ML infrastructure platform that data scientists use to define, compute, serve, and share features for model training and inference. Think about systems like Airwallex's AirSkiff, which is their open-source Java streaming feature store. Start by clarifying the requirements."))

    lines.append(("candidate", "Thanks. Feature stores solve a fundamental problem in ML engineering: the gap between training and serving. Data scientists compute features in notebooks using batch data, then engineers have to reimplement the same logic in real-time serving code. The two implementations drift, and models get features at inference time that don't match what they were trained on. So the core requirement is: write feature logic once, use it for both batch training and real-time serving. But let me dig deeper. Who are the users — data scientists, ML engineers, or both? And what kinds of models are we serving?"))

    lines.append(("interviewer", "Both data scientists and ML engineers use it. The primary use case is risk and fraud models — transaction fraud detection, credit risk scoring, AML. These models need real-time features during inference, like how many transactions a user made in the last hour, or the velocity of payments in the last 24 hours. They also need the same features computed over historical data for training, with point-in-time correctness to prevent data leakage."))

    lines.append(("candidate", "Fraud models are the killer app for feature stores — they need both real-time velocity features and historically accurate training data. Point-in-time correctness is critical — training on features that include future information relative to the prediction time causes data leakage that silently degrades model performance. Let me ask about scale. How many feature groups, how many serving queries per second, and what's the latency requirement for online serving?"))

    lines.append(("interviewer", "About 1000 feature groups across all teams, with roughly 100 to 200 features per group. Serving load is 10K TPS at peak. Latency requirement is 2 to 150 milliseconds for feature retrieval during inference, with p99 under 50 milliseconds. Features need to be fresh — real-time features should reflect events within the last few seconds. And multiple teams need to discover and share features — the risk team shouldn't have to reimplement the payment team's velocity features."))

    lines.append(("candidate", "Let me clarify a few more things. First, what's the feature computation model — are features computed on every event, on a schedule, or on demand at query time? Second, what data sources feed the features — Kafka streams, database changelogs, batch files? Third, is this a purely internal platform, or are we open-sourcing parts of it like AirSkiff?"))

    lines.append(("interviewer", "Features are computed both on every event for streaming features and on a schedule for batch features. Data sources are Kafka for real-time transaction events, database changelogs via CDC for account and user updates, and daily batch files from data warehouses for slower-moving features like credit scores and merchant category codes. It's internal for now, but the architecture should support open-sourcing the core computation engine, which is what AirSkiff does."))

    lines.append(("candidate", "Let me summarize. We're designing a Feature Store for ML models, primarily fraud and risk, with 1000 feature groups, 10K TPS serving, p99 latency under 50 milliseconds. Core requirements: batch and streaming feature computation from the same logic, point-in-time joins for training to prevent data leakage, real-time feature serving with sub-second freshness, a feature registry for discovery and reuse across teams, and an architecture that supports open-sourcing. Data sources are Kafka, CDC, and batch files. Let me move to estimation."))

    # SECTION 2: Estimation (~5 min)
    lines.append(("interviewer", "Go ahead with the numbers."))

    lines.append(("candidate", "Starting with feature groups. 1000 feature groups with 100 to 200 features each means roughly 100K to 200K individual features. Not all are served online — maybe 60 percent are online-serving features and 40 percent are batch-only training features. So about 60K to 120K features in the online store at any given time."))

    lines.append(("candidate", "Serving: 10K TPS with each request fetching maybe 100 features for a fraud model inference. That's 1 million feature lookups per second at p99 under 50 milliseconds. But there's a nuance — features are per-entity, so a single request fetches many features at once. If we store all features for an entity as a single row, that's 10K row reads per second, not 1 million individual lookups. Much more manageable — 2 to 3 Redis nodes handle that easily."))

    lines.append(("interviewer", "Good observation on entity-level grouping. What about storage for the offline store?"))

    lines.append(("candidate", "Offline store holds the full feature history for training. An entity — say a user — has maybe 10 feature groups applicable to them. Each feature group produces one row per time window per entity. For velocity features with daily windows over 90 days, that's 90 rows per entity per feature group. With 10 million active users and 10 feature groups, that's 9 billion rows. Each row is about 1 KB — 100 to 200 feature values at 8 bytes each, plus entity ID, timestamp, and version metadata. Nine billion rows at 1 KB is 9 TB for 90 days. With Parquet compression at 3 to 5x, that's about 2 to 3 TB on disk. Very manageable with a data lakehouse like Delta Lake or Iceberg."))

    lines.append(("candidate", "Online store is much smaller — just the latest feature values per entity per feature group. With 10 million active entities and 10 feature groups, that's 100 million rows at 1 KB each — about 100 GB in Redis. With compression and TTL for inactive entities, maybe 50 GB of actual memory. A 3-node Redis cluster with 32 GB each handles that with room to spare."))

    lines.append(("interviewer", "What about the streaming computation layer — how much compute do you need for real-time feature updates?"))

    lines.append(("candidate", "Real-time feature computation consumes from Kafka. At 5K to 10K transactions per second, each transaction triggers updates for maybe 5 to 10 feature groups — velocity features for the payer, payee, card, device, and merchant. So 25K to 100K feature group updates per second. Each update reads current feature values from the online store, applies the aggregation, and writes back — 50K to 200K online store operations per second from computation alone. The Redis cluster handles this comfortably."))

    lines.append(("candidate", "Compute for the streaming engine itself: at 100K updates per second with 1 millisecond of CPU per update, that's about 100 CPU cores. With overhead for serialization, window management, and state checkpoints, 200 to 300 cores across a Flink cluster. Memory for windowed state: 1 to 5 KB per entity times 10 million active entities equals 10 to 50 GB, or 100 to 200 GB with replication and overhead."))

    # SECTION 3: High-Level Architecture (~5 min)
    lines.append(("interviewer", "Good estimates. Let's move to the high-level architecture."))

    lines.append(("candidate", "The Feature Store has four major components: the computation engine, the offline store, the online store, and the feature registry. Let me walk through the data flow. Features are defined in the registry — a feature group specifies the entity key, the feature columns, the data source, and the computation logic. The computation engine has two modes: streaming and batch. In streaming mode, it consumes events from Kafka, applies the feature transformation logic, and writes updated feature values to the online store in real time. In batch mode, it reads historical data from the data warehouse, applies the same feature logic, and writes the results to the offline store for training."))

    lines.append(("candidate", "The key architectural principle is batch-streaming unification. The same feature definition produces both real-time features for serving and historical features for training. This is the Kappa architecture applied to feature computation — batch is just a special case of streaming. In AirSkiff's design, a leftJoin is point-in-time by default, which means when you join features to a training dataset, you get the feature values as they existed at the event timestamp, not the latest values. This prevents data leakage without requiring the data scientist to think about temporal correctness."))

    lines.append(("interviewer", "Why is Kappa architecture the right choice here? Why not Lambda with separate batch and stream processing?"))

    lines.append(("candidate", "The Lambda architecture for feature stores is a maintenance nightmare. You have two codepaths — a streaming job that computes features in real time and a batch job that computes the same features over historical data. They're written in different frameworks — maybe Flink for streaming and Spark for batch — with different semantics. Windowing behaves differently, late data handling differs, aggregation logic drifts over time. The result is training-serving skew — the model sees different feature values at inference time than it saw during training. This is exactly the problem the feature store is supposed to solve."))

    lines.append(("candidate", "Kappa avoids this by having a single computation engine. The streaming job processes events as they arrive. For backfill — computing features over historical data — you replay historical events through the same streaming job, just from an earlier offset. The computation logic is identical. This is what AirSkiff does: the same Java-based processing logic handles both real-time and historical computation. The batch path is just the stream path with a bounded data source. The only difference is where the output goes — streaming outputs to both online and offline stores, batch backfill outputs only to the offline store."))

    lines.append(("interviewer", "Walk me through the feature registry. What does it store and how does it integrate with the rest of the system?"))

    lines.append(("candidate", "The feature registry is the catalog and metadata layer. It stores feature group definitions — entity key, feature columns, data source, computation logic, and version. It tracks feature group lineage — which raw data sources feed which feature groups, and which feature groups are consumed by which models. It manages feature group versions — when a team updates a feature computation, a new version is created so existing training datasets aren't silently broken. And it provides discovery — data scientists can search for existing features by entity type, team, or keywords, and see documentation, statistics, and usage counts."))

    lines.append(("candidate", "The registry integrates with every other component. The computation engine reads feature definitions from the registry to know what to compute. The serving layer uses the registry to resolve which feature groups and versions to fetch for a given model. The training dataset builder — the component that creates point-in-time training datasets — uses the registry to join the right feature group versions at the right timestamps. And data scientists use the registry UI to discover features and understand their semantics before using them in models. Without the registry, feature stores devolve into a collection of undocumented data pipelines with no reuse."))

    lines.append(("interviewer", "How does a data scientist actually create a training dataset with point-in-time features?"))

    lines.append(("candidate", "The data scientist writes a training dataset query that specifies: the entity ID, the event timestamp for each training example, and the feature groups to join. The training dataset builder executes a point-in-time join against the offline store. For each training example with entity ID and timestamp T, it looks up the latest feature values for that entity from each feature group where the feature group's event timestamp is less than or equal to T. This is a left join with a temporal condition — you get the feature snapshot as it existed at time T, not the current feature values. If no feature value exists before T, you get null. This is exactly what AirSkiff's leftJoin does by default — it's point-in-time without requiring explicit temporal predicates."))

    lines.append(("candidate", "The alternative — a naive join — would use the latest feature values regardless of timestamp, leaking future information. At inference time, those future events don't exist yet, so the model's performance collapses. Point-in-time joins are not optional — they're a correctness requirement."))

    # SECTION 4: Deep Dive — Point-in-Time Joins, Batch/Streaming Unification, and Feature Serving (~10 min)
    lines.append(("interviewer", "Let's deep dive into the three trickiest areas. Start with point-in-time joins — how do you implement them efficiently at scale?"))

    lines.append(("candidate", "Point-in-time joins are essentially ASOF joins — for each left-side row with an entity key and timestamp, find the closest right-side row with the same entity key and a timestamp less than or equal to the left-side timestamp. The naive implementation scans the feature table for each training example, which is O(n times m) — catastrophic at scale. The efficient implementation uses the fact that feature values are stored with event timestamps and sorted by entity key and timestamp within each feature group."))

    lines.append(("candidate", "In the offline store, feature data is stored in Parquet files partitioned by feature group, then by date, then by entity key hash. For a point-in-time join, the builder first filters to the relevant time range, then co-partitions the training examples and feature data by entity key. For each entity, both datasets are sorted by timestamp, and the join becomes a merge join — walk both sorted streams simultaneously, and for each training example, the latest feature row seen so far is the point-in-time match. This is O(n plus m) after the sort, and the sort is cheap since data is already partitioned by entity."))

    lines.append(("interviewer", "What about feature groups with high update frequency — say, a velocity feature that updates every second for active users? That's a lot of rows in the offline store."))

    lines.append(("candidate", "High-frequency feature groups are a storage and join performance challenge. A velocity feature for 10 million users updating every second produces 864 billion rows per day — clearly infeasible. In practice, we don't store every streaming update in the offline store. Instead, we snapshot at a coarser granularity — for example, every minute or every 10 minutes. The streaming computation updates the online store every second for serving freshness, but writes to the offline store every minute. This reduces offline storage by 60 to 600x while preserving sufficient temporal resolution for point-in-time joins. Most training datasets don't need second-level granularity — if a fraud model predicts on transactions that occurred at time T, knowing the velocity feature at T minus 30 seconds versus T minus 1 second rarely changes the model's decision."))

    lines.append(("candidate", "For the rare cases where sub-minute granularity matters — say, a model that detects fraud within seconds of the first suspicious transaction — we can store the raw events in the offline store and compute the feature at join time. This is more expensive but available as an option. The feature registry records the offline storage granularity so data scientists know the temporal resolution of their training data."))

    lines.append(("interviewer", "Now let's deep dive into batch and streaming unification. How exactly does the same feature logic work in both modes?"))

    lines.append(("candidate", "The unification works through a shared feature definition language and a common computation engine. A feature group is defined once — say, transaction_velocity_features with entity key user_id, features like txn_count_1h, txn_count_24h, txn_count_7d, txn_amount_sum_1h, and data source Kafka topic transactions. The computation logic specifies windowed aggregations: count events within 1-hour, 24-hour, and 7-day tumbling windows, sum the amount within 1 hour. This definition is stored in the feature registry."))

    lines.append(("candidate", "In streaming mode, the computation engine — a Flink or AirSkiff job — reads this definition, subscribes to the Kafka topic, and processes events in real time. For each transaction event, it updates the windowed state for the corresponding user_id — incrementing counts, adding amounts to sums, handling window transitions when the 1-hour or 24-hour boundary passes. Updated feature values are written to the online store and also to the offline store as a snapshot."))

    lines.append(("candidate", "In batch mode — for backfill or recomputation — the same computation logic reads from a bounded source: historical transaction events stored in the data warehouse, maybe as a Parquet table. The engine processes these events in timestamp order, applying the same windowed aggregation logic. Because the data is bounded, the engine knows when each window closes and can finalize aggregations without waiting for late data. The output is identical in structure to the streaming output — same feature columns, same entity key, same timestamp semantics. The only difference is the input source and the absence of late data handling."))

    lines.append(("interviewer", "What happens when there's a bug in the feature logic and you need to recompute historical features?"))

    lines.append(("candidate", "This is where unification really pays off. The team fixes the feature definition in the registry — incrementing the version — and triggers a backfill. The computation engine replays historical events through the corrected logic and writes new feature values to the offline store under the new version. Old training datasets built on the old version are unaffected because they reference the version explicitly. New training datasets use the new version. The online store is updated by deploying the corrected streaming job, which starts computing new feature values going forward. The windowed state for the streaming job needs to be rebuilt from the backfilled offline data — we initialize the streaming job's state from the latest offline snapshot, then start consuming new events from that point. This is the bootstrap pattern, and it's how AirSkiff handles streaming job restarts."))

    lines.append(("interviewer", "Now let's deep dive into feature serving. How do you achieve 2 to 150 millisecond latency with 10K TPS?"))

    lines.append(("candidate", "Feature serving has two patterns: precomputed and on-demand. Precomputed features are the majority — velocity counts, historical sums, aggregated stats. These are computed by the streaming engine and materialized in the online store. At serving time, the feature server does a simple key-value lookup: given entity_id, fetch all feature group rows for that entity. With entity-level co-location in Redis — storing all feature groups for an entity in a single hash or sorted set — one Redis HGETALL per entity per request. At 10K TPS, that's 10K Redis reads per second. A 3-node Redis cluster handles this at sub-millisecond latency for the 99th percentile."))

    lines.append(("candidate", "On-demand features are computed at query time because they depend on the request context. For example, distance_from_home requires the current transaction location from the request and the user's home location from the profile — you can't precompute this because you don't know the transaction location until inference time. The feature server reads stored features, applies the on-demand transformation, and merges with precomputed features. This adds compute latency but avoids precomputing features for every possible request context."))

    lines.append(("interviewer", "What about the serving API itself? What does the inference service actually call?"))

    lines.append(("candidate", "The feature server exposes a get_features API that takes an entity_id, a list of feature group names and versions, and optional request context for on-demand features. The server resolves the feature groups from the registry, fetches precomputed values from the online store, computes on-demand features, and assembles the feature vector in the order expected by the model. The model-specific feature ordering is stored in the registry — the model expects features in a specific order, and the server must return them consistently, matching the order used during training. The server also handles missing features — if a feature group has no data for an entity, the server returns a default value or null flag."))

    lines.append(("candidate", "Caching is important for serving efficiency. The feature server caches feature registry metadata — which feature groups and versions to fetch for each model — so it doesn't hit the registry on every request. It also caches online store responses for hot entities — a user making multiple transactions in quick succession has their features fetched multiple times within seconds. A short TTL cache of 1 to 2 seconds catches these repeat accesses without serving stale data for more than a second or two. At 10K TPS with maybe 5K distinct active entities per second, the cache hit rate could be 30 to 50 percent, reducing online store load significantly."))

    lines.append(("interviewer", "How do you handle feature freshness? Real-time features should reflect events within seconds, but the online store might have stale data due to streaming delays."))

    lines.append(("candidate", "Freshness is a monitoring concern as much as a technical one. The streaming engine writes feature updates to the online store as events are processed. In normal operation, the delay from event occurrence to online store update is 1 to 5 seconds — Kafka consumer lag, processing time, and Redis write latency. The feature server reports a staleness metric per feature group — the difference between the current time and the feature's event_timestamp. If staleness exceeds a threshold — say, 30 seconds for a velocity feature — the feature server can either return the stale value with a staleness flag or fall back to a degraded mode, like using a slightly older snapshot. The model can use the staleness flag to decide whether to trust the feature or rely more on other inputs."))

    lines.append(("candidate", "For critical features where freshness is paramount — like real-time fraud scoring — we can use a push-based approach instead of pull-based. The streaming engine pushes feature updates to the online store and simultaneously notifies the feature server via a lightweight notification — a Redis pub/sub message or a gRPC stream. The feature server can then invalidate its cache immediately and serve the freshest value on the next request. This reduces the effective staleness from seconds to milliseconds, at the cost of slightly more complex serving logic."))

    # SECTION 5: Failure Modes (~4 min)
    lines.append(("interviewer", "What are the most critical failure scenarios for the feature store?"))

    lines.append(("candidate", "The scariest failure is stale features during inference. The streaming job falls behind — maybe Kafka has a partition rebalance or the Flink cluster hits a memory pressure issue — and the online store stops updating. The fraud model is making decisions on velocity features that are minutes or hours old. It might approve a fraudulent transaction because the velocity count hasn't been updated to reflect the current burst. This is a silent failure — the model doesn't crash, it just makes worse decisions. The detection relies on staleness monitoring — if the streaming lag exceeds the threshold, we alert the ML platform team and flag affected model predictions for review."))

    lines.append(("candidate", "The second critical failure is online store outage. If Redis goes down, the fraud model has no features. The inference service needs a fallback: serve with a reduced feature set from a secondary cache, use default values for missing features, or switch to a rule-based system. This degraded mode hurts model performance, but it's better than blocking all transactions."))

    lines.append(("candidate", "The third is data leakage from incorrect point-in-time joins. If the training dataset builder has a bug — say, it uses a regular join instead of an ASOF join — the model trains on future data and appears to perform well in backtesting but fails in production. This is the most insidious failure because it's invisible until the model is deployed and you compare online metrics to offline metrics. Prevention requires rigorous testing of the point-in-time join implementation — unit tests that verify feature values at specific timestamps match the expected historical values, and integration tests that compare training dataset features against independently reconstructed historical snapshots."))

    lines.append(("interviewer", "What about the feature registry — what happens if it goes down?"))

    lines.append(("candidate", "The feature registry is critical for management operations but not on the hot serving path — the feature server caches registry metadata and refreshes every few minutes. If the registry goes down, existing models continue serving with cached metadata. New deployments and feature group updates are blocked until recovery. We'd deploy the registry as a highly available database. The real risk is schema changes — if someone modifies a feature group without incrementing the version, cached metadata becomes stale. We prevent this with registry validation requiring version increments for breaking changes."))

    lines.append(("candidate", "There's also the failure mode of feature drift — not a system failure, but a data quality failure. Over time, the distribution of a feature shifts — maybe a new product launch changes the typical transaction amount, or a market event shifts FX volumes. The model trained on old feature distributions performs worse on new data. We monitor feature drift using statistical tests — Population Stability Index, Kolmogorov-Smirnov test, or Jensen-Shannon divergence — comparing the current feature distribution against the training distribution. When drift exceeds a threshold, we alert the model owner to retrain. This is a key part of the ML monitoring story that the feature store enables by tracking feature statistics over time."))

    # SECTION 6: Scale & Debrief (~3 min)
    lines.append(("interviewer", "How does the design change at 10x scale — 10,000 feature groups, 100K TPS serving?"))

    lines.append(("candidate", "At 10x, three things break. First, the online store — 100K TPS needs a larger Redis cluster, maybe 15 to 20 nodes. With more feature groups, each entity might have 20 to 30 rows instead of 10, so each read is larger. We'd shard by entity type — user features on one cluster, merchant features on another — to distribute load."))

    lines.append(("candidate", "Second, the streaming layer. 10,000 feature groups means 10,000 streaming jobs or one massive job. The state grows to 500 GB to 1 TB. We'd need incremental checkpointing and separate Flink clusters per domain — risk features, payments features, identity features — to limit blast radius."))

    lines.append(("candidate", "Third, and most important at 10x, is cross-org feature sharing. With 10,000 feature groups across dozens of teams, discovery becomes the bottleneck. The feature registry needs strong governance — feature naming conventions, mandatory documentation, ownership tracking, and deprecation workflows. Without governance, the registry becomes a dumping ground of undocumented, duplicated, and broken features. I'd implement a feature review process — like code review, but for feature definitions — and a feature health dashboard showing staleness, drift, and usage metrics for every registered feature. Features that are unused for 90 days get deprecated automatically after notifying the owner."))

    lines.append(("candidate", "At 0.1x scale — 100 feature groups, 1K TPS — everything simplifies. A single Flink job handles all streaming computation. A single Redis node handles serving. The feature registry is a simple database table. Point-in-time joins can be done with SQL ASOF joins in DuckDB or Spark. The architecture is the same, but the implementation is much simpler — fewer nodes, fewer shards, less automation. The key principles — unification, point-in-time correctness, feature registry — don't change, but the infrastructure to support them scales down dramatically."))

    # SECTION 7: End-to-End Walkthrough (~4 min)
    lines.append(("interviewer", "Walk me through the complete lifecycle of a feature request during fraud model inference. Trace it from the transaction arriving to the model getting its feature vector."))

    lines.append(("candidate", "Let's trace a specific example: a 500 USD card-not-present transaction from a user in Singapore, and the fraud model needs to score it. Step 1: The transaction arrives at the payment gateway. The fraud detection service receives the transaction event with user_id, card_id, amount, currency, merchant_category, and device_fingerprint. It calls the feature server's get_features API with the entity IDs — user_id and card_id — and the model's feature specification, which lists 120 features across 8 feature groups."))

    lines.append(("candidate", "Step 2: The feature server resolves the feature specification from its cached registry metadata. It needs: transaction_velocity_features for the user — txn_count_1h, txn_count_24h, txn_count_7d, txn_amount_sum_1h. transaction_amount_features — avg_txn_amount_30d, max_txn_amount_7d, amount_zscore. location_features — distance_from_home, distance_from_last_txn, country_mismatch_flag. behavioral_features — distinct_merchants_24h, new_device_flag, velocity_ratio_1h_to_7d. And so on for the other four feature groups."))

    lines.append(("candidate", "Step 3: The feature server issues parallel reads to the online store. For the user entity, one HGETALL on the key user:12345 fetches all user-level feature groups — velocity, amount, behavioral. For the card entity, one HGETALL on card:67890 fetches card-level features. Redis returns the feature values with their event_timestamps. The feature server checks staleness — the velocity features have an event_timestamp of 3 seconds ago, which is within the 30-second freshness threshold. The location features have an event_timestamp of 8 seconds ago, also fine. All features are fresh."))

    lines.append(("candidate", "Step 4: On-demand features. The distance_from_home feature needs the transaction's current location from the request context and the user's home location from the stored profile features. The feature server computes the Haversine distance between the two coordinates — let's say 8500 kilometers, which is unusual for this user. The country_mismatch_flag is computed by comparing the transaction country from the request with the user's registered country from the profile — different, so the flag is true. These on-demand computations take about 2 milliseconds."))

    lines.append(("candidate", "Step 5: Feature assembly. The feature server assembles the feature vector in the order specified by the model's feature specification. It maps feature names to their positions in the vector, fills in values from the online store reads and on-demand computations, and inserts default values for any missing features — this user has no behavioral features because they're a new user with less than 24 hours of history, so distinct_merchants_24h defaults to 0 and velocity_ratio defaults to 1.0. The feature vector has 120 values and is returned to the fraud detection service. Total latency: 8 milliseconds for Redis reads, 2 milliseconds for on-demand computation, 1 millisecond for assembly — 11 milliseconds, well within the 150-millisecond budget."))

    lines.append(("candidate", "Step 6: The fraud model scores the feature vector and returns a fraud probability of 0.87 — high risk. The transaction is flagged for review. Meanwhile, this transaction event is also being consumed by the streaming engine. Within 1 to 5 seconds, the velocity features for this user will be updated — txn_count_1h will increment, txn_amount_sum_1h will increase by 500. The next transaction from this user will see the updated velocity, making it even more likely to be flagged if the pattern continues. This is the real-time feedback loop that makes feature stores so powerful for fraud detection — the model's features improve with every event."))

    # SECTION 8: Thinking Process & Beats (~3 min) — interviewer monologue
    lines.append(("interviewer", "Let me close with my thinking process for evaluating feature store designs. My framework starts with the fundamental problem: the training-serving gap. Every design decision — unification, point-in-time joins, feature registry — exists to close this gap. If a candidate doesn't anchor on this, the design becomes a generic data pipeline rather than purpose-built ML infrastructure."))

    lines.append(("interviewer", "First beat: point-in-time joins preventing data leakage. This is the most important concept in feature stores. A candidate who doesn't bring up point-in-time joins unprompted hasn't operated ML in production. The naive approach — joining with current feature values — leaks future information. The ASOF join is correct. I look for candidates who explain why leakage is dangerous — models look good in backtesting and fail in production — and how point-in-time joins ensure training features reflect only information available at prediction time. AirSkiff's leftJoin being point-in-time by default is elegant — correct behavior is the easy behavior."))

    lines.append(("interviewer", "Second beat: batch-streaming unification. The Kappa principle applied to features — batch is just streaming with a bounded source. Candidates who propose separate batch and stream codepaths have missed the point of a feature store. The whole reason it exists is to eliminate the dual-implementation problem. I look for candidates who explain how a single feature definition produces both real-time and historical features through the same computation engine. Bonus points for mentioning AirSkiff's approach where the same Java logic handles both modes."))

    lines.append(("interviewer", "Third beat: feature registry for reuse and governance. Without a registry, feature stores become undocumented data pipelines. I look for: versioning — changes create new versions, not silent modifications; lineage — which raw data feeds which features, which features feed which models; discovery — search, documentation, and usage statistics; and governance — naming conventions, ownership, deprecation. At scale, the registry is more important than the computation engine because the organizational problem of feature duplication is harder than the technical problem of feature computation."))

    lines.append(("interviewer", "Fourth beat: serving latency and freshness trade-offs. Real-time features must be fresh, but freshness costs — more frequent updates, larger writes, more complex caching. I look for candidates who articulate the trade-off explicitly: what staleness threshold is acceptable and what degraded mode looks like. A candidate who assumes features are always fresh hasn't dealt with streaming job failures at 3 AM."))

    lines.append(("interviewer", "Then there are the traps. Trap one: data leakage from non-point-in-time joins. It's seductive because backtesting metrics improve — the model is cheating by seeing the future. The candidate who doesn't aggressively test for leakage — comparing offline metrics against online, unit testing join semantics with known timestamps — will ship a broken model. A blank stare when I ask how you verify no future information in training data is a red flag."))

    lines.append(("interviewer", "Trap two: separate batch and stream logic. The streaming team writes a Flink job, the data science team writes a PySpark batch job — they're supposed to do the same thing, but windowing semantics differ, late data handling differs, features diverge. Training-serving skew creeps in. The candidate who doesn't see this as fundamental hasn't felt the pain of a model's precision dropping 20 percent in production with no code change."))

    lines.append(("interviewer", "Trap three: no feature versioning. A team changes a feature computation — say, switching from tumbling to rolling windows — without creating a new version. Existing training datasets are now inconsistent with the serving logic. Models break silently. Versioning isn't bureaucracy — it's the mechanism that allows features to evolve without breaking consumers."))

    lines.append(("interviewer", "Overall: requirements well-scoped with focus on point-in-time correctness and freshness. Entity-level serving optimization was sharp. Kappa principle well-argued. Point-in-time merge join implementation was thorough. Staleness and drift monitoring showed operational maturity. For improvement: feature transformations versus raw features needed more discussion — on-the-fly transformations add flexibility but also latency. Also, multi-tenant isolation — one team's misbehaving streaming job shouldn't impact another team's feature freshness. Strong overall. Thanks."))

    lines.append(("candidate", "Thanks. You're right — on-the-fly transformations are powerful for normalization that depends on training parameters, but they add latency. I'd keep serve-time transformations minimal and push most into the computation layer. Multi-tenant isolation needs resource quotas per team for streaming compute and online store capacity, with circuit breakers isolating failures. Appreciate the feedback."))

    return lines
