"""Mock Interview: Fraud Detection System — Two-voice dialogue."""


def build():
    lines = []

    # SECTION 1: Requirements (~5 min)
    lines.append(("interviewer", "Hi, welcome. Today I'd like you to design a Fraud Detection System for a global payments platform like Airwallex. The system scores every transaction in real time, flags suspicious activity, and makes approve-review-block decisions. Start by clarifying the requirements."))

    lines.append(("candidate", "Thanks. Fraud detection is a domain where the requirements really drive the architecture — the latency budget, the false positive tolerance, and the detection approach all interact. Let me start with the most fundamental question: what's the primary detection paradigm? Are we doing pure rule-based scoring, pure ML, or a hybrid ensemble? Because a rule-only system is simple but brittle, an ML-only system is powerful but hard to explain, and a hybrid needs careful orchestration."))

    lines.append(("interviewer", "We want a hybrid — rule-based and ML-based scoring with an ensemble. Rules catch known fraud patterns fast and are explainable. ML catches novel patterns and subtle correlations that rules miss. The ensemble combines both into a single score. The system must score every transaction in under 100 milliseconds end-to-end."))

    lines.append(("candidate", "100 milliseconds is tight but achievable if we separate the feature computation from the scoring. The key insight is that most features can be precomputed and stored — only a few on-demand features need computation at scoring time. Next question: what's the false positive tolerance? In fraud detection, the false positive rate is arguably more important than the true positive rate because every false positive blocks a legitimate transaction, which is direct revenue loss and customer frustration. A 0.5 percent false positive rate on 10K TPS means 50 legitimate transactions flagged per second — that's a huge operational burden on the review team and a terrible customer experience."))

    lines.append(("interviewer", "The target false positive rate is under 0.1 percent. That's extremely aggressive, but in cross-border payments, blocking a legitimate business transaction can cost thousands in delayed settlement and lost customer trust. We'd rather let through 1 percent of fraud than block 0.5 percent of legitimate transactions. The system must also handle multi-currency fraud patterns — fraudsters exploit currency conversion to obscure amounts and routes."))

    lines.append(("candidate", "0.1 percent false positive rate is very aggressive — that shapes the entire design because it means the ML model needs very high precision, and the decision thresholds must be carefully calibrated. The cost of a false positive isn't just a blocked transaction — it's a customer who might switch to a competitor, and in B2B payments, it could mean a payroll doesn't go through or an invoice isn't paid on time. Let me ask about the decision framework. What are the outcomes for a scored transaction, and is there a human review component?"))

    lines.append(("interviewer", "Three outcomes based on the ensemble score: score below 30 — approve automatically. Score 30 to 70 — send to a human review queue. Score above 70 — block the transaction. Human reviewers examine flagged transactions within a configurable SLA — typically 5 minutes — and their decisions feed back into the model training pipeline. That feedback loop is essential for continuous improvement."))

    lines.append(("candidate", "Let me summarize. We're designing a real-time Fraud Detection System for a global payments platform. Core requirements: score every transaction in under 100 milliseconds, hybrid rule-based and ML-based detection with ensemble scoring, decision thresholds at 30 and 70 for approve-review-block, false positive rate under 0.1 percent, multi-currency fraud pattern support, and a feedback loop from human review to model retraining. Scale is 10K transactions per second. Let me move to estimation."))

    # SECTION 2: Estimation (~5 min)
    lines.append(("interviewer", "Go ahead with the numbers."))

    lines.append(("candidate", "10K TPS at peak, with a 3x peak-to-average ratio, so average is about 3.3K TPS — roughly 285 million transactions per day. Let's call it 300 million. That's a lot of volume, which matters both for the real-time scoring infrastructure and for the training data pipeline — more transactions means more labeled data, which means better models, assuming the feedback loop is healthy."))

    lines.append(("candidate", "Feature storage is the interesting part. Each transaction triggers feature lookups for roughly 5 entities — payer, payee, card, device, merchant. Each entity has 50 to 100 features in the online feature store. At 10K TPS, that's 50K entity lookups per second. With entity-level co-location — all features for one entity in a single row — that's 50K row reads per second. A Redis cluster with 5 to 7 nodes handles that at sub-millisecond latency per read."))

    lines.append(("interviewer", "What about the feature computation load — how many features need to be updated in real time per transaction?"))

    lines.append(("candidate", "Real-time feature updates are the heavy part. Each transaction updates velocity features for the payer — txn_count_1h, txn_count_24h, txn_amount_sum_1h — and similar features for the payee, card, and device. That's roughly 20 to 30 feature group updates per transaction. At 10K TPS, that's 200K to 300K updates per second. Each update reads current values, applies the aggregation — increment count, add to sum — and writes back. So that's 400K to 600K Redis operations per second from computation alone. A 10 to 15 node Redis cluster with consistent hashing handles this."))

    lines.append(("candidate", "Model serving: the rule engine is in-memory pattern matching — about 1 to 2 milliseconds per transaction. The ML model — typically XGBoost or LightGBM — scores in 5 to 10 milliseconds on CPU. We use CPU because batch size per request is 1; GPU only wins with large batches. At 10K TPS, if each instance handles 1K TPS, we need 10 instances. With redundancy, 15 to 20."))

    lines.append(("interviewer", "What about storage for the transaction and scoring history?"))

    lines.append(("candidate", "Each transaction record with feature vector and score is about 2 KB — the transaction metadata, all feature values, rule engine output, ML score, ensemble score, and the final decision. At 300 million per day, that's 600 GB daily. Hot storage for 90 days — 54 TB — goes to a columnar lakehouse like Delta Lake or Iceberg for analytics and training. The last 48 hours stays in an OLTP store for real-time queries and the review queue. The offline feature store holds feature history for point-in-time training — another 20 to 30 TB over 90 days. Long-term compliance retention of 7 years is about 1.5 PB on cold object storage."))

    # SECTION 3: High-Level Architecture (~5 min)
    lines.append(("interviewer", "Good. Let's move to the high-level architecture."))

    lines.append(("candidate", "The system has four major components: the Feature Engine, the Scoring Engine, the Decision Engine, and the Feedback Loop. A transaction arrives at the payment gateway. The Fraud Detection Service receives the event — payer ID, payee ID, amount, currency, merchant category, device fingerprint, geolocation — and calls the Feature Engine to fetch the feature vector. The Feature Engine retrieves precomputed features from the online store and computes on-demand features like distance_from_home that depend on the current transaction context. It returns the complete feature vector within about 30 milliseconds."))

    lines.append(("candidate", "The Scoring Engine has two sub-components: the Rule Engine and the ML Model. The Rule Engine evaluates a configurable set of fraud rules — hard limits, velocity thresholds, blacklists, pattern matches. Each rule contributes to the rule score. The ML Model takes the feature vector and produces a fraud probability. The ensemble combiner merges both into a single score between 0 and 100. This pipeline runs in about 50 milliseconds."))

    lines.append(("candidate", "The Decision Engine applies the threshold logic: below 30, approve; 30 to 70, queue for human review; above 70, block. For approved and blocked transactions, the decision is immediate and the transaction proceeds or is rejected. For reviewed transactions, the alert generator creates a case in the review queue with the transaction details, the feature vector, the rule and ML scores, and explainability information — which rules fired, which features contributed most to the ML score via SHAP values. The reviewer confirms fraud or clears as legitimate, and that decision feeds into the Feedback Loop."))

    lines.append(("interviewer", "Walk me through the Feedback Loop. How does a human reviewer's decision make it back to the model?"))

    lines.append(("candidate", "The Feedback Loop has two paths: rule updates and ML retraining. When a reviewer confirms fraud that the system approved — a false negative — the fraud operations team analyzes which rules would have caught it and either adds a new rule or tightens an existing threshold. This is the fast path — rule changes deploy within hours, sometimes minutes for critical patterns. When a reviewer clears a legitimate transaction that was blocked or flagged — a false positive — the team loosens the offending rule or adjusts its weight in the ensemble. Both paths improve the system, but they operate on different timescales."))

    lines.append(("candidate", "The ML path is slower but more powerful. Every reviewer decision is labeled and added to the training dataset. The batch training pipeline retrains the model weekly or daily, evaluates on a holdout test set — checking precision, recall, and the false positive rate — then promotes the new model to shadow deployment alongside production. In shadow mode, the new model scores in parallel but its decisions don't affect outcomes. After 24 to 48 hours with no regression, it's promoted to production — the canary deployment pattern for ML. This careful promotion process is essential because a model that looks good on the test set might behave differently in production due to feature distribution shifts or edge cases the test set doesn't cover."))

    lines.append(("candidate", "There's a critical piece in the feedback loop: point-in-time joins. When a transaction is processed, its features are logged with the transaction ID and timestamp. When the reviewer's label comes in later, the label is joined to the features at the correct point in time. This prevents data leakage — the model trains on features as they existed at scoring time, not features updated by subsequent transactions."))

    # SECTION 4: Deep Dive — Feature Engineering, Scoring, and Point-in-Time Correctness (~10 min)
    lines.append(("interviewer", "Let's deep dive into the three trickiest areas. Start with feature engineering — what features matter for fraud detection and how are they computed?"))

    lines.append(("candidate", "Feature engineering is where 80 percent of the fraud detection value comes from — the model architecture matters far less than the features you feed it. A mediocre model with great features will outperform a great model with mediocre features every time. I'll categorize the features into four groups: velocity features, amount features, location features, and behavioral features. Think of this as the AirSkiff feature store powering the fraud models."))

    lines.append(("candidate", "Velocity features are the most powerful — they capture the rate of activity. For each entity we track txn_count_1h, txn_count_24h, txn_count_7d — windowed counts updated in real time. The velocity ratio — txn_count_1h divided by txn_count_7d — is especially powerful because a sudden spike relative to the weekly baseline is a strong fraud signal. A user who normally does 3 transactions per day but has done 15 in the last hour is suspicious."))

    lines.append(("candidate", "Amount features capture spending patterns: avg_txn_amount_30d, max_txn_amount_7d, amount_zscore — how many standard deviations the current amount is from the entity's historical mean — and amount_currency_mismatch. The zscore is powerful because fraudsters make transactions unusually large for a specific user, even if the absolute amount is moderate. A 500 dollar transaction is normal for a business but suspicious for a student."))

    lines.append(("candidate", "Location features capture geographic anomalies: distance_from_home, distance_from_last_txn, country_mismatch_flag, impossible_travel_flag — whether the distance and time since the last transaction imply physically impossible speed, like Singapore to London in 30 minutes. These are on-demand features — they depend on the current transaction's location, so they can't be fully precomputed."))

    lines.append(("candidate", "Behavioral features capture patterns beyond velocity and amount: distinct_merchants_24h — number of unique merchants transacted with in the last 24 hours — new_device_flag, velocity_amount_interaction — the product of velocity and amount zscore capturing the dangerous pattern of many large transactions — time_since_last_txn, and cross-entity features like whether the payer and payee have transacted before or whether the payee is a newly created account. Cross-entity features are powerful because fraud often involves a new payee account receiving funds from a compromised payer account."))

    lines.append(("interviewer", "How are these features computed and kept fresh? Walk me through the computation architecture."))

    lines.append(("candidate", "The computation architecture follows the AirSkiff pattern — a streaming feature store computing features in real time from Kafka transaction events. Each transaction triggers feature updates for all associated entities. The streaming engine — Flink or AirSkiff's Java processor — maintains windowed state: counts within tumbling or sliding windows, sums, maxima. When a new transaction arrives for entity X, the engine increments the count, adds the amount, and writes updated values to Redis."))

    lines.append(("candidate", "The sliding window implementation is crucial. A tumbling window resets at fixed boundaries — the 1-hour window resets every hour. This creates a discontinuity — at 9:59 the count is 20, at 10:01 it resets to 1, even though activity hasn't changed. Sliding windows avoid this by expiring events as they age out, but they're more expensive — each entity's state contains individual timestamps. We use a hybrid: sliding windows for 1-hour features where the discontinuity hurts most, tumbling windows for 24-hour and 7-day features where the longer window makes the boundary less noticeable."))

    lines.append(("candidate", "For the online store, we use Redis with entity-level co-location — all features for a given entity in a single hash. One HGETALL per entity per scoring request, not one per feature. At 10K TPS with 5 entities, that's 50K HGETALL operations per second at under 2 milliseconds each. The streaming engine writes updates via HSET, updating only changed features. On-demand features like distance are computed by the feature server at query time."))

    lines.append(("interviewer", "Now let's deep dive into the scoring engine. How does the rule-plus-ML ensemble actually work?"))

    lines.append(("candidate", "The scoring engine is a pipeline: Rule Engine first, then ML Model, then Ensemble Combiner. The Rule Engine evaluates a configurable rule set maintained by the fraud operations team. Rules are conditions on features and transaction attributes — for example: if txn_count_1h greater than 20 and amount_zscore greater than 3, add 40 points. If country_mismatch_flag and new_device_flag both true, add 25 points. If payer on blacklist, add 80 points. Each rule contributes a score increment, total capped at 100. The rule engine runs in 1 to 2 milliseconds — a forward-chaining inference engine."))

    lines.append(("candidate", "The ML Model is a gradient-boosted tree — XGBoost or LightGBM — trained on historical features with fraud labels from the feedback loop. It takes 100 to 150 features and outputs a fraud probability scaled to 0 to 100. Inference takes 5 to 10 milliseconds on CPU. The model is relatively small — 200 to 500 trees with max depth 6 to 8."))

    lines.append(("candidate", "The Ensemble Combiner merges the rule score and ML score. A simple weighted average is the baseline, but the weights aren't static. We use a logistic regression meta-learner — stacking — that learns when to trust rules versus ML from historical data. Rules are more reliable for known patterns like blacklists; ML handles novel patterns. The meta-learner learns this automatically. There's also an edge case: rule overrides. If a payer is on the sanctions list, the rule engine short-circuits to score 100, skipping the ML model entirely. This ensures regulatory requirements are never overridden by the ML model."))

    lines.append(("interviewer", "Now let's deep dive into point-in-time correctness. Why is it so critical for fraud model training, and how do you implement it?"))

    lines.append(("candidate", "Point-in-time correctness is the most underappreciated concept in fraud ML, and it's where most teams silently introduce data leakage. When you build a training dataset, you join transaction features with fraud labels. The label might not be known until hours later. But the features must reflect only information available at scoring time. If you join with current feature values, you get values updated by subsequent transactions — the model sees the velocity count including transactions that happened after the one being scored, which is future information."))

    lines.append(("candidate", "For example: a user makes a transaction at 10:00 AM. At 10:05 AM, they make four more rapid transactions that are fraud. When we build the training dataset for the 10:00 AM transaction, if we use the current velocity features, txn_count_1h might be 5 — reflecting all five transactions. But at scoring time, the count was 1. The model learns that a count of 5 is predictive of fraud — which is true for the 10:05 AM transactions but leaked information for the 10:00 AM transaction. In production, when the model scores a new transaction, the velocity count doesn't include future transactions, so the model sees a count of 1 and might not flag it. Data leakage makes offline metrics look great and production metrics terrible."))

    lines.append(("candidate", "The implementation uses point-in-time joins — ASOF joins — against the offline feature store, which records every feature update with an event timestamp. For each training example with entity_id and timestamp T, we join to get feature values where the feature's event_timestamp is the largest value less than or equal to T — the feature snapshot at scoring time, without any future information. This is exactly what AirSkiff's leftJoin does by default — point-in-time is the default, not something the data scientist must remember to specify. Getting this wrong is so easy and so damaging that making correct behavior the default is a key architectural decision."))

    lines.append(("candidate", "The offline feature store is built from the streaming engine's output — every update to the online store is also written to a Delta Lake or Iceberg table partitioned by feature group, date, and entity key hash. For high-frequency features like velocity counts, we snapshot at minute-level granularity rather than storing every update. The streaming engine writes to the online store on every event for sub-second freshness, but to the offline store every minute for storage efficiency."))

    # SECTION 5: Failure Modes (~4 min)
    lines.append(("interviewer", "What are the most critical failure scenarios for the fraud detection system?"))

    lines.append(("candidate", "The scariest failure is model degradation without detection. Fraudsters adapt to the model, testing different patterns to find blind spots. Precision and recall silently degrade over weeks — concept drift — and the fraud ops team might not notice until chargebacks spike. The defense is continuous monitoring: false positive rate, false negative rate from chargebacks, score distribution over time, and feature drift. If the score distribution shifts — suddenly more transactions scoring 40 to 60 — something has changed in the input feature distribution and the model might need retraining. We also track the model's precision on recent labeled data weekly — if it drops below the deployment threshold, an automatic retraining is triggered."))

    lines.append(("candidate", "The second is feature staleness. The streaming engine falls behind — Kafka rebalance, Flink memory pressure — and the online store stops updating. The model scores with stale velocity features. A legitimate burst looks normal with stale counts, then the next update catches up all at once, causing false positive spikes — a cascading failure. We monitor streaming lag as a critical metric — if it exceeds 30 seconds, we alert and automatically widen decision thresholds to reduce false positive risk from stale features. If lag exceeds 2 minutes, we escalate to a page-the-oncall incident."))

    lines.append(("candidate", "The third is rule conflicts. When the fraud ops team adds rules reactively — there's an incident, they add a rule — the new rule might conflict with existing ones. A new rule flags all transactions from a country as high risk, but an existing rule whitelists known merchants there. Without a conflict resolution strategy — usually precedence ordering with explicit override rules — the rule set becomes an inconsistent tangle producing unpredictable scores. We manage this with rule versioning and a testing framework — new rules are backtested against historical transactions for false positive and true positive impact before deployment, and checked for conflicts with existing rules."))

    lines.append(("candidate", "The fourth is the feedback loop going cold. If reviewers can't keep up with the queue, labeled data dries up. Vicious cycle: model degrades, more flagged transactions, queue grows, less labeled data, model degrades further. The defense is managing queue size — if it exceeds capacity, temporarily lower the review threshold to reduce volume, and invest in auto-close rules for obvious cases. A 30-minute SLA on review decisions keeps the loop healthy. We also track the label freshness metric — the median time from transaction to labeled decision — and alert if it exceeds the SLA."))

    lines.append(("interviewer", "What about a total scoring engine outage — the system can't score at all?"))

    lines.append(("candidate", "A total outage has three fallback options, in order: serve from a secondary region with a cached model, fall back to a lightweight rule-only engine in the API layer that catches obvious fraud — blacklists, velocity thresholds — without the full ML stack, or as a last resort approve all transactions with enhanced monitoring for delayed batch review. Option two is the default fallback — fast, catches the worst fraud, doesn't require ML infrastructure. The key insight is that a degraded fraud system is better than no fraud system. Even a simple rule engine that catches 60 percent of fraud with a 0.05 percent false positive rate is preferable to approving everything."))

    # SECTION 6: Scale & Debrief (~3 min)
    lines.append(("interviewer", "How does the design change at 10x volume — 100K TPS?"))

    lines.append(("candidate", "At 100K TPS, three components need fundamental redesign. First, the online feature store — 500K lookups and 2 to 3 million updates per second. A single Redis cluster can't handle that write volume. We'd shard by entity type — user, card, merchant clusters — and move from synchronous to asynchronous writes with a write-behind cache, accepting 100 to 500 milliseconds of staleness. Each cluster is independently scalable, so we can add capacity to the user feature cluster if most updates are user-level velocity features."))

    lines.append(("candidate", "Second, the model serving layer needs 100 to 150 instances. We'd use consistent hashing for session affinity — routing same-entity transactions to the same server to cache features — and explore model distillation for faster inference. A distilled model that runs in 2 to 3 milliseconds instead of 5 to 10, at a small accuracy cost, effectively doubles the serving fleet's throughput. Third, the feedback loop must be faster — weekly retraining becomes daily or hourly. We'd invest in online learning — incremental model updates as labels arrive — rather than full retraining from scratch. At 100K TPS, a week of degraded detection is a lot of fraud. The faster the feedback loop, the less fraud slips through during the adaptation window."))

    lines.append(("candidate", "At 0.1x scale — 1K TPS — a single Redis node, a single model serving instance, and a single Flink job suffice. The rule engine runs in-process. The batch training pipeline can run on a single machine. But the core architecture — Feature Engine, Scoring Engine, Decision Engine, Feedback Loop — stays the same. Point-in-time joins are just as important at 1K TPS as at 100K. The feedback loop is just as critical. The decision thresholds are the same. The architecture is constant; the infrastructure varies. Correctness doesn't scale down."))

    # SECTION 7: End-to-End Walkthrough (~4 min)
    lines.append(("interviewer", "Walk me through the complete trace of a transaction from arrival to final decision."))

    lines.append(("candidate", "Let's trace a specific example: a 3,200 EUR card-not-present transaction from a user whose registered country is Singapore, using a device fingerprint never seen before. The payment gateway receives the transaction and calls the Fraud Detection Service."))

    lines.append(("candidate", "Step 1: Feature Retrieval. The Fraud Detection Service calls the Feature Engine with the entity IDs — user_id U-78432, card_id C-9921, device_id D-NEW, merchant_id M-4456. The Feature Engine issues parallel HGETALL requests to the online feature store: one for U-78432's features, one for C-9921, one for M-4456. The device_id D-NEW has no stored features — it's a new device. Redis returns the feature values in about 2 milliseconds. The Feature Engine then computes on-demand features: distance_from_home — the transaction is in Germany, the user's home is in Singapore, so 10,000 kilometers. country_mismatch_flag is true. impossible_travel_flag — the user's last transaction was in Singapore 45 minutes ago, and 10,000 kilometers in 45 minutes is impossible, so this flag is true. new_device_flag is true — D-NEW has no history. Total feature retrieval time: about 15 milliseconds."))

    lines.append(("candidate", "Step 2: Rule Engine Scoring. The feature vector and transaction attributes enter the Rule Engine. Rules evaluated: Rule R-12 — country_mismatch_flag and new_device_flag both true, add 30 points. Rule R-7 — impossible_travel_flag true, add 25 points. Rule R-3 — txn_count_1h equals 8, which exceeds threshold of 5 for this user's tier, add 15 points. Rule R-15 — amount_zscore is 4.2, which exceeds threshold of 3, add 10 points. Total rule score: 80, capped at 80. Rule engine time: 2 milliseconds."))

    lines.append(("candidate", "Step 3: ML Model Scoring. The full feature vector — 120 features including velocity, amount, location, and behavioral features — is fed to the XGBoost model. The model outputs a fraud probability of 0.72, scaled to 72. The top contributing features per SHAP values are: impossible_travel_flag with a SHAP value of plus-18, distance_from_home at plus-12, txn_count_1h at plus-9, new_device_flag at plus-8, amount_zscore at plus-7. These SHAP values will be included in the review case for explainability. Model inference time: 8 milliseconds."))

    lines.append(("candidate", "Step 4: Ensemble Scoring. The meta-learner takes the rule score of 80 and the ML score of 72. The learned weights for this transaction's feature profile give 0.35 weight to the rule score and 0.65 to the ML score — the meta-learner has learned that when both rules and ML agree on high fraud risk, the ML score is more calibrated. Ensemble score equals 0.35 times 80 plus 0.65 times 72 equals 74.8. Round to 75. Ensemble time: less than 1 millisecond."))

    lines.append(("candidate", "Step 5: Decision. The Decision Engine applies thresholds: 75 is above 70, so the decision is BLOCK. The transaction is rejected. An alert is generated and stored in the alert database with the full scoring context: feature values, rule contributions, ML score, SHAP values, ensemble score, and the decision. The payer is notified that the transaction was declined for security reasons, with a prompt to contact support if they believe this was an error. Total end-to-end latency: 15 milliseconds for features plus 2 milliseconds for rules plus 8 milliseconds for ML plus 1 millisecond for ensemble plus 4 milliseconds for decision and logging — 30 milliseconds total, well within the 100-millisecond budget. This leaves 70 milliseconds of headroom for network transit and queuing delays."))

    lines.append(("candidate", "Step 6: Feedback. If the payer contacts support and the reviewer determines this was legitimate — the user was traveling in Germany with a new phone — the reviewer marks it as a false positive. This label flows to the training pipeline. The next retraining includes this example: impossible_travel_flag true but actually legitimate. The model learns that impossible travel is less predictive for users with international travel history, captured by a feature like international_travel_count_30d. This is the feedback loop making the system smarter."))

    lines.append(("candidate", "Meanwhile, the streaming engine updates features in real time. Even blocked transactions update velocity features — txn_count_1h increments to 9 — because blocked transactions still reflect real account activity, and the velocity count should capture the full picture. The next transaction from this user will see even higher velocity features, making it more likely to be flagged if the suspicious pattern continues. This is the real-time feedback that makes streaming features so powerful for fraud detection — the model's input features improve with every event."))

    # SECTION 8: Thinking Process & Beats (~3 min) — interviewer monologue
    lines.append(("interviewer", "Let me close with my thinking process. My framework starts with one question: does the candidate understand that fraud detection is fundamentally a precision problem, not a recall problem? Most candidates optimize for catching all fraud, but in payments, the cost of a false positive often exceeds missed fraud. A 0.1 percent false positive rate forces this precision-first mindset. Candidates who don't anchor on it over-engineer detection and under-engineer the review queue, feedback loop, and explainability."))

    lines.append(("interviewer", "First beat: feature engineering is 80 percent of the work. I look for candidates who spend real time on velocity, amount, location, and behavioral features — and who understand computation semantics. Sliding versus tumbling windows isn't academic — it's the difference between catching fraud in the first minute of a burst and missing it until a window boundary resets. The on-demand versus precomputed distinction matters equally — distance_from_home can't be precomputed because you don't know the transaction location until inference time. Candidates who treat all features as precomputed haven't thought about the serving path."))

    lines.append(("interviewer", "Second beat: point-in-time joins preventing data leakage. A candidate who doesn't bring this up unprompted hasn't trained an ML model on temporal data. The naive join leaks future information — offline metrics look amazing, production metrics collapse. The ASOF join is correct. I look for candidates who explain the specific failure: the velocity count for a 10 AM transaction includes a 10:05 AM transaction that hasn't happened yet at scoring time. AirSkiff's leftJoin being point-in-time by default is the right design — correct behavior should be the easy behavior."))

    lines.append(("interviewer", "Third beat: the rule-plus-ML ensemble. Rules are fast, explainable, deterministic — they catch known patterns. ML is probabilistic, catches novel patterns, handles feature interactions rules can't express. ML-only can't explain decisions to regulators. Rules-only can't adapt to evolving fraud. The meta-learner that learns when to trust each is the right design. Hard rule overrides for sanctions are non-negotiable."))

    lines.append(("interviewer", "Fourth beat: the feedback loop as a first-class system. Fraud detection is adversarial — model and fraudsters both adapt. Without capturing reviewer decisions and feeding them back, the system degrades. The vicious cycle — model degrades, more false positives, queue grows, less labeled data, further degradation — is a real operational failure. Candidates who don't monitor label freshness and review queue depth miss the operational reality."))

    lines.append(("interviewer", "Then the traps. Trap one: data leakage from non-point-in-time joins. Seductive because offline metrics improve. Without testing for leakage — comparing offline versus production precision — you ship a model that fails in production. The silent killer. Trap two: ignoring false positive cost. Pushing thresholds lower blocks legitimate transactions — each one a complaint and churn risk. The 0.1 percent target is where false positive cost is lower than fraud loss. Trap three: no model monitoring. A 99 percent precise model degrades to 90 percent in a month. Without monitoring — score distribution, feature drift, chargebacks — degradation is invisible. I look for specific metrics and automated triggers. Trap four: batch-only features in a real-time system. Day-old velocity counts miss fraud happening in minutes. The streaming feature store is core infrastructure, not optional."))

    lines.append(("interviewer", "Overall: requirements well-scoped with precision-first mindset. Four-category feature taxonomy was well-organized. Point-in-time join explanation was precise with a concrete example. Ensemble meta-learner showed sophistication. Failure modes covered both acute outages and silent degradation. For improvement: multi-currency fraud patterns needed more depth — fraudsters exploit FX conversion to layer transactions across currencies, and currency-normalized velocity features deserve attention. Also, cold-start for new users and merchants — when there's no feature history — could be addressed with higher review thresholds or a separate cold-start model. The review queue UX and tooling for human reviewers could also use more attention — the reviewers need efficient tooling to make fast, accurate decisions, and the UI should surface the most relevant features and explainability information prominently. Strong overall. Thanks."))

    lines.append(("candidate", "Thanks. You're right on both points. Multi-currency fraud is a distinct pattern — fraudsters split a single large amount across multiple currencies to stay under per-currency velocity thresholds. Currency-normalized velocity features — like total_equivalent_amount_1h converted to a base currency — would catch this cross-currency layering. And for cold-start, I'd use a higher review threshold for entities with less than 30 days of history, plus a simpler model that relies on network features — is the payer connected to known fraud rings? Is the payee a newly created account with no transaction history? — rather than individual velocity features that don't exist yet. You could also use population-level features as a prior — what's the typical fraud rate for this merchant category or this country? — until entity-level features accumulate. Appreciate the feedback."))

    return lines
