"""Mock Interview: FX Rate Engine + Multi-Currency Double-Entry Ledger — Two-voice dialogue."""


def build():
    lines = []

    # SECTION 1: Requirements (~5 min)
    lines.append(("interviewer", "Hi, today I'd like you to design an FX rate engine combined with a multi-currency double-entry ledger. Think of what a company like Airwallex or Revolut would need — real-time currency conversion with a ledger that tracks every cent across multiple currencies. Start by clarifying the requirements."))

    lines.append(("candidate", "Thanks. This is a fintech system design that combines two deep domains — FX and accounting. Let me start with the FX side. First question: are we sourcing FX rates from external providers, or are we a market maker setting our own rates? Because if we're sourcing, we need aggregation logic, and if we're market making, we need pricing engines and risk management. They're very different systems."))

    lines.append(("interviewer", "We source rates from multiple external providers — typically two to three liquidity providers like Bloomberg, Reuters, and a regional provider. We aggregate and add a spread."))

    lines.append(("candidate", "OK, so we're a rate aggregator with markup. Next question: how many currency pairs, and how frequently do rates update? Also, do we support both spot rates and forward rates, or just spot?"))

    lines.append(("interviewer", "30 currency pairs. Rates update as frequently as every 100 milliseconds from the fastest provider. Spot rates only for now."))

    lines.append(("candidate", "30 pairs with 100ms updates — that's a high-frequency feed. Next, the ledger side. How many transactions per second do we need to support? And what types of ledger entries — just FX conversions, or also deposits, withdrawals, and transfers between accounts?"))

    lines.append(("interviewer", "About 50K TPS for ledger writes. We need to support all of those: deposits, withdrawals, transfers within the same currency, and cross-currency transfers with FX conversion. We also need to support multi-currency wallets where a single user can hold balances in multiple currencies."))

    lines.append(("candidate", "50K TPS is significant for a ledger — that's in the range where we need careful sharding. What about the user base? How many users have active wallets, and what's the typical number of currencies per wallet? This affects the account balance model."))

    lines.append(("interviewer", "About 20 million users with active wallets. The average user holds 2 to 3 currencies, but corporate clients might hold 10 or more. About 80 percent of transactions are retail and 20 percent are corporate, but corporate transactions tend to be much larger in value."))

    lines.append(("candidate", "50K TPS is significant for a ledger — that's in the range where we need careful sharding. A few more questions. First, do we lock FX rates at quote time with a TTL, or do we apply rates at execution time? This matters because it determines whether we have FX risk exposure. Second, what about settlement — do we settle instantly on our internal ledger, or do we also need to settle with external banking partners? Third, do we need audit trail capabilities — like an immutable transaction log that regulators can inspect?"))

    lines.append(("interviewer", "We lock rates at quote time with a 30-second TTL for retail and up to 5 minutes for corporate clients. Settlement on our internal ledger is instant. External settlement with banking partners is a separate system — we only need the internal ledger for this design. And yes, we need a full audit trail with immutability guarantees — regulators require it."))

    lines.append(("candidate", "Let me ask one more: for the audit trail, do we need to support audit proofs — the ability to prove that the ledger is consistent and has not been tampered with? Or is a regular append-only log sufficient?"))

    lines.append(("interviewer", "An append-only log is the minimum. But if you can add cryptographic verification like a hash chain, that would be a strong differentiator."))

    lines.append(("candidate", "Great. Let me summarize. We're designing an FX rate engine that aggregates from multiple providers for 30 currency pairs with 100ms updates, plus a multi-currency double-entry ledger at 50K TPS supporting deposits, withdrawals, same-currency transfers, and cross-currency transfers. Rates are locked at quote time with configurable TTLs. The internal ledger settles instantly. We need an immutable audit trail, ideally with hash chain verification. Let me move to estimation."))

    # SECTION 2: Estimation (~5 min)
    lines.append(("interviewer", "Go ahead."))

    lines.append(("candidate", "Let me start with the FX rate data. 30 currency pairs, updates every 100ms from the fastest provider, maybe every 500ms from slower ones. On average, let's say 5 updates per second per pair from all providers combined — that's 150 rate updates per second. Each update is about 200 bytes — currency pair, bid, ask, timestamp, provider ID, sequence number. That's 30 KB per second, about 2.6 GB per day of raw rate data. We don't need to persist all of it — we'd keep the latest rates in memory for serving and aggregate to 1-minute snapshots for history. The snapshot data is 30 pairs times 1440 minutes times 200 bytes, about 8.6 MB per day. Over 5 years, about 15 GB. Negligible. The hot rates live entirely in Redis — maybe 100 MB with history."))

    lines.append(("candidate", "Now the ledger. 50K TPS. Each transaction creates at least 2 ledger entries — debit and credit. For cross-currency transfers, it's 4 or 5 entries. Let's average 2.5 entries per transaction. So 125K ledger entry writes per second. Each entry is about 200 bytes — entry ID, transaction ID, account ID, currency, amount, direction, timestamp, description. At 125K entries per second, that's about 25 MB per second, or 2.16 TB per day. Wait, that seems high. Let me recalculate. 125K times 200 bytes is 25 million bytes per second, which is 25 MB per second. Times 86400 seconds is 2.16 TB per day. Over 7 years for regulatory retention, that's about 5.5 PB. That's a lot. We'd need to archive old data to cold storage — keep 90 days hot in the database and archive the rest to object storage. 90 days of data is about 194 TB, which requires a sharded database."))

    lines.append(("interviewer", "You mentioned the audit trail with hash chains. What's the storage overhead for that?"))

    lines.append(("candidate", "Right. For a hash chain, each entry needs to store the hash of the previous entry, which is 32 bytes for SHA-256. At 125K entries per second, that's an additional 4 MB per second — about 345 GB per day. Over 7 years, about 884 TB. Actually, we don't need to hash every individual entry — we can hash at the transaction level. Each transaction hashes all its entries together, producing one hash per transaction. At 50K TPS, that's 32 bytes times 50K per second — 1.6 MB per second, about 138 GB per day. Over 7 years, about 355 TB. Still significant but more manageable. We'd compress and archive old hash chain data alongside the ledger entries."))

    lines.append(("interviewer", "What about the account balance storage? How do you store and query balances efficiently?"))

    lines.append(("candidate", "Good point. Each account has a balance per currency. For a user with a multi-currency wallet holding USD, EUR, and GBP, we need three balance records. With 50M users and an average of 2 currencies per user, that is 100M balance records. Each record is about 50 bytes — account ID, currency, balance, last updated timestamp. Total: about 5 GB. This fits in memory easily. We store balances in both the database for durability and in Redis for fast lookups. The balance is updated within the same database transaction as the ledger entries, so it is always consistent. The Redis cache is updated after the transaction commits. If a balance read arrives before the Redis update, the stale balance is at most a few milliseconds old, which is acceptable for display purposes. For critical operations like balance checks before a transfer, we always read from the database, not the cache."))

    # SECTION 3: High-Level Architecture (~5 min)
    lines.append(("interviewer", "Good. Let's move to the high-level architecture."))

    lines.append(("candidate", "The system has two main subsystems: the FX Rate Engine and the Ledger Service. Let me start with the FX Rate Engine. It has three components: the Rate Ingestion Service, the Rate Aggregation Service, and the Rate Serving Service. The Rate Ingestion Service maintains WebSocket connections to each liquidity provider — Bloomberg, Reuters, and the regional provider. Each provider sends rate updates at different frequencies and in different formats. The ingestion service normalizes these into a common internal format — currency pair, bid, ask, timestamp, provider ID, sequence number — and publishes them to a Kafka topic called raw-rates, partitioned by currency pair."))

    lines.append(("candidate", "The Rate Aggregation Service consumes from the raw-rates topic and produces the best available rate for each pair. The aggregation logic is: for each currency pair, take the best bid across all providers and the best ask across all providers, apply our spread markup, and publish the resulting rate. The best bid is the highest bid, and the best ask is the lowest ask — this gives us the tightest possible spread. We add our markup by widening the spread — for example, if the best bid is 1.3010 and best ask is 1.3020, a 0.1 percent markup gives us a quoted bid of 1.2997 and ask of 1.3033. The aggregated rates are published to a rates-served topic and also written to Redis for low-latency lookups."))

    lines.append(("candidate", "The Rate Serving Service handles quote requests from the Ledger Service. When a user wants to convert 1000 USD to EUR, the Ledger Service calls the Rate Serving Service with the currency pair, direction, and amount. The Rate Serving Service checks if there's a valid locked rate for this user — if the user has a recent quote within the TTL, it returns that rate. Otherwise, it reads the latest aggregated rate from Redis, creates a rate lock entry with a TTL of 30 seconds, and returns the locked rate. The rate lock is stored in Redis with a key like ratelock:quoteID and a TTL equal to the lock duration. Redis automatically expires it."))

    lines.append(("interviewer", "Now let's talk about the Ledger Service."))

    lines.append(("candidate", "The Ledger Service implements double-entry bookkeeping across multiple currencies. The fundamental rule is: every transaction must balance — total debits equal total credits. But in a multi-currency system, debits and credits must balance per currency. You can't debit 100 USD and credit 85 EUR and call it balanced — they're different units. For a same-currency transfer from account A to account B, it's straightforward: debit A for 100 USD, credit B for 100 USD. For a cross-currency transfer, we use intermediate accounts. Let's say user Alice wants to convert 1000 USD to EUR at a rate of 0.85. Entry 1: debit Alice's USD account 1000 USD. Entry 2: credit the FX suspense account 1000 USD. Entry 3: debit the FX suspense account 850 EUR. Entry 4: credit Alice's EUR account 850 EUR. Entries 1 and 2 balance in USD. Entries 3 and 4 balance in EUR."))

    lines.append(("candidate", "Actually, wait. I need to reconsider the FX suspense account structure. If the FX suspense account holds both USD and EUR, its balance across currencies might not be zero — it will accumulate FX gains and losses over time. That's actually correct and expected — the FX suspense account's balance represents our FX position. But we need to reconcile it periodically. At end of day, the FX suspense account should be close to zero — any residual balance is our FX gain or loss for the day, which gets posted to an FX PnL account. Let me refine: entries 1 and 2 balance in USD. Entries 3 and 4 balance in EUR. The FX suspense account's USD side goes up by 1000 (credit) and its EUR side goes down by 850 (debit). Over time, the net position depends on the conversion rates applied. At end of day, we value the FX position at current market rates and post the mark-to-market gain or loss."))

    # SECTION 4: Deep Dive — Rate Locking, Per-Currency Balancing, Hash Chain Audit (~8 min)
    lines.append(("interviewer", "Let's deep dive into rate locking and how it interacts with the ledger."))

    lines.append(("candidate", "Rate locking is critical for both user trust and our FX risk management. Here's the detailed flow. When Alice initiates a cross-currency transfer, the front-end calls the Quote API with the source currency, target currency, and amount. The Quote API calls the Rate Serving Service, which reads the latest aggregated rate from Redis — say 1 USD equals 0.8515 EUR. It creates a rate lock in Redis: key is ratelock:quoteID, value is the rate, TTL is 30 seconds. It returns the quote ID and the locked rate to the client."))

    lines.append(("candidate", "Alice reviews the quote and clicks confirm. The front-end calls the Execute Transfer API with the quote ID. The Ledger Service receives the request and first validates the rate lock — it checks Redis for ratelock:quoteID. If the key exists and the rate has not expired, we proceed. If the key has expired — it's been more than 30 seconds — we reject the transfer and ask the client to get a new quote. This is important: we never execute a transfer with an expired rate because the market might have moved, and we would be taking on FX risk."))

    lines.append(("candidate", "Once the rate lock is validated, the Ledger Service starts a database transaction. Within this single transaction, it does four things atomically: first, checks that Alice's USD account has sufficient balance. Second, creates the four ledger entries — debit Alice USD, credit FX suspense USD, debit FX suspense EUR, credit Alice EUR. Third, updates the account balances — subtract 1000 from Alice's USD balance and add 850 EUR to Alice's EUR balance. Fourth, writes the audit hash chain entry. All of this commits or rolls back together. If Alice's balance is insufficient, the transaction fails and we return an error. If the database commit succeeds, the transfer is final and immutable."))

    lines.append(("interviewer", "What happens if the rate lock expires between validation and commit? Say the lock had 1 second remaining when we checked, but the database transaction took 2 seconds to commit?"))

    lines.append(("candidate", "That's a real concern. The rate lock check and the ledger write should happen in the same database transaction, or at least the lock check should be very close in time to the commit. But we can't put a Redis check inside a database transaction — they're different systems. So we need a different approach. Instead of checking the lock in Redis during the commit, we could write the rate lock to the database as well, with an expiration timestamp. Then the database transaction can check: is the expiration timestamp in the future? If yes, proceed. If no, reject. This way, the lock validation and the ledger write are in the same atomic transaction. We still use Redis for the fast quote serving path, but the database is the source of truth for lock validity during execution."))

    lines.append(("candidate", "Wait, let me think about this more carefully. If we write the rate lock to the database, that adds a database write to the quote path, which adds latency. The quote needs to be fast — under 50ms — to feel instant to the user. A database write might add 10 to 20ms. That might be acceptable. Let me consider the alternative: we accept a small window of FX risk. If the rate lock expires during the database commit — which typically takes 5 to 10ms — the market rate might have moved by 0.01 percent at most in that time. For a 1000 USD transfer, that's 10 cents of FX risk. For our business, that's acceptable — we would rather take the tiny risk than add latency to every quote. So I would stick with the Redis-based lock check before the database transaction, and accept the small FX risk window. For corporate clients with larger amounts, we could use the database-based lock for stronger guarantees."))

    lines.append(("interviewer", "Let's talk about per-currency balancing. How do you ensure the ledger is always in balance per currency?"))

    lines.append(("candidate", "The invariants we need to maintain are: for each currency, the sum of all account balances equals zero. Wait, that's not right — account balances represent assets and liabilities. The correct invariant is: for each currency, total debits equal total credits across all entries. Or equivalently, the sum of all account balances is zero — because every debit increases one account and every credit decreases another, or vice versa, depending on the account type. Let me be more precise. In double-entry bookkeeping, each account has a type: asset, liability, equity, revenue, or expense. Assets and expenses have debit-normal balances — debits increase them. Liabilities, equity, and revenue have credit-normal balances — credits increase them. The fundamental equation is: assets equal liabilities plus equity. For a multi-currency ledger, this equation must hold per currency."))

    lines.append(("candidate", "To enforce this at write time, every database transaction that writes ledger entries also verifies the balance. The simplest enforcement is an application-level check: before committing the transaction, we compute the net amount per currency across all entries in the transaction. If any currency has a non-zero net, we reject the transaction. This is a simple in-memory check that takes microseconds. For ongoing verification, we run a reconciliation job every hour that reads all ledger entries for each currency and verifies the sum of debits equals the sum of credits. If there's any discrepancy — which should never happen if the write-time check is working — it generates an alert for manual investigation."))

    lines.append(("interviewer", "Now let's talk about the hash chain audit trail. How exactly does that work?"))

    lines.append(("candidate", "The hash chain provides cryptographic proof that the ledger has not been tampered with. Each transaction in the ledger includes a hash field. The hash is computed as SHA-256 of the concatenation of: the transaction's data — all entry amounts, account IDs, currencies, and the rate — plus the hash of the previous transaction. This creates a chain where each transaction's hash depends on all previous transactions. If anyone modifies a historical entry, the hash chain breaks — the modified entry's hash changes, which causes the next entry's hash to change, cascading all the way to the latest entry. Verification is straightforward: recompute the entire hash chain and compare with stored hashes. Any divergence indicates tampering."))

    lines.append(("candidate", "There's a practical concern with this design. At 50K TPS, computing the hash of the previous transaction requires knowing it — which means transactions must be serialized. We can't process transactions in parallel if each depends on the hash of the previous one. This creates a bottleneck. The solution is to hash at the batch level instead of the transaction level. We group transactions into 100-millisecond batches — about 5000 transactions per batch at 50K TPS. Within a batch, transactions are ordered by transaction ID. We compute a Merkle tree over all transactions in the batch, producing a single batch root hash. Then we chain batches: each batch's hash includes the previous batch's root hash. This gives us parallel processing within a batch and serialization only between batches — a 100ms serialization window, which is negligible."))

    lines.append(("candidate", "For verification, an auditor can verify the hash chain of batches — checking that each batch's root hash is derived from the previous batch's root hash and the transactions within. They can also verify individual transactions by checking their Merkle proof against the batch root hash. This provides the same tamper-detection guarantee as a per-transaction chain, but with much better throughput. The storage overhead is one root hash per batch — 32 bytes every 100ms — which is about 27 MB per day. Negligible."))

    lines.append(("interviewer", "How do you handle cross-currency transfers in detail? What about FX gains and losses?"))

    lines.append(("candidate", "For a cross-currency transfer, we lock the rate at quote time. The locked rate determines the exact amounts in both currencies. For example, Alice converts 1000 USD to EUR at a locked rate of 0.8515. She gets exactly 851.50 EUR. But what about the actual cost of acquiring those EUR in the market? If the market rate when we execute is 0.8520, we effectively bought EUR slightly cheaper than what we quoted — we make a small FX gain of 0.50 EUR. If the market rate is 0.8510, we lose 0.50 EUR. The gain or loss is recorded automatically by the FX suspense account reconciliation. When we mark the FX suspense account to market at end of day, any imbalance between the USD side and the EUR side (converted at current rates) is posted to the FX PnL account. This is a standard accounting practice called mark-to-market."))

    lines.append(("candidate", "There's another subtlety: when we quote a rate with a spread, we're already building in a profit margin. The spread is our primary revenue source. The FX gain or loss from the suspense account is a secondary effect — it's usually small compared to the spread revenue. But it can accumulate over time, especially during volatile market conditions. That's why we keep the TTL short — 30 seconds for retail — to minimize the window where the market can move against our quoted rate."))

    # SECTION 5: Failure Modes (~4 min)
    lines.append(("interviewer", "What are the most critical failure scenarios?"))

    lines.append(("candidate", "The first is a rate provider outage. If Bloomberg goes down, we lose one of our rate sources. The aggregation service detects this via WebSocket disconnection and continues aggregating from the remaining providers. The spread might widen slightly because we have fewer competing bids and asks, but the system remains functional. If all providers go down simultaneously — extremely unlikely — we can't generate new quotes. Existing locked quotes still work. We'd reject new cross-currency transfers and serve only same-currency operations. As a last resort, we could fall back to stale rates with a wider spread, but that's a business decision."))

    lines.append(("candidate", "The second scenario is a ledger write failure. If the database transaction fails after we've already consumed the rate lock, we've used up a locked rate without completing a transfer. The rate lock in Redis expires naturally — it has a TTL. No harm done — the client retries with a new quote. But we need to make sure the database transaction is truly atomic. If it partially commits — say the ledger entries are written but the balance update fails — we have an inconsistent ledger. This is why we use a single database transaction with a write-ahead log. PostgreSQL's ACID guarantees prevent partial commits. Either all four entries and both balance updates commit, or none do."))

    lines.append(("candidate", "The third scenario is a reconciliation failure — the per-currency balance check finds a discrepancy. This should never happen, but if it does, it's a critical incident. We halt all new transactions for the affected currency, investigate the root cause, and apply a correcting entry with full audit trail documentation. The hash chain makes it easy to identify when the discrepancy was introduced — we verify the chain from the beginning and find the first batch where the computed hash differs from the stored hash."))

    lines.append(("candidate", "The fourth scenario is a hash chain break — an auditor finds that the recomputed chain does not match the stored chain. This indicates either a software bug in the hash computation or actual tampering. We investigate by comparing the individual transaction data against the hash inputs. If a transaction was modified, we can identify exactly which one and when. We keep an immutable backup of the entire ledger in a separate, write-once storage system — like WORM tape or a blockchain-style append-only log — as a secondary verification source."))

    # SECTION 6: Scale & Debrief (~3 min)
    lines.append(("interviewer", "How does the design change at 10x scale — 500K TPS?"))

    lines.append(("candidate", "At 500K TPS, the ledger database is the primary bottleneck. We'd need many more shards — maybe 50 to 100 shards partitioned by a combination of account ID range and currency. The hash chain batching would need shorter batch intervals — maybe 10ms instead of 100ms — to keep the Merkle tree size manageable. The FX rate engine scales more easily since it's mostly in-memory with Redis lookups. The real concern at 500K TPS is the account balance contention. If many transactions touch the same popular account — like a corporate payroll account — we have a hot spot. We'd need to implement a queuing mechanism for high-contention accounts, processing their transactions sequentially from a dedicated queue rather than allowing concurrent database transactions that would conflict and retry."))

    lines.append(("candidate", "At 0.1x scale — 5K TPS — the design simplifies considerably. A single PostgreSQL instance with read replicas handles the ledger. No sharding. Redis is a single node. The hash chain could be per-transaction instead of per-batch, since serialization at 5K TPS is feasible. The FX rate engine runs on a single server. But the core logic — double-entry per currency, rate locking, and audit trail — stays exactly the same. Financial correctness does not scale down."))

    lines.append(("interviewer", "Let me give you feedback. Positives: excellent requirements clarification — you asked about rate sourcing, rate locking, settlement scope, and audit requirements unprompted. The cross-currency ledger entry model with the FX suspense account and mark-to-market reconciliation was precise and well-explained. The batch-level Merkle tree for the hash chain shows strong understanding of the throughput bottleneck with per-transaction chaining. Your self-correction on the FX suspense account balancing was good — you caught that it accumulates a position and explained how reconciliation handles it. For improvement: when discussing the rate lock expiration race condition, you went back and forth a bit before settling on accepting the small FX risk — a more structured analysis of the options with a clear trade-off table would have been stronger. Also, you could have discussed how to handle a partial failure in a cross-shard transaction — when the sender and beneficiary accounts are on different database shards, the two-phase commit or saga approach adds complexity. Overall, very strong. Thanks."))

    lines.append(("candidate", "Thanks for the feedback. The cross-shard transaction issue is important — I should have addressed it explicitly. With 50K TPS, it's likely that many cross-currency transfers touch accounts on different shards, and a distributed transaction protocol like a saga with compensating entries would be needed. I'll make sure to cover that next time. Good interview."))

    return lines
