"""Mock Interview: Global Treasury Network — Two-voice dialogue."""


def build():
    lines = []

    # SECTION 1: Requirements (~5 min)
    lines.append(("interviewer", "Hi, welcome. Today I'd like you to design a Global Treasury Network — think of what a company like Airwallex provides for enterprise treasury management. You're managing cash across dozens of countries, hundreds of bank accounts, and over a hundred currencies. The core problem is: how do you give a CFO real-time visibility into every dollar, euro, and yen across the entire organization, and how do you automatically optimize where cash sits? Start by clarifying the requirements."))

    lines.append(("candidate", "Thanks. Treasury management is a deep domain — it sits at the intersection of banking, FX, accounting, and regulatory compliance. Let me start with the most fundamental question: are we building this for a single corporate entity with subsidiaries, or a platform that serves multiple enterprise clients, each with their own entity structures? Because multi-tenancy at the entity level changes the isolation model and the regulatory scope dramatically."))

    lines.append(("interviewer", "We're a platform — like Airwallex's treasury product. We serve multiple enterprise clients, each with their own legal entities across countries. So multi-tenancy is mandatory. One client might have 3 entities in 2 countries, another might have 40 entities across 25 countries."))

    lines.append(("candidate", "OK, multi-tenant platform. Next I'd want to understand the core operations. I'm thinking of several: cash position aggregation across all entities and accounts, cash pooling — both notional and physical — inter-company loans and settlements, FX exposure management, and payment netting between entities. Are all of these in scope, or should I prioritize? And what about reconciliation — matching inter-company transactions across entity ledgers seems like it must be in scope too."))

    lines.append(("interviewer", "All of them are in scope. But let me give you the color that drives the design. The key insight is that a multinational corporation's treasury is fundamentally about offsetting. Entity A owes Entity B 10 million EUR, and Entity B owes Entity C 8 million EUR, and Entity C owes Entity A 6 million EUR. If you net those positions, you reduce the total gross flows from 24 million to a much smaller net settlement. Every dollar of gross flow you eliminate saves FX conversion fees, bank transfer fees, and settlement risk. So the netting engine is really the heart of the system."))

    lines.append(("candidate", "That's a crucial insight — netting as the core value driver, not just cash visibility. A few more questions. First, bank connectivity: are we connecting to banks via APIs, SWIFT, host-to-host, or all of the above? And how many banks are we talking about? Second, what about regulatory constraints — capital controls in countries like China or India, withholding tax on inter-company transfers, different reporting requirements per jurisdiction? These constraints could fundamentally limit what the netting engine can do. Third, real-time — what does real-time cash position mean here? True real-time from bank feeds, or near-real-time with periodic refresh?"))

    lines.append(("interviewer", "Good questions. Bank connectivity: we connect via APIs where available — that's maybe 30 percent of banks — and SWIFT MT940 for balance reporting and MT103 for payments for the rest. We need to support 100-plus banks globally. Regulatory constraints are per-jurisdiction and they're critical — we can't just move money freely across borders. Some countries require central bank approval for outbound transfers above a threshold, others impose withholding tax on inter-company interest, and some restrict the types of pooling structures allowed. Real-time cash position means we get bank balance updates at least every 15 minutes for API-connected banks and every few hours for SWIFT-only banks. It's near-real-time, not tick-by-tick."))

    lines.append(("candidate", "Let me also ask about the cash pool types. Notional pooling — where balances are offset for interest calculation without physical movement — and zero-balancing — where end-of-day sweeps move cash to a header account — these have very different operational requirements. And are we supporting multi-currency pools, or just single-currency pools?"))

    lines.append(("interviewer", "We support both notional pooling and zero-balancing with sweep accounts. Single-currency pools for now, but the architecture should support multi-currency pools in the future. And yes, inter-company loans are in scope — when one entity lends to another, we need to track the loan principal, interest accrual, and the FX impact if they're in different currencies."))

    lines.append(("candidate", "Let me summarize. We're building a multi-tenant Global Treasury Network platform with: multi-entity, multi-currency management across 50-plus countries and 130-plus currencies; bank connectivity to 100-plus banks via APIs and SWIFT; cash position aggregation with near-real-time visibility; cash pooling including notional pooling, zero-balancing, and sweep accounts; inter-company loans with interest accrual and FX tracking; FX exposure management with hedging and netting; payment netting to offset payables and receivables between entities; regulatory compliance per jurisdiction including capital controls, withholding tax, and reporting; and reconciliation of inter-company transfers across entity ledgers. Annual volume is 50 billion dollars plus across 200-plus bank accounts. Let me move to estimation."))

    # SECTION 2: Estimation (~5 min)
    lines.append(("interviewer", "Go ahead with the numbers."))

    lines.append(("candidate", "Let me start with the entity and account model. 50 enterprise clients, average 10 legal entities each — that's 500 legal entities. Each entity averages 4 bank accounts across different banks and currencies, so 2,000 bank accounts total. Some large multinationals might have 30 entities with 200 accounts, others 2 entities with 3 accounts. For 130-plus currencies, not every entity holds every currency — the average entity holds 3 to 5. So currency-accounts — entity times currencies — is roughly 500 times 4, which is 2,000. But inter-company positions are entity-pair times currency — much larger. With 500 entities, maximum pairs are about 125,000, but only maybe 20 percent have active inter-company relationships. So about 25,000 position tracks."))

    lines.append(("candidate", "Daily volume: 50 billion annual translates to about 200 million net per business day, assuming 250 business days. But netting typically eliminates 60 to 70 percent of gross flows, so gross daily volume might be 500 to 600 million. With average transaction size of 100,000 dollars for B2B treasury operations, that's about 5,000 gross transactions per day, or roughly 500 to 600 per hour during business hours. Peak might be 5 to 10 TPS during settlement windows — when the netting engine executes a batch of settlements simultaneously. This is not a high-TPS system — it's a high-complexity, high-value system where correctness and regulatory compliance matter far more than raw throughput."))

    lines.append(("interviewer", "What about the netting savings? How would you quantify the value?"))

    lines.append(("candidate", "Netting savings come from three sources. First, FX conversion savings — netting 5 million EUR payable against 4 million EUR receivable reduces cross-border flow from 9 million to 1 million. At 0.3 to 0.5 percent spread, saving 8 million in conversion saves 24,000 to 40,000 dollars per cycle on a single pair. Scale that across hundreds of entity pairs and currencies, and annual savings easily reach millions. Second, bank fees — SWIFT transfers cost 25 to 50 dollars each, and with correspondent bank fees, it can be 100 dollars per transfer. Eliminating 3,000 gross transfers daily saves 300,000 to 1.5 million dollars annually. Third, settlement risk reduction — every open inter-company payable is a credit risk. Netting reduces outstanding positions, reducing the risk that one entity's default creates a cascade. The risk reduction is harder to quantify but often the most valuable benefit from the CFO's perspective."))

    lines.append(("candidate", "Storage is light — each transaction record including inter-company reference, FX details, regulatory metadata, and reconciliation status is 1 to 2 KB. At 5,000 gross transactions per day, that's 5 to 10 MB per day. Inter-company position state — 25,000 active tracks at 500 bytes each — is about 12 MB. Bank balance feeds: 2,000 accounts updating every 15 minutes produce about 192,000 snapshots per day at 200 bytes each, roughly 38 MB daily. Over 7 years, about 100 GB. SWIFT MT940 statements add maybe 10 MB per day. All manageable. The real storage concern is audit trail and regulatory reporting — some jurisdictions require 10-year retention — but even at 10 MB per day for 10 years, that's about 36 GB. The complexity here is in the domain logic, not the data size."))

    # SECTION 3: High-Level Architecture (~5 min)
    lines.append(("interviewer", "Good. Let's move to the high-level architecture."))

    lines.append(("candidate", "The architecture has five subsystems. First, the Bank Connector Layer — connectivity to 100-plus banks via APIs and SWIFT, normalizing balance reports, transaction statements, and payment submissions into a common internal format. Each bank adapter handles the protocol-specific quirks — SWIFT MT940 for statements, MT103 for payments, REST APIs for modern banks. Second, the Position Aggregator — maintains real-time cash position for every entity, account, and currency, consuming balance feeds and inter-company events. Third, the Netting Engine — computes multilateral netting positions to determine the minimum settlement set. Fourth, the FX Engine — manages FX exposure, hedging strategies, and cross-currency conversions. Fifth, the Sweep Engine — manages zero-balancing sweeps, notional pool calculations, and liquidity transfers."))

    lines.append(("candidate", "The data flow: Bank Connector pulls balance and transaction data on a schedule — every 15 minutes for API banks, every few hours for SWIFT-only banks — publishing normalized updates to a Kafka topic called balance-updates. The Position Aggregator consumes this and updates entity-account-currency positions. It also listens to inter-company transaction events — when an invoice is recorded or settled, the position changes. The Position Aggregator exposes a query API for the CFO dashboard showing real-time visibility across the entire organization."))

    lines.append(("interviewer", "How does the Netting Engine interact with the other components?"))

    lines.append(("candidate", "The Netting Engine runs on a schedule — daily or twice daily, depending on the client's treasury policy. When triggered, it queries the Position Aggregator for all outstanding inter-company payables and receivables, then runs multilateral netting. For each currency, it computes each entity's net position across all counterparties. In multilateral netting, we designate a netting center — typically the parent entity or a treasury center entity. Net payers transfer to the center, and the center transfers to net receivers. The center is just a pass-through — total paid equals total received. The key optimization: gross flows are dramatically reduced. Without netting, maybe 50 million EUR in gross flows. With netting, 8 million EUR. That 42 million reduction saves FX fees, bank fees, and settlement risk."))

    lines.append(("candidate", "After netting computes settlement instructions, it passes them to the FX Engine for cross-currency conversions — if an entity is a net payer in EUR but only holds USD, the FX Engine locks a rate and converts. Then the Sweep Engine checks whether settlements align with the cash pooling strategy — maybe a zero-balanced sub-account can sweep to the header, and the header pays the netting center directly, avoiding an extra transfer. Finally, instructions go to the Bank Connector Layer for execution via the appropriate banking rails — Fedwire for domestic USD, SEPA for EUR within the EU, SWIFT for cross-border."))

    lines.append(("interviewer", "Why use Kafka here? The volume is low — 5,000 transactions per day. Is Kafka necessary?"))

    lines.append(("candidate", "Kafka provides durable, ordered delivery with replay capability. If the Position Aggregator crashes, it resumes from its last committed offset. If we need to recompute positions from scratch — maybe after a data correction — we replay the entire balance-updates topic. In a financial system where correctness depends on processing every update, this is valuable. At our scale though, a database-backed event log would also work. I'd use Kafka for its replay semantics and operational maturity, but it's not the only option."))

    # SECTION 4: Deep Dive — Netting Engine, Cash Pooling, and Cross-Entity Reconciliation (~10 min)
    lines.append(("interviewer", "Let's deep dive into the three hardest parts: the netting engine, cash pooling, and cross-entity reconciliation. Start with the netting engine."))

    lines.append(("candidate", "The netting engine solves a constrained optimization problem. We have N entities and C currencies. For each currency c, P[i][j][c] is the amount entity i owes entity j. The gross flow is the sum of all bilateral positions. The netting objective: find settlement amounts Q such that every entity's net position is preserved — total received minus total paid stays the same — and total gross settlement flow is minimized."))

    lines.append(("candidate", "The algorithm: for each currency independently, compute each entity's net position — total receivables minus total payables. Net payers pay the netting center; net receivers receive from the netting center. The total gross flow in the netted case is just the sum of all positive net positions, which equals the sum of all negative net positions in absolute value. The savings is original gross flow minus this net flow."))

    lines.append(("interviewer", "Can you walk through a concrete example?"))

    lines.append(("candidate", "Sure. Let's say we have three entities in EUR. Entity A owes B 5 million, B owes C 3 million, C owes A 4 million. The gross flow is 5 plus 3 plus 4 equals 12 million EUR. Now compute net positions: A is owed 4 million by C and owes 5 million to B, so net is minus 1 million — A is a net payer of 1 million. B is owed 5 million by A and owes 3 million to C, so net is plus 2 million — B is a net receiver of 2 million. C is owed 3 million by B and owes 4 million to A, so net is minus 1 million — C is a net payer of 1 million. The net settlement: A pays 1 million to the netting center, C pays 1 million, the netting center pays 2 million to B. Total flow: 2 million instead of 12 million. An 83 percent reduction. That's a massive saving in FX fees and bank transfer costs."))

    lines.append(("candidate", "Now the complexity increases with multiple currencies. Suppose A owes B 5 million EUR and B owes A 4 million USD. Without cross-currency netting, these are separate — two settlements, two FX conversions. With cross-currency netting, convert the 4 million USD to EUR at a reference rate — say 1.08 USD per EUR, so 3.7 million EUR — and net against the 5 million EUR payable. A pays B only 1.3 million EUR. One settlement instead of two. But this introduces FX risk — the reference rate matters, and entities must agree on it upfront. Typically, we use a central bank fixing rate like the ECB rate for EUR, agreed before the netting cycle."))

    lines.append(("interviewer", "What about the regulatory constraints? You can't just net everything freely."))

    lines.append(("candidate", "Exactly. Each jurisdiction imposes constraints the algorithm must respect. China has capital controls — an entity in Shanghai can't freely send RMB abroad to a Singapore netting center. We might need to net within the same jurisdiction first, then handle cross-border settlements separately with regulatory approval. India requires RBI approval for outbound transfers above thresholds."))

    lines.append(("candidate", "So the netting engine has a constraint layer. For each entity pair and currency, it checks: is cross-border settlement allowed? Are there thresholds? Withholding tax? Restricted lists? These constraints live in a regulatory rules engine — configurable per jurisdiction without code changes. The netting algorithm becomes a constrained optimization: minimize total settlement flow subject to jurisdiction constraints. This is a linear programming problem — we'd use an LP solver like Gurobi or PuLP."))

    lines.append(("interviewer", "Now let's talk about cash pooling. How does notional pooling work, and how is it different from zero-balancing?"))

    lines.append(("candidate", "Notional pooling and zero-balancing serve the same goal — optimize interest on idle cash — but work very differently. In notional pooling, the bank calculates interest on the combined net position without moving money. If Entity A has plus 10 million EUR and Entity B has minus 2 million EUR, the bank pays interest on net 8 million rather than paying on 10 million and charging on 2 million separately. No physical movement means no inter-company loans, no FX conversions, no regulatory issues with moving money across borders. But not all banks or jurisdictions support it — some tax authorities treat the interest offset as a deemed loan requiring transfer pricing documentation."))

    lines.append(("candidate", "Zero-balancing is physical. At end of day, the bank sweeps all sub-account balances to a header account. A's surplus moves to the header; the header funds B's deficit to bring it to zero. This creates physical inter-company balances — the header is lending to overdrawn sub-accounts. These must be tracked with arm's-length interest rates — transfer pricing rules require it. Zero-balancing is more widely available than notional pooling, but it creates more accounting complexity and requires careful tracking of inter-company loan positions."))

    lines.append(("candidate", "In our system, the Sweep Engine manages both types. For notional pooling, it's mostly passive — we calculate the pool's net position for interest reporting but generate no transactions. For zero-balancing, the Sweep Engine triggers end-of-day sweeps: it queries the Position Aggregator for all sub-account balances in a pool, computes the sweep amounts, and submits instructions to the Bank Connector. Each sweep generates an inter-company loan entry in the ledger — Entity A's excess cash swept to the header is a deposit from A to the header, and B's deficit covered by the header is a loan from the header to B. Interest accrues daily on these inter-company balances at the configured arm's-length rate, which must comply with OECD transfer pricing guidelines."))

    lines.append(("interviewer", "Now let's talk about cross-entity reconciliation. Why is this hard?"))

    lines.append(("candidate", "Cross-entity reconciliation is hard because each entity maintains its own ledger, and inter-company transactions must match across independent books. When A records a 5 million EUR payable to B, B must record a 5 million EUR receivable from A. In practice they often don't: A records on invoice date, B on receipt date — timing difference. A records in invoice currency, B in functional currency after FX conversion — currency mismatch. A records gross, B records net after bank fees — amount mismatch. Different ERPs with different chart of accounts and rounding rules compound the problem."))

    lines.append(("candidate", "The reconciliation engine works in three stages. Stage 1 is automatic matching — it takes all inter-company entries and matches on the inter-company reference number. When A records a payable, it includes a reference that B should echo on the receivable. We match on reference plus amount plus currency, allowing small rounding tolerance — 0.01 percent or 1 currency unit, whichever is greater. Stage 2 is fuzzy matching for unmatched entries — maybe the reference was entered differently or omitted. The engine tries matching on amount and currency alone within a date range. If A has a 5 million EUR payable and B has a 5 million EUR receivable in the same week, that's a candidate match presented to a treasury analyst for confirmation. Stage 3 is exception handling — entries that couldn't be matched become reconciling items: potential errors, missing entries, or timing differences needing investigation."))

    lines.append(("candidate", "The reconciliation engine runs daily after netting and sweeps complete — these operations create new inter-company entries that must be matched. The output is a reconciliation report per entity pair and currency: matched items, candidate matches awaiting approval, and exceptions. Unresolved exceptions older than 30 days are escalated. In our platform, all entities' ledgers are unified, so the engine has direct read access. With external ERPs, we'd ingest trial balances via file feeds or APIs, which adds complexity."))

    # SECTION 5: Failure Modes (~4 min)
    lines.append(("interviewer", "What are the most critical failure scenarios?"))

    lines.append(("candidate", "The first is a bank API outage. If HSBC goes down, we lose balance updates for all accounts there and can't execute payments. The Position Aggregator continues serving the last known position with a STALE indicator and timestamp. For payments, the Bank Connector has circuit breakers per bank and falls back to alternative rails if available — maybe routing through a different correspondent bank. If no alternative exists, we queue the payment and alert the treasury operations team."))

    lines.append(("candidate", "The second is an FX spike during a netting cycle. We've computed positions and are about to settle when a geopolitical event causes a 5 percent currency move. The locked rates from our FX Engine are now stale. Two options: re-run the netting cycle with updated rates, or execute at the locked rates and absorb the FX difference. Most treasury policies fix rates at the cut-off time — subsequent movement is borne by the party whose currency depreciated. But the system needs to support both approaches as configuration, because different clients have different risk appetites."))

    lines.append(("candidate", "The third is a regulatory block. We try a cross-border settlement and the bank rejects it — maybe the jurisdiction changed capital control rules overnight, or we hit a previously unknown threshold. This is dangerous because it leaves the netting cycle partially settled. Entity A has paid the netting center, but the center can't pay Entity B because the outbound transfer was blocked. We mark the settlement as REGULATORY_HOLD and trigger manual review. The netting center's account holds the funds in suspense until the regulatory issue is resolved — which could take days or weeks. During this time, the inter-company positions are inconsistent, and the reconciliation engine will flag the discrepancy."))

    lines.append(("candidate", "The fourth is a reconciliation failure revealing a missing entry. A recorded a 5 million EUR payable to B, but B has no corresponding receivable. Could be genuine error — B's AP team forgot to record it — or it could indicate fraud. The reconciliation engine flags it as high-priority. But the system can't create the missing entry — each entity's ledger is independently maintained. Instead, it alerts both treasury teams with the reconciliation report, drill-down into both ledgers, and the audit trail. Resolution is a business process, not an automated fix."))

    lines.append(("interviewer", "What about a sweep failure? If the zero-balancing sweep for one account fails, does the whole pool fail?"))

    lines.append(("candidate", "In a strict zero-balancing pool, all sub-accounts must be swept simultaneously. We handle this with a two-phase approach. Phase 1: sweep all positive-balance accounts to the header — debits from sub-accounts that should always succeed if the accounts have funds. Phase 2: fund all negative-balance accounts from the header — credits to sub-accounts, which can fail if the header has insufficient funds to cover all deficits. If Phase 2 fails, we prioritize by entity or amount per configuration, and unfunded accounts remain overdrawn. That generates an inter-company loan from the header at a penalty rate. We alert the treasury team that the pool is underfunded — they may need to inject external liquidity."))

    # SECTION 6: Scale & Debrief (~3 min)
    lines.append(("interviewer", "How does the design change at 10x scale — 500 entities, 20,000 accounts, $500B annual volume?"))

    lines.append(("candidate", "At 10x, the netting engine becomes a computational challenge. 500 entities means 250,000 bilateral pairs per currency, times 130 currencies — 32.5 million position records. But the LP problem is sparse — most pairs have no positions in most currencies. A sparse solver handles this fine. The real bottleneck is the regulatory rules engine: 500 entities across potentially 100 jurisdictions creates a complex constraint matrix. We'd precompute the constraint set per netting cycle rather than checking each pair individually during the solve."))

    lines.append(("candidate", "The Bank Connector Layer at 10x needs a declarative adapter framework — specify bank API format, authentication, and field mappings without writing code, so operations can onboard banks faster. With 200-plus banks, managing individual adapters becomes unsustainable. The Position Aggregator handles 400,000 updates per day, about 5 per second average — easily managed by a single Kafka consumer, though we'd want replicas for availability."))

    lines.append(("candidate", "At 0.1x — 50 entities, 200 accounts — no LP solver needed; simple bilateral netting suffices. The regulatory rules engine becomes a static config file instead of a dynamic rules engine. The Bank Connector connects to maybe 10 banks, mostly via SWIFT with manual adapters — the declarative framework is overkill. Reconciliation runs synchronously. But the core architecture — Position Aggregator, Netting Engine, Sweep Engine, FX Engine, Bank Connector — stays the same because the domain logic doesn't change with scale. Even at 0.1x, you still need netting, pooling, and reconciliation. You just implement them more simply."))

    lines.append(("candidate", "One qualitative change at 10x: jurisdiction-specific deployments. China, Russia, India have data residency requirements preventing financial data from leaving their borders. We need regional Position Aggregator and Netting Engine instances with cross-region coordination for global netting cycles. The netting center might be Singapore for APAC, London for EMEA, New York for the Americas — the netting cycle must coordinate across these regional instances, running local netting first within each jurisdiction, then coordinating cross-regional settlements. Adds significant operational complexity but doesn't change the fundamental algorithm."))

    # SECTION 7: End-to-End Walkthrough (~4 min)
    lines.append(("interviewer", "Let's do an end-to-end walkthrough. Trace a full netting cycle from start to finish with concrete entities and numbers."))

    lines.append(("candidate", "Let's trace it with a concrete scenario. We have three entities: Airwallex US holding USD, Airwallex UK holding GBP and EUR, and Airwallex Germany holding EUR. The netting cycle triggers at 4 PM UTC — the daily cut-off time configured for this client. The netting center is Airwallex Singapore."))

    lines.append(("candidate", "Step 1: Position Aggregation. The Netting Engine queries the Position Aggregator for all outstanding inter-company positions. It gets: Airwallex US owes Airwallex UK 5 million USD for shared services fees. Airwallex UK owes Airwallex Germany 3 million EUR for a supplier payment on Germany's behalf. Airwallex Germany owes Airwallex US 4 million USD for a license fee. Three open payable-receivable pairs."))

    lines.append(("candidate", "Step 2: Compute Net Positions. For USD: US owes UK 5 million, Germany owes US 4 million. US net: receives 4, pays 5, so minus 1 million — net payer. UK net: receives 5 million — net receiver. Germany net: pays 4 million — net payer. Total payers 5 million, total receivers 5 million. Balanced. For EUR: UK owes Germany 3 million. UK is net payer, Germany is net receiver."))

    lines.append(("candidate", "Step 3: Cross-Currency Netting. UK receives 5 million USD and pays 3 million EUR. Converting 3 million EUR at ECB fixing rate of 1.08 gives 3.24 million USD. UK's net across both currencies: receives 5M, pays 3.24M equivalent — net receiver of 1.76M USD. Germany receives 3M EUR equivalent (3.24M USD) and pays 4M USD — net payer of 0.76M USD. US pays 1M USD. Verification: total payers 1M plus 0.76M equals 1.76M. Total receivers 1.76M. Balanced."))

    lines.append(("candidate", "Step 4: Regulatory Check. US paying 1 million USD domestically — no issues. Germany paying 0.76 million USD cross-border — EU free movement applies, no capital controls. Withholding tax check: no withholding on inter-company settlements under 1 million EUR equivalent. Pass."))

    lines.append(("candidate", "Step 5: FX Rate Lock. Germany needs to convert EUR to USD for the settlement. The FX Engine locks EUR-USD at 1.08 with a 0.1 percent spread for a 30-minute window. The quote ID and TTL are stored in the FX rate cache."))

    lines.append(("candidate", "Step 6: Settlement Execution. Three instructions go to the Bank Connector: US pays 1M USD to Singapore netting center via Fedwire. Germany converts 703,704 EUR to 760,000 USD at the locked rate and pays to Singapore via SWIFT. Singapore netting center pays 1.76M USD to UK via CHAPS. The Bank Connector routes each to the appropriate bank adapter — Fedwire adapter for the domestic US transfer, SWIFT adapter for the cross-border Germany-Singapore transfer, CHAPS adapter for the UK settlement."))

    lines.append(("candidate", "Step 7: Ledger and Reconciliation. As payments settle, the Bank Connector publishes settlement events. We write ledger entries on both sides — payer debited, netting center credited, then netting center debited and receiver credited. Inter-company loan entries record the arm's-length settlement of underlying payable-receivable positions. The reconciliation engine runs after a 24-hour settlement window, matching entries across all three ledgers. If US shows a 1 million USD payable to Singapore and Singapore shows a 1 million USD receivable from US — match. Any missing or mismatched entries become exceptions."))

    lines.append(("candidate", "Step 8: Cash Pool Update. The Sweep Engine checks pool positions after the netting cycle. If UK's USD account now has a large incoming 1.76 million and the zero-balancing pool sweeps to Singapore's header at end of day, the Sweep Engine schedules the sweep. The inter-company loan from UK to header is recorded at the day's arm's-length interest rate. The Position Aggregator updates, and the CFO dashboard reflects the new cash positions across all entities, accounts, and currencies."))

    # SECTION 8: Thinking Process & Beats (~3 min)
    lines.append(("interviewer", "Before we wrap up, I want to share my thinking process for evaluating a Global Treasury Network design — the framework I use when I approach any problem in this domain."))

    lines.append(("interviewer", "When I see a treasury management problem, the first thing I look for is whether the candidate recognizes this as an optimization problem layered on a compliance problem, not a data pipeline problem. The value is netting — reducing gross flows to save FX fees and bank charges. But every optimization must respect jurisdiction-specific regulatory constraints. If a candidate starts with API endpoints and schemas before understanding the netting algorithm and regulatory landscape, that's a red flag. They should ask about inter-company positions, netting cycles, and jurisdiction constraints first."))

    lines.append(("interviewer", "The first beat I listen for is netting saves FX cost. The candidate should understand why netting exists — every cross-currency transfer has a spread, every cross-border wire has a fee, every open position carries settlement risk. Bilateral netting reduces N-squared gross flows to N net flows; multilateral reduces further. Quantifying savings — even a rough 60 to 70 percent reduction — shows they grasp the value. Stronger candidates note that netting is most valuable when entity pairs have reciprocal flows — if A only pays B, there's nothing to net."))

    lines.append(("interviewer", "The second beat is cash pooling optimizes liquidity. The candidate should distinguish notional pooling from zero-balancing and understand tradeoffs. Notional pooling avoids fund movement — sidestepping inter-company loans, FX, and regulatory issues — but is limited to supporting banks and jurisdictions. Zero-balancing is more universal but creates inter-company loan balances requiring transfer pricing interest. The candidate should mention the liquidity angle — idle cash earning low interest while another entity borrows at high rates is waste; pooling centralizes liquidity to reduce external borrowing."))

    lines.append(("interviewer", "The third beat is regulatory per-jurisdiction — the most critical and most often overlooked constraint. Capital controls restrict cross-border movements. Withholding tax hits inter-company interest. Transfer pricing requires arm's-length rates. Central bank reporting varies by jurisdiction. A netting engine ignoring these produces instructions that can't execute — worse than no netting, because it creates false settlement expectations. The candidate should propose a configurable rules engine integrated into the netting algorithm as constraints."))

    lines.append(("interviewer", "Now the traps. The biggest is ignoring capital controls — elegant netting algorithms that produce optimal schedules where every settlement crosses a restricted border. Correct in theory, inoperable in practice. Constraints must go into the LP optimization itself, not as post-processing. The second trap is no reconciliation — inter-company positions must match across entity ledgers, and they frequently don't due to timing differences, FX rounding, missing entries, and errors. Without reconciliation, positions slowly diverge from reality until they're unreliable. Describe at least two-stage reconciliation: automatic matching on references, then fuzzy matching for exceptions."))

    lines.append(("interviewer", "The third trap is missing audit trail. Every netting decision, sweep, FX conversion, and inter-company loan must be traceable from original payable through to final settlement. Regulators will ask: why did A pay B this amount on this date? The system must answer by tracing the netting cycle, positions, FX rates, and approvals. The fourth trap is over-optimizing without considering operational simplicity. A theoretically optimal solution requiring 47 settlements in 12 currencies might be marginally better than a near-optimal with 15 settlements in 5 currencies — but the operational risk and overhead of managing 47 cross-border wires outweighs marginal FX savings. Treasury operations value predictability over theoretical optimality."))

    lines.append(("interviewer", "To summarize: identify the problem as optimization-under-constraints, demonstrate that netting reduces FX cost and gross flows, distinguish cash pooling types, build the regulatory rules engine as a first-class component, implement multi-stage reconciliation, and maintain a complete audit trail. Avoid ignoring capital controls, skipping reconciliation, omitting audit trail, and over-optimizing at the expense of operational simplicity. That's the mental model. Thanks — you covered these beats well, especially the regulatory integration and reconciliation stages."))

    return lines
