"""Mock Interview: Idempotent API for Financial Operations — Two-voice dialogue."""


def build():
    lines = []

    # SECTION 1: Requirements
    lines.append(("interviewer", "Hi, welcome. Today I'd like you to design an idempotent API for financial operations. This came up because at Airwallex, every payment endpoint must be idempotent — if a client retries a transfer due to a network timeout, we absolutely cannot process it twice. But idempotency in financial systems is more nuanced than in generic APIs. Start by clarifying the requirements."))

    lines.append(("candidate", "Thanks. Idempotency in fintech is genuinely harder than in other domains because the stakes are different. Retrying a like on a social media post — no one cares if it increments twice. Retrying a hundred-thousand-dollar wire transfer — that's a disaster. Let me ask the key questions. First, what operations need to be idempotent? Just payment creation, or also refunds, FX quotes, and account creation?"))

    lines.append(("interviewer", "All mutating operations on the API must be idempotent. Payment creation, refund processing, FX quote locking, account status changes, and webhook endpoint calls. Read operations are naturally idempotent — GET requests don't change state."))

    lines.append(("candidate", "Second question: who generates the idempotency key — the client or the server?"))

    lines.append(("interviewer", "The client generates the key and sends it as an HTTP header. We chose this because the client knows their intent — they know whether this is a new transfer or a retry of the same transfer. The server can't distinguish between a genuine new request and a retry if the client doesn't tell us."))

    lines.append(("candidate", "Third question: what's the TTL for idempotency records? If a client sends the same idempotency key a week later, should we treat it as a duplicate or a new request?"))

    lines.append(("interviewer", "Good question. Idempotency records should expire after twenty-four hours. If the same key is used after twenty-four hours, we treat it as a new request. This prevents the idempotency store from growing indefinitely while still protecting against the common retry pattern — clients typically retry within seconds to minutes, not days."))

    lines.append(("candidate", "Let me summarize. All mutating operations are idempotent. Client-generated idempotency key in an HTTP header. Twenty-four-hour TTL. And we process real money, so the dedup must be perfect — zero false negatives, meaning we never allow a duplicate, even under concurrent requests, network failures, or database restarts. Moving to the design."))

    # SECTION 2: Core Design — The Idempotency Layer
    lines.append(("interviewer", "Let's start with the core idempotency mechanism."))

    lines.append(("candidate", "The idempotency layer sits between the API gateway and the business logic. Here's how it works for a POST slash payments request. Step one: the client sends a request with the Idempotency-Key header — a UUID that uniquely identifies this operation from the client's perspective. Step two: the API gateway extracts the key and checks the idempotency store. The idempotency store is a database table — not just Redis — because we need durability. If the key exists with status COMPLETED, we return the stored response immediately — same HTTP status code, same response body. No processing occurs. If the key exists with status PROCESSING, we return twenty-two-two Accepted with a polling URL — the request is in progress, try again later. If the key does not exist, we proceed to step three."))

    lines.append(("candidate", "Step three: we INSERT into the idempotency_keys table within the same database transaction as the initial business state change. For a payment, this means: BEGIN TRANSACTION. INSERT into idempotency_keys with key equals the idempotency key, status equals PROCESSING, request_hash equals a hash of the request body. INSERT into transfers with status equals PENDING. COMMIT. The idempotency_keys table has a unique constraint on the combination of key and merchant_id. If two concurrent requests with the same key arrive, one INSERT succeeds and the other gets a unique constraint violation. The violating request falls back to reading the existing record."))

    lines.append(("interviewer", "Why not use Redis for the idempotency check? It's faster."))

    lines.append(("candidate", "Redis is faster, but it's not durable. If Redis crashes or restarts, all idempotency records are lost — and a client retrying during that window would create a duplicate payment. That's unacceptable for a financial system. However, we do use Redis as a first-level cache. Before hitting the database, we check Redis. If the key is in Redis, we return the cached response — this handles the common case of rapid retries within seconds. If the key is not in Redis, we check the database. This gives us the speed of Redis for the hot path and the durability of PostgreSQL for the safety net. The database is the source of truth. Redis is a performance optimization."))

    lines.append(("candidate", "I want to emphasize this pattern because it comes up in every fintech system: Redis for speed, PostgreSQL for truth. If Redis is down, the system still works — it's just slower because every idempotency check hits the database. If PostgreSQL is down, the system stops — because we can't safely process payments without the durable idempotency guarantee. This is the correct trade-off for a financial system."))

    # SECTION 3: Deep Dive — Concurrent Requests
    lines.append(("interviewer", "What happens when two requests with the same idempotency key arrive at exactly the same time on different servers?"))

    lines.append(("candidate", "This is the race condition, and it's the hardest part of idempotency design. Say server A and server B both receive a POST slash payments with idempotency key X at the same time. Both check Redis — cache miss. Both check the database — no record. Both try to INSERT into idempotency_keys. Because of the unique constraint, only one INSERT succeeds. The other gets a constraint violation error. The server that got the violation catches the error, reads the existing record, and returns the appropriate response — either the stored result if COMPLETED, or twenty-two-two Accepted if PROCESSING."))

    lines.append(("candidate", "But there's a subtlety. The database transaction does two things atomically: INSERT into idempotency_keys AND INSERT into transfers. What if server A's transaction commits the idempotency key but the transfer insert fails? Now we have an idempotency key in PROCESSING state but no transfer record. The solution: put both inserts in the same transaction with SERIALIZABLE isolation level. If the transfer insert fails, the entire transaction rolls back, including the idempotency key insert. Server B, which was waiting on the constraint violation, retries and succeeds. This guarantees that an idempotency key in PROCESSING state always has a corresponding transfer record."))

    lines.append(("interviewer", "What about the case where the transaction commits but the HTTP response is lost — the server crashes after committing but before sending the response?"))

    lines.append(("candidate", "This is the distributed systems classic: the client doesn't know if the request succeeded or failed. The client will retry with the same idempotency key. When the retry arrives, the idempotency store has the key in PROCESSING or COMPLETED state. If PROCESSING, the saga is still running — we return twenty-two-two Accepted. If COMPLETED, we return the stored response. The client gets a definitive answer without any duplicate processing. This is the whole point of idempotency — it makes retries safe."))

    lines.append(("candidate", "But there's a gap. Between the database commit and the response being sent, the server might crash. The idempotency record is in PROCESSING state because the saga hasn't finished yet. The client retries, gets twenty-two-two Accepted, and keeps polling. But the saga might have completed successfully — the transfer was submitted to the bank and settled. The idempotency record should be COMPLETED, but it's stuck in PROCESSING because the server that was supposed to update it crashed. The fix: a background reaper job that scans for idempotency records that have been in PROCESSING for more than five minutes. For each stale record, the reaper checks the corresponding transfer status. If the transfer is COMPLETED, the reaper updates the idempotency record to COMPLETED and stores the response. If the transfer is FAILED, it updates accordingly. If the transfer is still PROCESSING, the reaper leaves it alone — the saga is genuinely still running."))

    # SECTION 4: Deep Dive — Different Operation Types
    lines.append(("interviewer", "You said all mutating operations are idempotent. Does the implementation differ for different operation types?"))

    lines.append(("candidate", "Yes, and this is where it gets nuanced. There are three categories of idempotency in a financial API. Category one: create operations — POST slash payments. These are naturally idempotent with the key pattern I described. The same key always creates at most one resource. Category two: update operations — PATCH slash payments slash ID slash status with body status equals REFUNDED. These need idempotency too, but the semantics are different. Applying a refund twice should not create two refund transactions. The idempotency key here identifies the refund operation, not the payment. The client sends a refund request with a new idempotency key, and the same key always produces at most one refund, even if the payment already has a refund from a different key."))

    lines.append(("candidate", "Category three: operations with side effects that are hard to reverse — like submitting a payment to a bank. Once we've sent the payment instruction to SWIFT, we can't unsend it. The idempotency here must prevent the bank submission from happening twice. When the saga reaches the bank submission step, it checks a deduplication flag on the transfer record — a boolean column called bank_submitted. Before sending to the bank, it does SELECT bank_submitted FROM transfers WHERE id equals X FOR UPDATE. If false, it submits to the bank and sets the flag to true — all in one transaction. If true, it skips the submission and continues the saga. This is idempotency at the saga step level, not just the API level."))

    lines.append(("candidate", "The key phrase to remember: idempotency at every layer. API-level idempotency prevents duplicate requests. Saga-step idempotency prevents duplicate side effects. Both are necessary because a single API request can trigger a multi-step saga, and any step can fail and be retried independently."))

    # SECTION 5: Edge Cases
    lines.append(("interviewer", "What happens if a client sends the same idempotency key but a different request body?"))

    lines.append(("candidate", "This is an important edge case and it's a sign of a client bug. The first request creates the resource. The second request with the same key but a different body — say, a different amount or a different beneficiary — should not modify the existing resource. We store a hash of the original request body in the idempotency record. When a request arrives with a key that already exists, we compare the hash of the new request body with the stored hash. If they differ, we return a four twenty-two Unprocessable Entity with an error message: idempotency key already used with different request parameters. This prevents silent data corruption from client bugs."))

    lines.append(("interviewer", "What about the storage growth? Millions of idempotency records per day."))

    lines.append(("candidate", "With a twenty-four-hour TTL, the active set is about one to two days of records. At one hundred thousand transactions per day, each idempotency record is about five hundred bytes — key, status, request hash, response hash, timestamps. That's about fifty megabytes per day, one hundred megabytes for the active set. Negligible. But we also need to handle the expiry. We have a background job that deletes records older than twenty-four hours. The deletion runs in batches of ten thousand to avoid locking the table. We also partition the idempotency_keys table by date, so old partitions are dropped entirely rather than deleted row by row. This is much faster and doesn't fragment the table."))

    lines.append(("interviewer", "One more: how do you handle the case where the client doesn't send an idempotency key?"))

    lines.append(("candidate", "For a financial API, the idempotency key is required on all mutating endpoints. If the client omits it, we return a four hundred Bad Request with a clear message: Idempotency-Key header is required for this endpoint. This is a deliberate design choice — we'd rather reject a request than risk a duplicate. Some APIs make the key optional and generate one server-side if missing, but that defeats the purpose. The client needs to own the key because the client knows when they're retrying versus starting a new operation. A server-generated key would be different on every request, making retries impossible to detect."))

    # SECTION 6: Payment-Specific Idempotency
    lines.append(("interviewer", "Let's tie this back to the payment domain. How does idempotency interact with the Saga pattern?"))

    lines.append(("candidate", "This is where idempotency becomes critical. A payment saga has multiple steps — validate, lock FX, check compliance, debit ledger, submit to bank, credit ledger. If the saga crashes at step four — after debiting the ledger but before submitting to the bank — the replayer needs to resume from step four, not from step one. If it resumes from step one, it might lock a different FX rate or create a second compliance check. Each saga step must be individually idempotent. The saga maintains a state machine: PENDING, FX_LOCKED, COMPLIANCE_PASSED, LEDGER_DEBITED, BANK_SUBMITTED, COMPLETED. When the replayer starts, it reads the current state and resumes from the next unfinished step. Each step checks whether it's already been completed by checking the state machine. This is the saga idempotency guarantee: replaying a saga from any point produces the same result as running it once."))

    lines.append(("candidate", "Let me repeat the killer phrases that need to become automatic for this topic. One: client-generated idempotency key — the client knows their intent, the server doesn't. Two: Redis for speed, PostgreSQL for truth — never trust Redis alone for financial deduplication. Three: same database transaction for idempotency check and business state change — atomicity prevents race conditions. Four: unique constraint on idempotency key plus merchant_id — the database is the last line of defense against duplicates. Five: background reaper for stale PROCESSING records — don't let crashed servers leave keys in limbo. Six: idempotency at every layer — API level and saga step level. Seven: reject requests without an idempotency key — it's required, not optional, for financial operations. And eight: different request body with same key returns four twenty-two — catch client bugs early."))

    # SECTION 7: Estimation
    lines.append(("interviewer", "Before we wrap up, let me ask about the scale. How do you size the idempotency infrastructure?"))

    lines.append(("candidate", "At five thousand TPS peak, we create about five thousand idempotency records per second during peak hours. Average is about two thousand per second. Over twenty-four hours, that's about one hundred and seventy million records. With a twenty-four-hour TTL, the active set is about one hundred and seventy million records. Each record is about five hundred bytes — idempotency key — a UUID, thirty-six bytes — merchant ID, status, request hash — SHA-256, thirty-two bytes — response hash, created timestamp, updated timestamp. With PostgreSQL overhead — about two hundred percent for indexes and MVCC — the total storage is about one hundred and seventy million times one thousand bytes equals one hundred and seventy gigabytes for the active set. We'd partition the table by date — one partition per day — so the active set is two partitions. Dropping old partitions is instant — no row-by-row deletion."))

    lines.append(("candidate", "Redis cache: we cache the hot idempotency keys — the ones likely to be retried. Retries typically happen within seconds, so the Redis TTL is five minutes, not twenty-four hours. At five thousand TPS, the cache receives five thousand new keys per minute. Each key is about two hundred bytes in Redis — key name, status, response hash. Five thousand per minute times five minutes TTL means about twenty-five thousand keys in the cache at any time, which is about five megabytes. Trivial. The cache hit rate is high — probably eighty percent — because most retries happen within seconds of the original request."))

    lines.append(("candidate", "The background reaper: it scans for keys in PROCESSING state older than five minutes. At normal operation, the number of stale keys is very low — maybe ten to fifty per hour, from server crashes or network timeouts. The reaper runs every minute, queries the database for stale records, and resolves them by checking the transfer status. Each resolution takes about ten milliseconds — a database read and an update. Fifty resolutions per hour is negligible load."))

    # SECTION 8: E2E Walkthrough
    lines.append(("interviewer", "Walk me through the complete flow for a payment that gets retried three times."))

    lines.append(("candidate", "First attempt: the merchant's client sends POST slash payments with Idempotency-Key colon idem-abc-123 and a request body for a thousand USD to EUR transfer. The API gateway checks Redis — cache miss. Checks the database — no record. Begins a transaction: INSERT into idempotency_keys with key idem-abc-123, status PROCESSING. INSERT into transfers with status PENDING. COMMIT. The transaction succeeds. The payment orchestrator starts the saga. FX rate locked. Compliance passed. Ledger debited. The orchestrator submits to the bank via the Bank Connector. The bank takes about two seconds to respond. During those two seconds, the merchant's HTTP client times out — they had a one-second timeout configured. The client never received our response."))

    lines.append(("candidate", "Second attempt: the client retries the same request — same Idempotency-Key colon idem-abc-123, same request body. The API gateway checks Redis — still a cache miss because the first request hasn't completed yet. Checks the database — finds idem-abc-123 with status PROCESSING. Returns HTTP twenty-two-two Accepted with a Location header for polling. The client polls the status endpoint every five seconds."))

    lines.append(("candidate", "Meanwhile, the bank responds to the first request — payment accepted. The orchestrator updates the transfer status to COMPLETED. It updates the idempotency record to COMPLETED and stores the response — the transfer ID, the bank reference, and the settlement ETA. It also writes the response to Redis for future cache hits. The next time the client polls, the status endpoint returns COMPLETED with the transfer details. If the client had sent a third retry instead of polling, the API gateway would find the key in Redis — cache hit, COMPLETED — and return the stored response immediately. Same status code, same body. No duplicate processing."))

    lines.append(("candidate", "The critical point: across all three attempts, only one transfer was created, one FX rate was locked, one ledger entry was written, and one bank submission was made. The idempotency guarantee held despite the retry. And the client got a definitive answer. This is the power of idempotency in financial systems — it makes the distributed systems problem of unreliable networks manageable by making retries safe. Every retry is a no-op if the original succeeded, and a fresh start if it didn't. The client never needs to wonder did it work? — the idempotency key always gives them the answer."))

    lines.append(("candidate", "Let me repeat the key phrase one more time for muscle memory: client-generated idempotency key, same database transaction for key and business state, unique constraint as the last line of defense, background reaper for stale records. This pattern applies to every financial API endpoint — payments, refunds, quotes, and account changes. Memorize it, because the interviewer will probe every detail."))

    return lines
