"""Mock Interview: Distributed Job Scheduler — Two-voice dialogue."""


def build():
    lines = []

    # SECTION 1: Requirements (~5 min)
    lines.append(("interviewer", "Hi, welcome. Today I'd like you to design a distributed job scheduler — something like Airflow, Chronos, or a cloud-native equivalent. Users submit jobs that need to run at specific times or on recurring schedules, and the system dispatches them to workers for execution. Start by clarifying the requirements."))

    lines.append(("candidate", "Thanks. Job scheduling is one of those problems that sounds straightforward until you think about distributed coordination, failure recovery, and scale. Let me start with the most fundamental question: what types of jobs are we supporting? Are we talking cron-style recurring schedules, one-time delayed execution, or both? And are these lightweight tasks that finish in seconds, or heavy batch jobs that run for hours?"))

    lines.append(("interviewer", "We need to support all three — cron-style recurring, one-time delayed, and recurring interval-based jobs. Job durations range from a few seconds to several hours. We also need to support job dependencies — job B should only run after job A completes. Think of it as DAG-based workflow orchestration like Airflow."))

    lines.append(("candidate", "DAG dependencies add a lot of complexity — that's essentially workflow orchestration on top of scheduling. Let me ask about scale. How many jobs per second do we need to schedule and execute? How many total scheduled jobs are in the system at any given time? And what's the peak scheduling rate — for example, at the top of the minute when hundreds of cron jobs all fire simultaneously?"))

    lines.append(("interviewer", "We need to handle 10K job executions per second at peak, with millions of scheduled jobs in the system. The per-minute cron spike is significant — at the top of every minute, we might see thousands of jobs becoming due simultaneously. We need to dispatch them within seconds of their scheduled time."))

    lines.append(("candidate", "10K executions per second and millions of scheduled jobs — that's substantial. A few more questions. First, what's the reliability guarantee? If a job is scheduled, must it execute exactly once, or is at-least-once acceptable? Second, what happens on failure — do we retry, and if so, with what policy? Third, do we need to handle timezone-aware cron expressions? Fourth, what about job priorities — can some jobs jump the queue?"))

    lines.append(("interviewer", "At-least-once execution is the guarantee — exactly-once is impractical in a distributed system without two-phase commit on every job. We need retry with exponential backoff, up to a configurable max. Timezone handling is required — a cron job set to run at 9 AM EST must not drift. Priority queues are needed — some jobs are business-critical and must not be delayed behind low-priority cleanup tasks."))

    lines.append(("candidate", "Let me also ask about the worker side. Do we manage the worker pool, or do workers register themselves? And do we need auto-scaling — spinning up more workers when the queue is long and spinning them down when it's short? Also, what monitoring do we need — job latency, success rate, queue depth?"))

    lines.append(("interviewer", "We manage the worker pool, and we need auto-scaling based on queue depth. Monitoring is essential — we need per-job-type metrics for latency, success rate, and retry count, plus aggregate metrics for queue depth and worker utilization. We also need a dead letter queue for jobs that have exhausted their retries."))

    lines.append(("candidate", "Let me summarize. We're designing a distributed job scheduler supporting cron, one-time, and recurring jobs, with DAG-based dependencies, 10K executions per second, millions of scheduled jobs, at-least-once delivery, retry with exponential backoff, timezone-aware scheduling, priority queues, managed worker pool with auto-scaling, and comprehensive monitoring including a dead letter queue. Let me move to estimation."))

    # SECTION 2: Estimation (~5 min)
    lines.append(("interviewer", "Go ahead with the numbers."))

    lines.append(("candidate", "10K job executions per second at peak. Average is probably 3 to 5K, so let's say 4K average. That's about 350 million executions per day. Each job execution record — job ID, execution ID, status, start time, end time, retry count, worker ID, output summary, and error details if failed — is about 500 bytes. So 350 million times 500 bytes is about 175 GB of execution data per day. For 90 days of hot storage, that's about 16 TB. For 7-year retention of aggregated data — daily summaries per job type rather than individual executions — we're looking at maybe 500 GB. Manageable with sharding."))

    lines.append(("candidate", "For the scheduled job definitions — the millions of jobs in the system — each job definition is larger: job ID, owner, schedule expression, timezone, priority, dependency graph, retry policy, timeout, and the actual job payload or a reference to it. That's about 1 to 2 KB per job. At 5 million jobs, that's 5 to 10 GB. This fits in a single database with replicas, but we'd still shard for write throughput during the cron spikes."))

    lines.append(("interviewer", "What about the queue throughput? At 10K jobs per second, how much data is flowing through the queue?"))

    lines.append(("candidate", "Each queued job message is smaller than the full definition — just the job ID, priority, scheduled time, and maybe the payload reference. About 200 bytes per message. At 10K per second, that's 2 MB per second of queue traffic. Over a day, that's about 170 GB flowing through. But the queue itself doesn't store all of that — jobs are consumed and removed. The steady-state queue depth depends on the dispatch rate. If workers can consume at 10K per second and jobs arrive at 10K per second, the queue is nearly empty. But during a cron spike — say 5K jobs becoming due simultaneously — the queue could momentarily hold 5K messages, which is about 1 MB. Negligible. The real concern isn't data volume but coordination overhead — making sure we don't dispatch the same job twice."))

    lines.append(("interviewer", "What about the scheduling tier — the system that tracks when jobs are due? How much data does that hold?"))

    lines.append(("candidate", "The scheduling tier needs to hold a time-ordered structure of upcoming job executions. For millions of jobs, many of which are recurring, we might have tens of millions of upcoming execution slots. Each slot is a tuple of job ID, due timestamp, and priority — about 50 bytes. Tens of millions at 50 bytes is roughly 500 MB to 1 GB. This needs to be in memory for fast lookups — scanning the next-due jobs should be O(1), not a database query. A timing wheel or a priority queue per time bucket would work. I'd estimate about 2 GB of memory for the scheduling tier with replication, which is well within a single machine's capacity, but I'd replicate it for fault tolerance."))

    # SECTION 3: High-Level Architecture (~5 min)
    lines.append(("interviewer", "Good. Let's move to the high-level architecture."))

    lines.append(("candidate", "The architecture has four main components. First, the Job API — this is what users interact with to submit, update, and delete job definitions. It validates the schedule expression, resolves dependencies, and writes the job definition to the Job Store. Second, the Scheduler — this is the core component that tracks when jobs are due. It maintains an in-memory time-ordered structure and, when a job's due time arrives, moves it to the dispatch queue. Third, the Dispatcher — this pulls jobs from the dispatch queue, selects an available worker, and sends the job for execution. Fourth, the Workers — these are the execution engines that run the actual job logic and report results back."))

    lines.append(("candidate", "Behind these components are three storage systems. The Job Store is a durable database — PostgreSQL or a distributed KV store — holding all job definitions, dependency graphs, and execution history. The Dispatch Queue is a message queue like Kafka or a priority-aware queue like RabbitMQ with priority support, holding jobs that are ready to execute. And the Schedule Index is an in-memory data structure in the Scheduler that maps due timestamps to job IDs, essentially a priority queue sorted by time."))

    lines.append(("interviewer", "Why separate the Scheduler and the Dispatcher? Couldn't the Scheduler dispatch directly to workers?"))

    lines.append(("candidate", "They have different responsibilities and scaling characteristics. The Scheduler is about time management — it needs to be highly available and consistent because missing a schedule or double-scheduling is a correctness bug. There should be very few Scheduler instances — ideally one active leader with standby replicas. The Dispatcher is about load distribution — it needs to scale with the number of workers and the dispatch rate. At 10K jobs per second, we might need multiple Dispatcher instances. Separating them means the Scheduler can focus on correctness while the Dispatcher focuses on throughput. The queue between them provides a buffer — if all workers are busy, jobs pile up in the queue rather than overwhelming the Scheduler."))

    lines.append(("interviewer", "How does leader election work for the Scheduler?"))

    lines.append(("candidate", "We use a distributed consensus protocol — typically etcd or ZooKeeper with an ephemeral leader node. The active Scheduler holds a lease on the leader key. As long as it's alive, it renews the lease periodically — say every 5 seconds. If it fails to renew, the lease expires, and standby Schedulers compete to become the new leader. The transition should take under 10 seconds. During the transition, no new jobs are scheduled, but already-dispatched jobs continue executing on workers because the workers are independent. This is a key design choice — the Scheduler being down doesn't stop running jobs, only delays the scheduling of new ones."))

    lines.append(("interviewer", "What about partition-based scheduling as an alternative to a single leader?"))

    lines.append(("candidate", "Good question — that's the other main approach. Instead of one Scheduler scheduling all jobs, we hash job IDs onto N partitions, each owned by a Scheduler instance. Each Scheduler only handles jobs in its partition, so there's no single leader bottleneck. The advantage is horizontal scaling — if the scheduling load increases, add more partitions. The disadvantage is that DAG dependencies can span partitions — if job A is on partition 1 and job B depends on A and is on partition 2, we need cross-partition coordination. This gets complex quickly. I'd use the leader-standby model for up to 10K jobs per second, which a single Scheduler can handle, and switch to partition-based scheduling only at higher scale. The partition approach is how systems like Chronos work, but the coordination overhead for DAGs makes it a second choice rather than a first."))

    # SECTION 4: Deep Dive — Distributed Scheduling, Idempotency, and Failure Handling (~10 min)
    lines.append(("interviewer", "Let's deep dive into the hardest parts. How do you prevent duplicate execution — the same job being dispatched twice?"))

    lines.append(("candidate", "Duplicate execution is the classic distributed systems problem for job schedulers. It can happen in several ways. First, the Scheduler dispatches a job and crashes before recording that it was dispatched. On restart, it dispatches it again. Second, the Dispatcher sends a job to a worker, the worker starts executing, but the Dispatcher times out waiting for the acknowledgment and re-dispatches to another worker. Third, two Scheduler instances both think they're the leader during a leader election race and both schedule the same job."))

    lines.append(("candidate", "The defense is layered. For the Scheduler crash case, every job execution gets a unique execution ID generated before dispatch. The execution record is written to the Job Store with status SCHEDULED before the job goes into the dispatch queue. On Scheduler restart, it reads all SCHEDULED executions and checks their actual status — if they were never acknowledged by a worker, they're re-queued, but the execution ID stays the same. Workers use the execution ID for idempotency — before executing, they check the Job Store to see if this execution ID is already RUNNING or COMPLETED. If so, they skip it. This is the at-least-once guarantee — a job might be dispatched multiple times, but the worker's idempotency check prevents double execution in most cases."))

    lines.append(("interviewer", "You said 'in most cases.' When does the idempotency check fail?"))

    lines.append(("candidate", "The race condition is: two workers both receive the same execution ID, both check the Job Store, both see status SCHEDULED because neither has updated it yet, and both start executing. The check-then-act is not atomic. To prevent this, the worker must atomically transition the execution status from SCHEDULED to RUNNING using a conditional update — essentially a compare-and-swap. If the update succeeds, this worker owns the execution. If it fails because another worker already changed it to RUNNING, the second worker backs off. This is how databases implement pessimistic locking for job claims. With a distributed database, the CAS operation is serialized through the database's consensus protocol, guaranteeing only one worker wins."))

    lines.append(("candidate", "But there's still an edge case. What if Worker A claims the job, starts executing, and then crashes mid-execution? The status is RUNNING, but no one is actually running the job. We need a heartbeat mechanism — workers send periodic heartbeats to the Job Store confirming they're still alive and working on their claimed executions. If the heartbeat stops for a configurable timeout — say 30 seconds — the Scheduler marks the execution as ORPHANED and re-queues it. The new worker does the same CAS claim. But what if Worker A was just slow and is still running? Now we have two workers executing the same job. This is where at-least-once becomes the pragmatic ceiling — we can make duplicate execution extremely unlikely but not impossible without exactly-once semantics, which would require distributed transactions on every execution. The business must accept that idempotent job logic is a requirement, not a nice-to-have."))

    lines.append(("interviewer", "So the job implementations themselves must be idempotent. How do you communicate this to users?"))

    lines.append(("candidate", "It's a platform contract. When you submit a job to the scheduler, you agree that the job's execution logic must be safe to run more than once for the same execution context. For idempotency, the job should use a deterministic execution ID to deduplicate side effects — for example, if the job writes to a database, it should use the execution ID as a dedup key. If it sends an email, it should check whether an email for this execution ID was already sent. We provide a helper library that makes common idempotency patterns easy — a dedup table in the Job Store, an idempotent HTTP client wrapper, and a transaction helper that ties job state to side-effect state. But we can't enforce this — it's the user's responsibility, just like exactly-once processing in Kafka is the consumer's responsibility."))

    lines.append(("interviewer", "Now let's talk about retry and the dead letter queue. How exactly does the retry flow work?"))

    lines.append(("candidate", "The job state machine goes PENDING to SCHEDULED to RUNNING, and then either COMPLETED or FAILED. On failure, if the retry count is below the configured max, the state moves to RETRYING and a new execution is scheduled with an exponential backoff delay — first retry after 10 seconds, second after 20, then 40, 80, up to a cap of maybe 1 hour. The backoff is calculated as min(base_delay times 2 to the power of retry_count, max_delay) plus a small random jitter to prevent thundering herds when many jobs fail simultaneously and all retry at the same time. The jitter is typically plus or minus 10 percent of the calculated delay."))

    lines.append(("candidate", "When a job exhausts all retries — say the max is 5 — it moves to DEAD_LETTER state. The dead letter queue is a special queue that operations teams monitor. Dead-lettered jobs can be inspected for failure reason — we capture the error message and stack trace from the worker, the execution history showing all retry attempts and their outcomes, and the job's original definition. An operator can then either fix the underlying issue and manually requeue the job with a reset retry count, or mark it as permanently failed with a resolution note. We also auto-alert when the dead letter rate exceeds a threshold — if more than 1 percent of executions end up in the DLQ, something is systematically wrong and needs investigation."))

    lines.append(("interviewer", "What about job dependencies and DAGs? How does the scheduler resolve a dependency graph and execute jobs in the right order?"))

    lines.append(("candidate", "DAG orchestration is a separate layer on top of the core scheduler. Each workflow — a DAG — has a workflow ID and a list of jobs with their dependency edges. When a workflow is triggered — either by a schedule or manually — the orchestrator creates execution records for all jobs but only marks root jobs — those with no dependencies — as PENDING and ready to schedule. Dependent jobs are marked as BLOCKED. When a root job completes, the orchestrator checks all its downstream dependents. If all of a dependent's upstream jobs have completed successfully, the dependent is moved from BLOCKED to PENDING and scheduled. If any upstream job fails, the downstream job is marked as UPSTREAM_FAILED and the workflow is marked as FAILED."))

    lines.append(("candidate", "The tricky part is that the orchestrator must handle partial failures. If job A has two children, B and C, and B succeeds but C fails, the orchestrator shouldn't kill B or cancel the entire workflow automatically — maybe only C needs to be retried. We support configurable failure policies per workflow — fail-fast, which cancels all remaining jobs when any job fails, or continue-on-failure, which lets independent branches proceed. The orchestrator also needs to handle the case where a job completes but the completion event is lost — we need a reconciliation loop that periodically scans for BLOCKED jobs whose upstream dependencies are all COMPLETED and moves them to PENDING. This is similar to Airflow's scheduler loop, which runs every few seconds."))

    lines.append(("interviewer", "Now let's talk about timezone handling for cron jobs. This seems simple but has subtle bugs."))

    lines.append(("candidate", "Timezone handling is deceptively hard. The naive approach is to store the cron expression in UTC and convert the user's desired time to UTC. But this breaks twice a year during daylight saving transitions. Consider a cron job set to run at 9 AM Eastern. During EST, that's 14:00 UTC. During EDT, it's 13:00 UTC. If we convert once at job creation time and store the UTC cron expression, the job runs at the wrong time after a DST transition. The correct approach is to store the original cron expression and the timezone ID — like America/New_York — and always compute the next execution time in the original timezone, then convert to UTC for internal scheduling."))

    lines.append(("candidate", "There are even nastier edge cases. When clocks spring forward — say from 2:00 AM to 3:00 AM — a cron job scheduled for 2:30 AM in that timezone simply doesn't exist that day. Do we skip it or run it at 3:00 AM? Different cron implementations handle this differently. We'd default to running it at 3:00 AM — the next available time after the scheduled time — but make this configurable. When clocks fall back — from 2:00 AM back to 1:00 AM — a job scheduled for 1:30 AM could run twice. We detect this by checking whether the current UTC time has already produced an execution for this cron schedule within the same timezone offset period. We also need to update the IANA timezone database regularly — tzdata releases come out several times a year when countries change their DST rules or timezone boundaries. If we're using stale tzdata, jobs in affected timezones will run at the wrong time."))

    # SECTION 5: Failure Modes (~4 min)
    lines.append(("interviewer", "What are the most critical failure scenarios?"))

    lines.append(("candidate", "The scariest failure is the Scheduler crashing and losing its in-memory schedule index. On restart, it needs to rebuild the index from the Job Store — scanning all jobs with upcoming executions. With millions of jobs, this rebuild could take minutes, during which no new jobs are scheduled. To mitigate this, the Scheduler periodically snapshots its schedule index to durable storage — say every 10 seconds. On restart, it loads the latest snapshot and then replays any changes from the Job Store's write-ahead log since the snapshot. This reduces recovery time from minutes to seconds."))

    lines.append(("candidate", "The second critical failure is a worker crashing mid-execution. The heartbeat mechanism catches this — when heartbeats stop, the job is re-queued. But we need to be careful about the timeout. If we set it too short — say 10 seconds — we risk re-dispatching a job while the original worker is still running but just slow. If we set it too long — say 5 minutes — a genuinely crashed worker delays the job significantly. I'd make the heartbeat timeout configurable per job, with a default of 30 seconds, and add a separate job-level timeout that kills the job if it runs too long regardless of heartbeats. The timeout is important because some jobs have hard deadlines — a daily report must finish before business hours."))

    lines.append(("candidate", "The third failure is stuck jobs — a job that's RUNNING but never completes and never fails. Maybe it's in an infinite loop or waiting on a resource that's permanently unavailable. The job timeout handles this, but the timeout itself needs enforcement. If the worker process is unresponsive — maybe it's stuck in a busy loop and can't process the timeout signal — we need an external watchdog. I'd use a per-worker process supervisor that can forcefully kill the worker process and report the job as TIMED_OUT. This is similar to how Airflow uses a process kill as a last resort."))

    lines.append(("interviewer", "What about the dispatch queue itself? What if it goes down?"))

    lines.append(("candidate", "If the dispatch queue — Kafka or the message broker — is unavailable, jobs that are due can't be dispatched. They'd accumulate in the Scheduler's memory. We need to handle this gracefully. First, the Scheduler should have a backpressure mechanism — if the dispatch queue is unreachable or the queue depth exceeds a threshold, the Scheduler stops pulling new due jobs and instead buffers them. The buffer has a size limit, and if exceeded, we write overflow to the Job Store as SCHEDULED_BUT_QUEUED status. When the queue recovers, we drain the buffer first, then scan the Job Store for SCHEDULED_BUT_QUEUED jobs. Second, we need monitoring — the queue depth and the buffer size should be on the ops dashboard with alerts. Third, the queue itself must be highly available — Kafka with replication factor 3 and min.insync.replicas=2 survives a broker failure. If the entire Kafka cluster is down, that's a severity-1 incident, and the Scheduler's buffer buys us time to recover."))

    lines.append(("candidate", "There's also the failure mode of duplicate dispatch during a Scheduler leader transition. If the old leader dispatched a job right before crashing, and the new leader doesn't know about it, it might dispatch the same job again. The execution record in the Job Store prevents this — the new leader scans for SCHEDULED executions before dispatching anything. But the scan and the dispatch aren't atomic — the new leader could scan, see nothing, and then the old leader's late dispatch arrives. The worker-side CAS claim is the final safety net. This layered defense — Scheduler scanning, execution record, worker CAS — is necessary because no single mechanism is bulletproof in a distributed system."))

    # SECTION 6: Scale & Debrief (~3 min)
    lines.append(("interviewer", "How does the design change at 10x scale — 100K jobs per second?"))

    lines.append(("candidate", "At 100K jobs per second, the single-leader Scheduler becomes a bottleneck. Scheduling millions of cron ticks per minute through one node isn't feasible. I'd switch to the partition-based model I mentioned earlier — hash job IDs onto, say, 32 Scheduler partitions, each with its own leader. Each partition handles about 3K jobs per second, which is manageable. The dispatch queue partitions would mirror the Scheduler partitions — Kafka topics with 32 partitions, one consumer per Scheduler partition. The Dispatcher scales horizontally — more instances pulling from more queue partitions."))

    lines.append(("candidate", "The Job Store needs more shards at 10x. Instead of a single PostgreSQL cluster, we'd use a sharded key-value store or a distributed SQL database like CockroachDB or YugabyteDB that handles sharding transparently. The DAG orchestrator is the hardest to scale — a workflow with dependencies spanning multiple Scheduler partitions requires cross-partition coordination. I'd use an event-based approach: when job A completes on partition 3, it publishes a completion event to a dedicated dependencies topic. The orchestrator for partition 7 — which owns job B — consumes this event and checks if B's dependencies are all met. This avoids synchronous cross-partition RPC, but it adds latency — the dependency check is bounded by the event propagation delay, which is typically under 100 milliseconds with Kafka."))

    lines.append(("candidate", "Worker auto-scaling becomes more critical at 10x. With 100K jobs per second, the worker pool might need to scale from 500 to 5000 instances during peak hours and back down during off-peak. We'd implement this with a Kubernetes-based autoscaler that monitors the dispatch queue depth and scales worker pods accordingly. The target is to keep the queue depth below a threshold — say, 1000 pending jobs — by adding or removing workers. There's a lag between scaling a decision and new workers being ready — pod startup takes 10 to 30 seconds — so we need predictive scaling based on historical patterns. The cron spike at the top of every minute is predictable, so we can pre-scale 30 seconds before the spike."))

    lines.append(("candidate", "At 0.1x scale — 1K jobs per second — everything simplifies dramatically. A single PostgreSQL instance, a single Scheduler instance, a single Dispatcher, and a small worker pool of maybe 20 instances. No sharding, no partitioning, no auto-scaling. The DAG orchestrator could run as part of the Scheduler rather than as a separate service. The dispatch queue could be a simple Redis list instead of Kafka. But the correctness mechanisms — the execution record, the worker CAS claim, the heartbeat, and the retry with backoff — stay exactly the same. You can't scale down correctness."))

    # SECTION 7: End-to-End Walkthrough (~4 min)
    lines.append(("interviewer", "Walk me through a single scheduled job end-to-end — from submission to completion."))

    lines.append(("candidate", "Let's trace a cron job called daily_report that runs every day at 9 AM Eastern. It depends on a data_import job that must finish first. Here's the full lifecycle."))

    lines.append(("candidate", "Step 1: Submission. The user calls the Job API with the job definition — job ID daily_report, cron expression '0 9 * * *', timezone America/New_York, priority HIGH, dependency on data_import, retry policy of max 3 with base delay 60 seconds, timeout 30 minutes, and the job payload — a reference to a container image that generates the report. The API validates the cron expression, checks that the dependency job data_import exists, and writes the job definition to the Job Store with status ACTIVE. It also computes the next execution time — today at 9 AM Eastern, which in UTC is, say, 14:00 UTC during EST. The Scheduler's schedule index is updated with this due time."))

    lines.append(("candidate", "Step 2: Scheduling. The Scheduler runs a tight loop — every 100 milliseconds, it checks the schedule index for jobs that are due. At 14:00:00 UTC, daily_report's due time arrives. The Scheduler checks the dependency: is data_import's latest execution COMPLETED? It queries the Job Store. Let's say data_import completed at 8:45 AM Eastern — good, the dependency is met. The Scheduler creates a new execution record in the Job Store with execution ID exec_20240115_daily_report_001, status SCHEDULED, scheduled time 14:00:00 UTC. It then pushes the job to the dispatch queue with the execution ID, job ID, priority HIGH, and payload reference. The dispatch queue is partitioned, and this job lands on partition 5."))

    lines.append(("candidate", "Step 3: Dispatch. The Dispatcher instance consuming partition 5 picks up the job. It queries the worker registry for available workers capable of running this job type. Let's say Worker-12 is available and has the right capabilities. The Dispatcher sends the job to Worker-12 via gRPC with the execution ID, the container image reference, and the timeout of 30 minutes. It also updates the dispatch timestamp in the execution record."))

    lines.append(("candidate", "Step 4: Claim. Worker-12 receives the job. Before executing, it performs the CAS claim — it sends a conditional update to the Job Store: SET status = RUNNING, worker_id = Worker-12, claim_time = now WHERE execution_id = exec_20240115_daily_report_001 AND status = SCHEDULED. If the update returns 1 row affected, the claim succeeded. If 0, another worker already claimed it — Worker-12 discards the job and reports the duplicate to the Dispatcher. This is rare but the CAS ensures safety."))

    lines.append(("candidate", "Step 5: Execution. Worker-12 starts a container with the report-generation image. The container runs the job logic — it queries the data warehouse, generates the report, uploads it to object storage, and sends a notification email. Meanwhile, Worker-12 sends heartbeats to the Job Store every 10 seconds confirming it's still working on this execution. The Scheduler monitors these heartbeats — if it doesn't see a heartbeat for 30 seconds, it assumes the worker is dead and re-queues the job."))

    lines.append(("candidate", "Step 6: Completion. The container finishes after 12 minutes. Worker-12 updates the execution record: status = COMPLETED, end_time = now, output_summary = 'Report generated: 2.3 MB, uploaded to s3://reports/2024-01-15.pdf'. It also notifies the Dispatcher that it's available for new jobs. The Dispatcher returns Worker-12 to the available pool. The Scheduler detects the completion of daily_report and checks if any downstream jobs are now unblocked — none in this case. The Scheduler also computes the next execution time — tomorrow at 9 AM Eastern — and updates the schedule index."))

    lines.append(("candidate", "Now let me trace the failure path. Suppose the data_import job failed at step 2. When the Scheduler checks the dependency at 14:00 UTC, it finds data_import's latest execution is FAILED with all retries exhausted. The Scheduler marks daily_report's execution as UPSTREAM_FAILED, records the blocking dependency, and does not dispatch it. An alert is sent to the operations team. The daily_report will not run today unless an operator manually retries data_import and then triggers daily_report. This is the fail-fast policy — a failed dependency means the dependent job doesn't run."))

    lines.append(("candidate", "And the retry path: suppose daily_report itself fails during execution — maybe the data warehouse is temporarily unreachable. Worker-12 updates the execution record to FAILED with the error message 'Connection refused: data-warehouse.internal:5432'. The Scheduler detects the failure, checks the retry policy — max 3, base delay 60 seconds — and creates a new execution record with retry_count = 1, scheduled for 60 seconds from now. The second attempt might succeed, or it might fail again, leading to retry_count = 2 with a 120-second delay, then retry_count = 3 with a 240-second delay. If the third retry also fails, the execution moves to DEAD_LETTER, and the ops team is alerted."))

    # SECTION 8: Thinking Process & Beats (~3 min)
    lines.append(("interviewer", "Good walkthrough. Let me close with an interviewer's perspective on this problem. I'll share the mental framework and key beats I look for."))

    lines.append(("interviewer", "The framework I use for distributed job scheduler design has four layers: requirements and scope, core scheduling mechanism, distributed coordination and idempotency, and failure handling and observability. At the requirements layer, the key beats are: does the candidate ask about job types — cron, one-time, recurring? Do they surface the DAG dependency requirement? Do they ask about reliability guarantees — at-least-once versus exactly-once? Do they ask about timezone handling, or do they naively assume UTC everywhere? Do they ask about priority and queue ordering? A candidate who jumps straight to a priority queue without clarifying whether priorities are needed is designing ahead of the requirements."))

    lines.append(("interviewer", "At the core scheduling mechanism layer, the key beats are: does the candidate clearly separate the scheduling concern — when to run — from the dispatch concern — where to run? Do they describe a concrete data structure for the schedule index — timing wheel, delayed queue, time-bucketed priority queue? Do they handle the cron spike problem — thousands of jobs becoming due simultaneously at the top of a minute? The trap here is designing a single component that does everything — scheduling, dispatching, and executing in one process. That doesn't scale and doesn't tolerate partial failures. Another trap is not thinking about the schedule index recovery after a crash — if the in-memory index is lost, what happens? A strong candidate proposes periodic snapshots and write-ahead logging."))

    lines.append(("interviewer", "At the distributed coordination and idempotency layer, this is where the interview is won or lost. The key beats are: does the candidate identify the duplicate dispatch problem and propose a concrete solution? The compare-and-swap claim mechanism is the gold standard — a candidate who proposes it shows real distributed systems depth. Do they understand why at-least-once is the practical ceiling? Do they explain that exactly-once would require distributed transactions on every job? Do they surface the worker crash mid-execution problem and propose heartbeats as the detection mechanism? The biggest traps here are not thinking about idempotency at all — just assuming jobs won't be dispatched twice — and proposing a distributed lock without thinking about what happens when the lock holder crashes. Another trap is the heartbeat timeout being too aggressive and causing spurious re-dispatches, or too lenient and leaving jobs stuck for minutes. The best candidates explicitly discuss this tuning trade-off."))

    lines.append(("interviewer", "At the failure handling and observability layer, the key beats are: does the candidate propose a dead letter queue for exhausted retries? Do they describe a concrete retry policy with exponential backoff and jitter? Do they handle stuck jobs with a timeout mechanism? Do they discuss the Scheduler crash recovery path? Do they think about the dispatch queue failure and backpressure? The trap here is treating each failure in isolation — in reality, failures cascade. A Scheduler crash can cause a leader election race, which can cause duplicate dispatch, which can cause duplicate execution if the CAS claim isn't in place. The candidate who traces through a cascading failure scenario shows systems thinking. Another trap is not monitoring the system — a scheduler that silently fails to dispatch jobs is worse than one that crashes loudly, because the problem isn't detected until someone notices that reports are missing."))

    lines.append(("interviewer", "A few specific traps I always watch for. First, timezone bugs — if a candidate stores cron expressions in UTC without considering DST, that's a red flag. The twice-yearly DST transitions will cause jobs to run an hour off, and the fall-back transition can cause double execution. Second, missing DLQ — without a dead letter queue, failed jobs just disappear, and the operations team has no way to investigate or retry. Third, the thundering herd on retry — if 1000 jobs all fail simultaneously due to a downstream outage and all retry at the same backoff interval, they'll all hit the downstream service again at the same time, causing another failure. Jitter is the fix, and a candidate who doesn't mention it hasn't operated a real job scheduler at scale. Fourth, the DAG orphan problem — if a dependency completion event is lost, a downstream job stays BLOCKED forever. The reconciliation loop is the safety net, and it's essential. Overall, the strongest candidates treat a job scheduler as a distributed state machine with careful attention to transition atomicity, failure recovery, and the inherent limitations of at-least-once delivery. Thanks — that wraps it up."))

    return lines
