"""Mock Interview: Distributed Key-Value Store — Two-voice dialogue."""


def build():
    lines = []

    # SECTION 1: Requirements (~5 min)
    lines.append(("interviewer", "Hi, welcome. Today I'd like you to design a distributed key-value store — think DynamoDB or Cassandra. Something that supports high-throughput puts and gets, is highly available, and scales horizontally. Start by clarifying the requirements."))

    lines.append(("candidate", "Thanks. Before I jump in, I want to nail down what kind of key-value store we're building, because the design diverges a lot depending on the answer. Are we talking about a Dynamo-style eventually consistent store optimized for writes and availability, or a Bigtable-style strongly consistent store optimized for reads? The choice affects almost every downstream decision — replication, conflict resolution, read semantics."))

    lines.append(("interviewer", "Let's go with Dynamo-style — prefer availability and partition tolerance over strong consistency. Eventual consistency is acceptable for most use cases, but we should support configurable consistency levels per operation."))

    lines.append(("candidate", "OK, Dynamo-style. That sets the tone. Let me ask about scale and access patterns. What's the expected throughput, how much data are we storing, and what are the typical key and value sizes? Also, is this purely key-value, or do we need any range scans or secondary indexes?"))

    lines.append(("interviewer", "We need to support 10 million reads and 5 million writes per second across the cluster. Total data size is about 500 TB. Keys are up to 1 KB, values up to 1 MB, but the average value is around 10 KB. No range scans, no secondary indexes — pure key-value access. The system should tolerate up to one full data center outage."))

    lines.append(("candidate", "10 million reads and 5 million writes per second at 500 TB — that's serious scale. Let me clarify a few more things. Do we need durability — can we lose data on a node crash? What about TTLs on keys? And is the workload uniform, or are there hot keys?"))

    lines.append(("interviewer", "Yes, durability is required — data must survive node failures. TTLs are nice to have but not required for the initial design. The workload is mostly uniform, but we should handle hot keys gracefully. Multi-datacenter replication is required — we need to survive a full DC loss."))

    lines.append(("candidate", "Let me summarize. We're building a Dynamo-style, eventually consistent, distributed key-value store with configurable consistency levels, 10M reads and 5M writes per second, 500 TB of data, pure key-value access, durability guarantees, multi-DC replication, and tolerance for hot keys. That's our scope. Let me move to estimation."))

    # SECTION 2: Estimation (~5 min)
    lines.append(("interviewer", "Go ahead."))

    lines.append(("candidate", "500 TB of data at replication factor 3 is 1.5 PB. At 1 to 2 TB per node, we need roughly 1000 data nodes. For throughput: 10M reads across 1000 nodes is 10K reads per node. 5M writes is 5K per node, but each write goes to 3 replicas, so the actual write load per node is 15K writes per second. Wait, let me reconsider — with 3 replicas, each node handles writes for its own keys, so it's 5K writes per node client-facing, 15K internally. That's feasible with an LSM-tree engine, but we need to think about write amplification and compaction."))

    lines.append(("interviewer", "What about network bandwidth?"))

    lines.append(("candidate", "Right, let me calculate. Average value size is 10 KB. At 10M reads per second, that's 100 GB per second of read data — about 800 Gbps. At 5M writes per second replicated 3x, that's 150 GB per second internal write traffic — about 1.2 Tbps. Plus inter-DC replication adds about 100 GB per second of cross-DC traffic. We'd need dedicated high-bandwidth links between data centers. Each node sees about 100 MB per second outbound — with 10 GbE NICs, we have headroom, but it's not trivial."))

    lines.append(("interviewer", "How many nodes per data center?"))

    lines.append(("candidate", "With 3 DCs and 1000 total nodes, roughly 333 per DC. With overhead for compaction and growth headroom, let's say 400 per DC, 1200 total, at about 1.25 TB each. Throughput per node: about 8.3K reads and 12.5K writes per second including replication. That's more comfortable."))

    lines.append(("candidate", "The per-node write rate matters for the storage engine. With an LSM tree, each write goes to the WAL and the memtable. At 12.5K writes per second, a 128 MB memtable flushes every 10 seconds. Leveled compaction has 10 to 30x write amplification, so actual disk I/O is 1.25 to 3.75 GB per second. With NVMe SSDs at 2 GB per second writes, we'd need 2 drives for writes alone. I'd spec 4 NVMe SSDs per node for throughput."))

    lines.append(("interviewer", "Good. Let's move to the high-level architecture."))

    # SECTION 3: High-Level Architecture (~5 min)
    lines.append(("candidate", "Here's the overall design. Clients talk to any node in the cluster — there's no master. Each node serves as both a coordinator and a data node. When a client sends a write to a node, that node acts as the coordinator for that request. The coordinator uses a partitioner — typically consistent hashing — to determine which nodes are responsible for that key. It then forwards the write to those nodes and waits for acknowledgments based on the requested consistency level. For a quorum write with replication factor 3, the coordinator sends the write to all 3 replicas but waits for only 2 acknowledgments before responding to the client. The third replica receives the write asynchronously."))

    lines.append(("candidate", "On the read side, the coordinator sends the read request to all replicas and waits for the configured number of responses. With quorum reads, it waits for 2 out of 3. If the responses have conflicting versions — which can happen under eventual consistency — the coordinator reconciles the conflicts using vector clocks and returns the latest version. It also triggers read repair in the background to bring lagging replicas up to date."))

    lines.append(("interviewer", "How does the client know which node to talk to?"))

    lines.append(("candidate", "The client has a lightweight routing library — similar to DynamoDB's SDK. It maintains a cached copy of the token ring, which maps token ranges to nodes. When the client wants to read or write a key, it hashes the key, finds the token range it falls into, and identifies the responsible nodes. It then sends the request directly to one of the replicas — ideally the closest one for latency. If that node is down or slow, the client retries another replica. The token ring cache is refreshed periodically via gossip or by reacting to redirect responses from nodes. This avoids a single routing bottleneck."))

    lines.append(("candidate", "Actually, let me clarify something. The client can send the request to any node, and that node acts as coordinator if it's not a replica for the key. But for efficiency, the client-side routing library tries to send the request directly to a replica node. The coordinator role is a fallback. In practice, most production deployments use client-side routing because it eliminates an extra network hop. But the coordinator path is always available as a fallback."))

    lines.append(("interviewer", "Walk me through the data flow for a write operation at the storage engine level."))

    lines.append(("candidate", "Sure. When a write arrives at a replica node, two things happen in parallel. First, the write is appended to a write-ahead log on disk — this guarantees durability. If the node crashes before the memtable is flushed, the WAL is replayed on recovery. Second, the write is inserted into an in-memory memtable, which is a sorted data structure — typically a skip list or a red-black tree. The write is considered committed once both the WAL write and the memtable insert are complete. The memtable grows over time. When it reaches a configurable size threshold — say 128 MB — it's flushed to disk as an immutable SSTable. SSTables are sorted by key and have an index for efficient lookups. Over time, many SSTables accumulate, and a background compaction process merges them into larger SSTables, eliminating duplicates and removing tombstones for deleted keys."))

    lines.append(("candidate", "Wait, I should be more precise about the commit point. In Dynamo-style systems, the write is considered durable at a replica once it hits both the WAL and the memtable. The coordinator waits for W acknowledgments — where W is the write consistency level — before telling the client the write succeeded. But the write might not be immediately visible on all replicas. Replicas that were unavailable or slow receive the write later via hinted handoff or anti-entropy. This is the essence of eventual consistency."))

    # SECTION 4: Deep Dive — Consistent Hashing, Replication, and Consistency (~10 min)
    lines.append(("interviewer", "Let's dive deeper into consistent hashing. How exactly does it work, and how do you handle the hotspot problem?"))

    lines.append(("candidate", "In classic consistent hashing, each node is assigned a position on a ring — typically by hashing its IP address. A key is also hashed onto the ring, and the first node clockwise from the key's position owns that key. The problem with this basic approach is that the distribution can be very uneven — some nodes get way more data than others. Also, when a node joins or leaves, only its immediate neighbor's load changes, but that neighbor might get overwhelmed. The solution is virtual nodes — each physical node is assigned many positions on the ring, typically 100 to 200 tokens. This smooths out the distribution statistically. DynamoDB uses this approach, and Cassandra adopted it as well."))

    lines.append(("candidate", "With virtual nodes, when a node joins, it gets tokens spread across the ring, so it takes over small ranges from many existing nodes rather than one big range from a single neighbor. Similarly, when a node leaves, its load is distributed across many nodes. This also makes it easier to build a heterogeneous cluster — you can assign more virtual nodes to more powerful machines. For replication, we walk clockwise around the ring from the key's position and pick the next N distinct physical nodes as replicas. The first replica is the primary, the second and third are secondary replicas. This ensures that replicas are on different physical nodes."))

    lines.append(("interviewer", "What about ensuring replicas are in different data centers?"))

    lines.append(("candidate", "Ah, that's an important refinement. With a simple ring walk, all three replicas might end up in the same DC if the tokens happen to be close. Dynamo paper uses a preference list that skips nodes in the same DC as earlier replicas. We can implement this by tagging each virtual node with its DC and rack. When walking the ring to pick replicas, we prefer nodes in different racks within the same DC for the first two replicas, and the third replica goes to a different DC. More precisely, with 3 DCs, we'd place one replica in each DC. The replica selection algorithm walks the ring and picks the first node that satisfies the placement constraints — different rack from previous replicas, and for the last slot, a different DC."))

    lines.append(("candidate", "Actually, let me reconsider. The placement strategy depends on the consistency and latency tradeoff. If we place one replica in each DC, every quorum read or write needs responses from at least 2 DCs, which adds cross-DC latency — maybe 30 to 100 milliseconds. If instead we place 2 replicas in the local DC and 1 in a remote DC, then a quorum of 2 can be satisfied locally for reads, which is much faster. But then we can only survive the loss of 1 local rack or 1 remote DC, not a full local DC outage plus a remote DC outage simultaneously. DynamoDB's global tables handle this differently — they replicate across regions asynchronously, not as part of the quorum path. For our design, I'd go with 2 replicas local and 1 remote, and accept that a full local DC outage requires promoting the remote replica."))

    lines.append(("interviewer", "Now let's talk about consistency. You mentioned quorum reads and writes. How does that work exactly, and what are the tradeoffs?"))

    lines.append(("candidate", "With a replication factor of N, we define R as the number of replicas that must respond to a read and W as the number that must respond to a write. If R plus W is greater than N, we have a quorum — any read will see at least one replica that has the latest write. This is because the read and write sets must overlap by at least one node. Common configurations: R equals W equals 2 with N equals 3 gives strong eventual consistency — reads always see the latest write if there are no concurrent writes. R equals 1, W equals 1 gives maximum availability and lowest latency, but reads might see stale data. R equals 3, W equals 3 gives strong consistency but sacrifices availability — any node failure blocks operations."))

    lines.append(("candidate", "But here's the nuance — even with R plus W greater than N, you don't get linearizability. You get consistent reads of the latest completed write, but if two writes are concurrent — meaning they're initiated at roughly the same time to different replicas — the system accepts both, and they create conflicting versions. This is where Dynamo diverges from strongly consistent systems. Dynamo accepts concurrent writes and resolves conflicts using vector clocks. A strongly consistent system like etcd or ZooKeeper would use a leader and reject or serialize concurrent writes."))

    lines.append(("interviewer", "Explain vector clocks and how they're used for conflict resolution."))

    lines.append(("candidate", "A vector clock is a set of (node, counter) pairs. Each version of a key has an associated vector clock. When a node writes a key, it increments its own counter in the vector clock. When two versions are compared, one version is an ancestor of the other if all counters in its vector clock are less than or equal to the other's, and at least one is strictly less. If neither version is an ancestor of the other, they're siblings — concurrent versions that need to be reconciled."))

    lines.append(("candidate", "Here's a concrete example. Say key K is initially written by node A with vector clock A colon 1. Then node B updates K, incrementing its own counter, so the vector clock becomes A colon 1, B colon 1. Now suppose node A and node B both update K concurrently without seeing each other's update. Node A's version has clock A colon 2, B colon 1, and node B's version has clock A colon 1, B colon 2. Comparing these, A colon 2 is greater but B colon 1 is less, and A colon 1 is less but B colon 2 is greater — neither dominates. These are siblings."))

    lines.append(("candidate", "When a read encounters siblings, the coordinator returns both versions to the client and asks the client to reconcile. This is the Dynamo approach — the application knows best how to merge conflicting data. For a shopping cart, you'd merge the items. For a counter, you might take the higher value. After the client reconciles and writes back, the new version's vector clock subsumes both siblings, effectively resolving the conflict. An alternative approach is last-write-wins, where the system picks the version with the latest timestamp. This is simpler but can lose writes — if two clients write concurrently, one write is silently dropped. Cassandra uses last-write-wins by default, which is a deliberate tradeoff favoring simplicity over correctness."))

    lines.append(("interviewer", "What are the downsides of vector clocks?"))

    lines.append(("candidate", "The main downside is that the vector clock grows with the number of nodes that have updated a key. In a large cluster, this can get large — but in practice, since each key is only updated by a small subset of nodes — its replicas — the vector clock stays bounded. Typically it has at most N entries, where N is the replication factor. A more serious problem is that sibling explosions can happen during network partitions. If a node is partitioned for a long time, writes to different replicas create many siblings, and the client has to reconcile all of them. Dynamo limits the number of siblings — if it exceeds a threshold, it falls back to last-write-wins to prevent unbounded growth. This is a pragmatic compromise."))

    lines.append(("interviewer", "Now let's talk about anti-entropy. How do you keep replicas in sync?"))

    lines.append(("candidate", "There are three mechanisms. The first is read repair. When a coordinator reads from multiple replicas and finds that some have stale versions, it updates the lagging replicas with the latest version. This is synchronous for quorum reads — the coordinator updates the lagging replicas before returning to the client — or asynchronous in the background. Read repair fixes inconsistencies proactively on the read path, but it only fixes keys that are actively read. Cold data that's never read doesn't get repaired."))

    lines.append(("candidate", "The second mechanism is hinted handoff. When a replica is down and a write is supposed to go to it, the coordinator stores the write locally as a hint. When the failed node comes back online, the coordinator replays the hinted writes to it. This ensures that temporarily unavailable nodes catch up quickly after recovery. Hints have a TTL — typically a few hours — because after that, the data might be too stale and full anti-entropy is needed instead. If the coordinator itself goes down before delivering the hints, those writes are lost from the hint store, and the system relies on anti-entropy to catch up."))

    lines.append(("candidate", "The third mechanism is anti-entropy using Merkle trees. A Merkle tree is a hash tree where leaves hash key ranges and internal nodes hash their children. Two nodes exchange root hashes — if they match, data is consistent. If they differ, they compare children recursively to narrow down the inconsistent range. The key advantage: nodes only transfer data that's actually different. With 1 TB per node, full comparison is infeasible, but Merkle tree comparison needs only log N hash comparisons to find differences. Trees are recomputed periodically — every few hours — since computing them is expensive."))

    lines.append(("interviewer", "What about gossip protocol for membership?"))

    lines.append(("candidate", "Right, nodes need to know which other nodes are in the cluster. Each node maintains a membership list and heartbeat counter for every known node. Every second, each node picks a random peer and exchanges membership info. Over time, changes disseminate across the cluster in O(log N) rounds. Failure detection is also gossip-based — if a heartbeat hasn't incremented for 10 seconds, a node is suspected down; after 30 seconds, it's confirmed down and its ranges are reassigned."))

    lines.append(("candidate", "Hmm, but there's a subtlety — split-brain. If a partition splits the cluster, each side thinks the other is down. Dynamo-style systems prefer availability — both sides continue serving reads and writes. When the partition heals, conflicting writes are reconciled with vector clocks. This is the A in CAP. A strongly consistent system would make the minority partition unavailable."))

    # SECTION 5: Failure Modes (~4 min)
    lines.append(("interviewer", "What are the critical failure scenarios, and how does the system handle them?"))

    lines.append(("candidate", "The most common failure is a single node crash. This is routine in a 1000-node cluster — nodes fail every day. When a node goes down, its replicas take over. Reads and writes that would have gone to the failed node are redirected to the other replicas. With N equals 3 and quorum reads and writes, we can tolerate one node failure per key without any impact on availability or consistency. Hinted handoff ensures the failed node catches up when it recovers. The key detail is that the coordinator needs to detect the failure quickly — within a few seconds — and route around it. This is where the gossip-based failure detector matters."))

    lines.append(("candidate", "Actually, let me be more precise about what happens. When a coordinator sends a write to 3 replicas and one doesn't respond within the timeout — say 200 milliseconds — it doesn't wait for it. If W equals 2, the write succeeds with the 2 responses it got, and the coordinator stores a hint for the third. For reads, if R equals 2, the coordinator sends the read to all 3 replicas, gets 2 responses, and if the third is slower, the read still completes. The coordinator then does an async read repair to update the slow replica."))

    lines.append(("interviewer", "What about a network partition between two data centers?"))

    lines.append(("candidate", "This is the classic CAP scenario. If the link between DC1 and DC2 goes down, and DC3 can still reach both, then DC3 acts as a bridge. But if DC3 loses connectivity to one side too — say DC1 is completely isolated — then we have a partition. In the Dynamo model, both sides continue to serve traffic. DC1 serves reads and writes for keys where it has replicas, and DC2 and DC3 serve the other side. For keys that have replicas on both sides of the partition — which is most keys, since we have replicas in each DC — both sides accept writes. This creates conflicts that are resolved when the partition heals."))

    lines.append(("candidate", "But there's a design choice here. We said we'd place 2 replicas in the local DC and 1 remote. If DC1 is partitioned from DC2 and DC3, keys local to DC1 still have 2 replicas there — quorum works. But keys local to DC2 or DC3 now only have 1 local replica. With W equals 2, writes can still succeed if the two available DCs can communicate. If all inter-DC links fail, each DC has 2 replicas for local keys and 1 for remote keys. Remote keys can't achieve quorum, so they become read-only with R equals 1 or unavailable with R equals 2. This is a deliberate tradeoff."))

    lines.append(("candidate", "Another failure mode is disk corruption. Merkle trees catch this during anti-entropy — when hashes don't match, the correct data is copied from a healthy replica. With N equals 3, simultaneous corruption on all replicas is extremely unlikely. But we should still have per-block checksums in SSTables to detect corruption early."))

    lines.append(("interviewer", "What about compaction failures or tombstone accumulation?"))

    lines.append(("candidate", "Oh, that's a real operational issue. When a key is deleted, we don't immediately remove it from SSTables — that would require rewriting the entire SSTable. Instead, we write a tombstone marker. The tombstone is merged during compaction, and the data and tombstone are dropped together. But if compaction falls behind — say, because write throughput is too high — tombstones accumulate and take up space. Worse, if a tombstone is in an old SSTable that hasn't been compacted, and a replica that missed the delete reads an old version from a different SSTable, it might resurrect the deleted data because the tombstone isn't present in its SSTable. To prevent this, we use a garbage collection grace period — tombstones are kept for at least a configured period, say 10 days, to ensure all replicas have seen the delete before the tombstone is removed during compaction. If compaction is too slow to keep up, we'd need to add more nodes to distribute the compaction load."))

    # SECTION 6: Scale & Debrief (~3 min)
    lines.append(("interviewer", "How does the design change at 10x — 50M reads and 25M writes per second?"))

    lines.append(("candidate", "At 10x throughput, we'd need roughly 10,000 to 12,000 nodes. The fundamental architecture doesn't change — consistent hashing and replication scale horizontally by adding more nodes. But the operational complexity increases significantly. Gossip convergence takes longer in a 10,000-node cluster — we might need hierarchical gossip where nodes within a rack gossip frequently, and rack representatives gossip across racks and DCs. Merkle tree computation across 10,000 nodes is a lot of background I/O, so we might compute Merkle trees less frequently or only for ranges that have had recent writes."))

    lines.append(("candidate", "The bigger concern at 10x is compaction. With 12.5K writes per second per node at current scale, at 10x we'd have about 12.5K writes per second per node too if we scale nodes proportionally. But the compaction write amplification becomes a serious bottleneck. We might need to switch from leveled compaction to tiered compaction, which has lower write amplification — about 4 to 10x instead of 10 to 30x — at the cost of higher read amplification. Or we could use a hybrid approach like RocksDB's hybrid compaction. Also, at this scale, we'd likely want to separate the coordinator role from the data node role. Dedicated coordinator nodes handle client connections, routing, and consistency logic, while data nodes focus purely on storage. This simplifies capacity planning and failure handling."))

    lines.append(("candidate", "At 0.1x scale, we'd need about 100 to 150 nodes. The architecture stays identical — consistent hashing, vector clocks, LSM tree. We'd just run smaller instances with fewer SSDs. Anti-entropy could run more aggressively since there's less data. The fundamental design doesn't change at lower scale."))

    lines.append(("interviewer", "Let me give you feedback. Strengths: you asked the right clarifying questions up front, especially the Dynamo vs. Bigtable distinction, which fundamentally shapes the design. Your consistent hashing explanation with virtual nodes and DC-aware placement was thorough. The vector clock example was concrete and clear. The anti-entropy mechanisms — read repair, hinted handoff, and Merkle trees — were well-connected into a coherent story. Areas for improvement: when discussing the DC-aware replica placement, you changed your mind mid-stream — the initial all-DCs-equal placement to the 2-local-1-remote strategy was a reasonable evolution, but you could have explored the tradeoff more systematically upfront. Also, you didn't discuss the read path in as much depth as the write path — specifically, how a read locates data across multiple SSTables and the role of bloom filters. Overall, very strong performance."))

    lines.append(("candidate", "Thanks. You're right about the bloom filters — I should have covered that. For each SSTable, we maintain a bloom filter in memory that tells us whether a key might be in that SSTable or is definitely not. This avoids unnecessary disk reads for keys that don't exist in a given SSTable. On a read, we check the bloom filters of all SSTables, only read from the ones that might contain the key, and merge the results. Without bloom filters, every read would need to check every SSTable, which is O(number of SSTables) disk seeks. With bloom filters, it's typically O(1) or O(2) disk reads since the key is usually in the memtable or the most recent SSTable. I should have woven that into the storage engine discussion."))

    # SECTION 7: End-to-End Walkthrough (~4 min)
    lines.append(("interviewer", "Let's do an end-to-end walkthrough. Trace a write for key K with value V, and then a read for the same key, through the entire system step by step."))

    lines.append(("candidate", "Starting with the write. The client wants to put key K with value V. The client-side routing library hashes K — say using MD5 or MurmurHash3 — to get a 128-bit token. It looks up the token ring to find which token range this hash falls into and identifies the 3 responsible nodes — Node1, Node2, and Node3, where Node1 and Node2 are in the local DC and Node3 is in a remote DC. The client sends the write request to Node1, which will act as coordinator."))

    lines.append(("candidate", "Node1, as coordinator, generates a vector clock for this write. Since this is the first version of K, the vector clock is Node1 colon 1. Node1 sends the write — key K, value V, vector clock Node1 colon 1 — to all 3 replicas in parallel. It also writes the data locally since it is itself one of the replicas. Wait — actually, the coordinator might or might not be a replica. In our design, since the client sent the request directly to a replica, Node1 is both coordinator and replica. Let me continue with that assumption."))

    lines.append(("candidate", "On each replica node — Node1, Node2, Node3 — the write arrives and is processed as follows. First, the write is appended to the write-ahead log on disk. This is a sequential write, so it's fast — typically under a millisecond. Second, the write is inserted into the in-memory memtable. Once both operations complete, the replica sends an acknowledgment back to the coordinator. Since the write consistency level is quorum — W equals 2 — Node1 waits for 2 acknowledgments. Node1 itself is one ACK, and it receives Node2's ACK shortly after. Node1 now has 2 ACKs and returns success to the client. Node3's ACK arrives later and is noted but not required for the client response."))

    lines.append(("candidate", "If Node3 were down, Node1 would store a hint — a record saying, when Node3 comes back, send it this write. The hint includes the key, value, vector clock, and timestamp. The write still succeeds because W equals 2 and we have 2 available replicas. This is hinted handoff in action."))

    lines.append(("interviewer", "Now the read."))

    lines.append(("candidate", "Now the client reads key K. The client-side library hashes K, finds the same 3 nodes, and sends the read request to one of them — say Node2. Node2 acts as coordinator for the read. Since the read consistency level is quorum — R equals 2 — Node2 sends the read request to all 3 replicas in parallel and waits for 2 responses. Node1 and Node2 both respond quickly with value V and vector clock Node1 colon 1. Node3's response might arrive later, but Node2 already has 2 matching responses, so it returns V to the client. It also checks if all replicas have the same version — if they do, no repair is needed. If Node3 had a stale version, Node2 would trigger an async read repair to bring Node3 up to date."))

    lines.append(("candidate", "Let me trace a more interesting case. Suppose a concurrent write happened. While Node3 was briefly partitioned, the client wrote key K again with value V2 through a different coordinator — say Node2. Node2 incremented the vector clock to Node1 colon 1, Node2 colon 1 and wrote to Node1 and Node2, but Node3 didn't get this update due to the partition. Now Node3 has V with clock Node1 colon 1, while Node1 and Node2 have V2 with clock Node1 colon 1, Node2 colon 1. When the client reads K, the coordinator — say Node1 — gets responses from all 3. Node1 has V2 with clock A colon 1, B colon 1, Node2 has the same, and Node3 has V with clock A colon 1. The coordinator compares vector clocks and determines that V2's clock dominates V's clock — Node1 colon 1 equals Node1 colon 1 and Node2 colon 1 is greater than nothing. So V2 is the latest version. The coordinator returns V2 and triggers read repair to update Node3."))

    lines.append(("candidate", "Now the even trickier case — true siblings. Suppose during the partition, Node1 wrote V2 with clock Node1 colon 2, and Node3 wrote V3 with clock Node1 colon 1, Node3 colon 1. These are concurrent — neither clock dominates. When the partition heals and a read hits both versions, the coordinator returns both siblings to the client. The client reconciles — say it picks V2 — and writes back K equals V2 with a new vector clock that subsumes both: Node1 colon 2, Node3 colon 1. This resolves the conflict. The coordinator also triggers read repair to propagate the resolved version to all replicas."))

    # SECTION 8: Thinking Process & Beats (~3 min)
    lines.append(("interviewer", "To wrap up, let me walk through the thinking process and key beats I was looking for in this interview, along with common traps to avoid."))

    lines.append(("interviewer", "The mental framework has four layers. First, data partitioning — consistent hashing with virtual nodes; explain why virtual nodes matter for load balancing and heterogeneity. Second, replication and consistency — the R, W, N quorum model is the core, and you need to understand that R plus W greater than N guarantees overlap but not linearizability. Third, conflict resolution — vector clocks for detection plus application-level reconciliation, and the tradeoff with last-write-wins. Fourth, failure handling — hinted handoff, Merkle tree anti-entropy, and read repair are the three pillars, and you need to know when each kicks in."))

    lines.append(("interviewer", "Key beats. Beat one: the Dynamo versus Bigtable distinction up front — it shapes every downstream decision. Beat two: virtual nodes in consistent hashing — saying consistent hashing without the hotspot problem and virtual node solution misses the practical insight. Beat three: DC-aware replica placement — replicating 3 times is easy, placing across failure domains is what actually survives real failures. Beat four: the quorum model's limitations — R plus W greater than N doesn't prevent concurrent write conflicts or give linearizability. Beat five: vector clocks with a concrete example, not just abstract description — walk through an actual concurrent update scenario. Beat six: the three anti-entropy mechanisms and when each matters — read repair for hot data, hinted handoff for temporary failures, Merkle trees for cold data. Beat seven: the LSM tree write path — WAL, memtable, SSTable, compaction, tombstones. Without the storage engine, your system is just routing logic."))

    lines.append(("interviewer", "Traps to avoid. Trap one: saying strong consistency with a Dynamo-style system — you need Raft or Paxos for that, not a leaderless quorum with vector clocks. Don't mix paradigms. Trap two: ignoring write amplification and compaction — at scale, compaction is often the first bottleneck. Trap three: saying consistent hashing without virtual nodes — shows you haven't thought about uneven load. Trap four: overcomplicating conflict resolution with CRDTs everywhere — Dynamo uses simple vector clocks plus application-level reconciliation, which is more pragmatic. Trap five: forgetting bloom filters on the read path — without them, every read touches every SSTable. Trap six: not explaining how a partitioned node rejoins — hinted handoff covers short failures, long failures need Merkle tree sync. Trap seven: confusing eventual consistency with other models — eventual consistency means convergence, not that reads always see the latest write. Be precise."))

    lines.append(("interviewer", "Finally, the end-to-end walkthrough is where many candidates fall apart. Tracing a single key through a write and read — including failure cases like node downtime and conflict scenarios like concurrent updates — is the true test of whether you understand the system holistically or just know the buzzwords. The candidate who can smoothly handle the sibling resolution case — showing how vector clocks detect concurrency, how the client reconciles, and how the resolved version propagates — demonstrates real depth. That's the interview. Thanks for your time."))

    return lines
