"""Mock Interview: KYC/Onboarding System — Two-voice dialogue."""


def build():
    lines = []

    # SECTION 1: Requirements
    lines.append(("interviewer", "Hi, welcome. Today I'd like you to design a KYC and onboarding system for a fintech platform. Think of it as the system that verifies a merchant's identity, screens them against compliance databases, and either approves or rejects their account. Start by clarifying the requirements."))

    lines.append(("candidate", "Thanks. KYC onboarding is one of those problems that sounds simple — verify identity, check compliance, done — but is actually incredibly complex because of regulatory requirements, multi-jurisdiction differences, and the fact that every false positive costs manual review time while every false negative is a regulatory violation. Let me ask the key questions. First, what jurisdictions are we operating in, and are the requirements different per region?"))

    lines.append(("interviewer", "We operate in Singapore, Australia, UK, EU, and the US. Each has different requirements. Singapore requires MAS-regulated KYC. Australia requires AUSTRAC verification. The UK and EU require GDPR-compliant processing. The US requires FinCEN compliance. The documents required differ — Singapore accepts Singpass for digital identity, the US requires SSN verification, the EU requires GDPR consent for data processing."))

    lines.append(("candidate", "Second question: what's the target onboarding time? Fully automated, or are we expecting manual review for some cases?"))

    lines.append(("interviewer", "We want fully automated onboarding for low-risk merchants in under five minutes. For higher-risk categories — money services businesses, crypto, gambling — we need manual review, which takes twenty-four to forty-eight hours. About seventy percent of applications should be auto-approved, twenty percent go to manual review, and ten percent are auto-rejected."))

    lines.append(("candidate", "Third question: is KYC a one-time check at onboarding, or is it ongoing? In fintech, KYC isn't done when the account is approved — you need continuous monitoring. A customer who was clean at onboarding might appear on a sanctions list six months later."))

    lines.append(("interviewer", "Absolutely right. KYC is ongoing. We need to rescreen customers when watchlists are updated, when their transaction behavior changes, and on a regular cadence — annually for low-risk, quarterly for high-risk. The onboarding system is the first touch, but the monitoring system runs forever."))

    lines.append(("candidate", "Let me summarize: multi-jurisdiction with different document and compliance requirements, five-minute auto-approval for seventy percent, manual review for twenty percent, auto-reject for ten percent, and ongoing monitoring after onboarding. Moving to estimation."))

    # SECTION 2: Estimation
    lines.append(("interviewer", "Go ahead with the numbers."))

    lines.append(("candidate", "Onboarding volume: say five thousand new applications per day across all regions. Peak during business hours — maybe three times average, so about six hundred per hour at peak. Each application takes about five minutes for the automated path — that includes document upload, verification, screening, risk scoring, and decision. At six hundred per hour with five-minute processing, we need about fifty concurrent processing slots. That's trivial in compute terms — fifty parallel workflows on a serverless platform."))

    lines.append(("candidate", "For manual review: twenty percent of five thousand is one thousand per day. A compliance officer can review about twenty cases per hour — each takes about five to ten minutes of document reading and decision-making. So one thousand cases divided by twenty per hour means fifty compliance-officer hours per day. With a team of eight officers across time zones, each working six productive hours, that's forty-eight hours — tight but manageable. We'd monitor the queue depth — if it exceeds a threshold, we need more officers or we need to improve the automated system to reduce the manual review rate."))

    lines.append(("candidate", "Storage: each application generates about five to ten megabytes of document images — passport scan, proof of address, business registration. Plus metadata — about two kilobytes per application. At five thousand per day, that's about twenty-five to fifty gigabytes of documents per day. Over three years, that's about thirty to sixty terabytes of document storage. We'd store documents in encrypted object storage — S3 or R2 — with lifecycle rules to move older documents to cold storage. The metadata lives in PostgreSQL, with a reference to the document location in object storage. We never store PII in logs or caches."))

    # SECTION 3: High-Level Architecture
    lines.append(("interviewer", "Let's see the architecture."))

    lines.append(("candidate", "The onboarding flow has five stages. Stage one: application intake. The merchant fills out the onboarding form on our website or API. They select their business type, jurisdiction, and upload identity documents. The intake service validates the form data and stores the documents in encrypted object storage. It creates an application record in the database with status PENDING_VERIFICATION."))

    lines.append(("candidate", "Stage two: document verification. The document verification service sends the uploaded documents to a third-party provider — Jumio, Onfido, or similar. The provider checks document authenticity — is the passport genuine? Is the photo a live photo or a screen capture? — and performs liveness detection — asking the user to blink or turn their head. This takes about thirty to sixty seconds. The result comes back via a webhook callback. If verification passes, the application moves to stage three. If it fails, we auto-reject and notify the merchant."))

    lines.append(("candidate", "Stage three: compliance screening. The screening service checks the applicant against multiple databases. Sanctions lists — OFAC, EU, UN, and local lists. PEP lists — Politically Exposed Persons. Adverse media — is the applicant or their company mentioned in negative news? The screening uses fuzzy name matching because names can be transliterated differently — Abdul Rahman, Abd al-Rahman, Abdurahman should all match the same entry. We use Elasticsearch with phonetic analysis — the double metaphone algorithm — for fuzzy matching. The screening takes about one to two seconds per database."))

    lines.append(("candidate", "Stage four: risk scoring. A risk model evaluates the applicant based on their business type, jurisdiction, transaction volume projections, source of funds, and the screening results. The model produces a risk score from zero to one hundred. Scores below thirty: auto-approve. Scores above eighty: auto-reject. Scores between thirty and eighty: manual review queue. The risk model is a gradient-boosted decision tree trained on historical outcomes — which approved merchants later triggered fraud or compliance issues."))

    lines.append(("candidate", "Stage five: decision and account activation. For auto-approve, the system creates the merchant account, generates API credentials, and sends a welcome email. For manual review, the case goes to a queue that compliance officers access through a dashboard. For auto-reject, the system sends a rejection notice with the reason, and the applicant can appeal or reapply with additional documentation."))

    # SECTION 4: Deep Dive — Fuzzy Name Matching
    lines.append(("interviewer", "Let's deep dive into the fuzzy name matching. Why is it so hard, and how do you make it reliable?"))

    lines.append(("candidate", "Fuzzy name matching is the hardest part of sanctions screening, and it's where most false positives and false negatives originate. Here's why it's hard. First, transliteration: Arabic, Chinese, and Russian names can be transliterated into Latin characters in many ways. Mohammed, Muhammad, Mohamed, Mohamad — all the same person, but they look different to an exact-match system. Second, name ordering: in some cultures, the family name comes first; in others, it comes last. Third, abbreviations: J. Smith versus John Smith versus Jonathan Smith. Fourth, typos: both in the applicant's submission and in the sanctions list entries themselves — yes, government databases have typos."))

    lines.append(("candidate", "Our matching strategy uses multiple techniques layered together. Layer one: exact match after normalization — lowercase, remove punctuation, remove whitespace. This catches about forty percent of matches. Layer two: phonetic matching using double metaphone. This generates a phonetic code for each name — so Mohammed and Muhammad produce the same code. This catches another thirty percent. Layer three: edit distance — Levenshtein distance. If two names have an edit distance of one or two, they might be the same. This catches typos. Layer four: token-based matching — split the name into tokens and check if all tokens appear in the sanctions entry in any order. This handles name reordering."))

    lines.append(("candidate", "The key insight: we tune for high recall, not high precision. We'd rather have a hundred false positives — each requiring five minutes of manual review — than one false negative that lets a sanctioned entity open an account. A single false negative is a regulatory violation that can result in millions in fines and reputational damage. The compliance team understands this trade-off and accepts the false positive burden."))

    # SECTION 5: Deep Dive — Ongoing Monitoring
    lines.append(("interviewer", "Tell me more about the ongoing monitoring after onboarding."))

    lines.append(("candidate", "Ongoing monitoring has three triggers. Trigger one: watchlist updates. When OFAC or the EU updates their sanctions list — which happens about five times per week — we rescreen all customers against the new entries. Not all five million customers — we maintain an index of all customer names in Elasticsearch, and when a new sanctions entry is published, we query the index for fuzzy matches. This takes about ten seconds and returns maybe fifty to two hundred potential matches. Each match goes to a compliance officer for review. If confirmed, the customer's account is frozen and a Suspicious Activity Report is filed."))

    lines.append(("candidate", "Trigger two: behavioral changes. If a customer who was approved as a low-risk online retailer suddenly starts sending large wire transfers to high-risk jurisdictions, the transaction monitoring system flags the behavior. The risk score is recalculated, and if it crosses the manual review threshold, the case goes to the queue. This is the intersection of KYC and fraud detection — the onboarding system and the fraud detection system share the risk model."))

    lines.append(("candidate", "Trigger three: periodic rescreening. Every customer is rescreened at least annually, regardless of triggers. High-risk customers — money services businesses, crypto — are rescreened quarterly. Periodic rescreening catches changes that don't trigger the other two paths — for example, a customer's business partner appears on a PEP list, which affects the customer's risk profile. The rescreening is identical to the initial screening — same databases, same fuzzy matching, same risk scoring — but it runs asynchronously in the background without interrupting the customer's service."))

    # SECTION 6: GDPR and Data Privacy
    lines.append(("interviewer", "How do you handle the right to erasure under GDPR? A customer asks you to delete their data."))

    lines.append(("candidate", "This is the classic tension between GDPR and financial regulations. Under GDPR, a customer has the right to request deletion of their personal data. Under anti-money-laundering regulations — like the EU's AMLD five — we must retain customer identification data for five years after the business relationship ends. These requirements conflict, and the regulation with the stronger public interest — AMLD — takes precedence. Our approach: when a customer requests erasure, we pseudonymize their data rather than delete it. We replace their name with a pseudonym, their address with a region code, and their date of birth with an age range. The pseudonymized record is no longer personally identifiable under GDPR, but it's still usable for compliance investigations if needed. The mapping between the pseudonym and the original identity is stored in a separate, access-controlled system that requires legal authorization to access."))

    lines.append(("candidate", "The audit trail is never deleted — even the pseudonymized version. Regulators can audit our compliance decisions years after the fact, and they need to see that we performed the required checks, even if the customer's identity is no longer directly visible. This is a non-negotiable requirement that I'd state clearly in the interview: in a fintech system, the audit trail is permanent. You pseudonymize, you don't delete."))

    # SECTION 7: Failure Modes and Quality
    lines.append(("interviewer", "What happens when the document verification provider goes down?"))

    lines.append(("candidate", "The document verification is a synchronous dependency — we can't approve an account without verifying the documents. If the provider is down, the application stays in PENDING_VERIFICATION state. We queue it and process it when the provider recovers. To avoid blocking all onboarding during an outage, we implement a fallback: if the primary provider is unavailable for more than five minutes, we switch to a secondary provider. We maintain integration with at least two verification providers for exactly this reason. The switch is automatic — a health check monitors the primary provider's API, and if it fails three consecutive health checks, the router switches to the secondary."))

    lines.append(("interviewer", "What about KYC GenAI — Airwallex uses LLMs to reduce false positives. How would you integrate that?"))

    lines.append(("candidate", "KYC GenAI is applied at the screening stage. When the fuzzy matcher returns potential matches, instead of sending all of them to a compliance officer, we use an LLM to triage. The LLM is given the applicant's name, the sanctions entry's name, and the match score, and is asked: is this a true match or a false positive? The LLM can reason about transliteration patterns, name ordering, and cultural conventions that the fuzzy matcher can't. For example, if the applicant is Kim Jong-un and the sanctions entry is Kim Jung-woon, the fuzzy matcher might flag this as a potential match, but the LLM can determine that these are likely different people based on the Korean romanization patterns."))

    lines.append(("candidate", "The LLM reduces false positives by about fifty percent, which means our compliance team reviews five hundred cases per day instead of one thousand. That's a huge efficiency gain. But the LLM is never the final decision-maker. If the LLM says false positive, the case is still reviewed by a compliance officer — just at a lower priority. If the LLM says true match, the case is escalated immediately. The LLM is a triage tool, not an authority. This is the same guardrail pattern as the AI Agent Platform — AI assists, humans decide."))

    # SECTION 8: Summary with Killer Phrases
    lines.append(("candidate", "Let me close with the killer phrases for this topic. One: tune for high recall, not high precision — false positives are expensive, false negatives are illegal. Two: fuzzy matching uses four layers — normalization, phonetic double metaphone, Levenshtein distance, and token-based matching. Three: pseudonymize, never delete — GDPR right to erasure is satisfied by pseudonymization, not deletion, in a financial system. Four: the audit trail is permanent and immutable — regulators can audit your compliance decisions years later. Five: KYC GenAI reduces false positives by fifty percent but is a triage tool, not an authority — AI assists, humans decide. Six: maintain at least two verification providers — synchronous dependencies need automatic failover. And seven: ongoing monitoring has three triggers — watchlist updates, behavioral changes, and periodic rescreening. KYC doesn't end at onboarding."))

    # SECTION 8: E2E Walkthrough
    lines.append(("interviewer", "Walk me through the complete flow for a Singapore merchant onboarding."))

    lines.append(("candidate", "Step one: application intake. The merchant — say, a Singapore-registered e-commerce company — visits our onboarding portal. They select their jurisdiction as Singapore and business type as e-commerce. The form dynamically adapts — Singapore requires a Singpass verification, ACRA business registration number, and proof of registered address. They upload their passport, a utility bill for address proof, and their ACRA registration certificate. The intake service validates the ACRA number format — it should be a nine-character alphanumeric — and stores the documents in encrypted object storage in the Singapore region, complying with PDPA data residency. Application status: PENDING_VERIFICATION."))

    lines.append(("candidate", "Step two: document verification. The system sends the passport image to our primary provider, Jumio. Jumio performs three checks: document authenticity — is the passport genuine, not a photocopy or digital edit? Facial similarity — does the face in the passport match the selfie the merchant uploaded? Liveness detection — was the selfie taken from a live person, not a screen? Jumio takes about forty-five seconds. Result: PASS with ninety-eight percent confidence. If Jumio had failed, we'd auto-reject and notify. If Jumio returned an error — service unavailable — we'd queue and retry with Onfido as fallback. Status: PENDING_SCREENING."))

    lines.append(("candidate", "Step three: compliance screening. The screening service runs four checks in parallel. One: OFAC sanctions — the merchant's name, Mohamad Razak bin Ismail, is normalized to lowercase, and we search with double metaphone. No matches on OFAC. Two: EU sanctions — no matches. Three: MAS TRM watchlist — Singapore's specific list. No matches. Four: PEP check — is this person a Politically Exposed Person? The name appears in a PEP list with a similar entry — Muhammad Razak Ishmail, a former government official in a neighboring country. Edit distance is three — close but not exact. The fuzzy matcher flags this as a potential match with a confidence score of sixty-five percent. Status: PENDING_RISK_SCORING."))

    lines.append(("candidate", "Step four: risk scoring. The risk model evaluates: business type e-commerce — low risk. Jurisdiction Singapore — low risk. No sanctions matches. One PEP potential match with sixty-five percent confidence. The risk model produces a score of forty-two — in the manual review range of thirty to eighty. The system adds this case to the compliance officer queue with a priority of MEDIUM and a note: PEP potential match, fuzzy confidence sixty-five percent, recommend LLM triage."))

    lines.append(("candidate", "Step four point five: KYC GenAI triage. The LLM receives the applicant's name — Mohamad Razak bin Ismail — and the PEP entry — Muhammad Razak Ishmail, former deputy minister of country X. The LLM analyzes: the names share the root Razak and the patronymic structure is consistent with Malay naming conventions, but bin Ismail versus Ishmail suggests different patronymic origins — Ismail is a common Malay name while Ishmail is a variant found in specific regions. The LLM concludes: likely different person, confidence eighty percent. The case priority is downgraded from MEDIUM to LOW. The compliance officer still reviews it, but at lower urgency."))

    lines.append(("candidate", "Step five: compliance officer review. An officer in Singapore picks up the case. They examine the PEP match, compare the passport photo with the PEP entry's public photo, and confirm it's a different person. They approve the account. The system creates the merchant account, generates API credentials, and sends a welcome email. Total time from application to approval: about eight minutes — five minutes for automated checks, three minutes for officer review. This is the ideal flow: fast for the merchant, safe for the company, compliant for the regulator."))

    lines.append(("candidate", "And then ongoing monitoring kicks in. Next week, when the MAS watchlist is updated, the screening service automatically re-queries the Elasticsearch index. If Mr. Razak's name ever appears on a new list, his case is escalated immediately. His account could be frozen within minutes of a confirmed sanctions match. KYC never ends — it just moves from onboarding to monitoring. That's the phrase to remember: KYC doesn't end at onboarding, it just moves to monitoring."))

    return lines
