"""Mock Interview: Location-Based Service like Uber — Two-voice dialogue."""


def build():
    lines = []

    # SECTION 1: Requirements (~5 min)
    lines.append(("interviewer", "Hi, today I'd like you to design a location-based service — think of the core functionality that Uber or Lyft provides: finding nearby drivers, tracking their real-time locations, and estimating ETAs. Start by clarifying the requirements."))

    lines.append(("candidate", "Thanks. A location-based service has some really unique challenges around write throughput and spatial queries. Let me start with the most fundamental question: are we building the full ride-hailing system — including dispatch, routing, and payment — or just the location and proximity layer?"))

    lines.append(("interviewer", "Just the location and proximity layer: driver location updates, nearby driver search, real-time tracking, and ETA estimation. Dispatch and routing are separate systems."))

    lines.append(("candidate", "OK, that scopes it well. Next question: what's the scale — how many active drivers and riders, how frequently do drivers update their locations, and how many nearby-search queries per second? Also, what's the search radius for nearby drivers?"))

    lines.append(("interviewer", "10 million active users total, roughly split 3 million drivers and 7 million riders. Drivers update their location every 5 seconds. We need to handle 1 million nearby-driver queries per second. The default search radius is 5 kilometers, but it should be configurable."))

    lines.append(("candidate", "3 million drivers updating every 5 seconds — that's 600K location writes per second. Plus 1M reads per second for nearby searches. That's a write-heavy system with 600K writes and 1M reads per second. A few more questions. First, what accuracy do we need for the nearby search? Is it OK to return drivers who are slightly outside the 5km radius, or do we need precise distance filtering? Second, do we need to consider driver availability — only show drivers who are available, not on a trip? Third, what about the real-time tracking — do riders need to see the driver's live location during a trip, and if so, what's the update frequency for the rider?"))

    lines.append(("interviewer", "Good questions. Accuracy: returning drivers within approximately 5km is fine — we can filter more precisely on the client side. A small number of drivers slightly outside the radius is acceptable. We do need to filter by availability — only available drivers should appear in search results. For real-time tracking during a trip, the rider sees the driver's location updated every 3 to 5 seconds."))

    lines.append(("candidate", "What about the distribution of drivers across regions? Are we operating globally, or concentrated in specific cities? This affects the spatial density and the search optimization."))

    lines.append(("interviewer", "Primarily concentrated in urban areas across 50 major cities globally. Rural coverage is sparse. About 70 percent of drivers are in the top 10 cities."))

    lines.append(("candidate", "That means the spatial density in cities like New York or London could be extremely high — potentially tens of thousands of drivers within a 5km radius. The search results need to be intelligent about which drivers to show, not just return all of them. One more question: for ETA estimation, are we computing straight-line distance ETAs, or do we need to account for roads and traffic? Road-aware ETAs require a routing engine like OSRM or Google Maps, which is a significant dependency."))

    lines.append(("interviewer", "Straight-line distance for this design, but discuss how you would integrate a routing engine for production-quality ETAs."))

    lines.append(("candidate", "Let me summarize. We're designing a location service for 3M drivers updating every 5 seconds (600K writes/sec), 1M nearby-search queries/sec with 5km radius, availability filtering, real-time tracking during trips, and straight-line ETA estimation. Let me move to estimation."))

    lines.append(("interviewer", "Before you start, let me add one more requirement. We also need a geofencing capability — the ability to define geographic zones and trigger events when drivers enter or exit them. For example, an airport queue zone where only drivers who have entered the zone can receive airport ride requests."))

    lines.append(("candidate", "Good addition. Geofencing adds a reverse spatial query — instead of finding points near a query point, we're finding zones that contain a point. This is a different data structure problem. I'll incorporate it into the design. So the full scope is: driver location updates, nearby driver search, real-time tracking, ETA estimation, and geofence event detection."))

    # SECTION 2: Estimation (~5 min)
    lines.append(("interviewer", "Go ahead."))

    lines.append(("candidate", "600K location writes per second. Each location update is a driver ID, latitude, longitude, timestamp, and availability status — about 33 bytes per update. At 600K per second, that's about 20 MB per second, or 1.7 GB per day of raw location data. But we don't need to persist all of it — we only need the current location for each driver. The hot working set is 3M drivers times 33 bytes, about 100 MB. That fits comfortably in memory."))

    lines.append(("candidate", "Wait, I need to reconsider the persistence requirement. Even though we only need the current location for serving queries, we might need recent location history for ETA estimation and analytics. Let's say we keep the last 10 location updates per driver for smoothing and trend analysis. That's 10 times 3M times 33 bytes, about 1 GB. Still fits in memory with a distributed cache. For long-term storage, we would batch-write location data to a time-series database or data lake for analytics — maybe every minute we write a snapshot of all driver locations, which is 3M times 33 bytes per minute, about 100 MB per minute, or 144 GB per day. This goes to cold storage."))

    lines.append(("candidate", "For the read side, 1M nearby-search queries per second. Each query needs to scan a spatial index to find drivers within 5km. With a geohash-based index where we look up all drivers in the geohash cells covering a 5km radius, the number of cells depends on the geohash precision. At precision 5, each cell is about 4.9km by 4.9km. A 5km radius might span 4 to 9 cells. The Earth has about 32 million cells at precision 5. With 3M drivers, that's about 0.1 drivers per cell on average. But drivers are concentrated in urban areas, so popular cells might have thousands of drivers. In a dense city like Manhattan, a single cell at precision 6 might contain 5000 drivers. The lookup is fast — a few Redis GET commands per cell, each returning a list of driver IDs and locations."))

    lines.append(("candidate", "The bandwidth for reads is also worth estimating. Each nearby search returns, say, 20 drivers. Each driver result is about 50 bytes (driver ID, lat, lng, ETA estimate). At 1M queries per second, that's 20M results times 50 bytes equals 1 GB per second of outgoing data. Manageable with proper network infrastructure. The Redis read traffic for the spatial index lookups is about 10 to 15 key lookups per query, each returning maybe 1 to 5 KB of data per cell. At 1M QPS, that's 10 to 15M Redis reads per second, returning about 10 to 75 GB per second. This is significant and requires a well-sized Redis cluster."))

    lines.append(("candidate", "For the geofencing feature, we need to store geofence zones — polygons defined by a set of vertices. When a driver's location updates, we check if they have entered or exited any geofence. The number of geofences is relatively small — maybe 10,000 zones globally, covering airports, event venues, and restricted areas. Each geofence is a polygon with maybe 10 to 50 vertices. We store geofences in a separate index, also geohash-based. When a driver's location updates, we compute their geohash and check which geofences overlap that geohash cell. For each overlapping geofence, we do a point-in-polygon test using the ray casting algorithm. With 10K geofences and 600K updates per second, the geofence check adds about 5 to 10ms per update if we optimize with the geohash pre-filter. Most geohash cells have zero or one overlapping geofence, so the point-in-polygon test is rarely needed."))

    lines.append(("candidate", "The geofence check runs in parallel with the spatial index update. When a location update arrives, the Update Service simultaneously updates the driver's position in the spatial index and checks for geofence transitions. If a transition is detected — the driver was outside a geofence and is now inside, or vice versa — we publish a geofence event to a Kafka topic. Downstream consumers like the dispatch system use these events to manage airport queues, surge pricing zones, and restricted area alerts. The geofence events must be reliable — we can't afford to miss an airport entry event because it affects the driver's ability to receive airport ride requests."))

    lines.append(("interviewer", "What about the write throughput for location updates? 600K writes per second is significant."))

    lines.append(("candidate", "Right. 600K writes per second to a spatial index is the key challenge. If we use Redis, each location update requires removing the driver from their old geohash cell and adding them to the new cell. That's two Redis commands per update. At 600K updates per second, that's 1.2M Redis commands per second. A single Redis instance handles about 100K commands per second, so we would need about 12 Redis instances for the spatial index. The driver locations are partitioned by geohash prefix, so each Redis node handles a geographic region."))

    lines.append(("candidate", "Actually, wait. Partitioning by geohash prefix creates hot spots — urban areas like Manhattan have many more drivers than rural areas. A geohash prefix that covers Manhattan might have 100K drivers, while one covering rural Montana has 10. The load distribution is very uneven. A better approach is to partition by driver ID — hash the driver ID to determine the Redis node. But then a spatial query needs to scan all nodes to find nearby drivers, which is inefficient. This is the fundamental tension in spatial data systems: partitioning by space gives fast reads but uneven writes, while partitioning by entity gives even writes but slow spatial reads. I would optimize for the read-heavy case and partition by geohash, accepting uneven write distribution and handling hot spots by further sub-partitioning dense urban cells."))

    # SECTION 3: High-Level Architecture (~5 min)
    lines.append(("interviewer", "Good. Let's move to the high-level architecture."))

    lines.append(("candidate", "The system has four components: the Location Update Service, the Spatial Index, the Nearby Search Service, and the Tracking Service. The Location Update Service receives driver location updates via a persistent connection — probably WebSocket or gRPC streaming. When a driver's app sends a new location, the Update Service validates the coordinates, checks if the driver has moved significantly from their last known location — to avoid redundant updates — and then writes the new location to the Spatial Index. The write involves two steps: remove the driver from the old geohash cell and add them to the new cell. The Update Service also writes the full location to a per-driver record in Redis for the Tracking Service."))

    lines.append(("candidate", "The Spatial Index is a geohash-based index stored in Redis. For each geohash cell at precision 5 or 6, we maintain a sorted set of driver IDs currently in that cell, scored by their timestamp. This allows us to quickly expire stale entries — drivers who have not updated in 30 seconds are considered offline and removed. The Nearby Search Service handles queries: given a rider's latitude and longitude, it computes the geohash cells that cover a 5km radius, fetches the driver lists from those cells, filters by availability, computes the straight-line distance for each driver, sorts by distance, and returns the top N — say 20 — nearest available drivers."))

    lines.append(("interviewer", "Why geohash specifically? What about quadtree or Google's S2 geometry?"))

    lines.append(("candidate", "Good question. Let me compare the three. Geohash encodes a location into a string where prefixes represent larger areas. It's simple and maps naturally to Redis keys. The main drawback is boundary discontinuity — locations near a cell boundary might be close in reality but have very different geohash values, requiring us to check multiple adjacent cells. Quadtree is a tree structure that recursively subdivides space. It's more flexible for variable-density areas — dense areas get deeper subdivisions. But it's harder to implement with Redis and requires a custom tree structure. S2 geometry from Google divides the Earth's surface into cells on a sphere, avoiding the projection distortions of geohash and quadtree, which work on a flat plane. S2 cells have better boundary properties and more uniform area. For production, I would use S2. But for this design, geohash is simpler to explain and implement, and the boundary issue is handled by checking adjacent cells."))

    lines.append(("candidate", "For the adjacent-cell algorithm: when a rider at a given location queries for nearby drivers, we compute their geohash at precision 6 — which gives cells of about 1.2km by 0.6km. A 5km radius spans about 9 to 16 cells at this precision. We compute the 8 neighboring cells using a geohash neighbor algorithm — a well-known function that returns the geohash strings of all adjacent cells. We then query all 9 to 16 cells from Redis, merge the results, filter by availability and distance, and return the top N. The total number of Redis GET calls is 9 to 16, which is very fast — under 2ms total."))

    # SECTION 4: Deep Dive — Spatial Indexing, Proximity Search, ETA (~8 min)
    lines.append(("interviewer", "Let's deep dive into the spatial index and how you handle high write throughput."))

    lines.append(("candidate", "The write path is the bottleneck — 600K location updates per second. Let me walk through the optimization. First, we batch updates at the connection level. The Location Update Service buffers updates for 100 milliseconds — accumulating maybe 60K updates per batch — and writes them in a pipeline. Redis pipelining sends multiple commands in a single round-trip, reducing the per-command overhead from about 50 microseconds to about 5 microseconds. With a cluster of 15 to 20 nodes partitioned by geohash prefix, each node handles about 60 to 80K commands per second, which is within Redis's capability of about 100K commands per second for simple operations. The pipelining is done per partition — each Update Service instance pipelines commands for the partitions it's responsible for."))

    lines.append(("candidate", "But I realize there's a problem with my partitioning scheme. If we partition by geohash prefix, the Update Service needs to route each update to the correct Redis node based on the driver's current geohash. But the remove-from-old-cell command goes to one node and the add-to-new-cell command might go to a different node if the driver crossed a partition boundary. These two operations need to be atomic — otherwise, a driver might appear in two cells or in no cells momentarily. This is a distributed transaction problem."))

    lines.append(("candidate", "Let me reconsider. Instead of partitioning by geohash, I could partition by driver ID using consistent hashing. Then each driver's current cell membership is stored on their assigned node. A spatial query needs to scan all nodes, which is slower but avoids the atomicity problem. At 1M queries per second, each querying 15 nodes, that is 15M node queries per second — each node handles about 1M queries per second. That's too much. OK, this approach does not work for our read scale."))

    lines.append(("candidate", "Let me go back to geohash partitioning and solve the atomicity problem differently. Instead of storing cell membership in Redis sorted sets that need atomic remove-and-add, I can use a different data model. For each driver, I store their current geohash cell in a Redis hash keyed by driver ID. This is a single-key update on a single node — no cross-node atomicity needed. For the spatial index, I maintain a reverse index: for each geohash cell, I store a set of driver IDs. But this reverse index is eventually consistent — it's updated asynchronously. The write path is: update the driver's location hash (strongly consistent, single key) and publish an event to a Kafka topic. A consumer reads these events and maintains the reverse geohash index. The reverse index might be a few hundred milliseconds behind, but for nearby search, that's acceptable. A driver who just moved is at most 500ms stale, which at 60km/h is about 8 meters of position error."))

    lines.append(("candidate", "Wait, let me think about whether eventual consistency in the spatial index causes correctness problems. A rider searches for nearby drivers and gets a result based on a slightly stale index. A driver might appear who has since moved 8 meters away — negligible. A driver might be missing if they just entered the area and the index has not been updated — also rare and acceptable. The real problem is if a driver who has become unavailable is still showing as available. But availability is a separate flag stored in the driver's hash — the search service reads availability from the consistent hash, not from the spatial index. So the spatial index only provides the candidate set, and the search service does a consistent read of each candidate's current status. This hybrid approach gives us the best of both worlds: fast spatial queries with eventual consistency for the index, and strong consistency for availability and exact location."))

    lines.append(("interviewer", "That's a clever split. Now let's talk about ETA estimation."))

    lines.append(("candidate", "For straight-line ETA, we compute the Haversine distance between the rider and each nearby driver, divide by an assumed average speed — say 30 km/h in urban areas — and add a fixed pickup overhead of 3 to 5 minutes. This gives a rough estimate. The problem is that straight-line distance is a poor proxy for driving time, especially in cities with rivers, highways, and one-way streets. A driver 2km away by straight line might be 8km away by road."))

    lines.append(("candidate", "For production-quality ETAs, we would integrate a routing engine. The integration pattern is: the Nearby Search Service returns the top 20 candidates based on straight-line distance. Then an ETA Service calls an external routing API — like OSRM or Google Maps Distance Matrix — for each candidate in parallel. The routing API returns the actual driving distance and estimated time. We sort by driving time instead of straight-line distance and return the results. The routing API call takes 50 to 200ms, which adds latency to the search. To mitigate, we cache routing results for common origin-destination pairs — two locations that are 2km apart have a driving time that doesn't change much minute to minute. With a TTL of 5 minutes on the routing cache, most ETA lookups are cache hits. The cache hit rate depends on how many unique rider-driver pairs we see. With 1M queries per second and maybe 100K unique location combinations, the cache is about 100K entries at 100 bytes each — 10 MB. High hit rate."))

    lines.append(("interviewer", "How does the real-time tracking work during a trip?"))

    lines.append(("candidate", "During a trip, the rider's app subscribes to the driver's location updates via WebSocket. The driver continues sending location updates every 5 seconds to the Location Update Service. The Update Service publishes these updates to a Redis pub/sub channel keyed by the driver's ID. The rider's Connection Server subscribes to this channel and pushes updates to the rider's app. This is a direct pub/sub path — no spatial index lookup needed. The latency is just the WebSocket round-trip plus pub/sub propagation, typically under 200ms. For privacy, the rider only gets location updates during the trip — the pub/sub subscription is time-bounded and revoked when the trip ends."))

    lines.append(("candidate", "One subtlety: during a trip, the driver might enter a tunnel or area with poor GPS. The app should continue sending the last known location with a decreasing accuracy radius, rather than silently dropping updates. The rider's app can display a low-accuracy indicator. When GPS recovers, the app sends a rapid burst of updates to catch up. The Location Update Service handles this gracefully — it always accepts the latest update and discards stale ones based on timestamps."))

    lines.append(("interviewer", "Let's talk about the geofence implementation in more detail. How do you handle the enter and exit events?"))

    lines.append(("candidate", "Geofence events require state — we need to know whether a driver was previously inside or outside a geofence to detect transitions. We maintain a per-driver geofence membership set in Redis: a set of geofence IDs that the driver is currently inside. When a location update arrives, we compute which geofences the driver is now inside. We compare with the stored set. If a geofence appears in the new set but not the old one, that's an enter event. If it disappears from the new set but was in the old one, that's an exit event. We publish these events to a Kafka topic for downstream consumers — like the dispatch system, which might use airport zone entry to add the driver to the airport queue. The membership set update and the event publication happen in a Lua script on Redis, which is atomic, preventing duplicate events."))

    # SECTION 5: Failure Modes (~4 min)
    lines.append(("interviewer", "What are the most critical failure scenarios?"))

    lines.append(("candidate", "The first is a Redis node failure in the spatial index. If a node holding geohash cells for, say, lower Manhattan goes down, all nearby searches in that area return empty results until the node recovers or a replica takes over. With Redis Cluster and replication, failover takes about 15 to 30 seconds. During that window, searches in the affected area fail. We mitigate with application-level fallback: if the spatial index is unavailable for a region, we fall back to a full scan of the driver hash table — slower but still functional. We also over-replicate hot urban nodes — instead of one replica, we might have two or three for areas like Manhattan and San Francisco."))

    lines.append(("candidate", "The second scenario is a location update flood. If GPS glitches cause all 3M drivers to send rapid updates simultaneously — say every 100ms instead of every 5 seconds — the write throughput spikes from 600K to 30M updates per second. The system would be overwhelmed. We mitigate with client-side rate limiting: the driver app never sends updates more frequently than every 3 seconds. The server also enforces a per-driver rate limit — if more than one update per second is received, the excess is dropped. This is a simple defense that prevents GPS glitch cascades."))

    lines.append(("candidate", "The third scenario is stale location data. If a driver's phone dies or loses network, their last location stays in the index. We use the timestamp in the sorted set to expire stale entries — any driver who has not updated in 30 seconds is removed from the spatial index. A background job runs every 10 seconds to clean up expired entries. This is cheap — just a ZREMRANGEBYSCORE on each cell sorted set to remove entries with scores below the 30-second threshold."))

    lines.append(("candidate", "The fourth scenario is an ETA Service outage. If the routing engine is down, we fall back to straight-line ETAs. This is a graceful degradation — riders get less accurate ETAs but can still see and request nearby drivers. We alert the operations team and retry the routing engine with exponential backoff. We also pre-compute ETAs for the most popular routes during off-peak hours and cache them, which provides some coverage even during a routing engine outage."))

    # SECTION 6: Scale & Debrief (~3 min)
    lines.append(("interviewer", "How does the design change at 10x scale — 30M drivers, 10M queries per second?"))

    lines.append(("candidate", "At 10x scale, the write throughput hits 6M updates per second and reads hit 10M queries per second. The Redis cluster needs 50 to 100 nodes. The spatial index needs more aggressive sharding — maybe using a two-level geohash scheme where we first route by a coarse geohash prefix to a shard group, then within the group by a finer prefix. The ETA Service becomes a bigger bottleneck — 10M routing API calls per second would overwhelm any external provider. We would need to run our own OSRM instances with pre-loaded map data, giving us unlimited query capacity. We would also need to spatially partition the OSRM instances — one instance per major metropolitan area — to keep the road network in memory for each region."))

    lines.append(("candidate", "At 0.1x scale — 300K drivers, 100K queries per second — the design simplifies. A single Redis instance with a replica handles the spatial index. No partitioning needed. The Location Update Service is a single process. The ETA Service can call an external routing API without caching — 100K calls per second is within Google Maps API limits with an enterprise plan. The tracking service uses a single pub/sub channel. But the core spatial indexing approach — geohash cells with sorted sets — stays the same. It just runs on fewer machines."))

    lines.append(("interviewer", "Let me give you feedback. Positives: excellent requirements clarification — you asked about accuracy tolerance, availability filtering, real-time tracking frequency, and road-aware ETAs unprompted. Your analysis of the partitioning trade-off between space-based and entity-based sharding was thorough and honest. The hybrid consistency model — eventual consistency for the spatial index with strong consistency for driver status — is a sophisticated and practical solution to the atomicity problem. Your self-corrections were natural and well-reasoned. For improvement: when discussing the eventual consistency approach for the spatial index, you should have quantified the impact more precisely — exactly how many milliseconds of staleness and how many meters of position error, and whether that could cause a rider to be matched with a driver who has already left the area. Also, you did not discuss how to handle the geohash boundary problem in detail — near the boundary of a 5km search, drivers in adjacent cells that are just beyond 5km need to be filtered out, and you should have described the Haversine distance computation used for this filtering. Overall, very strong. Thanks."))

    lines.append(("candidate", "Thanks for the feedback. On the staleness quantification — with a 500ms index update lag and a driver moving at 60km/h, the position error is about 8 meters. That's well within the GPS accuracy of 3 to 5 meters, so the staleness error is dominated by GPS inaccuracy. For the boundary filtering — yes, I should have explicitly described the Haversine computation step that runs after the geohash candidate retrieval, filtering out drivers beyond the exact 5km radius. It's O(N) where N is the number of candidates from the geohash cells, typically 50 to 200, so it's fast. Good points."))

    return lines
