"""Mock Interview: Low-Latency FX Pricing System — Two-voice dialogue."""


def build():
    lines = []

    # SECTION 1: Requirements
    lines.append(("interviewer", "Hi, welcome. Today I'd like you to design a low-latency FX pricing system. Think of it as the engine behind a product like Optimize three-sixty — clients need sub-one-hundred-millisecond decision latency, and they need to see live prices streaming in real time. Start by clarifying the requirements."))

    lines.append(("candidate", "Thanks. This is fundamentally different from a generic FX rate engine because we're talking about market data, not just rate serving. Let me ask the critical questions. First, what's the client interface? Are we serving REST API queries — give me the current rate for AUD slash USD — or are we streaming live prices via WebSocket — here's every rate update as it happens? Or both?"))

    lines.append(("interviewer", "Both. The API serves on-demand rate queries for payment processing — the payment service needs a rate to lock a quote. The WebSocket stream serves live prices to the client application — traders and treasury dashboards that need to see rates ticking in real time."))

    lines.append(("candidate", "OK, so two distinct serving patterns with different latency requirements. The REST path — for payment processing — needs sub-fifty-millisecond latency because it's in the critical path of a payment that already has bank API latency to contend with. The WebSocket path needs sub-one-hundred-millisecond end-to-end — from the rate provider publishing an update to the client seeing it on screen. Next question: how many currency pairs and how many rate providers?"))

    lines.append(("interviewer", "Fifty major currency pairs. We integrate with three rate providers — Reuters, Bloomberg, and an ECN. Each provider sends updates at different frequencies — Reuters about every two hundred milliseconds for major pairs, Bloomberg about every three hundred milliseconds, and the ECN about every one hundred milliseconds during active trading."))

    lines.append(("candidate", "So worst case, for a single pair like EUR slash USD, we could get an update every hundred milliseconds from the ECN, every two hundred from Reuters, every three hundred from Bloomberg — that's about fifteen updates per second per pair. For fifty pairs, that's about seven hundred and fifty updates per second at peak. But during market open events or news releases, it can spike to ten times that — seven thousand five hundred updates per second. How many concurrent WebSocket clients?"))

    lines.append(("interviewer", "Up to five thousand concurrent WebSocket connections. Each client subscribes to an average of ten currency pairs."))

    lines.append(("candidate", "Five thousand clients, each subscribed to ten pairs. When a rate update comes in for EUR slash USD, we need to fan it out to every client subscribed to that pair. If, say, two thousand clients subscribe to EUR slash USD, a single rate update generates two thousand WebSocket pushes. At fifteen updates per second for that pair, that's thirty thousand WebSocket writes per second for just one pair. Across all pairs, we're looking at maybe one hundred thousand to two hundred thousand WebSocket writes per second at peak. Let me summarize: three rate providers, fifty pairs, up to seven thousand five hundred updates per second at peak, five thousand concurrent WebSocket clients, sub-one-hundred-millisecond end-to-end latency, and a REST API for payment processing at sub-fifty-millisecond latency. Moving to estimation."))

    # SECTION 2: Estimation
    lines.append(("interviewer", "Go ahead."))

    lines.append(("candidate", "Data volume: each rate update is about two hundred bytes — currency pair, bid, ask, timestamp, provider ID. At seven hundred and fifty updates per second, that's one hundred and fifty kilobytes per second of ingestion, or about thirteen gigabytes per day. At peak — seven thousand five hundred updates per second — that's one point five megabytes per second. Storage for audit: we keep every rate update for seven years. Thirteen gigabytes per day times three hundred and sixty-five days times seven years is about thirty-three terabytes. We'd compress this — financial time series data compresses about ten to one — so about three point three terabytes in cold storage. The hot path only keeps the latest rate per pair in Redis, which is fifty pairs times two hundred bytes — ten kilobytes. Negligible."))

    lines.append(("candidate", "WebSocket bandwidth: each push to a client is about one hundred bytes — the rate update without the provider ID. At two hundred thousand pushes per second, that's twenty megabytes per second outbound. With five thousand clients, each receiving updates for ten pairs at maybe five updates per second per pair, the average per client is about fifty updates per second — five kilobytes per second per client. Total: about twenty-five megabytes per second outbound. Well within a ten-gigabit link."))

    lines.append(("candidate", "The latency budget is the most critical estimation. Let me break down the sub-one-hundred-millisecond end-to-end requirement. Provider sends update: zero — the clock starts when we receive it. Ingestion into Kafka: about five milliseconds. Aggregator consumes and computes best bid slash ask: about ten milliseconds. Write to Redis: about two milliseconds. Publish to Redis pub-slash-sub: about one millisecond. WebSocket server receives pub-slash-sub message: about one millisecond. Serialize and push to client: about three milliseconds. Network to client: about five to twenty milliseconds depending on location. Total: about twenty-seven to forty-two milliseconds. That leaves about fifty-eight to seventy-three milliseconds of margin. Tight but achievable if we optimize every step."))

    # SECTION 3: High-Level Architecture
    lines.append(("interviewer", "Let's see the architecture."))

    lines.append(("candidate", "Here's the design. The ingestion layer: three WebSocket connections to our rate providers, one per provider. Each connection receives a stream of rate updates. We validate each update — is the rate within a reasonable range? Is the timestamp recent? — and publish it to a Kafka topic, one topic per provider. This gives us durability — if the aggregator crashes, it can re-consume from Kafka without losing updates."))

    lines.append(("candidate", "The aggregation layer: a Kafka Streams or Flink job that consumes from all three provider topics, groups updates by currency pair, and computes the best bid and best ask across providers. For each pair, the aggregator maintains a sliding window of recent updates — say, the last five hundred milliseconds — and takes the best bid and best ask from that window. The output is a single canonical rate per pair, published to a canonical-rates Kafka topic and written to Redis."))

    lines.append(("candidate", "The serving layer has two paths. Path one: the REST API. A client requests a quote for EUR slash USD. The service reads the canonical rate from Redis — a single GET, about half a millisecond — and returns it. Path two: the WebSocket stream. Clients connect to the WebSocket gateway and subscribe to specific pairs. The gateway subscribes to a Redis pub-slash-sub channel for rate updates. When the aggregator publishes a new canonical rate, the Redis pub-slash-sub fans it out to all WebSocket gateway instances. Each gateway pushes the update to its connected clients that are subscribed to that pair."))

    lines.append(("interviewer", "Why Redis pub-slash-sub and not Kafka for the WebSocket fan-out?"))

    lines.append(("candidate", "Latency. Kafka is designed for durability and exactly-once delivery, but it adds about five to ten milliseconds of end-to-end latency — produce, consume, process. Redis pub-slash-sub is fire-and-forget with sub-millisecond latency. We don't need durability for the WebSocket push — if a client misses an update because of a network glitch, the next update will arrive in a hundred milliseconds anyway. And we already have the canonical rate in Redis for the REST API path, so the pub-slash-sub is essentially free. We use Kafka for the ingestion and aggregation pipeline where durability matters, and Redis pub-slash-sub for the last-mile push where latency matters."))

    # SECTION 4: Deep Dive — Price Aggregation
    lines.append(("interviewer", "Let's deep dive into the price aggregation logic. How exactly do you compute the best bid and best ask?"))

    lines.append(("candidate", "The aggregator maintains a rate table for each currency pair. For EUR slash USD, the table has three rows — one per provider. Each row has the latest bid and ask from that provider, along with the timestamp and the provider's name. When a new update arrives, the aggregator updates the corresponding row. Then it scans all rows to find the highest bid and the lowest ask — that's the best executable price for the client. The spread between best bid and best ask is the tightest available price."))

    lines.append(("candidate", "But there's a subtlety. What if Reuters sends a bid of one point zero eight five zero at time T, and then Reuters sends a new bid of one point zero eight four zero at time T plus five hundred milliseconds — a worse price? The aggregator should use the latest bid from each provider, not the best historical bid. So the rate table always reflects the current state, not the best-ever state. But what about stale rates? If Reuters hasn't sent an update for two seconds — which is unusual since they usually update every two hundred milliseconds — their rate might be stale. The aggregator marks any rate older than five hundred milliseconds as indicative, not tradeable. The canonical rate includes a status flag: tradeable if at least one provider has a fresh bid and ask, indicative if all providers are stale."))

    lines.append(("interviewer", "Why does the indicative versus tradeable distinction matter?"))

    lines.append(("candidate", "Because a tradeable rate is one we're willing to lock for a client. If a client requests a quote and the rate is tradeable, we lock it for thirty seconds and guarantee that price. If the rate is indicative, we show it in the dashboard with a visual indicator — maybe a yellow badge — but we won't lock it for a quote. The client would need to wait for a fresh rate. This protects us from locking a stale rate that might have moved significantly — the FX risk would be on us. This is the same principle I'd mention in the interview: never serve a rate without a freshness check, and never lock a rate without a TTL."))

    # SECTION 5: Deep Dive — WebSocket Scaling
    lines.append(("interviewer", "How do you scale the WebSocket layer to five thousand concurrent connections?"))

    lines.append(("candidate", "Five thousand connections is actually modest for a single WebSocket server — a Node dot js or Go server can handle fifty to one hundred thousand concurrent connections on a single machine. But for high availability and zero-downtime deployments, we'd run multiple instances behind a load balancer. The key challenge is connection routing. When a client subscribes to EUR slash USD, which WebSocket server instance should they connect to?"))

    lines.append(("candidate", "There are two approaches. Approach one: any server can serve any subscription. Each server subscribes to all Redis pub-slash-sub channels, so it receives every rate update. When a client connects, the load balancer routes to the least-loaded server. The server tracks which clients are subscribed to which pairs and pushes updates accordingly. This is simple but means every server receives all updates — at two hundred thousand pushes per second across all pairs, each server processes all two hundred thousand, even if most of its clients don't subscribe to most pairs. Wasteful but manageable."))

    lines.append(("candidate", "Approach two: subscription-based routing. The load balancer uses sticky sessions based on the client's subscription list. Clients subscribing to the same pairs are routed to the same server. Each server only subscribes to the Redis pub-slash-sub channels for the pairs its clients care about. This reduces per-server load dramatically. But it's more complex — when a client adds or removes a subscription, the server needs to dynamically update its Redis subscriptions, and if the server has no clients subscribed to a pair, it unsubscribes to save resources."))

    lines.append(("candidate", "I'd use approach one for simplicity at this scale. Five thousand clients and two hundred thousand pushes per second is well within one server's capacity. I'd run three servers for redundancy and blue-green deployments. Each server subscribes to all channels. The load balancer uses least-connections routing. If we scale to fifty thousand clients, then approach two becomes necessary."))

    lines.append(("interviewer", "What about backpressure? During a market shock, rate updates can spike ten times. How do you handle that?"))

    lines.append(("candidate", "Backpressure is the defining challenge of a low-latency streaming system. During a market shock — say, a central bank surprise announcement — rate updates spike from seven hundred and fifty per second to seven thousand five hundred per second. The WebSocket push volume goes from two hundred thousand per second to two million per second. If we try to push every update to every client, we'll overwhelm both the servers and the clients' browsers. The solution: rate limiting at the fan-out layer."))

    lines.append(("candidate", "Here's the strategy. For each currency pair, we define a minimum update interval — say, one hundred milliseconds. If three updates arrive for EUR slash USD within one hundred milliseconds, we only push the latest one. The client sees the most recent price, just not every intermediate tick. This is called throttling, and it's what every real trading platform does. During normal operation, updates arrive every two hundred to three hundred milliseconds per pair, so throttling has no effect. During a spike, it caps the push rate to ten per second per pair, regardless of how fast the providers are sending. For fifty pairs, that's five hundred pushes per second per client — manageable. Without throttling, a spike could generate over one hundred pushes per second per pair — five thousand per client per second — which would overwhelm the browser's rendering."))

    lines.append(("candidate", "There's also server-side backpressure. If the Kafka consumer falls behind — the lag exceeds one thousand messages — the aggregator switches to a sampling mode instead of processing every update. It skips intermediate updates and only processes the latest one per pair. This reduces the aggregation workload while still producing the freshest rates. The lag indicator is exposed as a metric — if it's above zero, we're in backpressure mode and the rates might be slightly stale, so they get the indicative flag."))

    # SECTION 6: Failure Modes
    lines.append(("interviewer", "What happens when a rate provider goes down?"))

    lines.append(("candidate", "Provider failover is automatic. The ingestion layer monitors the WebSocket connection to each provider. If the connection drops — no messages for two seconds — it attempts to reconnect. During the reconnection period, the aggregator continues using the last known rate from that provider, but it marks it as stale after five hundred milliseconds without a fresh update. The canonical rate is computed from the remaining live providers. With three providers, losing one means we still have two — the best bid and best ask might widen slightly because we have less competition, but the rates are still tradeable."))

    lines.append(("candidate", "If two providers go down simultaneously, we're down to one. The canonical rate comes from a single source, and the spread might widen significantly — that single provider might quote a wider spread knowing there's no competition. We'd flag the rate as indicative if only one provider is live, requiring manual confirmation for large trades. If all three providers go down — extremely unlikely — we stop serving live rates entirely. The dashboard shows the last known rates with a prominent stale indicator, and the quote API returns an error: rates currently unavailable, try again in a few seconds. We never serve a rate that we can't verify is fresh."))

    lines.append(("interviewer", "What if Redis goes down?"))

    lines.append(("candidate", "Redis is the critical path — both the REST API and the WebSocket push depend on it. If Redis goes down, the REST API can't serve rates, and the pub-slash-sub stops pushing updates. The mitigation: Redis Sentinel or Redis Cluster with automatic failover. Redis Sentinel monitors the master and promotes a replica within about ten to thirty seconds. During those thirty seconds, the REST API falls back to reading from a local in-memory cache of the last known rates — each application server maintains a small in-memory cache updated from Kafka. The rates might be slightly stale — up to a few seconds — but they're better than nothing. The WebSocket stream pauses during the failover and resumes automatically when the new Redis master is available."))

    lines.append(("candidate", "But for a fintech pricing system, even thirty seconds of stale rates is concerning. An alternative design eliminates Redis from the hot path entirely: the aggregator writes the canonical rate directly to each WebSocket server via a dedicated gRPC stream. The WebSocket servers maintain an in-memory rate table updated by the gRPC stream. The REST API reads from this in-memory table too. This removes Redis as a dependency for the serving path. Redis is still used for rate locking — when a client locks a quote, we write the locked rate to Redis — but that's not latency-critical. The trade-off: we lose the simplicity of Redis pub-slash-sub and must manage our own fan-out, but we gain resilience against Redis failures."))

    # SECTION 7: E2E Walkthrough
    lines.append(("interviewer", "Walk me through the end-to-end flow for a rate update from Reuters to a client dashboard."))

    lines.append(("candidate", "Step one: Reuters sends an update for EUR slash USD — bid one point zero eight five zero, ask one point zero eight five two — over their WebSocket connection. The ingestion service receives it, validates the range and timestamp, and publishes it to the Kafka topic rates-dot-reuters. Ingestion latency: about five milliseconds. Step two: the aggregator consumes the update from Kafka. It updates the Reuters row in the EUR slash USD rate table. It recomputes the best bid and best ask across all providers. Let's say Reuters has the best bid and Bloomberg has the best ask. The canonical rate is bid one point zero eight five zero, ask one point zero eight four eight — note the crossed spread between providers, which is normal and represents an arbitrage opportunity in the market. The aggregator writes the canonical rate to Redis with a one-second TTL and publishes it to the Redis pub-slash-sub channel rates-colon-EUR-slash-USD. Aggregation latency: about ten milliseconds. Step three: the WebSocket server receives the pub-slash-sub message. It looks up which of its connected clients are subscribed to EUR slash USD — say, eight hundred clients on this server. It serializes the rate update as JSON and pushes it to all eight hundred WebSocket connections. Fan-out latency: about three milliseconds. Step four: the update travels over the internet to the client's browser — about five to twenty milliseconds depending on location. The browser receives it and updates the dashboard. Total: about twenty-three to thirty-eight milliseconds. Well within the sub-one-hundred-millisecond target."))

    lines.append(("candidate", "Let me repeat the killer phrases for this topic because they need to become automatic. One: sub-one-hundred-millisecond end-to-end means the latency budget is tight — every millisecond counts. Two: best bid across providers, best ask across providers — that's the canonical rate. Three: stale rates get the indicative flag, never lock an indicative rate. Four: throttle the WebSocket fan-out to ten updates per second per pair during spikes — that's the backpressure strategy. Five: Redis pub-slash-sub for sub-millisecond last-mile push, Kafka for durable ingestion — use the right tool for the right job. And six: if all providers are down, show stale rates with a prominent indicator, but never serve a rate you can't verify as fresh."))

    # SECTION 8: Auditing and Compliance for Rate Data
    lines.append(("interviewer", "One more thing: regulators require you to prove what rate you quoted at any given moment. How do you handle that?"))

    lines.append(("candidate", "This is a requirement that catches people off guard. When a customer disputes a payment — saying the rate we applied was different from what they saw on screen — we need to prove exactly what rate was displayed at that specific timestamp. The audit trail for rate data is critical. We store every canonical rate update in a time-series database — InfluxDB or TimescaleDB — with the currency pair, best bid, best ask, the contributing providers and their individual rates, and the timestamp to millisecond precision. When a dispute comes in, we query: what was the canonical rate for EUR slash USD at two-oh-two-four-oh-seven-fifteen-ten-thirty-four-point-five-six-seven UTC? The query returns the exact rate that was live at that moment, along with which providers contributed and their individual quotes."))

    lines.append(("candidate", "The storage for this audit trail is significant but manageable. About seven hundred and fifty updates per second times eighty-six thousand seconds per day is about sixty-five million rate snapshots per day. At two hundred bytes each, that's about thirteen gigabytes per day. Over seven years, about thirty-three terabytes. With time-series compression — which achieves about ten to one for financial data — that's about three point three terabytes. We'd keep the last ninety days in hot storage on SSD for fast queries, and older data in cold storage on object storage for compliance lookups. The compliance team queries this database maybe ten to twenty times per day — it's not high-throughput, but it must be accurate and fast for the query pattern: rate for a specific pair at a specific timestamp."))

    lines.append(("candidate", "The rate audit trail also serves another purpose: detecting anomalies. If the canonical rate for a pair suddenly jumps by more than two percent between consecutive updates, we trigger an alert. This could indicate a provider sending bad data, a configuration error in the aggregator, or a genuine market event. In all cases, the operations team needs to investigate immediately. The audit trail shows exactly what happened — which provider sent the anomalous rate, when it was received, and whether it was included in the canonical rate."))

    # SECTION 9: Complete Latency Budget Breakdown
    lines.append(("interviewer", "Give me the complete latency budget breakdown one more time, with specific numbers for each component."))

    lines.append(("candidate", "Here's the budget for the WebSocket streaming path, which is the most demanding. Rate provider sends update over WebSocket: zero — this is the starting point. Ingestion service receives and validates: two milliseconds. Publish to Kafka: three milliseconds — includes batching and broker acknowledgment. Aggregator consumes from Kafka: five milliseconds. Compute best bid slash ask across providers: two milliseconds. Write canonical rate to Redis: one millisecond. Publish to Redis pub-slash-sub: one millisecond. WebSocket server receives pub-slash-sub message: one millisecond. Look up subscribed clients: one millisecond. Serialize and push to client WebSocket connections: three milliseconds. Network transit to client browser: five to twenty milliseconds depending on location and connection quality. Browser receives and renders: five milliseconds. Total: twenty-five to forty-five milliseconds. Our budget is one hundred milliseconds, so we have fifty-five to seventy-five milliseconds of margin. This margin is important because every component adds variance — p ninety-nine latency is typically two to three times the median. So if the median is thirty-five milliseconds, p ninety-nine might be seventy to one hundred milliseconds — right at our budget."))

    lines.append(("candidate", "For the REST API path — used by the payment service for rate quotes — the budget is simpler. Read from Redis: one millisecond. Add rate-lock metadata: one millisecond. Serialize response: one millisecond. Network to payment service: two milliseconds — internal data center. Total: about five milliseconds. This is well within the sub-fifty-millisecond requirement. The critical optimization here is that the REST path reads from the same Redis that the aggregator writes to, so the rate is always fresh — no additional pipeline to traverse."))

    lines.append(("candidate", "The latency budget is a phrase you should practice saying out loud. In the interview, draw it on the whiteboard or Whimsical as a timeline: provider, ingestion, Kafka, aggregation, Redis, pub-slash-sub, WebSocket, network, browser. Each step with its millisecond number. This shows the interviewer that you understand where time goes and where to optimize. The biggest optimization opportunities are reducing the Kafka hop — maybe using a direct gRPC stream from ingestion to aggregation — and reducing the serialization overhead in the WebSocket push. But only optimize if the current budget isn't met — premature optimization is wasted effort."))

    return lines
