"""Mock Interview: Metrics/Monitoring Pipeline — Two-voice dialogue."""


def build():
    lines = []

    # SECTION 1: Requirements (~5 min)
    lines.append(("interviewer", "Hi, welcome. Today I'd like you to design a metrics and monitoring pipeline — the kind of observability platform that an organization like Airwallex would run to keep their payment infrastructure healthy. Think Prometheus, Grafana, alerting, the works. Start by clarifying the requirements."))

    lines.append(("candidate", "Thanks. Let me start with the fundamentals. What are we monitoring — infrastructure metrics like CPU and memory, application metrics like request latency and error rates, or business metrics like payment success rates? Because the data model and cardinality are very different. Infrastructure metrics are low-cardinality — a server has a fixed set of labels. Application metrics can have medium cardinality — method, endpoint, status code. Business metrics can be extremely high-cardinality — merchant_id, currency_pair, transaction_type."))

    lines.append(("interviewer", "All of the above. We have roughly 10,000 services across multiple regions. We need infrastructure metrics, application metrics, and business metrics. We also need to support the three pillars of observability — metrics, logs, and traces — though today we'll focus primarily on the metrics pillar with some discussion of how it integrates with logs and traces. The three pillars are all essential for a complete observability picture."))

    lines.append(("candidate", "10,000 services is a serious scale. Let me ask about the metrics model. Are we talking about the Prometheus model — metric name plus labels, pull-based collection — or the StatsD model — push-based with dot-separated names? Or do we need to support both ingestion patterns? Because the collection architecture is fundamentally different — pull means the monitoring system reaches out to services on a schedule, push means services emit data to the monitoring system as events occur."))

    lines.append(("interviewer", "We need both. Existing services use Prometheus-style pull scraping, but newer services and serverless functions prefer push-based emission via a StatsD-compatible interface. We need a unified backend that ingests both."))

    lines.append(("candidate", "Common reality. Next question: cardinality. With 10,000 services, each potentially exposing metrics with labels like user_id, tenant_id, or region, we could hit millions of unique time series. What cardinality are we designing for, and do we need to enforce limits at ingestion?"))

    lines.append(("interviewer", "Great question. We need to support millions of time series — let's say 10 million active time series at any given time. And yes, we need cardinality controls — unbounded labels are a real operational hazard. We need to detect and limit cardinality explosions at ingestion time, not after storage is already bloated."))

    lines.append(("candidate", "One more question: alerting. What's the alerting model? Simple threshold alerts — CPU above 80 percent — or SLO-based alerting with burn rate windows? And how should alerts integrate with incident management — PagerDuty, Slack, custom workflows?"))

    lines.append(("interviewer", "We need SLO-based alerting as the primary model, with threshold alerts as a fallback. The golden signals — latency, traffic, errors, saturation — should drive alerting. Multi-window, multi-burn-rate alerts are the target. Integration with PagerDuty and Slack is required."))

    lines.append(("candidate", "Let me summarize. We're designing a metrics and monitoring pipeline for 10,000 services across multiple regions. Support both Prometheus pull and StatsD push ingestion. 10 million active time series. Three pillars of observability — metrics first, with integration points for logs and traces. Time-series data model with metric name, labels, timestamp, and value. Cardinality controls at ingestion. SLO-based alerting with multi-window burn rates, plus threshold fallback. PagerDuty and Slack integration. Let me move to estimation."))

    # SECTION 2: Estimation (~5 min)
    lines.append(("interviewer", "Go ahead."))

    lines.append(("candidate", "Let me work through the numbers. 10 million active time series at an average scrape interval of 15 seconds — the Prometheus default, with some services at 5 seconds and batch jobs at 60 seconds. So 10 million times 1 per 15 seconds gives us about 667,000 data points per second. At peak with 1.5x headroom, that's about 1 million data points per second. Each data point — metric name, labels, timestamp, value — is about 200 bytes when encoded efficiently. At 667,000 samples per second, that's roughly 133 MB per second of raw incoming data, or about 11.5 TB per day."))

    lines.append(("interviewer", "How much storage do we need for the time-series data itself?"))

    lines.append(("candidate", "We can't store raw samples forever — time-series data has a lifecycle. Retention tiers: hot — last 24 hours at full 15-second resolution. Warm — 30 days at 1-minute resolution with min, max, sum, count per downsampled bucket. Cold — 1 year at 5-minute resolution. Archive — beyond 1 year at 1-hour resolution. For hot storage: 10 million series times 4 samples per minute times 1440 minutes equals about 57.6 billion samples. With Facebook's Gorilla encoding at 1.37 bytes per timestamp-value pair, that's roughly 800 GB for 24 hours. Warm with 5 values per downsampled bucket: roughly 32 TB for 30 days. Cold: about 72 TB for a year. Archive: about 3.6 TB per year. Total across all tiers: about 110 TB, 220 TB with replication. Monthly storage cost at cloud prices — SSD for hot and warm, HDD for cold and archive — roughly 3,200 dollars. Surprisingly reasonable. The real cost is compute for ingestion, query, and alerting."))

    lines.append(("interviewer", "What about query throughput?"))

    lines.append(("candidate", "Query load estimate: 500 active Grafana dashboards refreshing every 30 seconds, each querying 20 series — about 333 QPS for dashboards alone. Ad-hoc debugging queries: another 100 QPS. Alert evaluation is the hidden load — 5,000 rules evaluating every 30 seconds adds about 167 evaluations per second. Total: roughly 600 QPS. Each query touches 1 to 10,000 series depending on label selectors, averaging 50 — so 30,000 series lookups per second."))

    # SECTION 3: High-Level Architecture (~5 min)
    lines.append(("interviewer", "Good numbers. Let's move to the high-level architecture."))

    lines.append(("candidate", "The architecture has four layers: collection, ingestion, storage, and consumption. The collection layer has two paths. Path 1: Prometheus-style pull — scrapers discover targets via service discovery and forward samples via remote write. Path 2: StatsD-style push — services emit to a local sidecar agent that aggregates and flushes periodically. Both paths converge at the ingestion layer. The pull model is great for long-running services with stable endpoints — the scraper controls the sampling rate and can detect when a target is down. The push model is better for short-lived processes like serverless functions or batch jobs that might exit before the next scrape interval."))

    lines.append(("candidate", "Ingestion is the unified entry point: protocol translation for both remote write and StatsD, validation of metric names and labels, cardinality enforcement per service, and write forwarding to storage. It's stateless and horizontally scalable — add more ingest nodes behind a load balancer to handle higher throughput."))

    lines.append(("interviewer", "How does the ingestion layer handle cardinality enforcement?"))

    lines.append(("candidate", "Each service has a cardinality budget — say 10,000 active series. The ingestion layer maintains a cardinality tracker that counts distinct label combinations per metric per service. When a new series would exceed the budget, the high-cardinality label is collapsed — for example, if a service starts emitting http_request_duration_seconds with user_id as a label creating 100,000 unique series, the tracker detects this, keeps the top 9,999 by frequency, and collapses the rest into user_id equals __other__. This preserves the overall distribution while bounding cardinality. Top-K tracking uses a Count-Min Sketch for approximate frequency estimates with bounded memory. The tracker has a TTL so stale series naturally expire."))

    lines.append(("candidate", "Storage is a time-series-optimized columnar engine. Data is organized into immutable chunks covering 2-hour windows — one column for timestamps, one for values, plus an inverted index mapping label combinations to series IDs. Closed chunks are compressed and moved to the appropriate retention tier. Immutability is important — we never update written data, eliminating concurrency issues and enabling efficient compression since chunks are write-once-read-many. The consumption layer has three components: the query engine for PromQL execution against stored data, the alert manager for rule evaluation and notification, and the recording rule engine that continuously pre-computes derived metrics — like aggregating request latency across all instances of a service — to speed up dashboards and alerts. Recording rules are essentially cached queries that write their results back as new time series."))

    lines.append(("interviewer", "How do the three pillars — metrics, logs, and traces — integrate?"))

    lines.append(("candidate", "Integration happens through correlation IDs. Every request carries a trace ID that propagates through all services via context headers. Error metrics include the trace_id label so you can jump from an error rate spike to the specific failed traces. Logs are also tagged with trace_id. The workflow: see a spike on a Grafana dashboard, click through to traces via the trace_id label, find the slow span, click into logs for that span. This is the observability triangle — metrics tell you there's a problem, traces show you where, logs tell you why."))

    lines.append(("candidate", "For the logs pillar we'd use ELK or a modern alternative like Loki, which indexes only labels and stores log bodies compressed — much cheaper at scale. For traces, Jaeger or Tempo with the OpenTelemetry SDK. All three backends share the same label taxonomy — service, environment, region, trace_id — with Grafana as the unified query surface through its data source plugins."))

    lines.append(("candidate", "One more architectural point — the Kappa architecture perspective. In observability, batch processing is just a special case of streaming. Our metrics pipeline is inherently a streaming system — samples flow in continuously and are processed in real time. The downsampling and rollup pipeline that converts hot data to warm to cold is itself a stream processor that windows and aggregates. We don't need a separate batch system for rollups — the same streaming infrastructure handles both real-time alerting and historical aggregation. This simplifies the architecture significantly compared to a Lambda approach with separate batch and stream layers. The stream processor windows data into fixed intervals — 1 minute for warm, 5 minutes for cold — computes min, max, sum, count for each window, and writes the aggregated results to the appropriate storage tier. Old raw data is then garbage-collected once the downsampled version is confirmed written."))

    # SECTION 4: Deep Dive — Time-Series Storage, Cardinality, and Alerting (~10 min)
    lines.append(("interviewer", "Let's deep dive into the three trickiest areas. Start with time-series storage."))

    lines.append(("candidate", "Time-series storage is a specialized database problem with a very specific access pattern. Writes are append-only along the time axis. Reads are range scans — give me all values for this metric with these labels between T1 and T2. The data is high-volume and time-ordered. These properties enable significant optimizations that a general-purpose database can't match."))

    lines.append(("candidate", "The core data structure is a series chunk. Each series is identified by a series ID — a hash of metric name plus sorted label pairs. Samples are stored in 2-hour chunks using Gorilla compression: timestamps are delta-of-delta encoded — the difference of differences is typically -1, 0, or 1 for regular intervals, representable in 1-2 bits. Values are XOR-encoded — consecutive values for slowly-changing metrics like CPU are mostly zeros, compressing to a few bits. Facebook's paper reports 1.37 bytes per timestamp-value pair on average — a 12x compression ratio versus 16 bytes for an uncompressed pair of 64-bit timestamp and float."))

    lines.append(("candidate", "The index is an inverted index mapping label name-value pairs to posting lists of series IDs. A query like http_request_duration_seconds{status_code equals 500, region equals APAC} intersects the posting lists for both selectors to find matching series. Posting list intersection is efficient when individual lists are small — which is the case for high-cardinality labels where each value appears in relatively few series. With 10 million series and 5 label pairs per series on average, that's 50 million posting list entries — about 2.9 GB, fitting in memory on a single machine. At 10x scale, 29 GB needs a distributed index across nodes."))

    lines.append(("interviewer", "What about the posting lists for high-cardinality labels? If we have a label with 1 million distinct values, the posting list for each value is small, but the total index is large."))

    lines.append(("candidate", "Exactly. The index size scales with the total number of label name-value pairs across all series, which is the sum of the number of labels per series times the number of series. With 10 million series and an average of 5 label pairs per series, that's 50 million posting list entries. Each entry is a series ID — 8 bytes — plus the label name-value pair — maybe 50 bytes on average — so the total index is about 2.9 GB. This fits in memory on a single machine. But at 10x scale — 100 million series — the index grows to 29 GB, which is still manageable with a distributed index across multiple nodes."))

    lines.append(("candidate", "The real problem with high-cardinality labels isn't index size — it's query performance and storage cost. A query for a specific high-cardinality value is fast — the posting list is tiny. But a query with just the metric name scans all 10 million series. And each unique label value creates a new series with its own chunk, compressed data, and posting list entries. A label with 1 million distinct values creates 1 million series at 800 bytes overhead each — 800 MB of overhead for a single metric. Multiply by several high-cardinality labels, and you get cardinality explosion. This is why we can't just add arbitrary labels — the cost compounds."))

    lines.append(("interviewer", "So how do you control cardinality in practice?"))

    lines.append(("candidate", "Cardinality control is a multi-layered defense. Layer 1: prevention at the client library. Our metrics SDK should discourage high-cardinality labels by design — we provide a labeled counter or gauge API that only accepts predefined label names, not arbitrary strings. If a developer wants to add a user_id label, they explicitly opt in and specify expected cardinality like max 100 distinct values. This is a social mechanism as much as technical — it forces developers to think about cardinality before emitting metrics."))

    lines.append(("candidate", "Layer 2: enforcement at ingestion. The cardinality tracker counts distinct label combinations per metric name per service. When a metric exceeds its budget, new label combinations are collapsed — we replace the offending label value with a bucket. For example, if user_id has 10,001 distinct values and the budget is 10,000, we keep the top 9,999 by frequency and collapse the rest into user_id equals __other__. This preserves the overall distribution while bounding cardinality. Top-K tracking uses a Count-Min Sketch for approximate frequency estimates with bounded memory."))

    lines.append(("candidate", "Layer 3: detection and remediation. A cardinality dashboard shows top metrics by series count, growth rate, and label value distribution. When a metric's cardinality spikes — maybe someone deployed a change adding a request_id label — the dashboard flags it. We also track storage cost per metric so teams can decide whether a high-cardinality metric is worth it. At our scale, a single high-cardinality metric can cost thousands of dollars per month in storage and query compute. We can also set up automated alerts on cardinality growth rate — if a metric adds more than 1,000 new series in an hour, that's suspicious and warrants investigation."))

    lines.append(("interviewer", "Good. Now let's deep dive into alerting. How does SLO-based alerting work?"))

    lines.append(("candidate", "SLO-based alerting is fundamentally different from threshold-based. A threshold alert says 'fire when CPU exceeds 80 percent.' An SLO alert says 'fire when the error budget burn rate is too high.' Key concepts: SLI measures behavior — like the ratio of successful requests. SLO is the target — like 99.9 percent over 30 days. SLA is the contractual commitment with financial penalties. The error budget is 1 minus the SLO — at 99.9 percent, that's 0.1 percent, or about 43 minutes of allowed downtime per month."))

    lines.append(("candidate", "Simple SLO alerts fire too late — if you wait until the 30-day budget is consumed, the problem has been ongoing for days. Multi-window, multi-burn-rate alerts solve this: calculate burn rate over both a short and long window simultaneously. Short windows detect fast burns, long windows confirm the problem is sustained, not a blip. Concrete example: Condition 1 — 1-hour burn rate exceeds 14.4x AND 5-minute exceeds 14.4x, fires a page — we're consuming 14.4 hours of error budget in 1 hour, which is critical. Condition 2 — 6-hour exceeds 6x AND 1-hour exceeds 6x, fires a ticket — a slower burn but still concerning. Condition 3 — 3-day exceeds 1x AND 6-hour exceeds 1x, fires a low-priority notification — the SLO is slowly degrading. The multi-window approach gives both sensitivity and specificity."))

    lines.append(("interviewer", "You mentioned alerting on symptoms, not causes. What does that mean in practice?"))

    lines.append(("candidate", "This is the Google SRE principle: alert on what's broken, not why. A symptom is user-visible — high latency, errors, unavailable service. A cause is the underlying reason — high CPU, disk full. Alerting on causes gives fatigue — CPU is high on 50 servers but only 3 cause user-visible problems. Alerting on symptoms means you only wake the on-call when users are affected; they then use dashboards and logs to find the cause. In practice, our primary alerts are based on golden signals: latency — p99 exceeds SLO threshold. Traffic — request rate drops below 50 percent baseline, catching outages where the service is down but not reporting errors. Errors — 5xx rate exceeds error budget burn rate. Saturation — critical resource utilization exceeds 90 percent."))

    lines.append(("candidate", "In practice, this means our primary alerts are all based on golden signals. Latency: the 99th percentile request duration exceeds the SLO threshold. Traffic: the request rate drops below 50 percent of the baseline — this catches outages where the service is down but not reporting errors because it can't receive requests. Errors: the 5xx error rate exceeds the error budget burn rate. Saturation: the utilization of a critical resource — connection pool, thread pool, disk I/O — exceeds 90 percent. These four signals cover the vast majority of production issues."))

    lines.append(("candidate", "We still need cause-based alerts where symptoms lag causes — disk at 95 percent full won't cause write errors until it's 100 percent, which is an emergency. These go to Slack, not PagerDuty. Rule of thumb: if it would wake someone at 3 AM, it must be symptom-based. If it's a heads-up during business hours, cause-based is fine. This separation keeps the page channel high-signal while still providing early warning for slow-burn infrastructure issues."))

    lines.append(("interviewer", "What about aggregation types — counters, gauges, histograms, summaries? How do they affect storage and alerting?"))

    lines.append(("candidate", "The aggregation type determines what you can alert on and how you store data. Counters are monotonically increasing — like total_requests. You can't alert on a counter directly — you need to compute its rate, like requests per second. In PromQL, that's rate(http_requests_total[5m]). Counters compress well because delta encoding works when values mostly increase. Gauges are point-in-time values — like current_temperature or active_connections. You alert directly on gauges. They compress less well because values can go up or down."))

    lines.append(("candidate", "Histograms are the most important type for SLO alerting. A histogram buckets observations into configurable bins — 10ms, 50ms, 100ms, 500ms, 1s, 5s — plus a sum and count. This allows arbitrary percentile computation at query time — p99 of request latency — without storing every individual observation. Percentiles are approximate depending on bucket boundaries, but for alerting, approximate p99 is usually good enough. The key is choosing bucket boundaries wisely — you want buckets around your SLO thresholds so the p99 estimate is accurate where it matters most. Summaries are the alternative — they compute quantiles client-side for exact values. But you can't aggregate summaries across instances — quantiles aren't algebraically aggregatable. Histograms are aggregatable: sum bucket counts across instances and compute the aggregate p99. For distributed systems, histograms are always the right choice. Teams often pick summaries for exact quantiles, then realize they can't compute service-level percentiles — a common and expensive mistake."))

    # SECTION 5: Failure Modes (~4 min)
    lines.append(("interviewer", "What are the most critical failure scenarios for the metrics pipeline itself?"))

    lines.append(("candidate", "The most insidious failure is when the metrics pipeline goes down and nobody notices — the alerts that would tell you are powered by the pipeline that's down. Everything looks green because no alerts are firing, but actually no alerts can fire. This is the observability gap. If your alerting system depends on the metrics pipeline, and the pipeline fails silently, you have a false sense of security."))

    lines.append(("candidate", "The defense is layered monitoring — the metrics pipeline itself must be monitored by a separate, simpler system. A heartbeat-based watchdog with no dependency on the main pipeline. If the watchdog doesn't receive a heartbeat for 2 minutes, it fires through an independent channel — an SMS gateway or separate PagerDuty account. The 'who watches the watchers' problem, and the answer is: a simpler watcher. We also monitor key health metrics of the pipeline itself — samples received per second, query latency p99, alert evaluation lag — and expose these as metrics that our main pipeline scrapes. It's a bit recursive, but the independent watchdog provides the safety net when the recursion breaks."))

    lines.append(("candidate", "The second failure is cardinality explosion. Someone adds an unhashed session_id label and active series jump from 10 million to 100 million. Ingestion chokes — tracking 100 million series in the cardinality tracker uses more memory than expected. Storage fills up — 100 million series at 800 bytes overhead each is 80 GB of index alone, plus the sample data. Query performance degrades from 100ms to 10 seconds because queries touch 10x more series. A cascading failure from a single misconfigured metric."))

    lines.append(("interviewer", "How do you prevent that cascade?"))

    lines.append(("candidate", "Cardinality controls at ingestion limit the blast radius by capping per-service cardinality. But we also need circuit breakers at storage — if a partition exceeds 5 million series, it rejects new series while continuing to accept samples for existing ones. Rate limiting at ingestion throttles services emitting above their normal rate to protect the pipeline for other tenants. Two main circuit breakers: series count limits and sample rate limits. The important thing is that these are automatic protections, not manual interventions. By the time a human notices cardinality explosion, the damage is already done — the storage is bloated, queries are slow, and recovery requires manual cleanup. Automatic circuit breakers prevent the damage in the first place."))

    lines.append(("candidate", "Third failure: slow queries. A badly written PromQL selecting 1 million series with complex aggregation can consume massive CPU and memory in the query engine. If multiple engineers run heavy queries simultaneously, the engine becomes a bottleneck, affecting dashboard refreshes and alert evaluation. Mitigations: query timeouts at 30 seconds, concurrent query limits per tenant, and result caching — a dashboard query returning the same data every 30 seconds shouldn't recompute from scratch each time."))

    lines.append(("candidate", "Fourth: alert fatigue — the cry wolf problem. If alerts fire too often for non-actionable issues, engineers ignore them and miss real incidents. Multi-window burn-rate alerting reduces false positives compared to threshold alerts. But we also need alert hygiene: periodic rule review, retirement of alerts that never lead to action, and a requirement that every alert has a runbook — a documented procedure for investigating and resolving the issue. An alert without a runbook is noise."))

    # SECTION 6: Scale & Debrief (~3 min)
    lines.append(("interviewer", "How does the design change at 10x scale — 100 million time series? And what about multi-region observability?"))

    lines.append(("candidate", "At 10x scale — 100 million series — ingestion needs 50 to 100 nodes handling 10 million data points per second. We'd use DNS-based routing or consistent hashing instead of a central load balancer to avoid that bottleneck. Storage needs a distributed index — sharded by metric name hash, with scatter-gather queries spanning shards. This adds latency but scales horizontally. The data layer also needs sharding — different shards store different time ranges or different series, depending on query patterns."))

    lines.append(("candidate", "Multi-region: I'd recommend a regional-federated model. Each region — US, EU, APAC — has its own full pipeline: collection, ingestion, storage, query, alerting. A global query layer federates across regions for cross-region dashboards — it sends queries to each regional pipeline in parallel and merges results. Alerting is primarily regional, so a region outage doesn't affect other regions' alerting. Cross-region metrics like total global payment volume are computed by recording rules that periodically pull from regional instances. This avoids replicating all raw metrics across regions, which would be prohibitively expensive at 10 million series."))

    lines.append(("candidate", "At 0.1x scale — 1 million series — a single Prometheus instance with local storage handles everything. Grafana queries directly, Alertmanager runs alongside. No separate ingestion layer needed — Prometheus scrapes and stores locally. Cardinality tracking is unnecessary — 1 million series is well within a single server's capacity. Thanos or Cortex can add downsampling if needed, but local SSD with 30-day retention is probably sufficient. Simplicity wins at low scale. The key insight: at low scale, you can afford to skip the multi-layer architecture, but the core principles — cardinality awareness, SLO-driven alerting, retention tiers — should still guide your design even if the implementation is simpler."))

    # SECTION 7: End-to-End Walkthrough (~4 min)
    lines.append(("interviewer", "Walk me through the complete lifecycle of a metric — from application emission to alert firing. Let's trace an error rate spike in the payment service."))

    lines.append(("candidate", "Let me trace http_request_duration_seconds_count{service equals payment-service, status_code equals 500, region equals APAC}. Step 1: Emission. The payment-service SDK increments a Prometheus counter at /metrics every time a request returns 500. The counter lives in process memory, exposed for scraping via the standard Prometheus exposition format endpoint."))

    lines.append(("candidate", "Step 2: Collection. A scraper discovers payment-service instances via service discovery — it queries the service registry, finds all instances in APAC, and adds them to scrape targets. Every 15 seconds, the scraper sends an HTTP GET to each instance's /metrics endpoint, parses the Prometheus exposition format, computes counter deltas from the previous scrape, and forwards the samples via Prometheus remote write to the ingestion layer."))

    lines.append(("candidate", "Step 3: Ingestion. The remote write request hits the load balancer, routes to an ingest node. The node validates the request — correct tenant ID, valid metric names, no unauthorized labels. It checks the cardinality tracker — payment-service currently has 3,500 active series out of a 10,000 budget, so this series is allowed. The node assigns a series ID to this metric-plus-labels combination and forwards the sample to storage."))

    lines.append(("candidate", "Step 4: Storage. The sample writes to the current 2-hour chunk using Gorilla compression — delta-of-delta for the timestamp, XOR for the value. The inverted index posting lists for the label pairs are updated to include this series ID. All in memory, persisted to disk asynchronously. Step 5: Alert evaluation. Every 30 seconds, the alert engine runs the SLO rule for payment-service: the 1-hour error rate — sum(rate of 500s) divided by sum(rate of all requests) — queries the index, fetches the last hour from hot storage, computes rates. Normally 0.03 percent. Now it returns 1.2 percent — a spike."))

    lines.append(("candidate", "Step 6: Burn rate calculation. The 1-hour burn rate is 1.2 percent divided by 0.1 percent equals 12x — above the 6x page threshold. The 5-minute burn rate is 15x. Both confirm a fast, sustained burn. The alert fires. Step 7: Notification. PagerDuty receives the alert with context — service, region, 1.2 percent error rate, 12x burn rate. Slack notification follows with a Grafana dashboard link. The on-call engineer opens the dashboard, clicks through to traces via the trace_id label, finds database connection pool exhaustion causing all payment requests to fail with 500s, increases the pool, and the alert resolves."))

    lines.append(("candidate", "Total latency from error to alert: about 90 seconds — 15 seconds for the next scrape, 30 seconds for the next evaluation cycle, 45 seconds for burn rate windows. The 5-minute window prevents firing on a single bad scrape. Right trade-off — fast enough for real incidents, slow enough to avoid false alarms. The key insight is that alerting latency is dominated not by storage or query speed, but by the observation interval — how often we scrape and evaluate. To reduce alert latency, you'd need faster scraping and evaluation, at the cost of more load on the pipeline."))

    # SECTION 8: Thinking Process & Beats (~3 min) — interviewer monologue
    lines.append(("interviewer", "Let me close with my thinking process for evaluating metrics and monitoring designs. My framework starts with the data model — metric name plus labels plus timestamp plus value. Everything flows from it: how you store, query, and alert. The two key decisions are aggregation types and the label cardinality strategy."))

    lines.append(("interviewer", "First beat: three pillars awareness. A candidate who only talks about metrics ignores the fact that metrics tell you something is wrong, traces tell you where, logs tell you why. The integration — correlation IDs, trace_id in metric labels, pivoting from Grafana to Jaeger to Loki — is a core requirement. I don't expect all three systems designed, but candidates must acknowledge metrics alone are insufficient."))

    lines.append(("interviewer", "Second beat: cardinality control — the number one operational problem. A candidate who treats labels as just key-value pairs builds a system that works in testing and falls over in production. I look for three things: SDK-level prevention, ingestion-level enforcement with budgets and automatic collapse, and detection dashboards showing growth and cost. A candidate with all three has operated a metrics system at scale."))

    lines.append(("interviewer", "Third beat: SLO-driven alerting — a maturity indicator. Junior engineers alert on thresholds, senior engineers alert on symptoms using error budget burn rates. The multi-window approach is state of the art. Key insight: 99.9 percent dropping to 99.8 percent isn't an emergency over 30 days, but it is in 5 minutes. Burn rate captures this distinction."))

    lines.append(("interviewer", "Fourth beat: downsampling and retention tiers. High-resolution data loses value as it ages. A candidate who stores everything at full resolution hasn't thought about cost. The hot-to-warm-to-cold-to-archive progression with min, max, sum, count per bucket is essential. Downsampling must preserve aggregations for SLO calculation — averaging loses the max, making p99 unrecoverable."))

    lines.append(("interviewer", "Then there are the traps. Trap one: alert fatigue. An alerting system that pages at 3 AM for non-actionable conditions has missed the point. Every alert must be actionable, have a runbook, and be symptom-based. I've seen 500 rules firing 50 times a day — the on-call ignores all of them. Worse than no alerts, because it creates false confidence."))

    lines.append(("interviewer", "Trap two: unbounded labels. Allowing arbitrary label values designs a future incident — someone adds user_id or request_id and series explode overnight. The __other__ collapse mechanism is a safety requirement. I look for candidates who treat cardinality limits as first-class architecture."))

    lines.append(("interviewer", "Trap three: missing SLOs. Jumping to alerting without defining SLIs and SLOs puts the cart before the horse. Without SLOs, thresholds are arbitrary — why 1 percent and not 0.5 percent? The answer should be 'our SLO is 99.9 percent, and 1 percent burns the monthly budget in 3 days.' Without SLOs, thresholds are vibes. I also look for distinguishing SLIs from SLOs from SLAs — conflation is a red flag."))

    lines.append(("interviewer", "Overall: data model established early, cardinality identified as key risk, three-layer defense shows maturity, burn-rate alerting well-explained, walkthrough thorough, three pillars clear. Improvement: push versus pull needed deeper discussion — pull fails for short-lived and serverless workloads, push complements it. Also, AI platform metrics — prompt latency, hallucination rate, cost per session — are increasingly critical and weren't mentioned. Strong overall. Thanks."))

    lines.append(("candidate", "Thank you. You're right — pull-based scraping fails for short-lived processes and serverless functions with no persistent endpoint. Push via a StatsD sidecar or telemetry SDK that batches and flushes is the right complement. And AI platform metrics are critical — prompt latency p99, hallucination rate as the fraction of responses flagged by an evaluation model, agent session completion rate as the percentage of multi-turn sessions reaching successful conclusion, and cost per session in model API tokens. These need their own SLOs and alerting rules, just like infrastructure metrics. They also introduce novel cardinality concerns — for example, model_version as a label on inference latency can explode if models are updated frequently. Appreciate the feedback."))

    return lines
