"""Mock Interview: Multi-Region Global Infrastructure — Two-voice dialogue."""


def build():
    lines = []

    # SECTION 1: Requirements
    lines.append(("interviewer", "Hi, welcome. Today I'd like you to design a global infrastructure for a fintech company that operates in eight regions — Singapore, Australia, UK, US, Hong Kong, Netherlands, Korea, and Japan. The system processes real money, so we cannot lose transactions during failover. Start by clarifying the requirements."))

    lines.append(("candidate", "Thanks. Multi-region for fintech is fundamentally different from multi-region for a social media app, because we're moving money, not likes. Let me ask about the most critical requirement first: what's the failover expectation? Are we talking active-active — where every region can independently process transactions — or active-passive — where one region is primary and the others are hot standbys for disaster recovery?"))

    lines.append(("interviewer", "Good question. We want active-active for read operations — account balances, transaction history, FX rates. For writes — creating new transactions, moving money — we need a single leader per entity to maintain consistency. But different entities can have leaders in different regions."))

    lines.append(("candidate", "So it's a leader-per-entity model, not leader-per-region. That's important. A merchant based in Singapore has their ledger entries written in Singapore, but a merchant in London writes in London. Both regions are fully active — they just don't write to the same data simultaneously. Next question: what are the RPO and RTO targets? Recovery Point Objective — how much data can we afford to lose in a regional failure. Recovery Time Objective — how long before we're processing transactions again."))

    lines.append(("interviewer", "RPO must be under one minute — we can lose at most one minute of transactions. RTO must be under five minutes — we need to be processing again within five minutes of a region going down."))

    lines.append(("candidate", "RPO under one minute means near-synchronous replication. We can't use async replication because that can lag by minutes or hours during normal operation. We need synchronous replication to at least one other region before acknowledging a write. RTO under five minutes means automated failover — no human in the loop, because a human can't reliably make a failover decision in five minutes at three AM. Let me ask about data sovereignty. Different regions have different regulations."))

    lines.append(("interviewer", "Right. EU data must stay in the EU — GDPR requires it. Singapore data falls under PDPA and MAS TRM guidelines. Australian data under the Privacy Act and ASIC regulations. We can replicate for disaster recovery, but the primary storage and processing must be in-region for regulated data."))

    lines.append(("candidate", "So EU user data is stored in the Netherlands, Australian data in Sydney, Singapore data in Singapore. We can replicate cross-region for DR, but the replication target must also be in a jurisdiction that meets the data protection standards. EU to UK is fine post-Brexit if we have adequacy decisions. EU to US requires specific safeguards. Let me summarize the requirements: active-active for reads, leader-per-entity for writes, RPO under one minute, RTO under five minutes, data sovereignty per jurisdiction, eight regions, and we process real money so zero money loss during failover. Moving to estimation."))

    # SECTION 2: Estimation
    lines.append(("interviewer", "Go ahead with the numbers."))

    lines.append(("candidate", "Total transaction volume: about five thousand TPS across all regions. Singapore is the largest — maybe two thousand TPS. Australia and UK about one thousand TPS each. The rest split the remaining thousand. Each transaction is about one kilobyte. Replication factor: each write is synchronously replicated to one other region. So five thousand TPS of writes becomes ten thousand TPS of write replication network traffic. At one kilobyte each, that's about ten megabytes per second of cross-region replication traffic. Cross-region bandwidth between major data centers is typically one to ten gigabits per second, so ten megabytes per second — about eighty megabits — is well within capacity."))

    lines.append(("candidate", "But there's a latency cost. A synchronous write to another region adds the cross-region round-trip time to every write. Singapore to Sydney is about thirty milliseconds. Singapore to London is about one hundred and eighty milliseconds. Singapore to Virginia is about two hundred milliseconds. If we require synchronous replication to a region that's two hundred milliseconds away, every write takes at least two hundred milliseconds plus the local write time. For a payment system that needs sub-second API response, adding two hundred milliseconds is significant but acceptable. The key is choosing the replication partner wisely — replicate Singapore data to Hong Kong, which is only thirty to forty milliseconds away, not to Virginia."))

    lines.append(("interviewer", "What about the event bus? Kafka doesn't natively support multi-region replication."))

    lines.append(("candidate", "Right. We'd use MirrorMaker two for cross-region Kafka replication. Each region has its own Kafka cluster. MirrorMaker two replicates topics between clusters. The key design choice: unidirectional or bidirectional replication. For payment events, we use unidirectional — events flow from the region where the payment was created to the other regions for read purposes. For example, a payment.created event in Singapore is replicated to Sydney and London so that the read replicas there can show the updated status. Bidirectional replication is more complex because of conflict resolution — what if the same event is produced in two regions simultaneously? We avoid this by design: each entity has a single leader region, so events for that entity are only produced in one region."))

    # SECTION 3: High-Level Architecture
    lines.append(("interviewer", "Let's move to the high-level architecture."))

    lines.append(("candidate", "Here's the overall design. Each region is a complete stack: API gateway, application services, PostgreSQL database, Redis cache, Kafka event bus. The regions are connected by a backbone network with dedicated links between major pairs — Singapore-Hong Kong, Singapore-Sydney, London-Virginia, London-Amsterdam."))

    lines.append(("candidate", "For routing: a global DNS load balancer — think Cloudflare or AWS Route fifty-three — routes users to their nearest region based on geographic IP. A user in Singapore hits the Singapore API endpoint. A user in London hits the London endpoint. This gives them the lowest latency for reads."))

    lines.append(("candidate", "For writes: each entity — merchant, customer, account — has a home region determined at onboarding. When a merchant in Singapore creates a payment, the Singapore region processes it locally. If the same merchant later travels to London and creates a payment from there, the London API gateway receives the request, detects that this merchant's home region is Singapore, and forwards the write request to Singapore over the backbone. This adds about one hundred and eighty milliseconds of cross-region forwarding, but it ensures that all writes for an entity go through a single region, maintaining consistency."))

    lines.append(("interviewer", "That forwarding approach adds latency for the traveling user. Is there a way to avoid it?"))

    lines.append(("candidate", "Yes, but it involves trade-offs. Option one: allow writes in any region and use conflict resolution. This means two regions could update the same account simultaneously, and we need to resolve conflicts. For financial data, this is dangerous — we can't just merge conflicting account balances. Option two: entity migration — if a merchant moves from Singapore to London, we migrate their data to London during a maintenance window. This is operationally heavy but maintains the single-leader guarantee. Option three: accept the forwarding latency for the rare case of a user operating far from their home region. In practice, most merchants operate in their home region most of the time, so the forwarding case is rare. I'd go with option three."))

    # SECTION 4: Deep Dive — Database Replication and Failover
    lines.append(("interviewer", "Let's deep dive into the database replication and failover mechanism."))

    lines.append(("candidate", "This is the hardest part. For PostgreSQL, we use synchronous streaming replication to one cross-region standby. The primary in Singapore sends WAL — Write-Ahead Log — records to the standby in Hong Kong. The standby acknowledges receipt before the primary commits the transaction. This ensures that if Singapore goes down, Hong Kong has every committed transaction — RPO is zero for committed transactions. The replication adds about thirty to forty milliseconds to each write, which is acceptable for our sub-second SLA."))

    lines.append(("candidate", "For failover: we use a distributed consensus protocol — either Raft or etcd — to manage cluster membership and leader election. The consensus cluster runs across three regions — Singapore, Hong Kong, and Sydney. When Singapore becomes unreachable, the consensus cluster detects it within about ten seconds — using heartbeat timeouts — and promotes Hong Kong to primary. The promotion takes another ten to twenty seconds as Hong Kong replays any in-flight WAL records and opens for writes. Total RTO: about thirty seconds. Well within the five-minute target."))

    lines.append(("interviewer", "What about the in-flight transactions at the moment of failover?"))

    lines.append(("candidate", "Critical question. When Singapore goes down, there may be transactions that were committed on the primary but not yet replicated to Hong Kong — if the replication was lagging. With synchronous replication, this shouldn't happen for committed transactions. But there may be transactions that were in progress — the client sent the request, Singapore started processing, but the acknowledgment never reached the client because the network went down simultaneously. These transactions are in an indeterminate state — the client doesn't know if they succeeded or failed."))

    lines.append(("candidate", "The solution is the idempotency key. Every write request carries an idempotency key. After failover, when the client retries, Hong Kong checks the idempotency store. If the transaction committed before the failover, the retry returns the original result. If it didn't commit, the transaction is processed fresh. This is why idempotency is non-negotiable in distributed financial systems — it's not just about preventing double charges from retries, it's about recovering from partial failures in a multi-region setup."))

    lines.append(("interviewer", "Walk me through a specific failover scenario. Singapore goes down. What happens to a payment that was being processed?"))

    lines.append(("candidate", "Say a merchant in Singapore submits a payment at time T. The API gateway in Singapore receives the request and starts the payment saga. Step one: debit the sender's account — committed to the database and replicated to Hong Kong. Step two: FX rate locked — committed and replicated. Step three: compliance check passes — committed and replicated. Step four: submit to bank — the bank connector sends the payment to the partner bank. Now Singapore goes down. The bank has received the payment instruction but we don't know the response. The payment is in a pending state."))

    lines.append(("candidate", "When Hong Kong takes over, the reconciliation service detects payments in the pending state. It queries the partner bank — did you receive payment reference X? If the bank says yes, we mark the payment as submitted. If the bank says no, we reverse the ledger entries and mark the payment as failed. If the bank says they don't know yet — which happens — we keep the payment in pending and check again in an hour. The key insight: in financial systems, you never assume. You always verify. Every indeterminate state is resolved by asking the source of truth — the partner bank, the card network, the FX provider. This is what distinguishes a fintech failover from a generic failover."))

    # SECTION 5: Deep Dive — Data Sovereignty and Kafka
    lines.append(("interviewer", "Let's talk about the data sovereignty implementation. How do you ensure EU data stays in the EU?"))

    lines.append(("candidate", "Data sovereignty is enforced at three layers. Layer one: routing. The global DNS directs EU users to the Netherlands endpoint. The API gateway checks the user's jurisdiction — stored in their account record — and if they're an EU user, only processes their data in the Netherlands region. Layer two: storage. Each region's database only stores data for entities whose home region is that region. The schema includes a home_region column on every table, and a database-level constraint prevents storing data in the wrong region. Layer three: replication. Cross-region DR replication is allowed under GDPR if the target region has adequate data protection — this is the adequacy decision framework. Netherlands to UK is fine. Netherlands to Singapore requires additional contractual safeguards like Standard Contractual Clauses. We configure MirrorMaker two to only replicate topics that are approved for cross-region DR."))

    lines.append(("interviewer", "What about a customer who moves from the EU to Singapore? Can they keep their account?"))

    lines.append(("candidate", "This is a real scenario. If a customer moves, we need to migrate their data from the Netherlands to Singapore. This isn't just a database migration — we need regulatory approval. Under GDPR, the customer must consent to their data being transferred to a non-EU jurisdiction. We'd build a data migration workflow: the customer requests a region change, we present the required consents, they accept, and then we migrate their data during a maintenance window. The migration includes all historical transaction records, which must be copied and then deleted from the EU cluster. The deletion must be verified and logged for audit purposes. This is one of those operational challenges that you only face in a real multi-region fintech system."))

    lines.append(("interviewer", "How does the event bus handle sovereignty? If a payment event is created in Singapore, can it be consumed in London?"))

    lines.append(("candidate", "Yes, but with constraints. The event itself — the Kafka message — contains a jurisdiction tag. When MirrorMaker two replicates the event from Singapore to London, the London consumer can read it for read-only purposes — displaying the transaction status to the user, analytics, compliance monitoring. But the London consumer cannot use that event to initiate a new write that would modify the customer's data, because the customer's write leader is in Singapore. The event is informational in London, authoritative in Singapore. This is the read-only replica pattern applied to the event bus."))

    # SECTION 6: Deployment Strategy
    lines.append(("interviewer", "How do you deploy new code across eight regions without downtime?"))

    lines.append(("candidate", "Progressive rollout with feature flags. We use a feature flag service — think LaunchDarkly or an internal equivalent — that's replicated across all regions. When we deploy a new version of the payment service, we do it in stages. Stage one: deploy to the Singapore canary cluster — one instance out of ten. Monitor for five minutes — error rate, latency p ninety-nine, business metrics like payment success rate. If everything looks good, stage two: deploy to all Singapore instances. Stage three: deploy to Hong Kong, which is the DR partner. If anything goes wrong, Hong Kong can still serve traffic while we roll back Singapore. Stage four: deploy to the remaining regions in order of business priority — Australia, UK, US, then the smaller regions."))

    lines.append(("candidate", "Feature flags let us deploy code without enabling new behavior. We deploy the new code with the feature flag off. Then we turn the flag on region by region, monitoring after each activation. If a new feature causes problems, we turn the flag off — no rollback needed, no deployment, just a configuration change that takes effect in seconds. This is how you move fast with conviction, to use Airwallex's operating principle — you deploy confidently because you can instantly disable anything that goes wrong."))

    lines.append(("interviewer", "What about database schema migrations across regions?"))

    lines.append(("candidate", "Database migrations must be backward-compatible. We never run a migration that breaks the previous version of the code. For adding a column: just add it with a default value — the old code ignores it, the new code uses it. For removing a column: first deploy code that stops reading the column, then in a separate migration, drop the column. For renaming a column: add the new column, dual-write to both old and new, migrate readers to the new column, then drop the old one. Each step is a separate deployment. This takes longer but ensures zero downtime across regions, even if some regions are running different code versions simultaneously during a rollout."))

    # SECTION 7: Scale and Failure
    lines.append(("interviewer", "What happens at ten times scale? Five thousand TPS becomes fifty thousand."))

    lines.append(("candidate", "At fifty thousand TPS, the cross-region replication traffic becomes five hundred megabytes per second — about four gigabits per second. We'd need dedicated ten-gigabit links between regions, possibly multiple links for redundancy. The database in each region needs to handle about ten thousand writes per second locally. With PostgreSQL, we'd need to shard — partition by entity ID so that each shard handles a subset of merchants and customers. Each shard has its own primary and cross-region standby. With, say, ten shards per region, each shard handles about one thousand writes per second, which is manageable for PostgreSQL on good hardware."))

    lines.append(("candidate", "The Kafka event bus also needs scaling. At fifty thousand TPS, with events for each transaction — payment dot created, payment dot completed, ledger dot entry — we're looking at maybe one hundred and fifty thousand events per second globally. Each region handles its local events and replicates to other regions. With ten Kafka partitions per topic and three brokers per region, we can handle about one hundred thousand events per second per region. MirrorMaker two needs to be scaled to handle the replication — each MirrorMaker instance can handle about ten thousand events per second, so we'd need about five instances per region pair."))

    lines.append(("interviewer", "Final question: what's the single biggest risk in this architecture?"))

    lines.append(("candidate", "Split-brain. If the network between Singapore and Hong Kong becomes unreliable — not completely down, but flapping — the consensus cluster might elect a new primary in Hong Kong while Singapore still thinks it's the primary. Both regions could accept writes for the same entity, creating conflicting database states. This is the nightmare scenario for a financial system. The defense: require a quorum of three consensus nodes across three regions to elect a leader. With three nodes, a network partition can at most give a quorum to one side. The other side loses quorum and stops accepting writes. This guarantees that only one primary exists at any time, even during network partitions. The cost: if two out of three consensus regions go down, the remaining region loses quorum and can't elect a leader, so writes stop entirely. But that's the correct behavior — we'd rather stop writes than allow conflicting writes."))

    # SECTION 8: E2E Walkthrough with Thinking Beats
    lines.append(("interviewer", "Walk me through the complete flow for a payment that originates in Singapore and settles via a London bank."))

    lines.append(("candidate", "Let me think through this carefully because it crosses regions and involves external systems. Hmm. OK, so the merchant is in Singapore — their home region. They submit a payment to a beneficiary whose bank is in London, via SEPA. The Singapore API gateway receives the request with an idempotency key. The payment orchestrator starts the saga. First, it locks the FX rate — SGD to GBP — via the FX service, which reads the rate from the Singapore Redis cache. The rate is stored with a thirty-second TTL. Next, compliance screening — the compliance service in Singapore checks against sanctions lists. This is a synchronous check, about two hundred milliseconds. Both pass. Now the orchestrator writes the ledger entries — debit the sender's SGD account, credit the SGD FX suspense account. This write goes to PostgreSQL in Singapore, with synchronous replication to Hong Kong. The write takes about fifty milliseconds including replication acknowledgment. Next, the orchestrator submits the payment to the bank connector. But SEPA settlement requires a European bank connection. The Singapore region doesn't have a direct SEPA connection — the London region does. So the Singapore payment service calls the London bank connector service over the backbone. This is an intra-service RPC, not a client-facing request, so it's a direct gRPC call over the private backbone. Latency: about one hundred and eighty milliseconds. The London bank connector submits to the SEPA rail and returns the bank's acknowledgment. Total time: about five hundred milliseconds for the synchronous path. The payment is now in PROCESSING state. SEPA settlement happens later — same day if submitted before the two PM CET cutoff. When settlement completes, the London region publishes a payment dot settled event on its Kafka. MirrorMaker replicates this event to Singapore. The Singapore consumer updates the payment status and writes the final ledger entries — debit the FX suspense, credit the beneficiary's GBP account. If at any point Singapore goes down during this flow, the Hong Kong standby takes over and continues the saga from the last committed step, using the idempotency key to avoid reprocessing."))

    lines.append(("candidate", "One thing I want to emphasize: the key power phrases for this topic. Number one: RPO under one minute requires synchronous replication. Number two: RTO under five minutes requires automated failover with no human in the loop. Number three: leader-per-entity, not leader-per-region, gives us active-active without conflicts. Number four: split-brain prevention requires a quorum of three consensus nodes. Number five: every indeterminate state during failover is resolved by asking the source of truth — the partner bank, the card network. And number six: feature flags for progressive multi-region deployment, because you move fast with conviction."))

    # SECTION 8: Estimation Deep Dive
    lines.append(("interviewer", "Let's do the full estimation for the multi-region setup. What resources do we need per region?"))

    lines.append(("candidate", "Per region, we need the full stack. API gateway: about ten instances at five thousand connections per instance, so about fifty thousand concurrent connections capacity. We only need five thousand concurrent, so ten instances gives us plenty of headroom for peak. Application services: about twenty instances for the payment, ledger, FX, and compliance services. Database: PostgreSQL primary with one synchronous cross-region standby and one local async replica for read scaling. The primary needs about four CPUs and thirty-two gigabytes of RAM to handle two thousand writes per second. Storage: about five hundred gigabytes per region for ninety days of hot data, with older data in cold storage. Redis: a three-node cluster with about eight gigabytes per node for the rate cache and idempotency cache. Kafka: a three-broker cluster with about five hundred gigabytes of storage per broker, handling about two thousand events per second. Total per region: about thirty VMs or Kubernetes pods, costing about five to ten thousand dollars per month per region. Eight regions: about forty to eighty thousand dollars per month in compute. The backbone network between regions — dedicated links with one to ten gigabits per second — costs about two to five thousand dollars per month per link. With about twelve links in a mesh topology, that's about twenty-four to sixty thousand dollars per month. Total infrastructure: about sixty to one hundred and forty thousand dollars per month. At Airwallex's scale, this is reasonable."))

    lines.append(("interviewer", "What about the monitoring and observability across regions?"))

    lines.append(("candidate", "Each region runs its own Prometheus for metrics collection and Grafana for dashboards. A central observability platform — think Datadog or a self-hosted Thanos cluster — aggregates metrics from all regions for global dashboards and cross-region alerting. Key metrics we monitor per region: API latency p fifty and p ninety-nine, payment success rate, database replication lag, Kafka consumer lag, error rate, and circuit breaker state. Cross-region metrics: replication latency between region pairs, MirrorMaker two lag, failover readiness — is the standby in sync? Alert routing: alerts fire in the region where the issue is detected and are routed to the on-call team in the nearest time zone. A database issue in Singapore at three AM Singapore time pages the Singapore on-call, not the London team."))

    # SECTION 9: Disaster Recovery Drill
    lines.append(("interviewer", "How do you validate that failover actually works?"))

    lines.append(("candidate", "Chaos engineering. We run regular failover drills — at least quarterly — where we deliberately take down a region's database primary and verify that the standby promotes correctly and traffic reroutes. The drill procedure: first, announce the drill to all teams — no surprises. Second, switch the DNS to route all traffic to the DR region. Third, trigger a controlled failover of the database primary — we use Patroni, which has a switchover command for planned maintenance. Fourth, verify that all services reconnect to the new primary and process transactions normally. Fifth, measure the failover time — it should be under five minutes. Sixth, verify data integrity — run a reconciliation check comparing the ledger entries in both regions. Seventh, fail back to the original primary during a maintenance window."))

    lines.append(("candidate", "We also run unplanned drills — inspired by Netflix's Chaos Monkey. A service randomly terminates a database process or severs a network link in a non-production environment. The automated systems must detect and recover without human intervention. If they don't, we fix the automation and re-run the drill. This ensures that when a real outage happens at three AM, the system recovers without waking up an engineer. The goal: RTO under five minutes, with zero human involvement. If we need a human, our RTO is whatever time it takes that human to wake up, log in, understand the problem, and make a decision — which is at least fifteen minutes, probably more. Automated failover is the only way to hit a five-minute RTO."))

    lines.append(("candidate", "Let me repeat the killer phrases one final time for muscle memory. RPO under one minute means synchronous replication. RTO under five minutes means automated failover. Leader-per-entity means no write conflicts. Three-node quorum prevents split-brain. Every indeterminate state is resolved by asking the source of truth. Feature flags enable progressive deployment. And chaos engineering validates that it all actually works when you need it. These seven principles are the foundation of any multi-region fintech infrastructure."))

    return lines
