"""Mock Interview: Multi-Channel Notification System — Two-voice dialogue."""


def build():
    lines = []

    # SECTION 1: Requirements (~5 min)
    lines.append(("interviewer", "Hi, today I'd like you to design a multi-channel notification system. Think of something like a platform that sends push notifications, emails, and SMS to users — the kind of infrastructure that companies like Airbnb or Stripe use to communicate with their customers. Start by clarifying the requirements."))

    lines.append(("candidate", "Thanks. A notification system sounds deceptively simple but has a lot of hidden complexity. Let me start with the most fundamental question: are we building the delivery infrastructure ourselves — meaning direct integration with APNs, FCM, SES, Twilio — or are we layering on top of providers like SendGrid and Firebase? The operational burden and reliability story are very different."))

    lines.append(("interviewer", "We integrate directly with the delivery providers. APNs and FCM for push, SES for email, and Twilio for SMS. We own the retry logic, tracking, and compliance."))

    lines.append(("candidate", "OK, so we're the reliability layer. Next question: what's the scale — notifications per day, and what's the channel split? Also, are these mostly transactional notifications — like order confirmations and security alerts — or marketing campaigns with large bursts? Because burst patterns change the design significantly."))

    lines.append(("interviewer", "About 10 million notifications per day, split roughly 60 percent push, 30 percent email, 10 percent SMS. It's a mix: about 70 percent transactional and 30 percent marketing. Marketing campaigns can create bursts of up to 500K notifications in a few minutes."))

    lines.append(("candidate", "10M per day with 500K bursts — that's significant. How many users are we serving, and what's the average notification frequency per user? This helps me understand whether we're sending many notifications to a few users or a few to many users."))

    lines.append(("interviewer", "About 50 million registered users, with maybe 10 million active on any given day. The average is about 1 notification per active user per day, but power users — like merchants on a marketplace — might receive 50 to 100 per day."))

    lines.append(("candidate", "10M per day with 500K bursts — that's significant. A few more questions. First, user preferences: do users control which channels they receive notifications on, and can they opt out per notification type? Second, deduplication — if the same event triggers multiple notifications, should we collapse them? Third, what about compliance — CAN-SPAM for email, TCPA for SMS? Fourth, what's the expected delivery latency — do we need sub-second delivery for push, or is a few seconds acceptable?"))

    lines.append(("interviewer", "Good questions. Users have per-channel and per-type preferences, and we must respect them — this is non-negotiable. Deduplication: yes, within a 5-minute window, if the same notification type fires for the same user, we should coalesce and send only one. Compliance: absolutely — CAN-SPAM requires unsubscribe links, TCPA requires explicit opt-in for SMS. Latency: push should be under 5 seconds p99, email under 30 seconds, SMS under 10 seconds."))

    lines.append(("candidate", "One more important question: delivery tracking. Do we need to track whether a notification was delivered, opened, or clicked? And do we expose this to the sending services? This affects the data model significantly."))

    lines.append(("interviewer", "Yes, we track delivery status — sent, delivered, bounced, opened, clicked — and we expose this via a status API and webhooks. For push, we get delivery receipts from APNs and FCM. For email, we use SES callbacks and open-tracking pixels. For SMS, we use Twilio delivery receipts."))

    lines.append(("candidate", "Let me summarize. We're building a multi-channel notification platform at 10M notifications per day — 60/30/10 push/email/SMS — with direct provider integration, per-user preference management, 5-minute deduplication windows, compliance enforcement, sub-5-second push latency, full delivery tracking with webhooks, and support for marketing bursts up to 500K. Let me move to estimation."))

    # SECTION 2: Estimation (~5 min)
    lines.append(("interviewer", "Go ahead."))

    lines.append(("candidate", "10M notifications per day. Average TPS is 10M divided by 86400, which is about 116 per second. But with marketing bursts of 500K in a few minutes, peak could be around 2800 per second — call it 3K TPS peak. The read-to-write ratio is interesting — every notification requires a preference lookup, a deduplication check, and possibly a template render before we write the notification record. So maybe 3 to 4 reads per write. At peak, that's 12K reads per second. With caching at 80 percent hit rate for preferences and templates, the database sees about 2400 reads per second."))

    lines.append(("candidate", "Storage per notification: the notification record itself with type, channel, user ID, status, and content reference is maybe 500 bytes. The rendered content — especially email HTML — can be 5 to 20 KB, but we'd store that in object storage and keep a reference. So let's say 1 KB per notification in the database. At 10M per day, that's 10 GB per day. For 90 days hot storage, about 900 GB. For 2-year retention, about 7.3 TB. That's sharded PostgreSQL territory."))

    lines.append(("interviewer", "What about the preference data?"))

    lines.append(("candidate", "Right. With, say, 50 million users and an average of 10 notification types per user, that's 500 million preference records at maybe 50 bytes each — about 25 GB. That fits comfortably in a Redis cluster with replication. We'd load the full preference set on a cache miss and keep it warm. The deduplication cache is time-bounded — we only need the last 5 minutes of notification events per user. At 10M per day, that's about 3500 per minute. Each dedup key is maybe 64 bytes — user ID plus notification type. Wait, that's not right. We need per-user dedup keys, not global. With 50M users, even if only 10 percent are active in any 5-minute window, that's 5M keys. At 64 bytes each, about 320 MB in Redis. Totally fine."))

    lines.append(("candidate", "Actually, wait — I need to reconsider. The dedup key is not just user plus type. We might want to dedup based on the content hash too, so that two different order confirmation notifications for the same user don't get collapsed. Let me revise: the dedup key should be user ID plus notification type plus content fingerprint, maybe the first 8 bytes of an MD5 hash of the relevant payload fields. Still about 80 bytes per key. 5M keys times 80 bytes is 400 MB. Still fine for Redis."))

    lines.append(("interviewer", "What about the delivery tracking data? That adds to the storage too."))

    lines.append(("candidate", "Right. Each notification generates tracking events — sent, delivered, opened, clicked, bounced. Each event is about 100 bytes — notification ID, event type, timestamp, and metadata like the IP address for email opens. On average, each notification generates about 2 to 3 tracking events. At 10M notifications per day, that is 20 to 30M tracking events per day, about 2 to 3 GB per day. Over 90 days, about 200 to 270 GB. We store this in the same sharded PostgreSQL database, partitioned by notification ID. The tracking data is write-heavy but rarely read — it is accessed via the status API and webhook delivery. We can use a separate table with time-based partitioning so old data is easy to drop."))

    # SECTION 3: High-Level Architecture (~5 min)
    lines.append(("interviewer", "Good. Let's move to the high-level architecture."))

    lines.append(("candidate", "Here's the flow. A sending service — like the order service or marketing platform — calls our Notification API with the notification type, user ID, template ID, and template variables. The API layer first does a synchronous check: look up user preferences from the preference cache. If the user has opted out of this notification type on all channels, we return immediately with a SKIPPED status. If at least one channel is enabled, we proceed."))

    lines.append(("candidate", "Next, we check the deduplication cache. We compute the dedup key — user ID, notification type, content fingerprint — and check Redis. If there's a hit within the 5-minute window, we return a DUPLICATE status. If no hit, we write the notification to the database with status QUEUED and publish an event to a Kafka topic partitioned by user ID. The API returns 202 Accepted with a notification ID. Everything after this is async."))

    lines.append(("interviewer", "Why Kafka and not a direct queue to the channel senders?"))

    lines.append(("candidate", "Kafka gives us durability and replay. If a channel sender crashes, the messages aren't lost — they're still in Kafka. A direct queue like SQS would work too, but Kafka also lets us have multiple consumers — the channel senders, the analytics pipeline, and the delivery tracking service all consume from the same topic. Actually, let me think about this... with 3K TPS peak and partitioning by user ID for ordering guarantees, we'd need maybe 30 to 50 partitions. That's fine for Kafka. But there's a subtlety — we need to fan out to multiple channels per notification. A single notification might need to go to push, email, and SMS. We could either publish one event per channel, or publish one event and let a fan-out service split it."))

    lines.append(("candidate", "I think the fan-out approach is better. The Notification Router consumes from the main topic, determines which channels are enabled based on preferences, and publishes to per-channel topics — a push topic, an email topic, and an SMS topic. This way, each channel sender only deals with its own protocol and provider, and we can scale them independently. The router also applies rate limiting per user per channel — for example, no more than 5 push notifications per hour per user."))

    lines.append(("interviewer", "What about the template engine? Where does that fit?"))

    lines.append(("candidate", "The template engine sits between the router and the channel senders. Well, actually, it could sit in two places. Option A: the router renders the template before publishing to the channel topics, so the channel senders get fully rendered content. Option B: each channel sender renders its own template. I think Option A is better because we can centralize the template logic — one render pass, then format for each channel. But wait — each channel needs different formatting. An email template is HTML with a full layout, while push is a 200-character plain text summary. So maybe we don't render one template — we render per-channel variants from a common template definition. The template engine takes the template ID and variables, and produces channel-specific content."))

    lines.append(("candidate", "Actually, let me reconsider. If the template engine is synchronous in the router, a complex email template with loops and conditionals could slow down the routing. Better approach: the router determines which channels to use and publishes to each channel topic with the template ID and variables — unrendered. Each channel sender has its own lightweight template renderer, or we have a shared Template Service that channel senders call before sending. I'd go with a shared Template Service with a cache for compiled templates. The render time is under 5ms for most templates, and we cache the compiled template AST so we only parse once."))

    # SECTION 4: Deep Dive — Template Engine, Preferences, Rate Limiting, Deduplication (~8 min)
    lines.append(("interviewer", "Let's deep dive into the hardest parts. Start with the template engine."))

    lines.append(("candidate", "The template engine needs to handle a few things. First, template storage and versioning. Templates are stored in the database with version numbers — when a template is updated, we create a new version. In-flight notifications use the version that was active when they were created, so we never change content under a running notification. Second, template syntax — we need variable substitution, conditional blocks, and iteration for things like order line items. I'd use a Jinja2-like syntax that's familiar and well-understood. Third, per-channel rendering — a single template definition has sections for each channel: a push title and body, an email subject, HTML body, and plain text body, and an SMS body. The renderer selects the appropriate section."))

    lines.append(("candidate", "Wait, I want to reconsider the per-channel sections. That means every time you add a new channel, you need to update all templates. A better approach might be to have a single abstract template with structured data fields, and then have channel-specific formatters that know how to render that structured data. For example, the template defines title, summary, details, and action_url. The push formatter takes title and summary, truncates to fit, and adds the action_url as a deep link. The email formatter wraps everything in a branded HTML layout. The SMS formatter takes summary and shortens the URL. This is more maintainable — you write one template, and adding a new channel means writing a new formatter, not updating all templates."))

    lines.append(("interviewer", "That's a good evolution. What about template validation and preview?"))

    lines.append(("candidate", "Template validation happens at save time. We parse the template, check for syntax errors, and verify that all required channel sections are present. We also validate that the variables referenced in the template match the schema defined for that notification type. For preview, we provide an API that takes a template ID and sample variables, and returns the rendered output for each channel. This is important because marketing teams want to preview emails before sending campaigns. The preview service is stateless — it just renders on the fly."))

    lines.append(("interviewer", "Now let's talk about user preferences. How do you store and query them efficiently?"))

    lines.append(("candidate", "The preference model is a 3D matrix: user by notification type by channel. Each cell has an opt-in/opt-out status and possibly a quiet hours configuration. At 50M users, 10 notification types, and 3 channels, that's 1.5 billion cells. But in practice, most users have the default preference for most types — they only override when they opt out. So I'd use a sparse storage model: we store the default preferences per notification type per channel in a global config, and we only persist overrides for specific users. The lookup algorithm is: check for a user-specific override. If none, use the default. This reduces the storage from 1.5 billion to maybe 200 million override records — the users who have changed at least one preference."))

    lines.append(("candidate", "For the data model, I'd use a table with columns: user_id, notification_type, channel, status, updated_at. The primary key is user_id, notification_type, channel. For queries, when a notification needs to be sent, we look up all preference rows for that user and notification type across all channels. That's a single query returning at most 3 rows — one per channel. We cache the full preference set per user in Redis as a JSON object, keyed by user_id. The cache TTL is 5 minutes. On a cache miss, we load all preferences for the user — which is at most 30 rows — and populate the cache. This handles 12K reads per second easily with a small Redis cluster."))

    lines.append(("interviewer", "How do you handle preference updates? Cache invalidation is always tricky."))

    lines.append(("candidate", "On a preference update — user opts out of push for marketing emails, say — we write the new preference to the database, then delete the Redis cache key for that user. The next read will trigger a cache miss and reload. This is a simple cache-aside pattern. The risk is that a notification between the database write and the cache deletion could use stale preferences. But the window is tiny — milliseconds. And in the worst case, a user gets one unwanted notification before the cache expires. That's acceptable for most use cases. If we needed stronger consistency, we could update the cache directly instead of deleting it, but that introduces the risk of cache-database divergence if the database write fails after the cache update. I'd stick with delete-on-write."))

    lines.append(("interviewer", "Now let's talk about rate limiting and deduplication. How do these work together?"))

    lines.append(("candidate", "Rate limiting and deduplication are related but distinct. Deduplication says: don't send the same notification twice within 5 minutes. Rate limiting says: don't send more than N notifications per user per channel per time window. They both use Redis, but with different data structures. For deduplication, we use a Redis SET per user per notification type, storing the content fingerprints of recently sent notifications, with a TTL of 5 minutes. Actually, wait — a SET doesn't have per-member TTLs. Better to use individual keys with 5-minute TTLs: dedup:user123:order_confirmed:fingerprint_abc with TTL 300. Before sending, we check if the key exists. If it does, skip. If not, set it and proceed."))

    lines.append(("candidate", "For rate limiting, I'd use a sliding window counter in Redis. The key is ratelimit:user123:push:hour and it stores a sorted set of timestamps for recent sends. Before sending, we count the number of entries in the sorted set within the last hour. If it exceeds the limit — say 5 per hour for push — we skip the notification and log a rate limit event. After sending, we add the current timestamp to the sorted set and trim entries older than 1 hour. The sorted set is efficient for this — ZRANGEBYSCORE and ZCARD are O(log N) where N is the number of sends in the window, which is bounded by the rate limit itself. So it's effectively O(1)."))

    lines.append(("candidate", "Actually, I realize there's a subtlety with rate limiting. When we rate-limit a notification, should we drop it or defer it? For transactional notifications — like a security alert — we should never rate limit. The rate limit only applies to marketing and low-priority notifications. So we need a priority field on each notification type, and the rate limiter only applies to non-essential types. Essential notifications bypass rate limiting entirely. This also affects the template — transactional emails don't need unsubscribe links, but marketing emails do. So the priority classification ties into compliance as well."))

    lines.append(("interviewer", "Good catch. Let's talk about compliance more specifically. How do you enforce CAN-SPAM and TCPA?"))

    lines.append(("candidate", "Compliance is enforced at two points. First, at preference lookup time — if a user hasn't explicitly opted in to SMS marketing, we never send them marketing SMS. The preference model must distinguish between transactional opt-in and marketing opt-in. TCPA requires prior express consent for marketing SMS, so we need a separate consent flag that's only set when the user actively checks a box or texts a keyword. For email, CAN-SPAM requires that every marketing email includes an unsubscribe link and our physical mailing address. The template engine should automatically inject the unsubscribe link and footer for marketing email templates — it's not optional, it's baked into the rendering pipeline. We also need to process unsubscribe requests within 10 business days. When a user clicks unsubscribe, we update their preference to opt-out and invalidate the cache."))

    lines.append(("candidate", "For bounce handling, SES sends bounce notifications via SNS. We process these and mark the email address as bounced in our system. After 3 consecutive bounces, we automatically opt the user out of email for that notification type. Hard bounces — invalid email — opt out immediately. For SMS, Twilio sends delivery status webhooks. If a number is unreachable, we mark it and eventually stop trying. This is important because repeated sends to invalid numbers hurt our sender reputation and can get our account suspended by the providers."))

    lines.append(("interviewer", "What about device token management for push? APNs tokens can become invalid."))

    lines.append(("candidate", "Good point. APNs provides a feedback service that reports device tokens that are no longer valid — typically because the user uninstalled the app. We need to process this feedback and mark those tokens as inactive in our device registry. If we keep sending to invalid tokens, APNs may throttle or disconnect our connection. The device token registry is a separate table mapping user ID to device token, platform (iOS or Android), and app version. When we receive an invalid token report, we delete or deactivate that token entry. We also need to handle token migration — when Apple updates their token format, all tokens need to be refreshed, which the client app handles on next launch."))

    # SECTION 5: Failure Modes (~4 min)
    lines.append(("interviewer", "What are the most critical failure scenarios?"))

    lines.append(("candidate", "The first and most critical is provider failure. If APNs goes down — and it does, Apple has outages — all push notifications fail. We need a fallback strategy. For transactional push, we can fall back to email or SMS — the notification router should detect when push delivery failures spike and automatically escalate to the next preferred channel. This requires a feedback loop: the channel sender reports failure rates to the router, and the router adjusts its fan-out. For marketing push, we can just queue and retry later. Each channel sender should have a circuit breaker — if the failure rate exceeds 10 percent, open the circuit and stop sending to that provider for 30 seconds, then try again with a probe."))

    lines.append(("candidate", "The second failure scenario is deduplication cache loss. If the Redis node holding our dedup keys crashes, we lose the 5-minute dedup window and might send duplicate notifications. This is annoying but not catastrophic — it's a degraded experience, not a data loss. We mitigate by using Redis replication with automatic failover. A Redis cluster with replicas ensures that even if one node dies, the replica takes over with minimal data loss — at most a few seconds of writes."))

    lines.append(("candidate", "The third scenario is a Kafka partition leader failure. When a partition leader dies, Kafka elects a new leader, and there's a brief pause in consumption. During this pause, notifications are still being produced but not consumed. This is fine — the producers don't block, and consumers resume once the new leader is elected. The concern is the delay in processing. If the election takes 30 seconds and we're at peak, that's 90K queued notifications. When the consumer resumes, it processes them in a burst. The channel senders need to handle this burst without overwhelming the providers. We implement send throttling — even if 1000 notifications arrive at once for the push channel, we send them at a controlled rate, say 500 per second, to avoid getting rate-limited by APNs."))

    lines.append(("candidate", "The fourth scenario is database overload during a marketing burst. 500K notifications in a few minutes means 10K database writes per second, each creating a notification record and preference lookups. If the database can't keep up, the API layer starts returning 503s. We mitigate with a write-behind buffer: the API layer writes to Kafka first, and a separate consumer writes to the database asynchronously. The API returns 202 as soon as the event is in Kafka. This decouples the API from the database and smooths out write bursts. The tradeoff is that the status API might show PENDING for a few seconds until the database catches up, but that's acceptable."))

    # SECTION 6: Scale & Debrief (~3 min)
    lines.append(("interviewer", "How does the design change at 10x scale — 100M notifications per day?"))

    lines.append(("candidate", "At 100M per day, the peak TPS is around 30K. The database needs more shards — maybe 20 shards partitioned by user ID hash. The Kafka cluster needs more partitions — 100 to 200 for parallel consumption. The template engine, which is CPU-bound, needs horizontal scaling — maybe 10 instances behind a load balancer. The channel senders need more instances too. The big new concern is provider rate limits. APNs allows 10K notifications per second per app. At 60 percent of 100M, that's about 700 push per second on average, but bursts could exceed 10K. We'd need to implement batching — APNS supports sending multiple notifications in a single HTTP/2 connection — and potentially use multiple APNS certificates or tokens for higher throughput. For email, SES has its own sending limits that we'd need to request increases for. SMS costs scale linearly, so at 10M SMS per day, cost management becomes important — we might want to implement aggressive SMS deduplication and consolidation."))

    lines.append(("candidate", "At 0.1x scale — 1M per day — the design simplifies a lot. A single PostgreSQL instance, a single Redis node, and a single Kafka broker would suffice. The channel senders could be simple workers reading from SQS queues instead of Kafka, which reduces operational complexity. But the preference model, deduplication logic, and compliance enforcement stay the same — correctness and compliance don't scale down."))

    lines.append(("candidate", "One more consideration at 0.1x scale: the template engine might not need a separate service. We could embed the template rendering directly in the channel senders since the CPU load is minimal. The Notification Router and the channel senders could even be combined into a single process. This reduces operational overhead — fewer services to deploy and monitor. The architecture becomes a monolithic worker with the same logical components, just running in a single process. As scale grows, we split it back into separate services."))

    lines.append(("interviewer", "Let me give you feedback. Positives: your requirements clarification was thorough — you asked about compliance, deduplication, delivery tracking, and latency unprompted. The evolution of the template engine from per-channel sections to abstract templates with channel formatters was excellent — you recognized a maintainability problem and iterated on it. Your rate limiting design with the priority bypass for transactional notifications shows real product awareness. For improvement: when discussing provider failures, you didn't address the scenario where APNs returns a token invalidation — meaning the user has uninstalled the app. This requires updating the device token registry, and failing to do so wastes resources and can hurt your APNs connection. Also, you could have discussed the idempotency of notification sends more explicitly — what happens if a channel sender crashes after sending to APNs but before updating the notification status? The provider might send the notification twice on retry. Overall, very strong interview. Thanks."))

    lines.append(("candidate", "Thanks for the feedback. The token invalidation scenario is really important — I should have discussed the feedback service where APNs tells us about invalid tokens so we can clean up our device registry. And the idempotency point is valid — I should have mentioned that APNs has an HTTP/2 interface with a notification ID, so on retry we can use the same ID and APNs will deduplicate. Or at minimum, we should check our own send log before retrying. Good points to remember."))

    return lines
