"""Mock Interview: Object Storage like S3 — Two-voice dialogue."""


def build():
    lines = []

    # SECTION 1: Requirements (~5 min)
    lines.append(("interviewer", "Hi, today I'd like you to design an object storage service — something like Amazon S3. It should store arbitrary blobs, from small files to very large ones, with high durability and availability. Start by clarifying the requirements."))

    lines.append(("candidate", "Thanks. Object storage is a fundamental infrastructure problem — deceptively simple on the API surface but incredibly complex underneath. Let me start with the most important question: what's the durability target? S3 advertises 11 nines — 99.999999999 percent durability. Are we targeting the same, or is something less ambitious acceptable? Because 11 nines drives fundamentally different design decisions than, say, 5 nines."))

    lines.append(("interviewer", "Yes, 11 nines durability is the target. We also need 99.99 percent availability — 4 nines."))

    lines.append(("candidate", "11 nines durability means that if you store 10 million objects, you should expect to lose one object every 10,000 years. That is an extreme requirement. Next question: what's the scale — total stored data, number of objects, and request throughput? Also, what's the object size range? Are we storing tiny 1 KB config files or 5 TB video archives?"))

    lines.append(("interviewer", "100 petabytes of total data, about 1 trillion objects. Request rate is 1 million requests per second — mixed reads and writes. Object sizes range from 1 KB to 5 TB, with a bimodal distribution — lots of small objects and a smaller number of very large ones."))

    lines.append(("candidate", "1 trillion objects is enormous. The metadata system alone is a significant challenge. A few more questions. First, consistency model: after a write, are reads immediately consistent, or do we allow eventual consistency? S3 originally was eventually consistent, then added strong consistency. Second, do we need versioning — keeping multiple versions of the same object? Third, do we support multipart upload for large objects? Fourth, what operations do we need beyond PUT and GET — DELETE, LIST, COPY?"))

    lines.append(("interviewer", "We need strong consistency for overwrites — after a PUT completes, a GET should return the new data. Versioning is required — it is a key feature for enterprise customers. Multipart upload is essential for objects over 5 GB. We need DELETE and LIST operations. COPY is nice to have but not required for now."))

    lines.append(("candidate", "What's the typical write pattern? Are most writes new objects (create-heavy) or overwrites of existing objects? The consistency requirements are different — new object creates are naturally consistent since there's no stale data to worry about."))

    lines.append(("interviewer", "About 80 percent creates and 20 percent overwrites. Most workloads are append-heavy — log files, backups, user uploads. Overwrites happen mainly for configuration objects and website assets."))

    lines.append(("candidate", "Let me ask about the LIST operation semantics. With 1 trillion objects, listing all objects in a bucket is impractical. Do we support prefix-based listing with pagination? And what's the expected listing performance?"))

    lines.append(("interviewer", "Yes, prefix-based listing with pagination — return up to 1000 keys per request with a continuation token. Listing should return results within a few seconds even for buckets with billions of keys."))

    lines.append(("candidate", "What about the typical bucket size distribution? Are we dealing with a few massive buckets or millions of small ones? This affects the metadata partitioning strategy."))

    lines.append(("interviewer", "It varies widely. Some buckets have billions of objects — like log storage buckets — while others have just a few hundred. The average is probably around 10 million objects per bucket, but the distribution is heavily skewed."))

    lines.append(("candidate", "One more question: do we need server-side encryption, or is encryption a client-side responsibility? And what about object-level access control — is it bucket-level policies, or do we need per-object ACLs?"))

    lines.append(("interviewer", "Server-side encryption with customer-managed keys is required. Access control is bucket-level policies with IAM-style permissions — no per-object ACLs needed."))

    lines.append(("candidate", "Let me summarize. We're designing an object storage service at 100 PB scale, 1 trillion objects, 1M RPS, object sizes 1 KB to 5 TB, 11 nines durability, 4 nines availability, strong consistency on overwrites, versioning, multipart upload, prefix-based paginated listing, server-side encryption, and bucket-level IAM access control. Let me move to estimation."))

    # SECTION 2: Estimation (~5 min)
    lines.append(("interviewer", "Go ahead."))

    lines.append(("candidate", "100 PB of data. With replication factor of 3 for durability, that is 300 PB of raw storage. Wait — but 11 nines with just 3 replicas might not be sufficient. Let me think about this. The annual failure rate of a typical hard drive is about 2 to 4 percent. With 3 replicas, the probability of losing all 3 in a year is 0.02 cubed, which is 8 times 10 to the minus 6 — about 4 nines. That is nowhere near 11 nines. We need erasure coding for 11 nines. With erasure coding — say 12 data shards and 6 parity shards — the probability of losing 7 shards simultaneously out of 18 total is astronomically small. If each shard has a 2 percent annual failure rate, the probability of 7 out of 18 failing is a binomial calculation, but the result is far better than 11 nines. So erasure coding is essential for the durability target."))

    lines.append(("candidate", "With erasure coding at 12 plus 6, the storage overhead is 18 divided by 12, which is 1.5x — much better than 3x replication. So 100 PB times 1.5 is 150 PB of raw storage. But we also need replication for hot data — erasure coding is expensive for small reads because you need to access multiple shards. I would use a hybrid approach: replicate 3x for small, frequently accessed objects, and erasure code for large, infrequently accessed objects. Maybe 20 percent of data is hot and 80 percent is cold. So 20 PB replicated at 3x is 60 PB, and 80 PB erasure coded at 1.5x is 120 PB. Total raw storage: 180 PB. At current hard drive prices — let us say $15 per TB — that is about 2.7 million dollars in drives alone. With servers, networking, and facilities, maybe 8 to 10 million dollars in hardware."))

    lines.append(("interviewer", "What about the metadata storage?"))

    lines.append(("candidate", "1 trillion objects, each with metadata: object key, bucket ID, version ID, size, creation time, storage class, checksum, encryption key reference, and pointers to data locations. That is about 300 bytes per object. 1 trillion times 300 bytes is 300 TB of metadata. This needs to be in a database that supports fast key lookups and range scans for listing. A distributed key-value store like DynamoDB or a custom metadata service built on something like RocksDB would work. With 1M RPS and most requests needing a metadata lookup, the metadata service needs to handle 1M reads per second. With replication and caching, we would need maybe 100 to 200 metadata nodes. At peak, each node handles 5 to 10K reads per second from local RocksDB, which is well within its capability."))

    lines.append(("candidate", "For the LIST operation, we need an index sorted by bucket ID and object key prefix. This is essentially a B-tree index on the composite key. With 1 trillion entries, the B-tree might be 5 to 6 levels deep, and each level is an SSD read at about 100 microseconds. A single lookup takes about 0.5ms. A range scan returning 1000 keys is sequential and takes maybe 5 to 10ms. This meets the few-seconds requirement for listing. The B-tree index is stored alongside the metadata in each RocksDB instance, using the native sorted key feature of LSM trees."))

    lines.append(("candidate", "Wait, I should also estimate the cost of server-side encryption. Each object needs to be encrypted on write and decrypted on read. AES-256-GCM can encrypt at about 3 GB/s on modern hardware, so for a 1M RPS workload with an average object size of, say, 100 KB, the encryption throughput needed is 100 GB/s — about 34 CPU cores dedicated to encryption. This is feasible with hardware acceleration like AES-NI, which most servers have. The key management is handled by a separate KMS service — the metadata stores a reference to the customer master key, and the storage nodes request data encryption keys from the KMS at write time. The KMS returns the data key encrypted under the customer master key, and the storage node uses the plaintext data key for encryption. This way, the KMS is only involved in key generation, not in every read and write."))

    # SECTION 3: High-Level Architecture (~5 min)
    lines.append(("interviewer", "Good. Let's move to the high-level architecture."))

    lines.append(("candidate", "The system has four main components: the API Gateway, the Metadata Service, the Storage Nodes, and the Coordinator. Let me walk through a PUT operation. The client sends a PUT request with the bucket name, object key, and data. The API Gateway authenticates the request, checks IAM permissions, and forwards it to the Metadata Service. The Metadata Service checks if the bucket exists, generates a new version ID, and determines where to store the data — which storage nodes and which erasure coding or replication scheme to use based on the object size. It writes a pending metadata record with the version ID and storage locations, then returns the storage node addresses and a write token to the API Gateway."))

    lines.append(("candidate", "I should note that for small objects — under 16 MB — we can inline the data through the API Gateway rather than requiring a separate data path. The client sends the object in the PUT request body, the API Gateway forwards it to the Metadata Service, which returns storage node addresses, and the API Gateway sends the data to the storage nodes in parallel. This avoids the complexity of presigned URLs and direct uploads for the common small-object case. For larger objects, the API Gateway returns a presigned upload URL pointing to a data proxy, and the client uploads directly. This keeps the API Gateway lightweight for large transfers."))

    lines.append(("candidate", "The client then sends the data directly to the storage nodes — or through a data proxy if direct upload is not supported. For small objects under, say, 16 MB, we use replication — the data proxy sends the object to 3 storage nodes in parallel. For larger objects, we use multipart upload: the client splits the object into parts, uploads each part independently, and then calls a Complete Multipart Upload API. The Coordinator handles the multipart finalization — it assembles the parts, applies erasure coding if needed, distributes the shards to storage nodes, and notifies the Metadata Service."))

    lines.append(("interviewer", "Why separate the metadata from the data?"))

    lines.append(("candidate", "Metadata and data have very different access patterns and scaling requirements. Metadata is small but requires fast key lookups and range scans — it is essentially a database problem. Data is large and requires high-throughput sequential I/O — it is essentially a disk and network throughput problem. Mixing them would force us to use the same storage and scaling strategy for both, which is suboptimal. By separating them, we can scale metadata with fast SSD-backed database nodes and data with high-density HDD-backed storage nodes. Also, a LIST operation only touches metadata — it never needs to read the actual object data. Separation makes listing efficient and prevents listing from competing with data I/O."))

    lines.append(("candidate", "The Metadata Service is a distributed key-value store. The key is bucket ID plus object key plus version ID. For listing, we need range scans over bucket ID plus object key, so the primary index is on that composite key. We would partition metadata by bucket ID with sub-partitioning by key prefix. Each partition is a RocksDB instance with a write-ahead log for durability. Replication within the Metadata Service uses Raft consensus — each partition group has 3 replicas with a leader handling writes and followers serving reads."))

    lines.append(("candidate", "I should also address the authentication and authorization flow. When a client sends a PUT or GET request, the API Gateway first authenticates the request — verifying the access key and signature. Then it evaluates the bucket's IAM policy to determine if the action is allowed. IAM policies are stored in a separate policy database and cached at the API Gateway. Policy evaluation is fast — typically under 1ms for cached policies. For cross-account access — where one AWS account wants to read objects in another account's bucket — we evaluate both the bucket owner's policy and the requester's identity. This cross-account evaluation is more complex but still fast with caching."))

    lines.append(("candidate", "For a GET operation, the client sends GET with bucket and key. The API Gateway queries the Metadata Service, which returns the object's metadata: the storage locations, the version ID, the size, and the checksum. For a replicated object, the API Gateway or a data proxy reads from the nearest or least-loaded storage node and streams the data back to the client. For an erasure-coded object, we only need to read 12 out of 18 shards to reconstruct the data — we read the 12 data shards directly if they are all available. If some are unavailable, we read from parity shards to reconstruct. The client verifies the checksum and receives the data. For strong consistency, the metadata write must be committed before the metadata read can return the new version."))

    # SECTION 4: Deep Dive — Erasure Coding, Data Placement, Consistency (~8 min)
    lines.append(("interviewer", "Let's deep dive into erasure coding and data placement."))

    lines.append(("candidate", "Erasure coding uses Reed-Solomon codes. We split each object into 12 data shards of equal size, compute 6 parity shards, and store all 18 shards on different storage nodes in different failure domains. We can tolerate the loss of any 6 shards out of 18 — that is 6 simultaneous disk or node failures — without data loss. For a 1 GB object, each shard is about 83 MB. The read path is optimal when all data shards are available — we just read 12 shards of 83 MB each, total 1 GB of data read, which is the same as reading the object from a single replica. The overhead only appears on failure when we need to read parity shards and reconstruct."))

    lines.append(("candidate", "Wait, I need to correct myself. Reed-Solomon encoding has a significant CPU cost — encoding a 1 GB object with 12 plus 6 parameters takes non-trivial time. We should benchmark this, but it is probably in the range of 100 to 500 milliseconds on a modern CPU. For the write path, this is acceptable — the client is already waiting for the multipart upload to complete. But we should offload the encoding to the Coordinator nodes, which are optimized for CPU-intensive tasks, rather than doing it on the storage nodes, which are optimized for I/O. The Coordinator has a pool of encoding workers that process multipart completion requests in parallel."))

    lines.append(("interviewer", "How do you place the 18 shards to maximize durability?"))

    lines.append(("candidate", "Placement is critical for achieving 11 nines in practice, not just in theory. We need to ensure that the 18 shards for any single object are spread across different failure domains. A failure domain is a unit that can fail simultaneously — a disk, a server, a rack, a power circuit, or even an availability zone. I would organize storage nodes into a hierarchy: zone, rack, server, disk. When placing shards for an object, we first spread across availability zones — at least 3 zones, 6 shards per zone. Then within each zone, we spread across racks — no two shards on the same rack. This way, a zone outage takes out at most 6 shards, which is exactly our erasure coding tolerance. A rack failure within a zone takes out at most 1 shard. A disk failure takes out 1 shard."))

    lines.append(("candidate", "The placement algorithm works as follows. The Coordinator maintains a map of all storage nodes with their zone, rack, and current load. When placing a new object, it selects 18 nodes using a constraint solver: exactly 6 nodes per zone, no two in the same rack, and prefer nodes with lower utilization. For rebalancing after node failures, the same algorithm runs but only replaces the failed shards. We also need to avoid placing too many shards of the same popular object on nodes that are already busy — a simple load-awareness heuristic. The placement decisions are stored in the metadata so the Coordinator is stateless — it can reconstruct placement from metadata."))

    lines.append(("interviewer", "Let's talk about consistency after overwrite. How do you ensure strong consistency?"))

    lines.append(("candidate", "This is where the separation of metadata and data creates a challenge. When a client overwrites an object, we write the new data to storage nodes first, then update the metadata to point to the new data. But there's a window between the data write and the metadata update where a concurrent read might see the old metadata and return stale data. To achieve strong consistency, we need to make the metadata update atomic with respect to reads."))

    lines.append(("candidate", "Here is my approach. For a PUT, we write the data to all storage nodes first — 3 replicas for small objects, 18 shards for large ones. Each storage node writes the data to its local disk and returns a write acknowledgment with a checksum. Once all writes are acknowledged, we commit the metadata update. The metadata update is a compare-and-swap operation: update the object's metadata from version V-old to V-new only if the current version is still V-old. This happens atomically within the metadata Raft group. After the metadata commit, any subsequent GET reads the new metadata and returns the new data. The critical guarantee is: reads always see metadata that points to fully written data."))

    lines.append(("candidate", "But there is a subtle issue. What if the metadata commit fails because another write already updated the version? Then we have orphaned data on the storage nodes — the new data was written but the metadata does not point to it. We need garbage collection for this, which I will discuss later. And what about the case where the metadata commit succeeds but the client never receives the acknowledgment? The data is durable and consistent — the client just does not know it. They will retry the PUT, but the idempotency of the version check will handle it — the metadata is already at the new version, so the retry is a no-op."))

    lines.append(("interviewer", "What about versioning? How does that change the consistency model?"))

    lines.append(("candidate", "With versioning enabled, overwrites do not actually overwrite — they create a new version. Each PUT generates a new version ID, and the metadata stores the full version history as a linked list. The latest pointer is updated atomically. A GET without a version ID returns the latest version. A GET with a specific version ID returns that version. This actually simplifies consistency — there is no overwrite, only append. The atomic update is just appending a new version to the list and moving the latest pointer. Old versions remain accessible until explicitly deleted. The tradeoff is storage — every version consumes space, and we need lifecycle policies to expire old versions. For compliance-sensitive workloads, we might need to retain all versions indefinitely, which can be expensive."))

    lines.append(("interviewer", "Now let's talk about garbage collection. How do you reclaim space from deleted and orphaned objects?"))

    lines.append(("candidate", "Garbage collection in an object store is tricky because we can't use reference counting efficiently across a distributed system. I would use a tombstone-and-journal system. When an object is deleted, we write a tombstone to the metadata and add the data locations to a garbage queue. The garbage collector processes this queue asynchronously — it verifies that the metadata still has a tombstone for this object, then deletes the data from storage nodes. For orphaned data from failed writes, the write process itself adds cleanup entries to the garbage queue. This way, the garbage collector does not need to scan — it just processes a bounded queue."))

    lines.append(("candidate", "For incomplete multipart uploads — where a client started uploading parts but never called Complete — we need a lifecycle rule. We set a deadline of 7 days for multipart uploads. A background job scans for incomplete uploads older than 7 days, aborts them, deletes the uploaded parts, and adds the part locations to the garbage queue. This prevents clients from accumulating orphaned parts indefinitely. The garbage queue itself is stored in the metadata database, so it is durable. The garbage collector processes entries in batches, removing data from storage nodes in parallel to maximize throughput. We also run a reconciliation scan once a week — a full comparison of metadata against storage node contents — to catch any leaks that did not get a garbage queue entry."))

    # SECTION 5: Failure Modes (~4 min)
    lines.append(("interviewer", "What are the most critical failure scenarios?"))

    lines.append(("candidate", "The first is a storage node failure. A node goes down with 20 TB of data on it — some of it replicated, some erasure-coded. For replicated objects, we read from other replicas — no data loss, slight latency increase. For erasure-coded objects, we read from remaining shards — no data loss as long as fewer than 7 shards are missing. For repair, the Coordinator detects the node failure via heartbeat and triggers a rebuild: for each replicated object on the failed node, it copies from a surviving replica to a new node. For each erasure-coded shard, it reconstructs from the other 17 shards and writes to a new node. This is a background process that might take hours for a full node, but it runs incrementally — priority is given to objects that are close to their redundancy limit."))

    lines.append(("candidate", "The second scenario is a metadata service failure. If a metadata partition leader crashes, Raft elects a new leader within seconds. During the election, writes to that partition are briefly unavailable, but reads can continue from followers. For a full metadata service outage — unlikely with Raft replication — the system becomes read-only: existing objects can still be served because the data proxies cache metadata, but new writes are rejected. The third scenario is a consistency bug — the metadata points to data that does not exist or is corrupted. This violates our durability guarantee. We detect this through checksum verification: every GET computes the object's checksum and compares it with the metadata. A mismatch triggers an alert and automatic repair from redundant copies or shards."))

    lines.append(("candidate", "The fourth scenario is an availability zone outage. If an entire zone goes down — power failure, network cut — we lose 6 out of 18 shards for erasure-coded objects and 1 out of 3 replicas for replicated objects. Both are within our redundancy tolerance, so no data loss. Reads continue from surviving zones with increased latency. The Coordinator starts rebuilding shards to restore redundancy, spreading the new shards across the surviving zones temporarily. When the failed zone recovers, we rebalance back to the optimal 6-per-zone distribution. The rebuild generates massive cross-zone traffic, which we throttle to avoid impacting foreground reads and writes. Typically we limit rebuild traffic to 10 percent of network bandwidth, which means a zone recovery might take 12 to 24 hours for a full 100 PB dataset."))

    # SECTION 6: Scale & Debrief (~3 min)
    lines.append(("interviewer", "How does the design change at 10x scale — 1 exabyte?"))

    lines.append(("candidate", "At 1 exabyte, we are talking about 10,000 to 20,000 storage nodes. The placement algorithm needs to be much more sophisticated — with that many nodes, the probability of multiple correlated failures increases. We would need hierarchical erasure coding — erasure code within a zone for fast repair, and cross-zone replication for zone-level protection. The metadata service at 10 trillion objects needs about 3 PB of metadata storage, which is itself a significant distributed database. We would need more metadata partitions — maybe 1000 to 2000 — each managing about 5 to 10 billion objects. The garbage collection problem scales too — with more nodes and more data, the queue-based approach still works, but the weekly reconciliation scan becomes a major operation that needs careful scheduling to avoid impacting performance."))

    lines.append(("candidate", "At 0.1x scale — 10 PB — the design simplifies. We might have 200 to 500 storage nodes, which could all be in a single data center. Erasure coding still makes sense for cost efficiency, but the zone-level redundancy might become optional if we have good rack-level isolation. The metadata service could be a single Raft cluster with 5 nodes. The Coordinator could be a single stateless service. But the core data path — separate metadata and data, erasure coding for large objects, replication for small ones, versioning — stays the same. Durability does not scale down."))

    lines.append(("interviewer", "Let me give you feedback. Positives: excellent requirements clarification — you immediately identified durability as the key constraint and asked about versioning, multipart upload, consistency, and encryption unprompted. Your erasure coding analysis with the shard placement across failure domains was thorough and well-reasoned. The consistency protocol with compare-and-swap metadata updates shows strong understanding of distributed consistency. The evolution from full-scan garbage collection to a queue-based approach with incomplete multipart lifecycle rules was comprehensive. For improvement: you didn't discuss the multipart upload flow in enough detail — specifically, how parts are tracked before completion, what happens when a part upload fails mid-stream, and how the final object is assembled from parts on the Coordinator. Also, you could have discussed the encryption integration more — how server-side encryption with customer-managed keys affects the metadata model and the read path. Overall, excellent. Thanks."))

    lines.append(("candidate", "Thanks for the feedback. The multipart upload detail is important — each part is stored as an independent object with a temporary key referencing the upload ID, and the Coordinator tracks the list of expected parts. A failed part upload is simply retried by the client. On completion, the Coordinator reads all parts from their storage locations, concatenates them in order, and writes the resulting object through the normal write path. For encryption, the metadata stores a reference to the customer's key in the KMS, and the storage nodes encrypt data at rest using data keys wrapped by the customer master key. The encryption happens on the storage nodes, transparent to the client. Good points to cover in more depth next time."))

    return lines
