"""Mock Interview: Rate Limiter — Two-voice dialogue."""


def build():
    lines = []

    # SECTION 1: Requirements (~5 min)
    lines.append(("interviewer", "Hi, welcome. Today I'd like you to design a rate limiter — the kind you'd find in an API gateway that protects backend services from being overwhelmed. Think of something like Stripe's rate limiting or AWS API Gateway throttling. Start by clarifying the requirements."))

    lines.append(("candidate", "Thanks. Rate limiting sounds simple on the surface but there's a lot of nuance once you dig in. Let me start with the most basic question: what kind of system is this rate limiter protecting? Is it a public-facing API with many independent users, an internal microservice gateway, or something else? Because the granularity and distribution requirements change a lot depending on the answer."))

    lines.append(("interviewer", "Good question. We're building a rate limiter for a public-facing API gateway. Thousands of external clients — developers, mobile apps, partner services — call our APIs. We need to enforce per-user limits, and also global limits to protect backend capacity. Think of it as a shared API gateway for a platform like Twilio or Stripe."))

    lines.append(("candidate", "OK, so multi-tenant, public-facing, both per-user and global limits. Next I'd want to understand the granularity. Are we rate limiting per API endpoint, per user across all endpoints, or both? And what's the time window — per second, per minute, per hour? Also, do different users have different tiers — like free users get 100 requests per minute and paid users get 1000?"))

    lines.append(("interviewer", "We need hierarchical rate limiting — per-user per-endpoint, per-user global, and per-endpoint global. Users have tiers with different limits. Time windows vary — some limits are per-second for burst protection, others are per-minute or per-hour for quota enforcement. We need to support configurable windows."))

    lines.append(("candidate", "Hierarchical rate limiting with configurable windows and tiers — that's a real-world requirement, not a toy. Let me ask about the response behavior. When a request is rate-limited, do we reject it immediately with HTTP 429, or do we queue it and try to process it later? And should we return rate limit headers like X-RateLimit-Limit, X-RateLimit-Remaining, and X-RateLimit-Reset so clients can self-regulate?"))

    lines.append(("interviewer", "We reject immediately with 429 Too Many Requests and include a Retry-After header. And yes, we must return those rate limit headers on every response — not just 429s — so clients can track their usage. Also, we need strict limits — no overselling. If the limit is 100 per minute, the 101st request must be rejected, not conditionally accepted."))

    lines.append(("candidate", "Strict limits are important because they rule out some algorithms. Leaky bucket with a queue, for instance, delays excess requests rather than rejecting them — that's more like traffic shaping than rate limiting. Let me ask about distribution. Is this a single server or a distributed system? Because if we have multiple gateway instances, we need shared state for per-user limits, which introduces all the fun distributed systems problems."))

    lines.append(("interviewer", "It's distributed — we run dozens of gateway instances across multiple data centers. Per-user limits must be globally consistent. You can't have a user hitting 80% of their limit on each of two instances and getting 160% total."))

    lines.append(("candidate", "Right, so we need a centralized or replicated counter store. Let me also ask about failure semantics — if the rate limiter's backing store is down, do we fail open and let all requests through, or fail closed and reject everything? And what about consistency — is it OK if two concurrent requests from the same user both get through because they read the counter at the same time?"))

    lines.append(("interviewer", "Great questions. We prefer fail-open for availability — a rate limiter should not become a single point of failure that takes down the entire API. But we need to alert aggressively and recover quickly. For consistency, strict limits mean we can't allow race conditions to let extra requests through. You need to address that."))

    lines.append(("candidate", "Fail-open with strict limits is a tension — if the store is down, we're not enforcing limits at all. I'll need to think about how to mitigate that. Let me summarize: distributed rate limiter for a public API gateway, hierarchical limits at per-user-per-endpoint, per-user-global, and per-endpoint-global levels, configurable time windows, multiple user tiers, strict enforcement with no race-condition overselling, HTTP 429 with Retry-After and rate limit headers, fail-open on backing store failure, and global consistency across multiple data centers. Let me move to estimation."))

    # SECTION 2: Estimation (~5 min)
    lines.append(("interviewer", "Go ahead with the numbers."))

    lines.append(("candidate", "Let's think about scale. A platform like Stripe processes maybe 500 requests per second average and 5x that at peak, so 2,500 TPS. But that's application-level throughput. The rate limiter sees every request before it hits the backend, so it needs to handle at least 2,500 checks per second, plus any retries that also get checked. With retries, maybe 3,000 TPS. Actually, wait — the rate limiter also sees the requests that it rejects. So if 10% of requests are rate-limited, the limiter processes about 3,300 checks per second at peak. Let me round to 5,000 TPS to be safe."))

    lines.append(("candidate", "Now, how many distinct rate limit counters do we need? Per-user per-endpoint — if we have 100K active users and 50 endpoints, that's 5 million potential counters. But most users only hit a few endpoints, so maybe 2 million active counters at any time. Per-user global — 100K counters. Per-endpoint global — 50 counters. So roughly 2.1 million active counters. Each counter needs to store the current count and the window start time. That's about 50 bytes per counter — so roughly 100 MB of hot state. This fits comfortably in Redis."))

    lines.append(("interviewer", "What about write throughput? Every request that passes the rate limiter increments multiple counters."))

    lines.append(("candidate", "Right, that's the real bottleneck. Each allowed request increments three counters — per-user-per-endpoint, per-user-global, and per-endpoint-global. At 5,000 TPS, that's 15,000 writes per second to Redis. A single Redis node handles 100K+ ops per second, so we're fine. At 10x, we'd shard by user ID, keeping all counters for a user on one shard — important for atomicity."))

    lines.append(("interviewer", "What about read traffic? Do you check the counter before incrementing, or do you increment and check after?"))

    lines.append(("candidate", "Hmm, that's actually a design choice that affects correctness and performance. If I check-then-increment, that's two Redis round trips. I could just increment and check the result — one round trip. But wait, if I increment first and then reject, I've already bumped the counter for a rejected request, which means subsequent requests might get unfairly blocked. Let me think... Actually, for strict limits, I need to atomically check and increment. Otherwise two concurrent requests could both read 99, both increment to 100, and both be allowed when the limit was 100. So I need a Lua script in Redis that checks and conditionally increments in one atomic operation."))

    lines.append(("candidate", "For rejected requests, I shouldn't increment at all. The Lua script checks the counter — if it's below the limit, increments and returns allowed. If at or above, returns rejected without incrementing. Rejected requests don't pollute the counter. I can log rejections separately for analytics."))

    lines.append(("interviewer", "Good reasoning. Let's move to the architecture."))

    # SECTION 3: High-Level Architecture (~5 min)
    lines.append(("candidate", "Here's the overall design. The API gateway instances each run a rate limiter middleware. When a request arrives, the middleware extracts the user ID from the auth token and the endpoint from the request path. It then checks the rate limit counters in Redis using an atomic Lua script. The script takes the user ID, endpoint, and the configured limits for the user's tier, and checks all three levels — per-user-per-endpoint, per-user-global, and per-endpoint-global. If any limit is exceeded, the script returns immediately with which limit was violated. If all checks pass, it increments all three counters atomically and returns allowed."))

    lines.append(("candidate", "The response includes the rate limit headers regardless of whether the request is allowed or rejected. X-RateLimit-Limit shows the most restrictive limit that applies — if the per-user-per-endpoint limit is 100 and the per-user-global limit is 500, and the per-endpoint check was the one closest to being exceeded, we show that limit. X-RateLimit-Remaining shows how many requests are left under the most restrictive limit. X-RateLimit-Reset shows the Unix timestamp when the current window resets. For 429 responses, we also include Retry-After, which is the number of seconds until the window resets."))

    lines.append(("interviewer", "Why run the rate limiter as middleware in the gateway rather than as a separate service?"))

    lines.append(("candidate", "Good question. A separate rate limiter service would add a network hop and latency to every request — probably 1 to 2 milliseconds extra. At 5K TPS, that's significant. Running it as middleware inside the gateway means the Redis round trip is the only additional latency, which is typically under 1 millisecond if the Redis instance is in the same data center. Also, if the rate limiter service goes down, all requests fail — it's a critical dependency. With middleware, the rate limiter is co-located with the gateway and only depends on Redis, which is easier to make highly available."))

    lines.append(("candidate", "Actually, let me reconsider. There is an argument for a separate service — centralized configuration. If we have dozens of gateway instances, updating rate limit rules means updating all of them. But the latency cost is hard to justify. A compromise: rate limit rules live in a configuration service and are pulled by each gateway periodically, while the checks run as local middleware hitting Redis. Centralized config without the extra network hop."))

    lines.append(("interviewer", "How does the Redis Lua script work exactly? Walk me through the logic."))

    lines.append(("candidate", "The script receives the user ID, endpoint, current timestamp, and the list of limits to check. For each limit, there's a Redis key like rate_limit:{user_id}:{endpoint}:{window} or rate_limit:{user_id}:global:{window}. The script reads each key to get the current count and window start. If the current time is past the window start plus the window duration, the window has expired, so it resets the counter to 1 and updates the window start. If the window is still active and the count is at or above the limit, it returns rejected with the specific limit that was exceeded. If all checks pass, it increments each counter by 1 and returns allowed with the remaining counts. The whole thing runs atomically within a single Redis EVAL call."))

    lines.append(("candidate", "Wait, I'm describing a fixed window algorithm here. The problem with fixed windows is the boundary condition — if the limit is 100 per minute, a user can send 100 requests at 11:59:59 and another 100 at 12:00:01, getting 200 requests in 2 seconds. That's a 2x burst at window boundaries. For a public API with strict limits, that might not be acceptable. Let me reconsider the algorithm choice — this is actually one of the most important design decisions."))

    # SECTION 4: Deep Dive — Algorithms, Distributed Rate Limiting, and Throttling Responses (~10 min)
    lines.append(("interviewer", "You just identified the fixed window boundary problem. Let's dig into the algorithms. Walk me through the options and tradeoffs."))

    lines.append(("candidate", "There are four main algorithms. Fixed window is the simplest — you have a counter per time window that resets when the window expires. It's easy to implement and memory-efficient. But the boundary problem can allow 2x the rate in a short period. Sliding window log stores a timestamp for every request and counts how many fall within the sliding window. It's perfectly accurate — no boundary problems — but it's memory-intensive because you store every request timestamp, and computationally expensive because you need to count timestamps in the window on every check. At 5K TPS, storing a timestamp per request and scanning them is expensive."))

    lines.append(("candidate", "Sliding window counter is a hybrid — it combines two fixed windows weighted by their overlap with the current sliding window. For example, if the current time is 70% through the current minute window, the estimated count is 70% of the previous window's count plus the current window's count. This gives approximate sliding window behavior with fixed window efficiency. The approximation is good enough for most use cases — the worst case is slightly more than the limit, but nowhere near 2x like fixed window. And then there's the token bucket algorithm, which models a bucket that fills with tokens at a constant rate. Each request consumes one token. If the bucket is empty, the request is rejected. The bucket has a maximum capacity, which allows for controlled bursts — if the bucket is full, a burst of requests up to the bucket capacity can be served immediately. This is what AWS and Stripe use."))

    lines.append(("interviewer", "Which algorithm would you choose for our system?"))

    lines.append(("candidate", "Hmm, let me think about this. Our requirements are strict limits, configurable windows, and hierarchical levels. Token bucket is memory-efficient — one bucket per counter — but it doesn't naturally map to '100 requests per minute' semantics. With token bucket, you specify a replenishment rate and a burst capacity. At 100 per minute, that's about 1.67 tokens per second. After a quiet period, the bucket fills to 100 tokens. A burst of 100 requests drains it, then it refills at 1.67 per second. This allows bursts after quiet periods while enforcing the average rate over time."))

    lines.append(("candidate", "But strict limits mean no overselling. With a burst capacity of 100, an idle user can send 100 requests instantly, then 100 more as the bucket refills — that's 200 in just over a minute. The issue is concentration: 100 in the first second, then nothing for 59 seconds. Whether that's acceptable depends on whether we're protecting against average load or peak load on the backend."))

    lines.append(("interviewer", "We need to protect against both. Backends can't handle 100 concurrent requests in 1 second just because the user was quiet before. What would you recommend?"))

    lines.append(("candidate", "In that case, I'd use a combination. Token bucket with a lower burst capacity for burst protection — say, replenishment rate of 100 per minute but burst capacity of 20. This means a user can never send more than 20 requests in a burst, and they average 100 per minute over time. The burst capacity acts as a per-second rate limit implicitly. Actually, even better — I'd use two layers. A token bucket for the per-minute or per-hour quota, and a separate sliding window counter for per-second burst protection. The per-second window is so short that the sliding window approximation error is negligible — a 2x burst in a 1-second window is only 2 extra requests, not 200. This is what Stripe does — they have per-second and per-minute limits, and the per-second limit acts as a burst cap."))

    lines.append(("candidate", "Wait, let me reconsider again. For simplicity and correctness, sliding window counter is the best single algorithm for our use case. It gives approximate sliding window semantics with fixed window memory efficiency. The approximation error is bounded — we might allow a few percent more than the strict limit, but we can compensate with a safety margin. And it maps naturally to 'N requests per T seconds' semantics, which is what API users expect. Token bucket is great for network traffic shaping, but for API rate limiting where users think in terms of 'how many requests per minute,' sliding window counter is more intuitive."))

    lines.append(("interviewer", "OK, let's go with sliding window counter. Now, how do you implement it in a distributed setting with Redis?"))

    lines.append(("candidate", "For sliding window counter in Redis, we store two keys per rate limit rule: the current window counter and the previous window counter. Each key has a TTL equal to the window duration, so expired windows are automatically cleaned up. The Lua script takes the current timestamp, the user ID, the endpoint, and the limit configuration. It computes which window the current time falls in — for a 1-minute window, the window key includes the minute number, like rate_limit:{user}:{endpoint}:1689120000. It reads the current window counter and the previous window counter. Then it calculates the weighted count: previous_window_count times the fraction of the previous window that overlaps the current sliding window, plus the current window count. If this weighted count is below the limit, it increments the current window counter and returns allowed. Otherwise, it returns rejected without incrementing."))

    lines.append(("candidate", "The overlap fraction is calculated as 1 minus the position within the current window. For example, if the current time is 45 seconds into a 60-second window, the overlap fraction is 1 minus 45 over 60, which is 0.25. So the estimated count is 0.25 times the previous window count plus the current window count. This approximation assumes a uniform distribution of requests within the previous window, which isn't always true, but it's close enough for rate limiting. The worst case is a burst at the end of the previous window and a burst at the start of the current window — the sliding window counter might slightly underestimate the true count, potentially allowing a few percent more requests than the strict limit. We can compensate by setting the effective limit to, say, 95% of the stated limit."))

    lines.append(("interviewer", "You mentioned atomicity. What happens with concurrent requests from the same user hitting different gateway instances?"))

    lines.append(("candidate", "This is the race condition problem. If two requests from the same user arrive at two different gateway instances at the same time, both could read the counter, see it's at 99, both increment, and now the counter is at 101 — exceeding the limit of 100. Two extra requests got through. The Lua script solves this because Redis executes Lua scripts atomically — no other commands run between the reads and writes in the script. So even if two gateway instances send EVAL commands simultaneously, Redis serializes them. The first script sees 99, increments to 100, and returns allowed. The second script sees 100, which is at the limit, and returns rejected. This is why we must use a Lua script instead of separate GET and INCR commands."))

    lines.append(("candidate", "But there's a subtlety with the sliding window counter. The Lua script reads two keys — the current window and the previous window — does a calculation, and then conditionally increments the current window. If two scripts run concurrently, they both read the same previous window count and current window count, both compute the same weighted count, and both decide to increment. But since Lua scripts are atomic in Redis, this can't actually happen — the second script won't start until the first one finishes. So the atomicity is guaranteed by Redis's single-threaded execution model for Lua scripts."))

    lines.append(("interviewer", "What if we can't use Redis — or what if we need even lower latency? Could we do rate limiting locally on each gateway instance?"))

    lines.append(("candidate", "We could, but it only works for per-instance limits. If the per-user limit is 100 per minute and we have 10 instances, each gets a quota of 10 — but if all of a user's requests hit the same instance, they can only use 10 of their 100-request budget. Dynamic quota rebalancing adds complexity, and if an instance crashes, its quota is lost. Gossip-based protocols introduce eventual consistency — not strict enough. For strict limits, centralized Redis with Lua scripts is the right choice."))

    lines.append(("candidate", "Actually, we could use a hybrid — local rate limiting for short windows like per-second burst protection, and centralized Redis for longer windows. The per-second limit protects the gateway from a single connection flooding it, and local state is fine because the burst comes from one connection to one instance. Per-minute and per-hour limits need global consistency, so they go to Redis. This reduces Redis load because per-second checks are local."))

    lines.append(("interviewer", "Now let's talk about the throttling response. What exactly does the 429 response look like?"))

    lines.append(("candidate", "The 429 response should include all the rate limit headers plus Retry-After. On every response — 200, 400, 429 — we include X-RateLimit-Limit, X-RateLimit-Remaining, and X-RateLimit-Reset. For the most restrictive limit that applies to this request, X-RateLimit-Limit shows the configured limit, X-RateLimit-Remaining shows the remaining count after this request, and X-RateLimit-Reset shows the Unix timestamp when the window resets. For 429 responses specifically, we also include Retry-After. The value can be either the number of seconds until the window resets or an HTTP-date. I prefer seconds because it's easier for programmatic clients to use. The Retry-After value is the window reset time minus the current time, in seconds."))

    lines.append(("candidate", "One design question: with hierarchical limits, which remaining count do we show? If per-user-per-endpoint has 50 remaining but per-user-global has 200, showing 50 is most useful — it's the binding constraint. Stripe just shows the per-project limit. I'd do the same — show the most restrictive limit's numbers, and document the hierarchy in the API docs."))

    lines.append(("interviewer", "What about the response body for 429?"))

    lines.append(("candidate", "The body should be a JSON object with an error type and a human-readable message. Something like { 'error': { 'type': 'rate_limit_exceeded', 'message': 'Rate limit exceeded. Retry after 45 seconds.', 'retry_after': 45 } }. This gives programmatic clients a structured error to parse and human developers something readable. Some APIs also include a documentation link in the error response pointing to their rate limit policy page, which is a nice touch."))

    # SECTION 5: Failure Modes (~4 min)
    lines.append(("interviewer", "Let's talk about failure modes. What happens when Redis goes down?"))

    lines.append(("candidate", "This is the fail-open versus fail-closed decision we discussed earlier. If Redis is down and we fail-closed, every request gets a 429, which effectively takes our entire API offline. That's catastrophic — the rate limiter becomes a single point of failure worse than the problem it's solving. If we fail-open, all requests pass through without rate limiting, which risks overwhelming backends but keeps the API available. For our system, I'd fail-open with aggressive mitigations."))

    lines.append(("candidate", "The mitigations are: first, Redis should be in a cluster with replicas — Redis Sentinel or Redis Cluster with automatic failover, giving us sub-second failover. Second, each gateway instance maintains a local in-memory cache of recently seen rate limit decisions. If Redis is unreachable, the gateway uses the local cache as a fallback — it's not globally consistent, but it provides some protection based on the traffic each instance has seen recently. Third, we alert immediately when Redis connectivity drops — page the on-call team. Fourth, the backend services should have their own coarse rate limiting as a defense-in-depth measure, independent of the gateway's Redis-backed limiter. This way, even if the gateway fails open, backends aren't completely unprotected."))

    lines.append(("interviewer", "What about partial failures — Redis is up but slow, or some shards are down?"))

    lines.append(("candidate", "If Redis is slow, the rate limiter adds latency to every request. We should set a timeout on the Redis call — say, 5 milliseconds. If the call exceeds the timeout, we treat it as a failure and fall back to the local cache, same as if Redis were down. This prevents a slow Redis from degrading the entire API's latency. For partial shard failures in a Redis Cluster, we'd fail-open for the users whose counters are on the affected shard and continue enforcing limits for users on healthy shards. This is better than all-or-nothing."))

    lines.append(("candidate", "There's another failure mode I want to mention: the Lua script itself could have a bug that corrupts counters. If a script bug causes counters to never increment, no requests get rate-limited — it's a silent failure. We need monitoring on the rate limiter's effectiveness — tracking the ratio of allowed to rejected requests, alerting if the rejection rate drops to zero unexpectedly, and comparing the rate limiter's counts against actual backend traffic. This is a backstop against logical failures, not just infrastructure failures."))

    lines.append(("interviewer", "What about clock skew in a distributed system? Your sliding window algorithm depends on timestamps."))

    lines.append(("candidate", "Good catch. Since all counter operations happen in Redis, the key is to use Redis's own TIME command instead of the gateway's local clock. The Lua script calls TIME internally, so all decisions are based on a single clock — Redis's clock. This eliminates clock skew entirely."))

    # SECTION 6: Scale & Debrief (~3 min)
    lines.append(("interviewer", "How does this design scale to 10x — 50K TPS?"))

    lines.append(("candidate", "At 50K TPS, we need 150K Redis writes per second for the three-level hierarchy. A single Redis shard handles about 100K ops per second, so we'd need at least 2 shards, probably 4 for headroom. We shard by user ID using consistent hashing, so all counters for a user live on the same shard. This is critical — if the per-user-per-endpoint counter and the per-user-global counter were on different shards, the Lua script would need to access two shards, which Redis doesn't support atomically. By co-locating all counters for a user on one shard, the atomic Lua script works without change. Consistent hashing means adding or removing shards only moves a fraction of users, minimizing disruption."))

    lines.append(("candidate", "At 50K TPS, we should also consider network bandwidth between gateways and Redis. Each Lua script call is about 200 bytes in, 100 bytes out. At 50K TPS, that's 10 MB/s inbound and 5 MB/s outbound — negligible over a 10 Gbps link. The real concern is connections — 50K TPS across 50 gateway instances is 1,000 TPS per instance. Each instance uses a Redis connection pool of 10 to 20 connections. Redis handles 10K connections comfortably."))

    lines.append(("candidate", "At 0.1x scale — 500 TPS — a single Redis instance with no sharding suffices. The Lua script is unchanged. The main simplification is no sharding and no local fallback cache — if Redis goes down at 500 TPS, the backend can probably handle the brief unthrottled traffic until Redis recovers."))

    lines.append(("interviewer", "One more thing — what about multi-region deployment? If we have gateways in US-East and EU-West, and the Redis cluster is in US-East, EU users have higher latency for rate limit checks."))

    lines.append(("candidate", "Multi-region is the hardest part. Option one: local Redis clusters per region. Per-user counters live in the nearest region's Redis. But this breaks global limits — a user could send 100 requests per minute to both US and EU regions, exceeding the global limit. Option two: accept cross-region latency for global checks. Per-user-per-endpoint limits are checked locally, but global and per-endpoint limits go to centralized Redis — adding 50 to 100 milliseconds. A better approach: enforce global limits asynchronously — each region periodically sends counter increments to a central aggregation service, which computes global counts and pushes updated thresholds back. Small window of inconsistency, but low latency. For strict global limits, we'd need synchronous cross-region checks. It's a tradeoff."))

    # SECTION 7: End-to-End Walkthrough (~4 min)
    lines.append(("interviewer", "Walk me through a single request end-to-end — from arrival at the gateway to accept or reject."))

    lines.append(("candidate", "Let's trace a request from a user named Alice, who's on the paid tier with a per-user-per-endpoint limit of 1000 per minute, a per-user-global limit of 5000 per minute, and a per-endpoint-global limit of 50,000 per minute. Alice sends a POST to /api/messages at time T equals 1,689,123,045 — that's 45 seconds into the current minute."))

    lines.append(("candidate", "Step 1: The request hits the gateway. The authentication middleware extracts Alice's user ID — let's say user_12345 — from the JWT token in the Authorization header. Step 2: The rate limiter middleware kicks in. It looks up Alice's tier configuration — paid tier, limits as I described. It identifies the endpoint as /api/messages. Step 3: The middleware constructs the Redis keys. For the per-user-per-endpoint limit, the key is rl:user_12345:/api/messages:1689123000 — the 3000 is the minute-level window ID. For the per-user-global limit, the key is rl:user_12345:global:1689123000. For the per-endpoint-global limit, the key is rl:/api/messages:global:1689123000. It also needs the previous window keys — the same but with 1689122940, which is the previous minute."))

    lines.append(("candidate", "Step 4: The middleware sends an EVAL command to Redis with the Lua script. The script runs atomically. Inside the script, it first calls TIME to get Redis's server time — let's say it's 1,689,123,046, one second later. It computes the current minute window ID as 1,689,123,000. The position within the window is 46 out of 60 seconds, so 0.767 of the way through the current window. The overlap weight for the previous window is 1 minus 0.767, which is 0.233."))

    lines.append(("candidate", "Step 5: The script reads the six keys — current and previous for each of the three limits. Let's say the per-user-per-endpoint current count is 800 and the previous count is 950. The weighted count is 0.233 times 950 plus 800, which is about 1021. That exceeds the limit of 1000! The script returns rejected immediately with details: the violated limit is per-user-per-endpoint, the limit is 1000, the current weighted count is 1021, and the window resets at 1,689,123,060 — which is in 14 seconds."))

    lines.append(("candidate", "Step 6: The middleware receives the rejection response. It constructs the HTTP response: status 429 Too Many Requests. Headers: X-RateLimit-Limit is 1000, X-RateLimit-Remaining is 0, X-RateLimit-Reset is 1689123060, and Retry-After is 14. The body is { 'error': { 'type': 'rate_limit_exceeded', 'message': 'Rate limit exceeded for /api/messages. Retry after 14 seconds.', 'retry_after': 14 } }. The middleware short-circuits — the request never reaches the backend. Total added latency: the time for one Redis EVAL call, about 0.5 milliseconds."))

    lines.append(("candidate", "Now let me trace an allowed request. Bob, also a paid user, sends a GET to /api/users at the same timestamp. His per-user-per-endpoint current count is 50, previous count is 200. Weighted count is 0.233 times 200 plus 50, which is about 97. Well under 1000. His per-user-global current count is 2000, previous is 4000. Weighted count is 0.233 times 4000 plus 2000, which is about 2932. Under 5000. The per-endpoint-global current count is 20,000, previous is 35,000. Weighted count is 0.233 times 35,000 plus 20,000, which is about 28,155. Under 50,000. All checks pass. The script increments all three current counters by 1 and returns allowed with the updated remaining counts: 903 for per-user-per-endpoint, 2067 for per-user-global, and 21,844 for per-endpoint-global. The middleware adds the headers — showing the most restrictive one, which is per-user-per-endpoint with remaining 903 — and passes the request to the backend. The backend processes it normally and returns the response, which flows back through the gateway to Bob with the rate limit headers attached."))

    # SECTION 8: Thinking Process & Beats (~3 min)
    lines.append(("interviewer", "Great walkthrough. Let me close with an interviewer's perspective on this problem. I'll share the mental framework and key beats I look for."))

    lines.append(("interviewer", "The framework I use for rate limiter design has four layers: requirements and scope, algorithm selection, distributed implementation, and failure handling. At the requirements layer, the key beats are: does the candidate ask about granularity — per-user, per-IP, per-endpoint? Do they ask about strict versus soft limits? Do they surface the hierarchical limit requirement, or do they only consider a single level? Do they ask about fail-open versus fail-closed? A candidate who jumps straight to an algorithm without clarifying these is skipping a crucial step — the algorithm choice depends entirely on the requirements."))

    lines.append(("interviewer", "At the algorithm layer, the key beats are: can the candidate explain at least three algorithms — token bucket, leaky bucket, sliding window, fixed window — and articulate the tradeoffs? The fixed window boundary problem is a classic test — a strong candidate identifies it themselves and proposes a solution. The distinction between token bucket's burst tolerance and fixed window's boundary spike is subtle and separates good candidates from great ones. The trap here is choosing an algorithm without justifying it against the requirements — if the requirement is strict limits, token bucket's burst behavior might be problematic, and the candidate should acknowledge that. Another trap is not understanding that leaky bucket queues requests rather than rejecting them — it's traffic shaping, not rate limiting."))

    lines.append(("interviewer", "At the distributed implementation layer, the key beats are: does the candidate recognize the race condition with concurrent requests? Do they propose Lua scripts for atomicity, or do they naively use separate GET and INCR? Do they think about sharding strategy — co-locating all counters for a user on one shard is essential for atomic hierarchical checks. Do they consider the latency impact of centralized rate limiting? The trap here is proposing local rate limiting without acknowledging that it can't enforce global limits, or hand-waving about eventual consistency when the requirement is strict. Another trap is not addressing clock skew — if different servers use different clocks, window boundaries become inconsistent. Using Redis TIME solves this elegantly."))

    lines.append(("interviewer", "At the failure handling layer, the key beats are: does the candidate explicitly choose fail-open or fail-closed and justify it? Do they propose mitigations for fail-open — local fallback caches, backend defense-in-depth, aggressive alerting? Do they consider partial failures like slow Redis or individual shard outages? Do they think about monitoring the rate limiter's effectiveness, not just its uptime? The trap is treating fail-open as a simple boolean choice without acknowledging that it means the system is unprotected during failures, or proposing fail-closed without recognizing that it makes the rate limiter a single point of failure. The best candidates propose a layered defense — the gateway rate limiter is the first line, but backends have their own coarse limits as a safety net."))

    lines.append(("interviewer", "One more thing I look for: does the candidate consider the client experience? Returning rate limit headers on every response, not just 429s, is essential for well-behaved clients that want to self-regulate. Including Retry-After in 429 responses is a must. And the distinction between showing the most restrictive limit's headers versus all applicable limits shows awareness of API usability. A rate limiter isn't just a technical gate — it's part of the API contract with developers. The candidate who treats it as purely an infrastructure problem misses this. Overall, the strongest candidates treat rate limiting as a distributed systems problem with real user impact, not just a data structure question. Thanks — that wraps it up."))

    return lines
