"""Mock Interview: Ride-Sharing Platform — Two-voice dialogue."""


def build():
    lines = []

    # SECTION 1: Requirements (~5 min)
    lines.append(("interviewer", "Hi, thanks for coming in. Today I'd like you to design a ride-sharing platform — think Uber or Lyft. Passengers request rides, nearby drivers get matched, and we handle the whole trip lifecycle. Start by clarifying the requirements."))

    lines.append(("candidate", "Thanks. Ride-sharing is a really rich system — there are a lot of moving parts, so getting the scope right matters. Let me start with the most basic question: are we building just the passenger-driver matching and trip management, or are we also handling payments, driver onboarding, and the full marketplace? Because the scope changes the design significantly."))

    lines.append(("interviewer", "We want the full system. Passenger app, driver app, matching, pricing, trip lifecycle, payments, and ratings. You don't need to design the driver onboarding and background check pipeline in detail, but acknowledge it exists."))

    lines.append(("candidate", "OK, full marketplace. Next I'd want to understand scale. How many daily rides, how many drivers, and what geographic area? Also, are we in a single city or multiple cities? And is this purely ride-hailing, or do we also have shared rides and scheduled rides?"))

    lines.append(("interviewer", "We operate in 50 major cities. About 10 million rides per day globally, with roughly 2 million active drivers. We support single rides and shared rides — no scheduled rides for now. Peak is about 3x the average."))

    lines.append(("candidate", "10 million rides per day is substantial. Let me think about peak — 10 million over 24 hours, but rides are concentrated. Probably most rides happen in a 6-hour window — morning and evening commute. So peak is around... 10 million divided by 6 hours, that's roughly 1.7 million rides per hour at peak, or about 470 rides per second globally. But it's higher in individual cities. A city like New York might see 100K rides per day, with peak around 15 rides per second. That matters for geospatial indexing. Let me ask about the matching — do we dispatch the single nearest available driver, or do we batch multiple requests and optimize?"))

    lines.append(("interviewer", "We want batch matching — we collect ride requests over a short window and then optimally match drivers to riders. The batch window should be configurable. Also, we need surge pricing — when demand exceeds supply in a region, prices go up to incentivize more drivers."))

    lines.append(("candidate", "Batch matching is more efficient but introduces latency. A few more questions. First, location tracking — how frequently do drivers send their GPS coordinates? This directly affects matching quality and cost. Second, what about ETA estimation — do we need road-network-based ETAs or is straight-line distance acceptable? Third, idempotency — a passenger tapping the request button twice should not create two rides."))

    lines.append(("interviewer", "Driver location updates every 3 seconds. ETA should be road-network-based for the passenger-facing estimate, but the matching algorithm can use straight-line distance for initial filtering. And yes, idempotent ride requests are required — no double-booking."))

    lines.append(("candidate", "Good. Every 3 seconds from 2 million drivers is about 670K location updates per second globally. That's a lot of write load just for location tracking. Let me also ask about the shared rides — how does that affect matching? Are we matching two passengers to one driver, or can it be more?"))

    lines.append(("interviewer", "Up to two additional passengers can share a ride with the first. The driver picks up each passenger along the route, with detours capped at a certain percentage of the original trip time. We'll say 30 percent maximum detour."))

    lines.append(("candidate", "OK. Let me summarize: full ride-sharing platform, 10 million rides per day across 50 cities, 2 million active drivers, batch matching with configurable window, surge pricing, location updates every 3 seconds, road-network ETAs for passengers, idempotent ride requests, and shared rides with up to 2 additional passengers and 30 percent max detour. Let me move to estimation."))

    # SECTION 2: Estimation (~5 min)
    lines.append(("interviewer", "Go ahead."))

    lines.append(("candidate", "So 10 million rides per day, peak at about 470 rides per second globally. But I should break this down per city because matching is local. The biggest city might have 200K rides per day, peaking at maybe 30 rides per second. That's the scale our matching engine needs to handle per city. Now, location updates — 2 million drivers sending updates every 3 seconds. That's 2 million divided by 3, roughly 667K updates per second globally. Per city, maybe 40K active drivers, so about 13K location updates per second per major city. These are hot data — they need to be written fast and read even faster for matching."))

    lines.append(("candidate", "Storage per location update: driver ID, latitude, longitude, timestamp, and maybe heading and speed. That's about 50 bytes. At 667K updates per second, we're writing about 33 MB per second or about 2.8 TB per day. But we don't need to persist all of this — location data is ephemeral. We only need the current location for matching and maybe the last few minutes for ETA calculations. So the persistent storage is minimal — we'd keep maybe the last known location per driver in a geospatial index, which is about 50 bytes times 2 million drivers, or 100 MB total. The historical location trail for completed trips is separate — we'd batch-write that to object storage for analytics."))

    lines.append(("interviewer", "What about the ride data itself?"))

    lines.append(("candidate", "Right. Each ride record: ride ID, passenger ID, driver ID, pickup and dropoff locations, timestamps for each phase — requested, matched, picked up, dropped off — fare, surge multiplier, distance, duration, rating. Plus shared ride metadata if applicable. Let me estimate about 500 bytes per ride. At 10 million rides per day, that's 5 GB per day. For 5-year retention, that's about 9 TB. Very manageable. The hot data — active rides in progress — is maybe 500K at peak globally, so 250 MB in memory. Also manageable."))

    lines.append(("interviewer", "And the matching engine — how much compute does it need?"))

    lines.append(("candidate", "Hmm, that's a good question. Let me think. In a batch window of, say, 3 seconds, a city might accumulate 90 new ride requests at peak. For each request, we need to find nearby available drivers — maybe 50 within a 3 km radius. So we're evaluating 90 times 50 equals 4500 driver-rider pairs. For shared rides, we also need to check detour feasibility, which adds complexity — for each candidate driver who already has a passenger, we need to compute the rerouted path and verify the detour is within 30 percent. That's maybe 10 times more expensive per pair, so call it 45K path evaluations per batch. At one batch every 3 seconds, that's 15K path evaluations per second per city. Not trivial, but doable with a fleet of matching workers."))

    lines.append(("candidate", "Wait, let me reconsider. The 90 requests per batch is a high estimate. Most cities won't hit that. And many drivers are already occupied, so the pool of available drivers within radius is probably more like 10 to 20, not 50. So the actual compute is more like 90 times 15 equals 1350 pairs for single rides, plus maybe 200 shared-ride evaluations. That's about 500 evaluations per second per city at peak. Very manageable. I was overestimating."))

    # SECTION 3: High-Level Architecture (~5 min)
    lines.append(("interviewer", "Good. Let's move to the high-level architecture."))

    lines.append(("candidate", "Here's the overall flow. The passenger opens the app and sees nearby drivers on the map. This requires the client to periodically query a Nearby Drivers API, which reads from the geospatial index. When the passenger enters a destination and taps Request Ride, the client sends a ride request to the Trip Service. The Trip Service creates a pending ride record, checks idempotency, and publishes a ride-requested event. The Matching Service consumes these events in batches — it collects requests over a configurable window, then runs the matching algorithm to assign drivers."))

    lines.append(("candidate", "For matching, the Matching Service queries the Location Service, which maintains the geospatial index of all available drivers. It finds nearby drivers, computes ETAs, and produces driver-rider pair assignments. The assignments are sent to the Trip Service, which updates the ride record and sends push notifications to both the passenger and the matched driver via the Notification Service. The driver has a few seconds to accept or decline. If they decline or time out, the ride goes back into the matching queue for the next batch."))

    lines.append(("interviewer", "Why use a separate Matching Service instead of having the Trip Service do the matching directly?"))

    lines.append(("candidate", "Two reasons. First, the matching algorithm is computationally intensive and has its own scaling profile — we might want to run it on different hardware or scale it independently from the Trip Service. Second, matching is batch-oriented while the Trip Service is request-response. Mixing synchronous and batch processing in the same service creates awkward coupling. The event-driven boundary also lets us swap matching algorithms without touching the Trip Service — we could go from greedy nearest-driver to bipartite matching to a machine-learned model without changing the downstream consumers."))

    lines.append(("candidate", "After the driver accepts, we enter the trip lifecycle. Both the passenger and driver maintain WebSocket connections to the Trip Service for real-time updates — driver location, ETA changes, trip status transitions. The driver's app continues sending GPS updates every 3 seconds, which go to the Location Service and are also forwarded to the passenger via the WebSocket. When the driver taps Arrived at Pickup, the Trip Service updates the status. When the trip starts, we begin tracking the actual route for fare calculation. When the driver taps Complete Trip, the Trip Service calculates the fare — base fare plus time and distance, multiplied by the surge multiplier — and hands off to the Payment Service."))

    lines.append(("interviewer", "Tell me about the geospatial index. How are you storing and querying driver locations?"))

    lines.append(("candidate", "This is one of the core technical challenges. We need to support two operations at high throughput: write current driver location, and query all available drivers within a radius of a given point. There are a few approaches. The simplest is to use Redis with geospatial commands — GEOADD for writes and GEORADIUS or GEOSEARCH for reads. Redis uses a sorted set backed by a geohash-encoded score, which gives us O(log N + M) query complexity where M is the number of results. For our scale — 13K writes per second and maybe 50 reads per second per city — Redis handles this easily."))

    lines.append(("candidate", "But Redis has limitations. It doesn't support complex spatial queries like polygon-based regions, which we'd need for geofencing and surge pricing zones. For that, I'd use a two-tier approach. The hot tier is Redis for real-time matching — current driver locations, nearby driver queries. The warm tier is a proper geospatial database like PostGIS for analytical queries — surge zone boundaries, heat maps, coverage analysis. Driver locations are written to both, but the Redis path is the critical one for latency."))

    lines.append(("candidate", "Actually, wait. Let me reconsider. PostGIS might be overkill for the warm tier. We could use S2 geometry or Uber's H3 hexagonal grid to partition the map into cells. Each cell has a fixed ID, and we store which drivers are in each cell. This gives us efficient neighbor lookups — to find drivers within radius R, we just look up all cells that intersect the circle. S2 and H3 both support this natively. H3 is particularly nice because hexagons have roughly equal distances to all neighbors, unlike S2's rectangular cells which have distortion at the poles. For our purposes, I'd go with Redis geospatial for the hot tier and H3-indexed cells in a key-value store for the warm tier."))

    # SECTION 4: Deep Dive — Driver Matching, Pricing, and Location Tracking (~10 min)
    lines.append(("interviewer", "Let's deep dive into the matching algorithm and surge pricing. How exactly does batch matching work?"))

    lines.append(("candidate", "So the batch matching window collects ride requests over, say, 3 seconds. When the window closes, we have a set of unmatched riders and a set of available drivers. The simplest approach is greedy — assign the nearest available driver to each rider, one at a time. But greedy is suboptimal because the first assignment affects all subsequent ones. If we assign the nearest driver to Rider A, that driver might have been even closer to Rider B, and Rider A could have been served almost as well by a slightly farther driver."))

    lines.append(("candidate", "The better approach is bipartite matching. We construct a bipartite graph where one side is riders and the other is available drivers. Each edge has a weight — typically the ETA or a cost function that combines ETA, driver utilization, and other factors. Then we find the minimum-weight matching, which optimizes the overall assignment. The Hungarian algorithm does this in O(N cubed), which is fine for our batch sizes of 20 to 90 riders per city. For shared rides, we extend the graph — drivers who already have a passenger are still in the available set, but the edge weight includes the detour cost and we add a constraint that the total detour for the existing passenger stays under 30 percent."))

    lines.append(("interviewer", "What factors go into the matching cost function besides ETA?"))

    lines.append(("candidate", "Good question — ETA alone can lead to bad outcomes. The cost function should incorporate several factors. First, ETA — shorter is better. Second, heading direction — a driver heading toward the rider's pickup is better than one heading away, even if the latter is geographically closer. Third, driver idle time — we want to avoid the deadheading problem where a driver has been idle for a long time because they keep getting skipped in favor of slightly closer drivers. This is both a fairness issue and a retention issue — drivers who sit idle churn. So we add a boost for drivers who've been waiting longer. Fourth, for shared rides, detour penalty. Fifth, we might want to avoid assigning drivers to rides that take them out of a high-demand area unless there's no alternative — this is related to repositioning and supply rebalancing."))

    lines.append(("candidate", "Actually, I realize I should mention that the matching cost function is also where we can incorporate predicted demand. If we know from historical data that a certain area will have high demand in 15 minutes, we might prefer to not assign drivers far from that area to current rides that would take them away. This is essentially supply positioning — not just matching current supply to current demand, but anticipating future demand. It's an optimization layer on top of the basic matching."))

    lines.append(("interviewer", "Now tell me about surge pricing. How does it work?"))

    lines.append(("candidate", "Surge pricing adjusts the fare multiplier based on supply-demand imbalance in a region. The basic model is: for each geographic zone — let's say an H3 hex cell at resolution 7 or 8, which covers a few city blocks — we track the number of active ride requests and the number of available drivers. The surge multiplier is a function of the ratio of requests to drivers. If the ratio is 1 or below, no surge — multiplier is 1.0x. If the ratio is 2, maybe 1.5x. If it's 5 or above, maybe 2.5x or higher. The exact mapping is tuned by the business."))

    lines.append(("candidate", "But there are subtleties. First, the surge multiplier shouldn't jump discontinuously — passengers would be frustrated if the price doubles between two taps. So we smooth the multiplier over time, maybe using an exponential moving average. Second, the surge should be communicated transparently to both passengers and drivers. Passengers see the surge multiplier before requesting, and drivers see it as an incentive to move to that area. Third, there's the feedback loop — surge pricing increases supply because drivers move toward surge zones, which naturally reduces the surge. This is the intended behavior, but it can overshoot — too many drivers converge on a surge zone, the surge drops, and drivers are now over-supplied. We need dampening in the algorithm."))

    lines.append(("candidate", "Hmm, but there's a more fundamental problem. If we just use the ratio of current requests to available drivers, the surge reacts slowly. By the time the ratio spikes, passengers are already experiencing long wait times. A better approach is to predict demand using historical patterns — we know that demand spikes after concerts, during rain, on holiday evenings. We can use a time-series model trained on historical ride data, weather data, and event data to predict demand 10 to 15 minutes ahead, and pre-surge before the actual spike. This is a machine learning problem layered on top of the real-time system."))

    lines.append(("interviewer", "How do you handle the location tracking at scale? You mentioned 667K updates per second globally."))

    lines.append(("candidate", "Right. The location pipeline has two paths — a fast path for matching and a slow path for analytics. The fast path: the driver app sends a location update via WebSocket every 3 seconds. The WebSocket is connected to a Connection Gateway, which is a horizontally scalable service that maintains persistent connections. The Connection Gateway receives the update, validates it — sanity checks on coordinates, speed limits, GPS accuracy — and writes it to the Redis geospatial index. The update also goes into a Kafka topic for downstream consumers."))

    lines.append(("candidate", "The Connection Gateway is stateless from a business logic perspective — it just holds the WebSocket connection and routes messages. We can scale it horizontally behind a load balancer. The tricky part is connection affinity — when a driver reconnects, they should ideally connect to the same gateway instance to avoid unnecessary state transfer. We can use sticky sessions or a connection registry in Redis that maps driver IDs to gateway instances."))

    lines.append(("candidate", "For the WebSocket connection itself, both the passenger and the driver maintain connections during an active trip. The passenger's connection receives driver location updates and ETA changes. The driver's connection receives ride assignments, navigation instructions, and passenger location. That's dual WebSocket connections per trip — up to 500K concurrent trips at peak, so about 1 million WebSocket connections globally. Each connection is maybe 1 KB of server memory, so 1 GB total. A single gateway instance can handle 50K to 100K connections, so we need 10 to 20 instances globally. Very manageable."))

    lines.append(("interviewer", "What about ETA estimation? You said road-network-based for passengers."))

    lines.append(("candidate", "Right. Straight-line distance is fine for the matching algorithm's initial filter — we just need to know which drivers are roughly nearby. But the passenger-facing ETA needs to account for actual roads, traffic, and turns. We'd use a routing engine like OSRM or Valhalla that computes road-network distances and travel times. The challenge is that we can't call the routing engine for every candidate driver during matching — that would be too slow. So we do a two-phase approach. Phase 1: matching uses straight-line distance from the Redis geospatial index to filter to the top 5 nearest available drivers. Phase 2: for these 5 candidates, we call the routing engine to compute actual road-network ETAs. The final assignment uses the road-network ETA."))

    lines.append(("candidate", "The routing engine itself needs to handle real-time traffic data. We'd ingest traffic updates from map providers and update the road network graph. The ETA computation for a single query takes maybe 10 to 50 milliseconds, so 5 queries per ride request adds 50 to 250 milliseconds. That's acceptable since the batch window is 3 seconds — we have time. The key optimization is caching frequent routes — the ETA from downtown to the airport doesn't change every minute, so we cache it with a short TTL."))

    # SECTION 5: Failure Modes (~4 min)
    lines.append(("interviewer", "What are the most critical failure scenarios?"))

    lines.append(("candidate", "The scariest failure is a driver getting matched to two rides simultaneously — double-booking. This would happen if two matching batches overlap, or if the matching engine doesn't atomically remove a driver from the available pool when they're assigned. To prevent this, the assignment must be atomic — when the Matching Service assigns driver D to rider R, it must update the driver's status from AVAILABLE to ASSIGNED in a single atomic operation. We'd use a compare-and-swap in Redis — update the driver's status only if it's still AVAILABLE. If the CAS fails, that driver was already assigned by another batch, and we skip them."))

    lines.append(("candidate", "Another critical failure is the WebSocket connection dropping. If the driver loses connectivity during a trip, we stop receiving location updates and the passenger sees a frozen driver icon. We handle this with a heartbeat mechanism — the driver app sends a lightweight ping every 5 seconds. If the server doesn't receive a ping for 15 seconds, it marks the driver as potentially disconnected and alerts the passenger. If no ping for 60 seconds, we consider the driver unresponsive and may cancel the trip. The driver can reconnect and resume the trip within the grace period."))

    lines.append(("interviewer", "What about the matching service going down entirely?"))

    lines.append(("candidate", "If the matching service goes down, no new rides get assigned. Existing rides in progress continue — the Trip Service and the WebSocket connections are independent. But pending ride requests accumulate. We'd have a fallback matching mode — a simpler greedy algorithm that runs in the Trip Service itself, bypassing the batch matching. This is less optimal but keeps the system functional. We'd also queue pending requests in Kafka so they're not lost — when the Matching Service recovers, it processes the backlog. The key is that the Kafka topic acts as a buffer. Pending requests older than a certain threshold — say 30 seconds — should be expired and the passenger notified that no driver is available, rather than matching them to a driver who's now far away."))

    lines.append(("candidate", "There's also the payment failure scenario. If the Payment Service fails after a trip completes, the driver doesn't get paid immediately. We'd persist the fare record and retry payment asynchronously. The driver's earnings balance is updated eventually — consistency, not immediacy. But we must never lose a fare record. The trip completion event is persisted in Kafka and the database before we attempt payment, so even if payment fails, we have the record. The Payment Service has its own retry logic with exponential backoff and a dead letter queue for persistent failures that need manual intervention."))

    lines.append(("candidate", "One more failure mode worth mentioning — GPS spoofing. A driver could fake their GPS location to appear in a high-surge area or to get matched to rides they're not actually near. We'd detect this by comparing the reported GPS coordinates with the driver's previous location — if they jump 5 kilometers in 3 seconds, that's physically impossible. We can also cross-reference with cell tower data or Wi-Fi positioning as a secondary signal. Repeated spoofing would trigger an investigation and potential deactivation."))

    # SECTION 6: Scale & Debrief (~3 min)
    lines.append(("interviewer", "How does the design change at 10x scale — 100 million rides per day?"))

    lines.append(("candidate", "At 100 million rides per day, the geospatial index becomes the biggest challenge. 20 million drivers sending 7 million location updates per second — a single Redis cluster can handle maybe 100K to 500K writes per second per shard, so we'd need maybe 20 to 30 Redis shards partitioned by region. The matching engine also needs to scale — bipartite matching is O(N cubed), and at 10x the batch sizes, we might need to switch to approximation algorithms like min-cost flow with capacity constraints instead of exact Hungarian algorithm. Or we could shard the matching by zone — each H3 cell runs its own matching independently, which reduces the problem size but creates boundary issues where a driver is near the edge of two zones."))

    lines.append(("candidate", "At 10x, the WebSocket connection count goes from 1 million to 10 million concurrent connections. That's 50 to 100 gateway instances. We'd also need to think about multi-region deployment — with 100 million rides, we're probably in hundreds of cities across many continents. Each region should have its own matching engine, location service, and Redis cluster to keep latency low. Cross-region communication is only needed for global analytics and driver/passenger accounts when they travel. The Kafka event bus also needs to be regional — a single global Kafka cluster would have unacceptable latency for real-time matching."))

    lines.append(("candidate", "At 0.1x scale — 1 million rides per day — everything simplifies dramatically. A single Redis instance handles the geospatial index. A few matching workers running greedy dispatch instead of bipartite matching. The Connection Gateway might be 2 instances. Even the database — PostgreSQL with read replicas handles all ride records. The architectural skeleton stays the same — Location Service, Matching Service, Trip Service, Payment Service — but the internal complexity drops. You don't need H3 cells for surge zones; simple city-level surge multipliers suffice. You don't need bipartite matching; greedy nearest-driver is fine when the batch size is 2 to 3 riders per window."))

    lines.append(("candidate", "The one thing that doesn't scale down is correctness. Even at 0.1x, double-booking is unacceptable. The atomic compare-and-swap for driver assignment is mandatory. Idempotency for ride requests is mandatory. The trip state machine — requested, matched, picked up, in_trip, completed — must be enforced consistently. These correctness requirements are invariant with scale. What changes is the sophistication of optimization — at low scale, simple and correct beats optimal and complex."))

    lines.append(("interviewer", "Let me give you feedback. The positives: your requirements clarification was thorough — you asked about batch matching, location update frequency, ETA methodology, and shared ride constraints unprompted. The bipartite matching explanation was clear, and the cost function discussion showed real understanding of the trade-offs beyond just minimizing ETA. The surge pricing discussion, especially the feedback loop and predictive pre-surge, was strong. The two-phase ETA approach — straight-line filter plus road-network final selection — was practical. For improvement: you didn't discuss the geofencing and region-based configuration in much detail — how different cities might have different fare structures, vehicle types, or regulatory constraints. Also, when discussing the deadheading problem, you mentioned it as a matching cost factor, but didn't propose concrete driver incentivization mechanisms like destination-based matching or repositioning incentives. Overall, very strong performance."))

    lines.append(("candidate", "Thanks for the feedback. You're right about geofencing — different cities have different regulatory requirements, vehicle categories, and fare structures, and the system needs a region configuration service that defines these rules per city or even per zone within a city. And for deadheading, destination-based matching — prioritizing drivers whose current trip ends near a high-demand area — would be a concrete mechanism, along with repositioning bonuses paid to drivers who move to underserved areas. I'll make sure to cover those next time."))

    # SECTION 7: End-to-End Walkthrough (~4 min)
    lines.append(("interviewer", "Before we wrap up, walk me through a single ride end-to-end — from the passenger opening the app to the driver arriving at the pickup."))

    lines.append(("candidate", "Sure. Let me trace the whole path. Step 1: The passenger opens the app. The app calls the Nearby Drivers API, sending the passenger's current GPS coordinates. The API queries the Redis geospatial index — GEORADIUS with the passenger's coordinates and a 3 km radius — and returns a list of available driver locations. The app renders these as car icons on the map. This query takes maybe 5 milliseconds from Redis."))

    lines.append(("candidate", "Step 2: The passenger enters a destination. The app calls the Fare Estimate API, which computes the estimated fare based on distance, time, and the current surge multiplier for the pickup zone. The surge multiplier comes from the Pricing Service, which reads the current supply-demand ratio for the H3 cell at the pickup location. The app shows the fare estimate — let's say $18 with a 1.2x surge."))

    lines.append(("candidate", "Step 3: The passenger taps Request Ride. The app sends a POST to the Trip Service with an idempotency key, pickup location, destination, and ride type. The Trip Service checks the idempotency store — if this key already exists with a completed or in-progress ride, it returns the existing ride. If it's new, the Trip Service creates a ride record with status REQUESTED, stores the idempotency key in Redis with a 30-second TTL, and publishes a ride-requested event to Kafka. The passenger sees a matching screen."))

    lines.append(("candidate", "Step 4: The Matching Service is consuming from the ride-requested topic. It doesn't match immediately — it waits for the batch window to close, collecting ride requests for up to 3 seconds. When the window closes, it queries the Location Service for available drivers near each pickup point, constructs the bipartite graph with ETA-based weights, and runs the matching algorithm. It produces assignments and sends them back to the Trip Service via an assignment event."))

    lines.append(("candidate", "Step 5: The Trip Service receives the assignment. It does a compare-and-swap on the driver's status in Redis — from AVAILABLE to ASSIGNED — to prevent double-booking. If the CAS succeeds, it updates the ride record to status MATCHED and sends push notifications to both the passenger and the driver. The passenger sees the driver's name, car, and ETA. The driver sees the pickup location and the offer with a countdown timer — typically 15 seconds to accept."))

    lines.append(("candidate", "Step 6: The driver taps Accept. The app sends an acceptance message via the WebSocket connection to the Connection Gateway, which forwards it to the Trip Service. The Trip Service updates the ride status to DRIVER_ACCEPTED. Now both the passenger and driver maintain active WebSocket connections — the driver's app continues sending GPS updates every 3 seconds, which flow through the Connection Gateway to the Location Service for storage and also get forwarded to the passenger's WebSocket so the passenger can watch the driver approach in real time."))

    lines.append(("candidate", "Step 7: The driver navigates to the pickup. The passenger's app shows the driver's moving position on the map, updating every 3 seconds via the WebSocket. The ETA is recalculated periodically using the routing engine — maybe every 10 seconds or when the driver's location changes significantly. If the driver is delayed, the passenger gets an updated ETA notification."))

    lines.append(("candidate", "Step 8: The driver arrives at the pickup location and taps Arrived. The Trip Service updates the ride to status ARRIVED and notifies the passenger. The passenger gets in the car and the driver taps Start Trip, which transitions the ride to IN_TRIP. Now we start tracking the actual route for fare calculation — every GPS update from the driver is also stored in the trip's location trail. The whole sequence from tap to arrival takes maybe 3 to 8 minutes depending on distance, and the critical latency points are the 3-second matching batch window and the 15-second driver acceptance timeout."))

    # SECTION 8: Thinking Process & Beats (~3 min)
    lines.append(("interviewer", "Let me summarize the mental framework and key beats for this problem. This is how I'd think through a ride-sharing design systematically."))

    lines.append(("interviewer", "First, the framework. Ride-sharing is a geospatial matching problem at its core. The mental model has four layers: location, matching, trip lifecycle, and marketplace. Location is the foundation — you can't match without knowing where drivers and riders are. Matching is the brain — it turns location data into assignments. Trip lifecycle is the state machine — it governs everything from request to completion. Marketplace is the economic layer — pricing, incentives, and supply-demand balance. Any design that skips one of these layers is incomplete. I always start by asking: which layer is the hardest? In ride-sharing, it's matching, because it requires real-time geospatial computation with optimization constraints."))

    lines.append(("interviewer", "Key beats to hit. First, the geospatial data structure decision — Redis geospatial versus quadtree versus S2/H3. You should explain the trade-off: Redis gives you fast reads and writes with built-in commands but limited query flexibility; S2 and H3 give you more spatial reasoning at the cost of managing the index yourself. The right answer is usually a combination. Second, batch versus greedy dispatch. Greedy is simpler but suboptimal; bipartite matching is optimal but more complex. You should discuss both and justify your choice based on batch size and latency budget. Third, the atomicity of driver assignment — this is the correctness invariant. Double-booking is the cardinal sin of ride-sharing, and the compare-and-swap pattern is the standard solution. If a candidate doesn't mention this, it's a red flag."))

    lines.append(("interviewer", "Fourth, surge pricing feedback loops — this separates surface-level candidates from deep thinkers. Anyone can say raise prices when demand is high. But understanding that surge creates a feedback loop — higher prices attract more drivers, which reduces demand-supply gap, which reduces surge — and that this loop can oscillate without dampening, shows real systems thinking. Bonus points for mentioning predictive pre-surge using historical data. Fifth, the dual WebSocket architecture — both passenger and driver need real-time updates, and the connection management is non-trivial at scale. Sixth, the two-phase ETA — straight-line for filtering, road-network for final selection. This is a practical optimization that shows you understand the cost of routing engine calls."))

    lines.append(("interviewer", "Traps to avoid. The biggest trap is over-focusing on the map and under-focusing on matching. Many candidates spend too long on how to render driver icons on the map — that's a client-side problem. The server-side challenge is the matching algorithm and its correctness guarantees. The second trap is ignoring the shared-ride complexity — adding a second passenger to an existing trip requires detour computation and feasibility checks, which significantly increases the matching algorithm's complexity. The third trap is treating surge pricing as a simple multiplier — it's a dynamic system with feedback loops, not a static lookup. The fourth trap is underestimating the location update write path — 670K writes per second to a geospatial index is a real engineering challenge, not just a Redis GET call. The fifth trap is forgetting idempotency for ride requests — passengers on spotty mobile networks will double-tap, and double-booking is unacceptable."))

    lines.append(("interviewer", "Finally, the meta-point: ride-sharing is fundamentally a local problem masquerading as a global one. The matching happens within a city, within a few kilometers. This means your design should be region-sharded by default — a single global matching engine would be both a latency disaster and a single point of failure. Think locally, deploy regionally, and only go global for the data that actually needs to be global — user accounts, payments, and analytics. That's the framework."))

    return lines