"""System Design Q&A — Power Answers for the 12 Interview Topics — Single-voice think-aloud."""


def build():
    lines = []

    lines.append(("narrator", "System design Q&A. Power answers for the twelve interview topics you'll face. This episode covers the questions interviewers actually ask, and the answers that actually impress. We're organized around the twelve problems from the Airwallex interview list — five generic, seven domain-specific. For each problem, I'll give you the killer questions the interviewer will ask, the structured answers that score points, and the common mistakes that lose points. Think of this as your answer key, but the kind you study before the test, not during it."))

    # SECTION 1: Generic Problems Q&A
    lines.append(("narrator", "Section one. The five generic problems. The interviewer said these are not necessarily finance-related. But here's the trick: even when the problem is generic, bringing in fintech context scores extra points. It shows you can connect abstract concepts to real business domains. Let's go through each one."))

    # URL Shortener Q&A
    lines.append(("narrator", "Problem one: URL shortener. The interviewer asks: how would you generate the short code? Wrong answer: use a random string. Right answer: there are three approaches, and you should discuss all three. Approach one: auto-incrementing counter. The database gives you a sequential ID, you base-sixty-two encode it. Simple, deterministic, easy to debug. But predictable — someone can enumerate all your URLs. Approach two: random generation. Generate a random seven-character string, check for collision, retry if taken. With seven characters in base sixty-two, you have about four trillion possible codes. Collision probability is negligible until you have billions of URLs. Approach three: pre-generated key pool. A background service generates a pool of available keys and stores them in a distributed cache. When a new URL needs shortening, grab a key from the pool. This avoids the collision check entirely. At Airwallex scale, you'd use approach one for internal services and approach two for user-facing URLs."))

    lines.append(("narrator", "Killer question: how do you handle redirects? Do you use three-oh-one or three-oh-two? Three-oh-one is permanent — the browser caches the redirect, which reduces server load but means you can't change the destination. Three-oh-two is temporary — every click hits your server. For analytics, you want three-oh-two because you need to count every click. For performance, you want three-oh-one. The smart answer: use three-oh-two by default, but offer three-oh-one as an option for links that will never change. Track clicks via the three-oh-two server hit before redirecting."))

    lines.append(("narrator", "Another killer question: what if a link goes viral and gets ten thousand clicks per second? Your single server can't handle that. Answer: caching layer. Put the hot URL mappings in a CDN or Redis. The redirect service checks the cache first. If it's a cache hit — and for viral links, it will be — the redirect happens in microseconds without hitting the database. The database only sees cache misses, which are mostly new URLs. This pattern — cache hot items, let the database handle the cold tail — is the answer to almost every scale question in system design interviews."))

    # Rate Limiter Q&A
    lines.append(("narrator", "Problem two: rate limiter. The interviewer asks: what algorithm would you use? Wrong answer: token bucket. Right answer: it depends on the requirements, and here are the four options. Token bucket: tokens are added at a fixed rate, each request consumes one token. Allows burst traffic up to the bucket size. Best for APIs where you want to allow short bursts but enforce an average rate. Leaky bucket: requests enter a queue and are processed at a fixed rate. Smooths out traffic but adds latency for burst requests. Best for downstream services that can't handle bursts. Fixed window counter: count requests in each one-minute window. Simple but has a boundary problem — if a client sends its full quota at eleven fifty-nine and again at twelve-oh-one, it sends double the rate in a two-minute window. Sliding window log: store timestamps of every request in a sorted set, count requests in the last window. Most accurate but memory-intensive. Sliding window counter: hybrid — use fixed windows but weight the current window based on overlap with the previous window. Best balance of accuracy and performance. This is what most production rate limiters use."))

    lines.append(("narrator", "Killer question: how do you make the rate limiter distributed? Single-server rate limiting is trivial — use an in-memory counter. But in production, you have multiple application servers, and they need to share state. Answer: Redis. Store counters in Redis with TTL equal to the window size. Each request does a Redis INCR and checks the result. Latency: one Redis round-trip per request, about half a millisecond in the same data center. Alternative for ultra-low latency: send rate limit checks to a dedicated rate-limiter service that keeps hot counters in memory and periodically syncs to Redis. This adds complexity but reduces latency to under one hundred microseconds."))

    lines.append(("narrator", "Another killer question: what if Redis goes down? This is a reliability question. Answer: you need a fallback strategy. Option one: fail open — if Redis is unreachable, allow all requests. This prevents outages but risks overload. Option two: fail closed — if Redis is unreachable, reject all requests. This protects downstream services but causes a complete outage for rate-limited clients. Option three: local fallback — each server keeps a local copy of counters synced from Redis, and uses the local copy if Redis is down. The local copy is slightly stale, so rate limits are approximate during a Redis outage. This is the best balance. In a fintech context like Airwallex, you'd fail closed for external API rate limiting — you can't risk a rogue client overwhelming your payment services — but fail open for internal rate limiting, since internal clients are trusted."))

    # Notification System Q&A
    lines.append(("narrator", "Problem three: notification system. The interviewer asks: how do you handle multiple channels — push, email, SMS — with different delivery guarantees? Answer: use a channel abstraction layer. Each channel — push, email, SMS — has its own sender implementation that handles the protocol details. APNS for iOS push, FCM for Android, SMTP for email, Twilio for SMS. But the core flow is the same: event comes in, check user preferences — do they want push, email, or both? — then fan out to the selected channels. Store notification metadata and delivery status per channel. This way, a single event like payment-received can trigger a push notification for instant awareness and an email for the record, each tracked independently."))

    lines.append(("narrator", "Killer question: how do you prevent notification fatigue? A user who receives fifty push notifications per day will disable them, which defeats the purpose. Answer: rate limiting and batching. Per-user rate limits: no more than ten push notifications per hour, and no more than fifty per day. Beyond that, batch into a digest — Hey, you have twelve new notifications — and deliver it as a single push. Email batching: instead of sending one email per event, batch events over an hour or day into a single digest email. User preference: let users choose their notification frequency per category — instant, daily digest, or off. This is especially important for a fintech app where every payment notification feels urgent but most aren't."))

    lines.append(("narrator", "Another killer question: how do you guarantee that a payment confirmation notification is delivered? This is a reliability question with real financial consequences. Answer: retry with exponential backoff, persistent queue, and delivery tracking. When a notification fails — say, the push service returns an error — put it in a retry queue. Retry at one second, five seconds, thirty seconds, five minutes, thirty minutes. Track the delivery status: pending, delivered, failed, bounced. If a payment confirmation still hasn't been delivered after all retries, escalate: send via a fallback channel — if push failed, try email; if email bounced, try SMS. As a last resort, show the notification in the app's notification center on next login. The user must eventually see it. Log every delivery attempt for audit — regulators require proof that you attempted to notify the customer about a transaction."))

    # Distributed Job Scheduler Q&A
    lines.append(("narrator", "Problem four: distributed job scheduler. The interviewer asks: how do you prevent the same job from running twice? This is the idempotency question, and it's critical for a scheduler because duplicate job execution can cause double-charges, duplicate reports, or data corruption. Answer: three mechanisms. First, idempotency keys. Each job execution gets a unique key derived from the job ID and the scheduled time. Before executing, the worker checks if this key exists in the database with a status of RUNNING or COMPLETED. If so, skip. Second, distributed locks. Before picking up a job, the worker acquires a lock in Redis using SET with NX and a TTL equal to the job's timeout. If the lock is acquired, the worker owns that execution. If not, another worker is already running it. Third, at-least-once acknowledgment. The worker updates the job status to COMPLETED only after the job finishes. If the worker crashes mid-execution, the lock expires, and another worker picks up the job and reruns it. This means your jobs must be idempotent — they must produce the same result if run twice."))

    lines.append(("narrator", "Killer question: how do you handle jobs that have dependencies — job B must run after job A completes? Answer: DAG execution. Model the job schedule as a directed acyclic graph. Each job has a list of upstream dependencies. The scheduler maintains a dependency tracker — when job A completes, the tracker checks which downstream jobs now have all their dependencies satisfied, and enqueues those jobs for execution. Store the DAG in the database with each job's dependency list. On scheduler startup, load the DAG, find all jobs whose dependencies are met, and start them. This is how Airflow works, and it's the standard pattern. In a fintech context, your settlement jobs depend on FX rate refresh, and your reconciliation jobs depend on settlement completion. The DAG ensures correct ordering."))

    lines.append(("narrator", "Another killer question: what happens when a job in the middle of the DAG fails? Answer: it depends on the failure mode. If the job is retriable — network timeout, external service unavailable — retry it with exponential backoff. If it exhausts retries, mark it as FAILED and propagate the failure downstream: all dependent jobs are also marked as FAILED without execution. This prevents wasted compute on jobs that will produce incorrect results because their input data is stale. For critical DAGs — like settlement — have a manual retry mechanism: an operator can fix the root cause and restart the failed job, which then re-triggers the downstream chain. Store the full DAG execution state — which jobs succeeded, which failed, which were skipped — so operators can debug."))

    # Metrics Pipeline Q&A
    lines.append(("narrator", "Problem five: metrics pipeline. The interviewer asks: how do you handle high-cardinality metrics? This is the problem that kills naive monitoring systems. Answer: cardinality control. Every unique combination of label values creates a new time series. If you have a metric called http_request_duration with labels for method, status, and service, that's manageable — maybe a few hundred series. But if you add a label for user ID or request ID, you get millions of series, each consuming memory and storage. Control cardinality at ingestion time. Before accepting a metric, check the label count and the cardinality of each label. If a label has more than, say, ten thousand unique values, drop it or replace it with a lower-cardinality bucket. For example, replace user ID with user_tier: free, pro, enterprise. Record the dropped labels in a log for debugging, but don't store them as time series."))

    lines.append(("narrator", "Killer question: how do you implement alerting on top of the metrics pipeline? Answer: alert rules that evaluate periodically against the metrics store. Each rule has a condition — for example, error rate above one percent over five minutes — and an action — page the on-call engineer. The alerting service queries the metrics store every minute, evaluates all rules, and fires alerts for any that breach the threshold. But there's a subtlety: alert fatigue. If a service goes down and generates fifty alerts in five minutes, the on-call engineer ignores them. Solution: alert grouping and inhibition. Group related alerts — all alerts for the same service — into a single incident. Inhibit lower-severity alerts when a higher-severity alert is already firing for the same service. This is the PagerDuty model."))

    lines.append(("narrator", "Another killer question: what's the difference between metrics, logs, and traces, and when do you use each? Answer: metrics are numeric aggregates — counters, gauges, histograms — used for monitoring and alerting. Low storage cost, fast queries, but no individual request detail. Logs are discrete events — each request logs what happened — used for debugging. High storage cost, slow queries, but full detail. Traces track a request across multiple services — each service adds a span — used for understanding request flow and identifying latency bottlenecks. In practice: use metrics for alerting, logs for debugging known issues, and traces for debugging unknown latency issues. At Airwallex, you'd use metrics to alert on payment processing latency, logs to debug a specific failed payment, and traces to find why the payment processing pipeline is slow end-to-end."))

    # SECTION 2: Airwallex-Domain Q&A
    lines.append(("narrator", "Section two. The seven Airwallex-domain problems. These are where domain knowledge becomes a differentiator. The generic problems test your system design fundamentals. These test whether you can apply those fundamentals to financial infrastructure. The interviewer expects deeper answers here — not just how would you design it, but what are the regulatory constraints, the failure modes specific to money, and the real-world patterns that fintech companies use."))

    # Distributed Wallet Q&A
    lines.append(("narrator", "Problem six: distributed wallet. The interviewer asks: how do you prevent double-spending in a distributed wallet? Answer: single-threaded execution per account. This is the key insight behind Auticuro, Airwallex's wallet engine. For any given account, all transactions must be processed sequentially — no concurrent debits or credits. This guarantees that the balance is always consistent without distributed locks or two-phase commit. Implementation: shard accounts across nodes, and route all transactions for a given account to the same node. On each node, maintain an in-memory queue per account. Process transactions from the queue one at a time, updating the balance in the database with each transaction. If the node crashes, the queue is lost, but the database has the correct balance because each transaction was committed before acknowledging the next."))

    lines.append(("narrator", "Killer question: what about hot accounts that receive hundreds of transactions per second? Single-threaded execution becomes a bottleneck. Answer: internal sharding. Split a hot logical account into multiple physical sub-accounts. For example, the platform's main settlement account might be split into ten sub-accounts. Incoming credits are distributed across sub-accounts using round-robin or hash-based routing. Each sub-account processes independently on its own thread. The logical balance is the sum of all sub-account balances, computed on read. This trades read complexity — you must aggregate across sub-accounts — for write parallelism. In a fintech system, reads are less frequent than writes — you check your balance occasionally, but money moves constantly — so this is the right trade-off."))

    lines.append(("narrator", "Another killer question: how do you handle cross-currency transfers without distributed transactions? Answer: the suspense account pattern. When transferring from USD to AUD, you don't try to atomically debit one currency and credit another — that would require a distributed transaction if they're on different shards. Instead, use a three-step process with compensating actions. Step one: debit USD from the sender, credit USD to a suspense account — both on the same shard since they share the same owner entity. Step two: asynchronously, debit AUD from the suspense account, credit AUD to the beneficiary — on a potentially different shard. Step three: if step two fails, the suspense account still holds the USD. A reconciliation job detects orphaned suspense entries and reverses them, crediting the USD back to the sender. This is the saga pattern applied to financial transactions, and it's how every real payment system works."))

    # FX Rate Engine Q&A
    lines.append(("narrator", "Problem seven: FX rate engine. The interviewer asks: how do you handle the gap between quoting a rate and settling the payment? This is the FX risk problem, and it's the reason fintech companies lose money on bad rate management. Answer: rate locking. When a customer requests a quote, you lock the current rate by storing it in a Redis key with a TTL — thirty seconds for consumers, five minutes for B2B. The customer must initiate the payment within this window. If they do, the locked rate is used for settlement, regardless of what the market rate is at settlement time. The difference between the locked rate and the actual settlement rate is your FX gain or loss. With a short TTL, this difference is small — maybe zero point zero one to zero point zero five percent. Over millions of transactions, this adds up, but it's predictable and bounded."))

    lines.append(("narrator", "Killer question: what if the FX provider goes down? You can't quote rates without a provider. Answer: tiered fallback. Provider A is primary. If Provider A's feed drops, switch to Provider B within one second. If both providers are down, use the last known rates with a stale marker — the API response includes a field indicating the rate is not real-time. Stale rates are acceptable for a few minutes — the market doesn't move that fast for major pairs. If the outage lasts more than five minutes, stop accepting new quotes. You can't take FX risk on rates that might be significantly stale. During the outage, existing locked quotes continue to be honored — you've already committed to those rates."))

    lines.append(("narrator", "Another killer question: how do you prevent arbitrage? If your quoted rate is slightly off from the market, a sophisticated client could profit from the difference by making rapid trades. Answer: per-client rate limits on quote requests and per-client volume limits on trades. If a client requests an unusual number of quotes without converting them to trades, flag the account. If a client's conversion rate from quote to trade is too high — they only trade when the rate is in their favor — they may be exploiting stale rates. Add a spread to the quoted rate that covers your risk — this is how market makers work. And monitor the FX gain and loss per client over time. If a client is consistently profitable for themselves and costly for you, their pricing tier needs adjustment."))

    # AI Agent Platform Q&A
    lines.append(("narrator", "Problem eight: AI agent platform. The interviewer asks: how do you prevent an AI agent from executing a dangerous action — like deleting production data or making an unauthorized payment? Answer: the policy enforcement layer, also called guardrails. Every action an agent wants to take goes through a policy check before execution. The policy engine has two tiers. Tier one: static rules. Hardcoded allow and deny lists — agents can read any database but cannot modify production tables; agents can draft emails but cannot send them without human approval; agents can read payment records but cannot initiate transfers. These rules never change and cannot be overridden. Tier two: dynamic rules. Context-dependent policies — an agent can modify a staging database but only during business hours; an agent can approve a refund up to one hundred dollars but not more. These rules are configurable by administrators and stored in a policy database."))

    lines.append(("narrator", "Killer question: how do you sandbox the agent's execution environment? Answer: containerized execution with restricted capabilities. Each agent session runs in its own Docker container or Kubernetes pod with: no network access except to explicitly whitelisted services; read-only filesystem except for a temporary workspace; no privilege escalation; CPU and memory limits; and a timeout — if the agent runs longer than the allowed time, it's killed. The agent communicates with the outside world only through a well-defined API — a tool interface. The tool interface validates every call against the policy engine before forwarding it to the actual service. This means even a compromised or hallucinating agent cannot bypass the guardrails."))

    lines.append(("narrator", "Another killer question: how do you handle the cost of LLM API calls at scale? Answer: model tiering. Not every agent task needs GPT-4. Route tasks to the cheapest model that can handle them. Routine formatting, summarization, and classification: use GPT-3.5 or an open-source model like Llama, which costs about one-tenth as much. Complex reasoning, multi-step planning, and ambiguous queries: use GPT-4. Implement this as a router that estimates task complexity based on the prompt — length, presence of reasoning keywords, number of tools available — and selects the appropriate model. Cache common query patterns: if an agent is repeatedly asking similar questions about the same codebase, cache the LLM responses and reuse them. At Airwallex scale, this caching can reduce LLM costs by thirty to fifty percent."))

    # Security Automation Q&A
    lines.append(("narrator", "Problem nine: security automation platform. The interviewer asks: how do you determine if a CVE actually affects your systems? Most CVEs are false positives — they affect a version you don't use or a feature you don't have enabled. Answer: the triage pipeline. Step one: ingestion — pull CVE data from the National Vulnerability Database and vendor advisories. Step two: matching — for each CVE, check your software inventory to see if you use the affected product and version. This requires a Software Bill of Materials — a complete list of every package and version in your stack. Step three: reachability analysis — even if you use an affected version, does your code actually call the vulnerable function? Static analysis tools can check this. Step four: exploitability scoring — is there a known exploit? What's the attack surface? Can it be exploited remotely or only with local access? Step five: remediation — if the CVE is real and exploitable, generate a patch or update recommendation automatically. The key insight is that step three — reachability — eliminates about eighty percent of apparent vulnerabilities. Without it, you're drowning in false positives."))

    lines.append(("narrator", "Killer question: how do you patch running services without downtime? Answer: rolling deployments with health checks. Deploy the patched version to one instance at a time. After each deployment, run a health check — does the service respond correctly? If yes, continue to the next instance. If no, roll back that instance and stop the deployment. For critical security patches that must be applied immediately, use a canary deployment: patch one percent of instances first, monitor for five minutes, then continue to ten percent, fifty percent, one hundred percent. In a fintech context, you can't take down the payment service for patching — transactions are always flowing. The rolling deployment ensures zero downtime."))

    lines.append(("narrator", "Another killer question: how do you prove to auditors that you've addressed every relevant CVE? Answer: the audit trail. Every step of the triage pipeline is logged immutably — which CVEs were ingested, which matched your inventory, which were deemed not reachable, which were remediated, and when. The remediation record includes the patch commit, the deployment timestamp, and the verification that the patched version is running in production. Auditors don't just want to know that you patched it — they want to know when you became aware of it, how long it took to patch, and that the patch is actually deployed. Store these records for at least three years."))

    # Distributed Job Scheduler (fintech) Q&A
    lines.append(("narrator", "Problem ten: distributed job scheduler in fintech context. The interviewer asks: how do you ensure that settlement jobs run at the correct time even when servers fail? Answer: the active-passive scheduler pattern. You have two scheduler instances: active and standby. The active scheduler holds a distributed lock in Redis with a TTL of, say, ten seconds. Every five seconds, the active scheduler renews the lock. If it fails to renew — because it crashed or lost network — the lock expires after ten seconds, and the standby takes over. On failover, the standby loads the job schedule from the database, determines which jobs should have run but didn't, and runs them. This is called catch-up scheduling. The key constraint: settlement jobs must run within their banking window. If a SEPA settlement job was supposed to run at one PM and the scheduler crashed at twelve fifty-eight, the standby must start the job by one-oh-two at the latest. This means your failover detection time plus job start time must be under two minutes."))

    lines.append(("narrator", "Killer question: what happens if a settlement job partially succeeds — some payments were submitted to the bank but others weren't? Answer: checkpoint and resume. The settlement job doesn't process all payments in one big batch. Instead, it processes them in chunks — say, one thousand payments at a time. After each chunk, it checkpoints: writes the last successfully submitted payment ID to the database. If the job crashes mid-run, the resume logic starts from the last checkpoint, skipping already-submitted payments. This is idempotent because each payment has an idempotency key — resubmitting an already-submitted payment is a no-op at the bank side. The chunk size is a trade-off: smaller chunks mean more frequent checkpoints and faster recovery, but more database writes and slightly lower throughput."))

    # Global Treasury Q&A
    lines.append(("narrator", "Problem eleven: global treasury network. The interviewer asks: how do you implement cash pooling across legal entities in different countries? Answer: the notional pooling and physical pooling patterns. Notional pooling: entities keep their money in their own accounts, but the bank calculates interest as if all balances were consolidated. Zero physical movement of money, so no FX conversion or cross-border transfer costs. But this requires a banking partner that supports it, and it doesn't actually consolidate cash — each entity's cash is still in its own account. Physical pooling: sweep excess balances from subsidiary accounts to a central master account at the end of each day. This actually consolidates cash, enabling the treasury team to invest it or use it for funding. But it requires cross-border transfers with FX conversion, which costs money and takes time. In practice, Airwallex would use notional pooling within the same currency and physical pooling when converting currencies."))

    lines.append(("narrator", "Killer question: how do you handle netting? Netting is the process of offsetting what entity A owes entity B against what entity B owes entity A, so that only the net difference is transferred. Answer: bilateral netting for simple cases, multilateral netting for the general case. In multilateral netting, you calculate the net position of each entity against all others, and find the minimum set of transfers that settles all obligations. This is a graph optimization problem. For two hundred entities, the algorithm runs in milliseconds. The savings are significant: if Entity A owes B one million and B owes A eight hundred thousand, bilateral netting reduces this to a single two hundred thousand dollar transfer. Over two hundred entities, multilateral netting can reduce the total transfer volume by sixty to eighty percent, which directly reduces FX and transfer fees."))

    lines.append(("narrator", "Another killer question: how do you ensure that treasury operations comply with transfer pricing regulations? Answer: arm's-length principle and audit trail. Every inter-entity transfer must be at arm's-length rates — the same rates you'd charge an unrelated third party. The treasury system stores the market rate at the time of each transfer, the transfer pricing justification, and the approval chain. Regulators in multiple jurisdictions can audit these records. The system must also handle withholding tax: some countries tax outbound interest payments, which reduces the benefit of pooling. The treasury system calculates the after-tax benefit of each pooling decision and recommends the optimal strategy."))

    # Feature Store Q&A
    lines.append(("narrator", "Problem twelve: feature store. The interviewer asks: what does point-in-time correctness mean, and why does it matter? Answer: when you train an ML model, you must use the feature values as they were at the time of the event, not the current values. For example, if you're training a fraud detection model on historical transactions, you need to know the user's transaction count and average amount as they were at the time of each past transaction — not the user's current transaction count, which includes all subsequent transactions. Using current values instead of point-in-time values causes training-serving skew — the model sees different data during training and inference, and its predictions are unreliable. The feature store solves this by storing feature values with timestamps and allowing queries like: give me feature vector for user one-two-three at timestamp two-oh-two-four-oh-one-fifteen-ten-thirty-oh-oh. This returns the feature values as they were at that exact moment."))

    lines.append(("narrator", "Killer question: how do you serve features in real time with sub-fifty-millisecond latency? Answer: online store backed by Redis. The batch pipeline computes features daily and writes them to both the offline store — for training — and the online store — for serving. The streaming pipeline updates features in real time as events arrive, writing to the online store immediately and queuing writes to the offline store. The serving API reads from the online store, which is a Redis cluster with feature vectors stored as hashes. A read of five hundred features is a single HMGET call, which takes about one hundred microseconds in the same data center. With network overhead and serialization, the total latency is about two to five milliseconds — well within the fifty-millisecond budget."))

    lines.append(("narrator", "Another killer question: how do you handle feature backfill when you add a new feature to an existing model? Answer: the backfill pipeline. When you define a new feature, you need its historical values for all entities to train the model. The feature store has a backfill mode: you specify the feature definition and the time range, and it recomputes the feature from raw historical data. This can take hours to days depending on the data volume and computation complexity. For a user-level feature over five million users and two years of history, you're processing about five million entities times seven hundred and thirty days equals three point six five billion data points. With a Spark cluster of fifty nodes, this takes about four to eight hours. The backfilled values are written to both the offline store — for training — and the online store — for inference. You must verify the backfilled features match the production computation logic, or you'll introduce subtle training-serving skew."))

    # SECTION 3: Cross-Cutting Patterns
    lines.append(("narrator", "Section three. Cross-cutting patterns that apply across all twelve problems. These are the power phrases and patterns that make your answers stand out regardless of the specific problem."))

    lines.append(("narrator", "Pattern one: always start with requirements, not solutions. The interviewer says design a rate limiter. Don't jump to token bucket. Say: before I design the solution, let me clarify the requirements. What are we rate limiting — external API calls, internal service calls, or both? What's the granularity — per user, per API key, per IP? What's the expected scale? What happens when a request exceeds the limit — reject it, queue it, or throttle it? This shows structured thinking and prevents you from designing the wrong system."))

    lines.append(("narrator", "Pattern two: quantify everything. The interviewer loves numbers. When you say the system needs to be fast, say instead: the p ninety-nine latency should be under one hundred milliseconds. When you say we need a cache, say instead: with a read-to-write ratio of ten to one and an eighty percent cache hit rate, the database sees only thirty-six percent of the read load. Numbers make your answers credible and concrete."))

    lines.append(("narrator", "Pattern three: name the trade-off, not just the technology. Don't say we'll use Kafka. Say: we need to decouple the payment service from the notification service, because the payment service must respond in under two seconds, but notification delivery can take up to thirty seconds. Kafka provides this decoupling with durable message storage and at-least-once delivery. The trade-off is increased operational complexity — we now have a Kafka cluster to manage — and eventual consistency — the notification might arrive a few seconds after the payment completes. This is acceptable because notifications are informational, not transactional. See the difference? The second answer shows why you chose Kafka and what you gave up by choosing it."))

    lines.append(("narrator", "Pattern four: always discuss failure modes. For every component in your architecture, say: what happens when this fails? If the Redis cache goes down, we fall back to the database. If the database goes down, we serve stale data from a read replica. If the message queue goes down, we buffer events locally and replay when it recovers. The interviewer is testing your reliability engineering, not just your feature engineering. In a fintech interview, this is especially important — failure modes in financial systems have real monetary consequences."))

    lines.append(("narrator", "Pattern five: use the RESHADED framework for system design answers. Requirements, Estimation, High-level architecture, Deep dive, Failure modes, and Extra considerations. This gives your answer a clear structure that the interviewer can follow. It also ensures you don't skip the estimation step, which is the most common mistake."))

    # SECTION 4: Common Mistakes
    lines.append(("narrator", "Section four. The five most common mistakes in system design interviews, and how to avoid them."))

    lines.append(("narrator", "Mistake one: jumping to solution without clarifying requirements. The interviewer says design a URL shortener, and you start drawing boxes. Stop. Ask: what's the scale? What's the read-to-write ratio? Do we need analytics? Do we need custom aliases? Five minutes of questions saves you from designing the wrong system and shows the interviewer you think before you code."))

    lines.append(("narrator", "Mistake two: naming tools without explaining why. Saying we'll use Kafka and Redis and Kubernetes is not system design — it's name-dropping. The interviewer will push back: why Kafka? What problem does it solve here? Could you use RabbitMQ instead? What would you lose? You need to explain the trade-off, not just the technology."))

    lines.append(("narrator", "Mistake three: ignoring failure modes. Your architecture looks great on the whiteboard, but what happens when Redis goes down? When the network partitions? When a data center loses power? If you can't answer these questions, the interviewer assumes you've never operated a system in production, which is a red flag for a senior role."))

    lines.append(("narrator", "Mistake four: not estimating. If you don't estimate QPS, storage, and bandwidth, you can't justify your architectural choices. Why shard the database? Because at five thousand writes per second, a single PostgreSQL instance can't keep up. Why use a cache? Because at ten thousand reads per second, the database becomes the bottleneck. Without numbers, these decisions look arbitrary."))

    lines.append(("narrator", "Mistake five: going silent. In a forty-five-minute interview, silence is death. If you're thinking, say what you're thinking. Even if it's: let me think about the trade-offs here. On one hand, sharding gives us write throughput. On the other, it makes cross-shard queries expensive. I think the right call is to shard because writes dominate reads in this system. This narration shows your thought process and gives the interviewer something to engage with."))

    # Closing
    lines.append(("narrator", "Those are the power answers for all twelve interview topics. Five generic, seven Airwallex-domain. Practice these until the answers feel natural, not rehearsed. The interviewer can tell the difference between someone who has thought deeply about these problems and someone who is reciting a script. The key is to internalize the patterns — requirements first, quantify everything, name the trade-off, discuss failures, use RESHADED — and apply them flexibly to whatever problem you're given. Good luck."))

    return lines
