"""Mock Interview: Top-K Elements / Heavy Hitters in a Data Stream — Two-voice dialogue."""


def build():
    lines = []

    # SECTION 1: Requirements (~5 min)
    lines.append(("interviewer", "Hi, today I'd like you to design a system that finds the top-K elements — also called heavy hitters — in a real-time data stream. Think of identifying the most popular products on Amazon, the most watched videos on YouTube, or the most queried search terms. Start by clarifying the requirements."))

    lines.append(("candidate", "Thanks. Top-K in a stream is a classic data streaming problem with really interesting memory and accuracy trade-offs. Let me start with the most fundamental question: what does the data stream look like — what are the items, and what's the event rate? Also, is each event a single item, or does each event have a count or weight?"))

    lines.append(("interviewer", "The stream is 1 million events per second. Each event is an item ID — like a product ID or video ID. Each event counts as 1. We need to find the top 100 items."))

    lines.append(("candidate", "1M events per second, top 100. Next question: what's the time window? Are we looking for the top-K of all time, or the top-K in a sliding window — like the last minute, the last hour, and the last day? This fundamentally changes the algorithm."))

    lines.append(("interviewer", "We need sliding windows: 1 minute, 1 hour, and 1 day. Each window independently tracks its own top-100."))

    lines.append(("candidate", "Three sliding windows with different granularities — that's important. What's the distribution of events across items? Is it a power-law distribution where a few items get most of the traffic, or is it more uniform? This affects the memory efficiency of probabilistic data structures."))

    lines.append(("interviewer", "It's a classic power-law — the top 1 percent of items get about 50 percent of the traffic. The top 100 items each have millions of events per day, while the long tail has items with just a few events."))

    lines.append(("candidate", "Three sliding windows with different granularities — that's important. Next question: what accuracy do we need? Exact top-K would require counting every item, which might be expensive in memory. Approximate top-K — where the reported items are close to the true top items but might miss some or have slightly wrong counts — is much more memory-efficient. What's the acceptable error rate?"))

    lines.append(("interviewer", "Approximate is fine. We want the reported top-100 to include at least 95 of the true top-100 items. Item counts can be off by up to 1 percent of the total stream count in that window."))

    lines.append(("candidate", "So 95 percent recall and 1 percent relative error on counts. That gives us room to use probabilistic data structures. A few more questions: how many distinct items are there in the stream? And do we need to support adding and removing items — like when a user un-watches a video — or is it append-only?"))

    lines.append(("interviewer", "About 100 million distinct item IDs. Append-only — no removals. Each item ID is a 64-bit integer."))

    lines.append(("candidate", "One more: what's the query pattern? Do we need to query the top-100 continuously — like push it to a dashboard every second — or do we query on demand when a user opens a page?"))

    lines.append(("interviewer", "Both. We need a continuous feed for real-time dashboards that updates every second, and we need an on-demand API that returns the current top-100 for a given window."))

    lines.append(("candidate", "Let me summarize. We're designing a top-100 heavy hitter system over a 1M events/sec append-only stream with 100M distinct items. Three sliding windows: 1 minute, 1 hour, 1 day. Approximate results with 95 percent recall and 1 percent count error. Both continuous and on-demand query patterns. Let me move to estimation."))

    # SECTION 2: Estimation (~5 min)
    lines.append(("interviewer", "Go ahead."))

    lines.append(("candidate", "Let me estimate memory for different approaches. First, the exact approach: maintain a hash map of item ID to count for each window. For the 1-day window with 100M distinct items, that's 100M entries. Each entry is 8 bytes for the item ID plus 8 bytes for the count, which is 16 bytes. Total: 1.6 GB per window. For all three windows, that's about 5 GB. Plus we need a min-heap of size 100 per window to track the top-K, which is negligible. So the exact approach uses about 5 GB of memory. That's feasible on a single machine, but it's tight, and it does not scale well if the distinct item count grows."))

    lines.append(("candidate", "Wait, I need to reconsider. For the 1-minute window, we might not see all 100M distinct items. At 1M events per second, a 1-minute window has 60M events. Even if every event is a distinct item, that's at most 60M distinct items — but in practice, there's a power-law distribution where a small number of items get most of the traffic. Maybe 5 to 10M distinct items appear in any 1-minute window. So the 1-minute window hash map is about 80 to 160 MB. The 1-hour window has 3.6 billion events — wait, that can't be right. 1M events per second times 3600 seconds is 3.6 billion events per hour? No, wait. 1M per second times 3600 is 3.6 billion. That's the total events, not distinct items. The distinct items in an hour might be 30 to 50M. The hash map is 480 to 800 MB. The 1-day window: 86.4 billion events, maybe 80 to 100M distinct items. Hash map is 1.3 to 1.6 GB. Total across all windows: roughly 2 to 2.5 GB. Manageable."))

    lines.append(("candidate", "Actually, I made an error. 1M events per second times 60 seconds is 60 million events in a minute, not 60M distinct items. Let me redo this more carefully. The number of distinct items in a window depends on the data distribution. If we assume a Zipf distribution — which is typical for popularity data — with 100M total distinct items and a Zipf parameter of about 1.1, then in a 1-minute window with 60M events, we might see about 20M distinct items. In a 1-hour window with 3.6B events — no wait, that's definitely wrong. 1M per second times 3600 is 3.6 billion, but that seems way too high for a single hour. Let me recheck. 1,000,000 times 3,600 equals 3,600,000,000. Yes, 3.6 billion events per hour. OK, with 3.6B events, we'd see most of the 100M distinct items. The hash map is about 1.6 GB for the 1-hour window. For the 1-day window, it's also about 1.6 GB since we already see most items in an hour. So total is about 3.5 to 4 GB. This is feasible but leaves little headroom."))

    lines.append(("interviewer", "What about using approximate data structures to reduce memory?"))

    lines.append(("candidate", "Right, that's the more interesting approach. A Count-Min Sketch uses far less memory. The error bound is approximately N divided by W, where N is the total count in the window and W is the number of buckets. For 1 percent error on the 1-day window with 86.4 billion total counts, we need the error to be at most 864 million — which is 1 percent of 86.4 billion. Wait, that's a huge absolute error. The requirement was 1 percent of the total stream count in that window. So for the 1-day window, the acceptable error is 864 million. For the Count-Min Sketch, the error is N divided by W. Setting N over W equal to 864 million with N equal to 86.4 billion gives W equals 100. With 5 hash functions, the total memory is 5 times 100 times 8 bytes per counter, which is 4 KB. That's ridiculously small. Something is wrong with my calculation."))

    lines.append(("candidate", "Let me reconsider the error requirement. A 1 percent error on counts means that the estimated count for an item can differ from the true count by at most 1 percent of the total events in the window. For the 1-minute window with 60M events, the error budget is 600K. For the 1-day window with 86.4B events, the error budget is 864M. The Count-Min Sketch error for an individual item is at most epsilon times N, where epsilon is 1 over W. To guarantee epsilon times N less than 0.01 times N, we need epsilon less than 0.01, which means W greater than 100. With 5 hash functions and W equal to 1000 — giving epsilon equal to 0.001, which is well within our budget — the memory is 5 times 1000 times 8 bytes equals 40 KB. That seems too small. I think the issue is that the 1 percent error on individual counts is actually a very loose requirement for a stream this large. The real challenge is the 95 percent recall requirement — making sure we don't miss items that are actually in the top 100. A Count-Min Sketch can overestimate counts but never underestimate. An item that's truly in the top 100 might be pushed down if other items' counts are overestimated. To guarantee 95 percent recall, we need the sketch to be accurate enough that the top 100 items are not displaced by overestimated counts of items outside the top 100. This requires a tighter sketch — more buckets and more hash functions."))

    # SECTION 3: High-Level Architecture (~5 min)
    lines.append(("interviewer", "Good. Let's move to the high-level architecture."))

    lines.append(("candidate", "The system has three layers: the ingestion layer, the counting layer, and the query layer. The ingestion layer receives the 1M events per second and distributes them to the counting layer. The counting layer maintains the data structures for each window and updates them in real time. The query layer reads from the counting layer to produce the top-100 lists."))

    lines.append(("candidate", "For the ingestion layer, we use Kafka partitioned by item ID. This ensures all events for a given item go to the same partition, which simplifies counting. With 1M events per second and maybe 50 partitions, each partition handles about 20K events per second. A stream processor — Flink or a custom service — consumes from Kafka and updates the counting data structures."))

    lines.append(("candidate", "For the counting layer, I'd use a combination of Count-Min Sketch and a min-heap per window. Here's the idea. The Count-Min Sketch tracks approximate counts for all items. But we don't want to scan all 100M items to find the top 100 — that would take too long. Instead, we maintain a min-heap of size K equals 100 alongside the sketch. For each incoming event, we increment the item's count in the sketch. If the item is already in the heap, we update its count and re-heapify. If it's not in the heap, we check if its approximate count exceeds the minimum count in the heap. If yes, we replace the minimum with this item and re-heapify. This way, the heap always contains the approximately top-K items, and we only need O(log K) work per event for heap operations."))

    lines.append(("interviewer", "Why use a Count-Min Sketch at all? Why not just maintain exact counts for items that are in or near the top-K?"))

    lines.append(("candidate", "That's a good question. The Space-Saving algorithm does exactly that — it maintains exact counts for the K items currently in the structure and replaces the minimum when a new item arrives. It guarantees that all items with count greater than N divided by K are included in the result. With K equal to 100 and N equal to 86.4 billion, that means any item with count greater than 864 million is guaranteed to be found. But there might be items just below the top 100 with counts of, say, 500 million that are missed because they never get a chance to enter the structure. The Count-Min Sketch plus heap approach gives us better recall because the sketch provides approximate counts for all items, including those not currently in the heap. When a new item arrives, we can check its approximate count against the heap minimum, and if it's close enough, we give it a chance to enter."))

    lines.append(("candidate", "Hmm, actually, I'm overcomplicating this. Let me reconsider. The Space-Saving algorithm with a monitor size slightly larger than K — say 1000 instead of 100 — provides excellent recall. It tracks the top 1000 items exactly and then returns the top 100 from those. With 1000 tracked items, the error for each item is at most N divided by 1000, which is much smaller. The memory is 1000 times 16 bytes equals 16 KB per window. That's tiny. And the recall is near-perfect because we're tracking 10x more items than we need. I think the Space-Saving algorithm with a larger monitor is simpler and more effective than the Count-Min Sketch plus heap approach for this specific problem. Let me revise my architecture."))

    lines.append(("candidate", "Wait, but I need to be careful. Space-Saving only works for a single stream. For sliding windows, we need to handle item expiration — when an item's oldest event falls out of the window, we need to decrement its count. Space-Saving does not support decrements naturally. This is where the sliding window requirement makes things significantly harder."))

    # SECTION 4: Deep Dive — Sliding Window Algorithms, Count-Min Sketch, Memory Efficiency (~8 min)
    lines.append(("interviewer", "Good catch. Let's deep dive into the sliding window challenge."))

    lines.append(("candidate", "Sliding windows are the hardest part of this problem. There are three main approaches. The first is brute force: maintain a queue of all events in the window. When an event expires, remove it and decrement the item's count. This requires storing all events in the window. For the 1-day window, that's 86.4 billion events at maybe 12 bytes each (8 bytes for item ID plus 4 bytes for timestamp), which is about 1 TB. Impractical for in-memory processing. The 1-minute window is 60M events at 12 bytes, which is 720 MB — feasible but expensive."))

    lines.append(("candidate", "The second approach is partitioned counting with time buckets. Instead of a true sliding window, we divide time into discrete buckets — say 1-second buckets for the 1-minute window, 1-minute buckets for the 1-hour window, and 1-hour buckets for the 1-day window. Each bucket contains a Count-Min Sketch or hash map of item counts during that time interval. To compute the top-K for a sliding window, we aggregate the relevant buckets. For the 1-minute window, we sum 60 1-second buckets. For the 1-hour window, we sum 60 1-minute buckets. For the 1-day window, we sum 24 1-hour buckets. The advantage is that we only need to store the sketches for the active buckets, not individual events. The disadvantage is that the window boundary is approximate — we're computing the top-K for a slightly different window depending on bucket alignment."))

    lines.append(("candidate", "The third approach is a more sophisticated streaming algorithm specifically designed for sliding windows, like the LossyCounter with expiration or the SWAF (Sliding Window Aggregation Framework). But these are complex and often have worse practical performance than the bucket approach. I'd go with the bucket approach for its simplicity and practical efficiency."))

    lines.append(("interviewer", "Let's flesh out the bucket approach. How does it work in detail for the 1-minute window?"))

    lines.append(("candidate", "For the 1-minute window, we maintain 60 1-second buckets. Each bucket is a hash map from item ID to count for that second. Every second, a new bucket is created and the oldest bucket is discarded. To compute the top-100 for the last minute, we iterate over all 60 buckets, sum the counts per item, and find the top 100. But iterating 60 hash maps and summing counts for all items is expensive — with 20M distinct items per minute, summing 60 maps each with 300K entries — wait, that's 20M total distinct items, but per second we see about 333K distinct items (20M divided by 60). So each 1-second bucket has about 333K entries. Summing 60 buckets with 333K entries each means processing about 20M entries total. Even at 100ns per entry, that's 2 seconds — way too slow for a 1-second update cycle."))

    lines.append(("candidate", "I need a different strategy. Instead of recomputing from scratch every second, I should maintain a running aggregate. The idea is to keep a single hash map that represents the sum of all active buckets. When a new bucket arrives, we add its counts to the aggregate. When an old bucket expires, we subtract its counts from the aggregate. The top-100 can then be computed from the aggregate hash map. The aggregate update is much cheaper — we only need to process one bucket's worth of entries per second, not all 60. That's 333K entries per second, which at 100ns per entry takes about 33ms. Feasible."))

    lines.append(("candidate", "But there's a problem: when we subtract an expired bucket, some items' counts might drop to zero, and we need to remove them from the aggregate. If we don't, the aggregate grows unbounded. We'd need to track which items are in which buckets — a reverse index. This adds complexity. An alternative is to use a Count-Min Sketch per bucket instead of a hash map. The sketch has fixed size regardless of the number of distinct items. When we add and subtract sketches, the fixed-size structure is easy to manage. But sketch subtraction only works for sketches with the same hash functions, and the subtraction amplifies errors — the error after subtracting is the sum of the errors of both sketches."))

    lines.append(("candidate", "Let me think about which approach is best. For the 1-minute window with 60 1-second buckets, using a Count-Min Sketch per bucket is elegant. Each sketch is small — maybe 50 KB with 1000 buckets and 5 hash functions. Sixty sketches total 3 MB. The aggregate is another sketch that we update by adding and subtracting sketches. The error accumulates, but with 60 additions and subtractions, the total error is about 60 times the single-sketch error. If each sketch has epsilon equals 0.01, the aggregate error is about 0.6 — which means the estimated count can be off by 60 percent of N. That's terrible. We'd need much tighter individual sketches to keep the aggregate error acceptable. With epsilon equals 0.001 per sketch and 5 hash functions, each sketch is 5 times 1000 times 8 equals 40 KB. Sixty sketches total 2.4 MB. Aggregate error is 60 times 0.001 times N equals 0.06 times N. Still too high for 1 percent accuracy."))

    lines.append(("candidate", "OK, the Count-Min Sketch per bucket approach does not work well for aggregation due to error amplification. Let me go back to the hash map per bucket approach with the running aggregate. The key optimization is: we don't need to track all items in the aggregate — we only need the top 1000 or so candidates. So we use a two-level structure. Level 1: each 1-second bucket stores exact counts for all items in that second using a hash map. Level 2: the running aggregate only tracks items that are candidates for the top-100. When a new bucket arrives, for each item in the bucket, we add its count to the aggregate. When a bucket expires, we subtract the counts. Items that drop to zero are removed. The aggregate hash map only contains items that have appeared in at least one non-expired bucket — so it's bounded by the number of distinct items in the window, not the total events."))

    lines.append(("interviewer", "How do you handle the case where the aggregate hash map is still too large?"))

    lines.append(("candidate", "For the 1-minute window, the aggregate has at most 20M entries at 16 bytes each — about 320 MB. That's large but manageable on a single machine. For the 1-hour and 1-day windows, the aggregate would be too large. Here's where we use a different strategy for each window size. The 1-minute window: exact counting with the running aggregate approach. The 1-hour window: we use 60 1-minute aggregates, each computed as I just described. To get the 1-hour top-100, we merge the 60 1-minute aggregates. We only need to merge the top-1000 candidates from each 1-minute window, which is 60 times 1000 equals 60K items to merge. That's fast — under 10ms. The 1-day window: similarly, we merge the top-1000 candidates from each 1-hour window — 24 times 1000 equals 24K items. This hierarchical merging approach limits memory and computation at each level."))

    lines.append(("candidate", "Actually, wait — there's a flaw. The top-1000 from each 1-minute window might not include all items that are in the top-100 for the 1-hour window. An item that consistently ranks 200th in every minute would be in the top-100 for the hour but excluded from each minute's top-1000. Hmm, but if we keep top-1000 per minute, an item at rank 200 in each minute would be included in each minute's top-1000 and thus in the merge. The risk is an item that has a count just below the top-1000 threshold in each minute but accumulates to be in the top-100 over the hour. With top-1000, this is unlikely — the threshold for rank 1000 is much lower than the count needed to be in the hourly top-100. But to be safe, we could increase the candidate list to 5000 per minute. The merge still only processes 60 times 5000 equals 300K items, which is fast."))

    # SECTION 5: Failure Modes (~4 min)
    lines.append(("interviewer", "What are the most critical failure scenarios?"))

    lines.append(("candidate", "The first is a stream processor failure. If the Flink job or custom counter crashes, we miss events during the downtime. For the 1-minute window, missing even a few seconds of data creates visible gaps in the top-100. We mitigate with Kafka as a durable buffer — the stream processor can resume from the last committed offset. Kafka retains data for 24 hours by default, so even a prolonged outage is recoverable. After recovery, the processor replays the missed events and the aggregates catch up. The 1-hour and 1-day windows are more resilient — missing a few seconds barely affects the top-100."))

    lines.append(("candidate", "The second scenario is a skew in the event distribution. If a single item suddenly goes viral — say a product goes viral on social media and gets 10 percent of all traffic — the counting infrastructure for the partition handling that item becomes a hot spot. With Kafka partitioned by item ID, one partition gets a disproportionate share of events. The counter for that partition might fall behind. We mitigate by using a two-stage counting approach: first, a local counter per partition that accumulates counts and periodically flushes to the global aggregate. The flush interval is short — 100ms — so the latency is bounded. If a single partition is overwhelmed, we can split it into sub-partitions at the application level."))

    lines.append(("candidate", "The third scenario is a cold start — when the system boots up with empty data structures. The 1-minute window recovers in 1 minute as buckets fill. The 1-hour window takes an hour to fully recover. The 1-day window takes a day. During the recovery period, the top-100 is incomplete — it only reflects events since boot. We should indicate this in the API response with a data_completeness flag. For the dashboard, we could show a partial data indicator. An alternative is to pre-populate from a historical data store — load the last day's worth of pre-computed buckets from a database on startup. This takes minutes instead of hours but requires persistent storage of the bucket data."))

    lines.append(("candidate", "The fourth scenario is memory pressure on the counting nodes. If the number of distinct items in a window exceeds expectations, the aggregate hash maps grow beyond available memory. We mitigate with a fallback: if the hash map exceeds a size threshold, we switch to a Count-Min Sketch with fixed memory. The accuracy drops, but the system stays up. We also monitor the hash map sizes closely and alert if they approach the threshold, giving us time to add more memory or more counting nodes."))

    # SECTION 6: Scale & Debrief (~3 min)
    lines.append(("interviewer", "How does the design change at 10x scale — 10M events per second?"))

    lines.append(("candidate", "At 10M events per second, the 1-day window would have 864 billion events. The exact counting approach becomes impractical for all but the 1-minute window. We'd need to use Count-Min Sketches throughout, accepting higher error rates for the larger windows. The stream processing would need more partitions — maybe 200 to 500 Kafka partitions — and more counting nodes. The hierarchical merging still works: each counting node handles a subset of partitions, computes local top-1000 candidates, and a merge service combines them. For the 1-day window, we might increase the bucket granularity to 15-minute or 1-hour buckets to reduce the number of buckets to manage. The trade-off is coarser window boundaries, but for a 1-day window, a 15-minute boundary error is negligible. We'd also need to compress the bucket data for storage — using delta encoding for item IDs and variable-length encoding for counts."))

    lines.append(("candidate", "At 0.1x scale — 100K events per second — everything simplifies. A single counting node handles all three windows. The 1-minute window aggregate is about 32 MB. The 1-hour and 1-day windows use the hierarchical merge from 1-minute data. No distributed processing needed. We might even use a simple in-memory hash map for all windows without the bucket optimization, since the data volumes are small enough. A single Go or Java process handles it all."))

    lines.append(("interviewer", "Let me give you feedback. Positives: excellent requirements clarification — you immediately identified the sliding window requirement, accuracy trade-offs, and query patterns as key constraints. Your evolution from exact counting to Count-Min Sketch to Space-Saving to the bucket-based running aggregate was thoughtful — you evaluated each approach and recognized its limitations. The hierarchical merging design for different window sizes is elegant and practical. For improvement: the Count-Min Sketch per bucket with error amplification was a dead end that took a while to resolve. You could have identified the error amplification issue earlier by doing a quick error calculation upfront. Also, you didn't discuss the Space-Saving algorithm in enough depth — it's actually the most relevant algorithm for this problem, and understanding its theoretical guarantees would strengthen your analysis. Overall, strong interview with good self-corrections. Thanks."))

    lines.append(("candidate", "Thanks for the feedback. You're right — I should have done the error amplification calculation before committing to the Count-Min Sketch per bucket approach. A quick epsilon times sqrt(d) estimate would have shown the problem immediately. And I agree that Space-Saving deserves more depth, especially its guarantee that all items with count greater than N divided by m are included, where m is the monitor size. I'll study that more. Good interview."))

    return lines
