"""Mock Interview: Search Autocomplete / Typeahead — Two-voice dialogue."""


def build():
    lines = []

    # SECTION 1: Requirements (~5 min)
    lines.append(("interviewer", "Hi, today I'd like you to design a search autocomplete system — the kind of typeahead you see on Google or Amazon when you start typing and get suggestions. Start by clarifying the requirements."))

    lines.append(("candidate", "Thanks. Typeahead is a classic systems problem with really interesting latency constraints. Let me start with the most fundamental question: what's the primary use case — is this a general web search autocomplete like Google, or is it domain-specific like e-commerce product search or a social media search? The suggestion sources and ranking are very different."))

    lines.append(("interviewer", "It's a general search engine autocomplete. Think Google-scale. Users type a query prefix and we return the top suggestions."))

    lines.append(("candidate", "OK, Google-scale. That immediately raises the latency bar. Let me ask about that specifically. What's the latency requirement — I'm guessing it needs to feel instant, which means under 50 milliseconds from keystroke to suggestion. Also, how many suggestions do we return per query? And does the system support personalization — meaning, do two different users typing the same prefix see different results based on their history?"))

    lines.append(("interviewer", "Good questions. 50 milliseconds p99 latency, which means p50 should be under 20ms. We return 10 suggestions per query. Personalization is a second-tier feature — the base suggestions are global, but we overlay personal history on top. So if a user has previously searched for something, it should rank higher for them."))

    lines.append(("candidate", "A two-tier system — global base with personalization overlay. That's a good architectural split. Next question: how do we determine which suggestions to show? Is it purely based on query frequency — the most popular completions win — or do we factor in other signals like recency, trending topics, or user location?"))

    lines.append(("interviewer", "The base tier is query frequency weighted by recency — recent queries count more. We also have a trending tier that boosts queries that are suddenly spiking. Location is not required for now."))

    lines.append(("candidate", "A few more questions. First, multi-word queries: when someone types a prefix like 'new y', we need to suggest 'new york times' and 'new york weather'. Are we matching on the full prefix of the query string, or do we also support word-break matching like 'y t' matching 'youtube tv'? Second, do we need to support typeahead for queries that contain typos or misspellings? Third, what's the scale — how many daily active users and how many autocomplete requests per day?"))

    lines.append(("interviewer", "For now, only prefix matching on the full query string — 'new y' matches 'new york' but 'y t' does not match 'youtube tv'. Fuzzy matching is out of scope. Scale: 100 million DAU, about 5 billion autocomplete requests per day. That's roughly 60K queries per second on average, and peak could be 200K QPS."))

    lines.append(("candidate", "Let me also ask about the suggestion corpus size. How many unique query strings do we track? And do we need to support real-time addition of new queries, or can we batch-update the suggestion index periodically?"))

    lines.append(("interviewer", "Good question. About 100 million unique queries in the corpus. Real-time addition would be ideal but is not strictly required — a few minutes of lag for new queries is acceptable."))

    lines.append(("candidate", "What about the minimum query length before we start showing suggestions? Typing a single character generates a huge number of candidates, while typing 3 or more characters narrows it significantly. Most systems only start suggesting after 2 or 3 characters."))

    lines.append(("interviewer", "We start showing suggestions after the first character. The single-character prefix is the most expensive case, but it's also the most commonly triggered since every query starts with one character."))

    lines.append(("candidate", "Let me summarize. We're designing a search typeahead at Google scale — 100M DAU, 5B requests per day, 200K QPS peak, 50ms p99 latency, returning 10 suggestions. The suggestion ranking is frequency-based with recency weighting and a trending overlay. There's a personalization tier on top. Only full-prefix matching, no fuzzy search. The corpus has about 100M unique queries with near-real-time updates. Let me move to estimation."))

    # SECTION 2: Estimation (~5 min)
    lines.append(("interviewer", "Go ahead with the numbers."))

    lines.append(("candidate", "5 billion requests per day, 200K QPS peak. Each request is lightweight — a prefix string of maybe 10 to 20 characters and a response of 10 suggestions, each about 50 characters. So the response is about 500 bytes per request. At 200K QPS, that's 100 MB per second of outgoing bandwidth — about 800 Mbps. Manageable with a CDN or edge caching layer."))

    lines.append(("candidate", "The more interesting number is the size of the suggestion corpus. A typical search engine might track the top 100 million unique query strings. Each query string is about 30 characters on average. Wait, that's not enough — we need the frequency and recency data too. Let me think about the data structure. If we use a trie, we need to store the trie in memory. With 100 million unique queries averaging 30 characters each, a naive trie with one node per character would have at most 3 billion nodes. Each node stores a character, a pointer to children, and potentially a list of top suggestions for that prefix. At about 50 bytes per node — character, children pointers, suggestion list header — that's 150 GB. That seems high. Let me reconsider."))

    lines.append(("candidate", "Actually, 3 billion nodes is the worst case. In practice, many queries share prefixes. A prefix like 'how to' is common to millions of queries. The actual number of unique nodes is much smaller — maybe 200 to 500 million nodes for 100 million queries. At 50 bytes per node, that's 10 to 25 GB. Plus the top suggestion lists. If each node stores the top 10 suggestions as references — say 8 bytes per reference — that's 80 bytes per node for the suggestion list. So 200 to 500 million nodes times 130 bytes, which is 26 to 65 GB. That fits in memory across a few machines, but we need replication for availability and sharding for the full dataset at Google scale."))

    lines.append(("interviewer", "What about the personalization data?"))

    lines.append(("candidate", "Right. For 100M DAU, we need to store each user's recent search history. If we keep the last 100 queries per user at 30 bytes each, that's 3 KB per user, times 100M users — 300 GB. This needs its own storage tier. We wouldn't load all of it in memory — just the active users. With 100M DAU, they're all active by definition, so 300 GB in a distributed cache like Redis with sharding. Each autocomplete request would first look up the user's recent queries from the cache, then merge them with the global suggestions, boosting any personal queries that match the prefix. The cache lookup adds maybe 2 to 3ms if we co-locate the cache with the suggestion servers."))

    lines.append(("candidate", "Actually, I need to reconsider that latency estimate. A Redis lookup from the same data center is about 0.5ms. But if the personalization cache is in a different region from the suggestion server, it could be 10 to 30ms, which blows our latency budget. We need to co-locate the personalization cache with each suggestion cluster. With a globally distributed system, each region has its own Redis cluster for personalization data. The user's search history is replicated to the region closest to them. This adds operational complexity but is essential for latency."))

    # SECTION 3: High-Level Architecture (~5 min)
    lines.append(("interviewer", "Good. Let's move to the high-level architecture."))

    lines.append(("candidate", "The system has two main paths: the read path for serving autocomplete requests, and the write path for updating the suggestion index. Let me start with the read path since it is latency-critical."))

    lines.append(("candidate", "When a user types a character, the client sends a request to our autocomplete service. The request includes the prefix typed so far, the user ID for personalization, and possibly a client timestamp. The request hits a load balancer that routes to one of many stateless autocomplete servers. Each server holds a replicated copy of the trie in memory. The server walks the trie from root following the prefix characters, finds the node for the prefix, and retrieves the pre-computed top 10 suggestions stored at that node. Then it checks the personalization cache for this user's recent queries, finds any that match the prefix, and merges them into the top 10, boosting personal matches above the global ones. The whole thing needs to complete in under 20ms to stay within the 50ms p99 budget including network latency."))

    lines.append(("interviewer", "Why pre-compute the top suggestions at each node instead of computing them on the fly?"))

    lines.append(("candidate", "Computing the top 10 for a prefix on the fly would require traversing the entire subtree under that node and aggregating frequencies. For a single-character prefix like 'h', the subtree could contain millions of queries. Even at microsecond-per-node traversal, that is seconds of compute — way over budget. Pre-computing means each node already has its top 10 stored, so the lookup is O(prefix length) — just walk the trie, read the pre-computed list, and return. The prefix length is at most maybe 50 characters, so that is 50 memory lookups, which takes microseconds."))

    lines.append(("candidate", "Now for the write path. We can't update the trie on every single query — that would be 60K writes per second to the in-memory trie, and updating a node's top-10 list requires recomputing from its subtree, which is expensive. Instead, we use a Lambda architecture. The speed layer tracks recent query counts in a rolling window — say the last hour — using a distributed counter in Redis or a stream processing framework like Flink. The batch layer processes the full query log every few hours, recomputes all frequencies with recency weighting, rebuilds the trie, and deploys it as a new snapshot. The serving layer merges both: it serves from the batch trie but boosts entries that are trending in the speed layer."))

    lines.append(("interviewer", "How exactly does the merge between batch and speed layer work?"))

    lines.append(("candidate", "Each autocomplete server holds two data structures in memory: the batch trie with pre-computed top suggestions, and a hash map from the speed layer that maps query strings to their recent hourly counts. When a request comes in for a prefix like 'new y', the server walks the batch trie to get the top 10 suggestions — say 'new york times' with frequency 1M, 'new york weather' with frequency 800K, and so on. Then it checks the speed layer: are any of these queries trending? If 'new york times' has a normal hourly count of 10K but the speed layer shows 100K in the last hour, it is trending and gets boosted. The server computes a combined score — batch frequency plus speed layer frequency with a higher weight for recency — and returns the top 10 by combined score."))

    lines.append(("candidate", "Wait, that last part has a problem. Checking the speed layer for all queries matching 'new y' means we need an index on the speed layer too. A simple hash map won't work for prefix lookups. We would need a second trie for the speed layer, or we would need to maintain a list of trending prefixes. Let me think about this differently. Maybe the speed layer only contains the top trending queries — say the top 100K queries that are spiking. Then we can keep a separate smaller trie for just those trending queries. When serving, we look up both the main trie and the trending trie, merge the results, and return. The trending trie is much smaller — 100K queries instead of 100M — so it is fast to update and fast to walk."))

    lines.append(("candidate", "The trending trie is updated by the Flink speed layer job. This job processes the query event stream, maintains a sliding window of query counts, and identifies queries whose current count significantly exceeds their baseline — maybe 3x the baseline count. These trending queries are published to a Kafka topic, consumed by the trending trie updater, and inserted into the in-memory trending trie on each suggestion server. The update is incremental — we only add or update trending queries, not rebuild the entire trie. A query that stops trending is removed from the trending trie on the next cycle, which runs every 30 seconds."))

    # SECTION 4: Deep Dive — Trie, Sharding, and Personalization (~8 min)
    lines.append(("interviewer", "Let's deep dive into the trie data structure and how you handle sharding."))

    lines.append(("candidate", "The trie is the heart of the system. Each node represents a character in a query prefix. The root node represents the empty prefix. Each edge is labeled with a character. A path from root to a node spells out a prefix. Nodes that represent complete queries store the query's frequency score. Every node stores its top 10 suggestions — pre-computed during the batch rebuild."))

    lines.append(("candidate", "For the trie structure, I would use a radix tree — also called a compressed trie — where chains of single-child nodes are merged into a single edge. For example, if only one query starts with the characters 'xyl', the path for 'x', 'y', 'l' collapses into a single edge labeled 'xyl'. This reduces the node count significantly — maybe by 50 to 70 percent — which saves memory and improves cache locality. Each node stores: the edge label string, a map from first-character to child node, the top-10 suggestion list, and optionally the frequency score if this node represents a complete query. In a language like Java or Go, the child map can be a hash map for fan-out nodes or a sorted array for binary search when fan-out is small."))

    lines.append(("interviewer", "How do you shard a trie across multiple machines?"))

    lines.append(("candidate", "This is one of the trickier parts. We can't just hash query strings because prefix lookups need to traverse from the root. We need to shard by prefix. The idea is to assign subtrees to different shards. For example, all queries starting with 'a' through 'c' go to shard 1, 'd' through 'f' to shard 2, and so on. But the distribution is very uneven — the prefix 'h' (as in 'how to...') and 'w' (as in 'what, when, where...') are far more common than 'z' or 'q'. So we need a smarter partitioning."))

    lines.append(("candidate", "I would use a two-level approach. The first level is a lightweight router that knows which prefix ranges are on which shard. The router maintains a mapping like: 'a' goes to shard 1, 'b' goes to shard 2, 'c' and 'd' go to shard 3 (because 'c' and 'd' subtrees are smaller), 'h' goes to shard 4 AND 5 (because the 'h' subtree is huge), and so on. The mapping is determined during the batch rebuild based on subtree sizes, with the goal of balancing memory and CPU load across shards. For a really large 'h' subtree, we split it further: 'ha' through 'hn' on shard 4, 'ho' through 'hz' on shard 5."))

    lines.append(("candidate", "When a request comes in for a prefix like 'how to', the router looks at the prefix and determines the target shard — shard 5 in this case. The request is forwarded to that shard, which walks its local trie and returns the top 10. If the prefix is very short — just 'h' — it might need to query multiple shards and merge the results. That is the tradeoff: shorter prefixes are more expensive because they fan out to more shards. But in practice, most autocomplete requests have prefixes of 3 or more characters, which map to a single shard. And for the first character, we can pre-compute the top 10 at the router level — cache the global top 10 for each single-character prefix."))

    lines.append(("interviewer", "How do you handle multi-word queries in the trie?"))

    lines.append(("candidate", "Multi-word queries are stored as-is in the trie — spaces are just another character. So 'new york' is a path through 'n', 'e', 'w', space, 'y', 'o', 'r', 'k'. The space character is a valid edge label. This works naturally for prefix matching. When someone types 'new y', they are already walking the trie through 'new ' and into 'y'. No special handling needed. The radix tree would compress common sequences like 'new ' into a single edge, which is efficient."))

    lines.append(("candidate", "But there's a subtlety I should address. Users often type queries in different word orders — 'york new restaurant' versus 'new york restaurant'. In our design, since we only do prefix matching, 'york new' would not suggest 'new york restaurant'. That is a limitation. Google handles this with query rewriting and matching on token permutations, but we explicitly scoped that out. We could add a simple enhancement: store common query rephrasings as separate entries in the trie. If 'new york restaurant' is popular, we also index 'restaurant new york' as a redirect that maps to the same suggestion. This is done during the batch processing by analyzing query co-occurrence data."))

    lines.append(("interviewer", "Now let's talk about the personalization tier in more detail."))

    lines.append(("candidate", "Personalization works like this. For each user, we maintain a list of their recent queries — last 100 or so — with timestamps and click-through information. When a user types a prefix, we first look up their personal query history from the personalization cache. We find any queries in their history that match the prefix — prefix matching on their past queries. Then we merge these with the global suggestions. The merge strategy is: personal queries always rank above global queries if they match the prefix, up to a maximum of 3 personal suggestions out of 10. This prevents the typeahead from becoming completely different for each user — we still show mostly global suggestions, which helps discoverability."))

    lines.append(("candidate", "The personalization cache lookup needs to be fast — under 3ms. We store each user's recent queries as a sorted set in Redis, keyed by user ID. The values are the query strings with scores based on recency and frequency. For prefix matching on personal queries, we can't use a per-user trie — that would be 100M in-memory tries, which is impractical. Instead, we store the last 100 queries as a list and do a linear scan for prefix matching. 100 string comparisons is trivially fast — under 0.1ms. Actually, wait. If we want to scale to users with thousands of past queries, a linear scan becomes expensive. But 100 is a reasonable limit, and we can use a simple optimization: store queries sorted alphabetically and do a binary search for the prefix range, then scan only the matching range. With 100 queries, it is marginal, but at 1000 queries, binary search would help significantly."))

    lines.append(("candidate", "Let me think about how to handle prefix matching more efficiently for personalization. We could build a small in-memory trie per request from the user's last 100 queries. Building a trie from 100 strings of average length 30 takes about 3000 node insertions, which is under 0.1ms. Then the prefix lookup is O(prefix length). This is actually faster than a binary search for short prefixes because the trie pruning eliminates non-matching queries immediately. For longer personal query histories — say 500 queries — the trie build takes about 0.5ms, which is still acceptable. I'd go with the per-request mini-trie approach for personalization."))

    lines.append(("interviewer", "How do you update the personalization data in real time?"))

    lines.append(("candidate", "When a user submits a search query, we update their personalization data asynchronously. The search service publishes an event to a Kafka topic: user ID, query string, timestamp, and whether they clicked a result. A personalization updater consumer reads these events and updates the Redis sorted set for each user. We append the new query and trim the set to keep only the most recent 100. The update is append-only and very fast — a ZADD and ZREMRANGEBYRANK in Redis, which takes under 1ms. The autocomplete service might serve a slightly stale personalization list — at most a few seconds behind — but that is completely acceptable. No one expects their typeahead to reflect a search they just did milliseconds ago."))

    # SECTION 5: Failure Modes (~4 min)
    lines.append(("interviewer", "What are the most critical failure scenarios?"))

    lines.append(("candidate", "The first is trie shard failure. If a shard goes down, all prefixes in its range return no suggestions. We mitigate with replication — each shard has at least 2 replicas, and the router fails over to a healthy replica. The trie is read-only from the serving perspective, so replicas are perfectly consistent. The second scenario is a stale batch trie. If the batch rebuild is delayed — maybe the data pipeline is slow — users see outdated suggestions. This is where the speed layer helps: even with a stale batch trie, the trending trie captures recent spiking queries. Users still get timely suggestions for breaking events."))

    lines.append(("candidate", "The third scenario is a personalization cache outage. If Redis goes down, we lose personalization and serve only global suggestions. This is a graceful degradation — users still get suggestions, just not personalized ones. We would serve from the batch trie alone and skip the personal merge step. The client might notice slightly less relevant suggestions, but the service remains functional. We'd alert the operations team and restore the cache from a Redis snapshot backup, which takes a few minutes."))

    lines.append(("candidate", "The fourth scenario is a thundering herd on trending events. When a major news event happens, millions of users type the same few queries simultaneously. This creates a hot spot on the trie nodes for those prefixes. The shard holding the 'b' prefix for 'breaking news' gets hammered. We mitigate with application-level caching — each autocomplete server caches the top-10 result for popular prefixes with a short TTL of 30 seconds. If the same prefix is queried multiple times within 30 seconds, we return the cached result without walking the trie. For a breaking news event, the cache hit rate for that prefix would be nearly 100 percent, which actually reduces load on the trie. The cache also handles the read path efficiently — we do not need to worry about stale results because the speed layer will update the trending data and the next request after cache expiry will pick it up."))

    lines.append(("candidate", "Actually, let me reconsider the thundering herd scenario more carefully. The application-level cache helps, but the initial cache miss spike could still overwhelm a single shard. When news breaks, within the first second, thousands of requests hit the same shard for the trending prefix. The shard might handle 10K QPS normally, but a sudden spike to 100K could cause timeouts. We need request coalescing — when multiple requests for the same prefix arrive at a server within a few milliseconds, we process only one of them and return the same result to all. This is essentially a de-duplication layer at the request level, implemented with a concurrent hash map that tracks in-flight requests per prefix. It reduces the effective load on the trie by 10 to 100x during hot spot events."))

    # SECTION 6: Scale & Debrief (~3 min)
    lines.append(("interviewer", "How does the design change at 10x scale — 50B requests per day?"))

    lines.append(("candidate", "At 50B requests per day, peak QPS could hit 2 million. That is a different beast. The trie would need many more shards — maybe 100 to 200 shards. The routing layer becomes more critical and might itself become a bottleneck. We would need hierarchical routing — a first-level router that directs to a second-level router, which then directs to the actual shard. Or we could use consistent hashing on the prefix to distribute across shards, but that breaks the prefix locality that our trie design depends on."))

    lines.append(("candidate", "I think we would need to move to an edge-computed model. Instead of all requests hitting a central cluster, we deploy the trie — or a subset of it — to edge locations worldwide. The most popular suggestions can be served from CDN edge nodes with no backend call at all. We would pre-compute top suggestions for all prefixes up to length 3 and distribute them to edges. Longer prefixes still hit the backend, but they represent a smaller fraction of traffic. This edge-tier approach is what large-scale systems like Google actually use — the first few characters are resolved at the edge, and deeper queries go to regional data centers."))

    lines.append(("candidate", "At 0.1x scale — 500M requests per day — the design simplifies. A single trie replica might fit in memory on a single machine. We would need 3 to 5 machines for redundancy, but no sharding. The speed layer could be a simple Redis counter instead of a full Flink pipeline. The batch rebuild could run on a single machine in an hour. The personalization cache is still 30 GB for 10M users, which needs a small Redis cluster, but nothing dramatic. The core architecture stays the same — trie with pre-computed suggestions, Lambda architecture for updates, personalization overlay — just with fewer machines."))

    lines.append(("interviewer", "Let me give you feedback. Positives: excellent requirements clarification — you asked about personalization, multi-word handling, fuzzy matching scope, and corpus update frequency unprompted. The two-tier suggestion design with the trending overlay is well thought out, and the per-request mini-trie for personalization is a creative optimization. Your trie sharding by prefix range with load-aware splitting shows real understanding of the data distribution problem. The radix tree optimization for memory efficiency was a good detail. For improvement: when discussing the speed layer merge, you initially proposed a hash map approach that doesn't support prefix lookups, then caught and corrected it — that's fine in an interview, but you could have been more systematic in evaluating options upfront. Also, you didn't discuss the cost of the batch rebuild — rebuilding a 100M-query trie every few hours is a significant compute job, and you should have estimated the time and resources. Overall, very strong. Thanks."))

    lines.append(("candidate", "Thanks for the feedback. You are right about the speed layer — I should have considered prefix lookup requirements before choosing the data structure. And the batch rebuild cost is an important operational consideration — at 100M queries, rebuilding a trie might take 30 to 60 minutes on a cluster of 10 machines, which limits how frequently we can update. We would need to optimize the build process with parallel subtree construction and incremental diff-based updates where possible. Good points to remember."))

    return lines
