"""Mock Interview: Video Streaming Platform — Two-voice dialogue."""


def build():
    lines = []

    # SECTION 1: Requirements (~5 min)
    lines.append(("interviewer", "Hi, welcome. Today I'd like you to design a video streaming platform — something along the lines of YouTube. Users upload videos, other users watch them. Start by clarifying the requirements."))

    lines.append(("candidate", "Thanks. Video streaming is a broad problem, so scoping matters a lot. Let me start with the most fundamental split: are we building primarily for video-on-demand, or does live streaming need to be part of this too? Because the architecture is quite different — VOD can go through a full processing pipeline before anyone sees it, but live streaming has real-time constraints that change almost everything downstream."))

    lines.append(("interviewer", "Good question. Let's start with VOD as the core product, but I want you to keep live streaming in mind as a future extension. So design for VOD first, but mention where live would change things."))

    lines.append(("candidate", "OK, VOD with live as a future consideration. Next: scale. How many users, how many videos watched per day, and what's the upload volume? Also, what's the average video length and resolution? A platform of 10 million daily active users watching short clips is very different from one serving long-form 4K content."))

    lines.append(("interviewer", "We have about 1 billion total users, 500 million daily active users. Roughly 5 billion video views per day. About 500 hours of video uploaded every minute. Average video length is 10 minutes, and we need to support up to 4K resolution."))

    lines.append(("candidate", "500 hours per minute of upload — that's massive. That immediately tells me the processing pipeline is going to be a major engineering challenge, not just the serving side. Let me ask about a few more requirements. First, do we need to support adaptive bitrate streaming, or is a single quality level sufficient? Second, what about monetization — ads, subscriptions? Third, do we need search and recommendation, or is this purely a hosting and delivery platform?"))

    lines.append(("interviewer", "Yes, adaptive bitrate streaming is required. Monetization is out of scope for now — focus on the core upload, process, and serve pipeline. But search and recommendation are important. Users need to discover videos, and we need a basic recommendation system."))

    lines.append(("candidate", "Got it. A few more things. Do we need a view counter — like, a real-time view count displayed on each video? And what about content moderation — with 500 hours uploaded per minute, human review is impossible at scale. Do we need automated moderation?"))

    lines.append(("interviewer", "Yes, view counter is required and it needs to be reasonably accurate. Content moderation — let's say we need automated flagging for policy-violating content, but you don't need to design the ML model, just the pipeline that processes moderation decisions."))

    lines.append(("candidate", "Let me summarize. We're designing a VOD platform with 1 billion users, 500 million DAU, 5 billion daily views, 500 hours uploaded per minute, up to 4K resolution, adaptive bitrate streaming, search and recommendation, a view counter, and automated content moderation. Live streaming is a future extension. Let me move to estimation."))

    # SECTION 2: Estimation (~5 min)
    lines.append(("interviewer", "Go ahead."))

    lines.append(("candidate", "Let's start with storage, since video is the dominant cost. 500 hours of video uploaded per minute. That's 500 times 60 times 24 equals 720,000 hours per day. Average video is 10 minutes, so that's 720,000 times 6 equals 4.32 million videos per day. Wait, that doesn't feel right. Let me recalculate. 500 hours per minute means 500 times 60 minutes per hour times 24 hours equals 720,000 hours of raw video per day. At 4K, raw uncompressed video is enormous, but uploaded video is already compressed. Let's assume the uploaded video is roughly 10 Mbps on average — that's a mix of 4K at higher bitrates and 1080p at lower ones. 720,000 hours times 3600 seconds times 10 Mbps divided by 8 bits per byte equals about 3.24 petabytes per day of uploaded content."))

    lines.append(("candidate", "But that's just the original upload. After transcoding, we store multiple renditions — typically 4 to 6 bitrates per video. So multiply by about 4 on average, and we're looking at roughly 13 petabytes per day of total storage. Over 5 years, that's about 13 times 365 times 5 equals roughly 24,000 petabytes, or 24 exabytes. That's enormous. This is why storage tiering is critical — hot videos go on fast storage or CDN, while cold videos go to cheaper object storage."))

    lines.append(("interviewer", "What about bandwidth for serving? That's usually the biggest cost."))

    lines.append(("candidate", "Right, bandwidth dominates. 5 billion views per day, average video length 10 minutes. But not every view watches the full video — let's assume average watch time is 5 minutes. And with adaptive bitrate, the average bitrate served might be around 3 Mbps — some users on slow connections get 720p, others get 1080p, a small fraction gets 4K. So 5 billion times 5 minutes times 60 seconds times 3 Mbps divided by 8 equals roughly 562,500 terabytes, or 562 petabytes per day of egress bandwidth. At scale, that's why CDN is not optional — it's the only way to serve this economically. Even with CDN, bandwidth is typically 50 to 70 percent of total infrastructure cost for a video platform."))

    lines.append(("candidate", "For the metadata side, each video has maybe 1 KB of metadata — title, description, tags, uploader info, timestamps, view count. With 4.32 million new videos per day, that's only about 4.3 GB per day of new metadata. Over 5 years, that's about 8 TB. The metadata database is tiny compared to video storage — it fits comfortably in a sharded relational database. The search index is larger but still in the low terabytes range."))

    lines.append(("interviewer", "What about the view counter specifically? You said it needs to be reasonably accurate."))

    lines.append(("candidate", "View counter is interesting because it's extremely write-heavy. 5 billion views per day means about 57,000 view increments per second at peak — probably closer to 100K at peak hours. A relational database can't handle that directly. We'd buffer views in a write-back cache — increment a counter in Redis, and periodically flush aggregates to the database. But we need deduplication — a user watching the same video on loop shouldn't inflate the count. Typically, we count unique views per video per user within a time window — say, one view per user per 24 hours. We'd use a Bloom filter or a set in Redis per popular video to track recent viewers. Actually, wait — a set per video for every video is too much memory. A Bloom filter at, say, 0.1 percent false positive rate is much more memory-efficient. We accept a tiny overcount in exchange for feasibility."))

    # SECTION 3: High-Level Architecture (~5 min)
    lines.append(("interviewer", "Good. Let's move to the high-level architecture."))

    lines.append(("candidate", "OK. The overall flow has two main paths — upload and playback. On the upload side, the user uploads a video through the Upload Service. Instead of uploading directly to our servers, we give them a pre-signed URL to upload directly to object storage — S3 or equivalent. This keeps our upload service stateless and avoids funneling terabytes of video through our API servers. Once the upload completes, object storage sends a notification — via a webhook or event — to the Video Processing Service."))

    lines.append(("candidate", "The Video Processing Service orchestrates a DAG of processing tasks. The first task is transcoding — the video is converted into multiple renditions at different bitrates and resolutions using something like FFmpeg. Simultaneously, we extract thumbnails, generate subtitle files if needed, extract audio, and run content moderation checks. Each task in the DAG can run in parallel where possible. The transcoded outputs are stored back in object storage, and the metadata — including all rendition URLs, duration, and thumbnails — is written to the Metadata Service, which backs a relational database and a search index."))

    lines.append(("candidate", "On the playback side, the client requests a video from the Streaming Service. The Streaming Service looks up the video metadata, determines the appropriate manifest — HLS or DASH — and returns a URL pointing to the CDN. The client then streams the video from the nearest CDN edge. The manifest lists all available bitrates and resolutions, and the client's ABR algorithm selects which rendition to fetch based on current network conditions. The view counter increments in the background as part of the playback start event."))

    lines.append(("interviewer", "Why use a pre-signed URL for uploads instead of accepting the upload directly?"))

    lines.append(("candidate", "Two reasons. First, scale — if videos flow through our API servers, we'd need massive upload capacity and connection handling. With a pre-signed URL, the client uploads directly to S3, which is built for exactly this. Our Upload Service just generates the URL and records the intent. Second, reliability — if our upload service crashes mid-transfer, the user has to start over. S3 supports multipart upload, so the client can upload in chunks and retry individual chunks. This is especially important for large 4K videos that might take hours to upload on a slow connection."))

    lines.append(("interviewer", "What about the video processing DAG — how do you coordinate all those tasks?"))

    lines.append(("candidate", "I'd use a workflow engine — something like a DAG-based task queue. Each video upload triggers a new workflow instance. The workflow defines dependencies: transcoding must complete before we finalize the manifest, but thumbnail extraction, audio extraction, and content moderation can run in parallel with transcoding. Each task runs on a worker pool. For transcoding specifically, GPU workers are much faster than CPU-only, so we'd have a dedicated GPU-backed transcoding pool. The workflow engine retries failed tasks with exponential backoff. If a task fails permanently — say, the video file is corrupt and can't be transcoded — the workflow marks the video as UPLOAD_FAILED and notifies the uploader."))

    # SECTION 4: Deep Dive — Video Processing, CDN, and Adaptive Bitrate Streaming (~10 min)
    lines.append(("interviewer", "Let's deep dive into the most complex parts. Start with transcoding — how exactly does it work?"))

    lines.append(("candidate", "Transcoding takes the uploaded video and produces multiple renditions. For a typical video, we'd produce something like: 4K at 20 Mbps, 1080p at 8 Mbps, 1080p at 4 Mbps, 720p at 2.5 Mbps, 480p at 1 Mbps, 360p at 500 Kbps, and 144p at 200 Kbps. Each rendition is encoded using H.264 for broad compatibility, with H.265 or VP9 for newer devices that support it. The output format is HLS — HTTP Live Streaming — which segments the video into small chunks, typically 2 to 10 seconds each, and generates an M3U8 manifest file that lists all segments for each rendition. DASH works similarly with MPD manifests and MPEG-TS or fMP4 segments."))

    lines.append(("candidate", "The reason we use segmented formats like HLS is that it enables adaptive bitrate streaming — the client can switch between renditions at segment boundaries without interrupting playback. If we just had one big MP4 file per rendition, the client would need to download the entire file or do byte-range requests, which is less efficient for switching bitrates mid-stream. Also, HLS segments are cacheable on the CDN — each segment is a static file with a predictable URL, which makes CDN caching very effective."))

    lines.append(("interviewer", "Walk me through adaptive bitrate streaming from the client's perspective. How does the client decide which rendition to play?"))

    lines.append(("candidate", "The client's ABR algorithm is actually one of the trickiest parts of video streaming, and it directly impacts user experience. Here's how it works. The client first fetches the master manifest, which lists all available renditions with their bandwidth requirements. It starts by requesting a low-quality rendition — say, 480p — to begin playback quickly, minimizing startup delay. Then it monitors two signals: the current download throughput and the playback buffer level. Download throughput is estimated from the time it takes to download each segment. If throughput is consistently higher than the current rendition's bitrate — say, 5 Mbps throughput while playing 2.5 Mbps 720p — the algorithm switches up to the next higher rendition on the next segment request."))

    lines.append(("candidate", "Actually, let me reconsider. It's a bit more nuanced than that. A naive throughput-based algorithm oscillates a lot — throughput varies from segment to segment due to network jitter, and if you switch up and down on every fluctuation, the user sees visible quality shifts. Good ABR algorithms use a buffer-based approach: they maintain a target buffer level — say, 10 seconds — and only switch up when the buffer is full enough to absorb a temporary throughput drop. If the buffer drops below a low-water mark — say, 2 seconds — the algorithm aggressively switches down to avoid rebuffering, which is the worst user experience. The key insight is that a momentary drop in quality is much less noticeable than a playback stall."))

    lines.append(("interviewer", "What happens when the client switches renditions — does the manifest change?"))

    lines.append(("candidate", "No, the master manifest stays the same. Each rendition has its own sub-manifest listing its segments. When the client decides to switch from 720p to 1080p, it simply starts requesting segments from the 1080p sub-manifest instead of the 720p one. The segment boundaries are time-aligned across all renditions, so the client can seamlessly switch at any segment boundary. The CDN sees these as independent file requests — segment 42 of 1080p is a different URL than segment 42 of 720p, and each is cached independently. This is why segment-based formats are so CDN-friendly."))

    lines.append(("interviewer", "Now let's talk about the CDN architecture. How do you design it for this scale?"))

    lines.append(("candidate", "At 562 petabytes of daily egress, CDN is not a nice-to-have — it's the entire serving model. The architecture has three tiers. The first tier is the edge cache — hundreds of points of presence around the world, close to users. Edge nodes serve segments that are currently popular. The second tier is a mid-tier or regional cache — maybe 20 to 30 regional hubs. These cache everything that's been recently accessed from their region, reducing origin fetches. The third tier is the origin, which is our object storage — S3 or equivalent — holding all video segments for all renditions."))

    lines.append(("candidate", "When a user requests a segment, the edge checks its local cache. If it's a cache hit — which it will be for popular videos — the segment is served immediately with minimal latency. If it's a miss, the edge fetches from the mid-tier. If the mid-tier also misses, it fetches from the origin. The segment is then cached at each tier on the way back. Cache hit rates are crucial — for a platform like this, I'd expect 90 to 95 percent hit rate at the edge for popular content, and maybe 70 to 80 percent overall including long-tail content. The cache eviction policy is typically LRU with some weighting toward recently uploaded videos, which tend to get a lot of traffic in their first 48 hours."))

    lines.append(("interviewer", "How do you handle the cache eviction problem? Video segments are large and there's a lot of content."))

    lines.append(("candidate", "This is where it gets interesting. A naive LRU cache would constantly evict content because the long tail of videos is enormous — most videos get very few views, but they collectively consume a lot of cache space. I'd use a tiered eviction strategy. Tier 1 is the hot cache — videos in the top 1 percent by view count in the last 24 hours. These are pinned or given very long TTLs. Tier 2 is the warm cache — moderately popular content. Standard LRU eviction. Tier 3 is the cold cache — long-tail content. These get short TTLs and are evicted first. The classification is updated periodically based on the view counter data."))

    lines.append(("candidate", "Hmm, but there's a subtlety. A new video from a popular creator might get millions of views in the first hour, but it starts with zero views. We can't wait for the view counter to catch up — by then, we're already serving from origin and wasting bandwidth. So we'd also have a prefetch mechanism: when a video from a top creator is published, we proactively push its segments to edge caches in regions where that creator has a large audience. This is like a targeted cache warm-up. It costs some bandwidth upfront but saves far more by avoiding origin fetches during the initial traffic spike."))

    lines.append(("interviewer", "What about the transcoding pipeline itself — how do you handle 500 hours per minute of upload? That's a lot of compute."))

    lines.append(("candidate", "It is. Let's estimate the compute needed. Transcoding a 10-minute video into 7 renditions takes roughly 7 times the video duration on a CPU — so about 70 minutes of compute per 10-minute video. With GPU acceleration, it's more like 7 times 0.3 times the duration, or about 21 minutes. But at 500 hours per minute, we need to transcode 500 times 60 equals 30,000 minutes of video per minute in real-time. Even with GPUs, that's about 30,000 times 2.1 minutes of compute per minute of video equals 63,000 minutes of compute per minute. So we need about 63,000 divided by 60 equals roughly 1,050 GPU-transcoding-minutes per minute of wall clock time. In other words, about 1,050 concurrent GPU instances dedicated to transcoding. At peak — which is probably 2 to 3x average — we'd need 2,000 to 3,000 GPU instances."))

    lines.append(("candidate", "This is why cloud-based auto-scaling is essential. We'd use spot or preemptible GPU instances for transcoding — if a spot instance is preempted, we just retry the task on another instance. The transcoding state is stored in object storage — input video, intermediate files, and output renditions — not on the instance itself. So preemption just means the task takes a bit longer, not that we lose work. Well, we might lose partial progress on an in-progress FFmpeg job, but the input is still in S3, so we can restart from the beginning. For very long videos, we could implement checkpointing within the transcoding pipeline, but that adds complexity."))

    lines.append(("candidate", "Wait, actually there's a better approach. Instead of transcoding the entire video as a single FFmpeg job, we can split the video into segments first, then transcode each segment independently across multiple workers. This parallelizes the transcoding — a 10-minute video split into 1-minute chunks can be transcoded across 10 workers simultaneously, reducing end-to-end latency from 21 minutes to about 2 to 3 minutes including segment reassembly. This is how large platforms actually handle it, and it also means losing a worker only requires re-transcoding one small chunk, not the entire video."))

    lines.append(("interviewer", "What about the other tasks in the processing DAG — thumbnails, audio, moderation?"))

    lines.append(("candidate", "Thumbnails are lightweight — extract a few frames at key points using FFmpeg's scene detection, maybe generate 3 to 5 candidates, and let the uploader pick or use the one with the highest sharpness score. Audio extraction is also straightforward — demux the audio track and store it separately for features like background listen or podcast mode. Content moderation is the heavy one. We'd run a multi-stage pipeline: first, an ML classifier flags potentially violating content — violence, adult content, hate speech. Flagged videos go to a human review queue. For efficiency, we can run the classifier on extracted keyframes rather than the full video — say, one frame per second. That's 600 frames for a 10-minute video, which is much cheaper than processing every frame. The classifier outputs a confidence score, and we set thresholds that balance false positives against safety requirements. The moderation decision — approve, reject, or age-restrict — is written to the metadata service, and rejected videos are removed from search results and recommendations."))

    # SECTION 5: Failure Modes (~4 min)
    lines.append(("interviewer", "What are the most critical failure scenarios?"))

    lines.append(("candidate", "The most user-visible failure is CDN origin shield overload — if the origin goes down or becomes slow, the CDN can't fill its cache, and users experience rebuffering or playback failures. To mitigate this, we'd have multiple origin endpoints across regions, and the CDN mid-tier acts as a buffer. Even if the origin is temporarily unreachable, the mid-tier and edge caches continue serving cached content for hours. The real problem is with newly uploaded or long-tail content that isn't cached yet — those users would see failures. We'd degrade gracefully by serving a lower-quality rendition if the higher-quality one isn't available, rather than failing entirely."))

    lines.append(("candidate", "Another critical failure is the transcoding pipeline going down. If transcoding workers are unavailable — say, the GPU spot market dries up — newly uploaded videos sit in an unprocessed state. Users can't watch them. We'd need reserved GPU capacity as a baseline, with spot instances for burst. And we'd prioritize transcoding — popular creators' videos get processed first, while low-priority uploads might wait longer. This is a business decision, but technically it's a priority queue for the transcoding scheduler."))

    lines.append(("interviewer", "What about data loss — could a video be lost after upload?"))

    lines.append(("candidate", "Object storage like S3 provides 11 nines of durability through erasure coding across multiple availability zones. So the probability of a stored video being lost is essentially zero. The risk is during upload — if the multipart upload fails partway through, the incomplete parts are eventually garbage-collected by S3. We handle this by recording the upload intent in our metadata service before generating the pre-signed URL. If the upload never completes — say, the user loses their connection — a background job detects the orphaned intent after a timeout and cleans up any partial uploads. The uploaded video is only marked as AVAILABLE after the processing DAG completes successfully."))

    lines.append(("candidate", "There's also the failure mode of a transcoding job producing corrupt output. FFmpeg can silently produce broken files — a segment might have a glitch or be unplayable. We'd run a validation step after transcoding: probe the output with FFprobe to verify the container format, codec, bitrate, and duration match expectations. If validation fails, we retry the transcoding job, potentially on a different worker. If it fails multiple times, we flag the video for manual review — the source file itself might be corrupt."))

    lines.append(("interviewer", "What about the view counter — what happens if the Redis counter gets out of sync with the database?"))

    lines.append(("candidate", "The view counter uses eventual consistency by design. Redis increments are fast but volatile — if a Redis node fails before the counter is flushed to the database, we lose some counts. We mitigate this in two ways. First, we use Redis with persistence enabled — AOF or RDB snapshots — so even a restart doesn't lose all data. Second, we flush counters to the database frequently — every 30 seconds or so. The worst case is losing 30 seconds of view increments, which is a tiny fraction of the total. For the displayed count, we serve from Redis, which is approximately accurate. The database is the source of truth for analytics and reporting, and it's eventually consistent with Redis."))

    lines.append(("candidate", "Actually, let me reconsider the deduplication problem under Redis failures. If a Redis node serving the Bloom filter for a popular video crashes and the replica takes over, the Bloom filter state might be slightly stale — some recently added user hashes could be lost. This means we might count a few duplicate views temporarily. But since Bloom filters can have false positives anyway, we're already tolerating a small error rate. The alternative — persisting the Bloom filter to disk — adds latency to every view increment, which defeats the purpose of using Redis. So we accept the slight inaccuracy under failure conditions. It's a view count, not a bank transaction."))

    # SECTION 6: Scale & Debrief (~3 min)
    lines.append(("interviewer", "How does the design change at 10x scale — 5 billion hours of video watched per day?"))

    lines.append(("candidate", "At 10x, the CDN architecture fundamentally changes. A single CDN provider might not have enough edge capacity globally. We'd likely use a multi-CDN strategy — two or three CDN providers with traffic split between them based on geography and cost. A CDN selector service routes each client to the best CDN for their region and current network conditions. This also provides redundancy — if one CDN has an outage, we shift traffic to another. The downside is cache splitting — the same segment might be cached in multiple CDNs, reducing the effective hit rate per CDN. But the total egress is so large that no single CDN can handle it all anyway."))

    lines.append(("candidate", "The transcoding pipeline at 10x would need 10,000 to 30,000 GPU instances. This is probably beyond spot instance availability — we'd need reserved capacity contracts or even custom transcoding hardware. Some large platforms build their own encoding ASICs because GPU transcoding is still not efficient enough at extreme scale. The processing DAG scheduler also becomes more complex — at this scale, you're managing a distributed computing cluster, and you need sophisticated scheduling to minimize cost while meeting processing latency SLAs."))

    lines.append(("candidate", "The metadata service would need more sharding — probably by video ID range with maybe 50 to 100 shards. The search index would need to be distributed — Elasticsearch or similar with a multi-cluster setup. The recommendation system, which I've barely touched on, becomes critical at 10x because the long tail of content is so vast that discovery is the main bottleneck for content creators. Collaborative filtering — users who watched X also watched Y — is the starting point, but at 10x you'd need matrix factorization or deep learning models trained on watch history, with real-time feature extraction and model serving infrastructure."))

    lines.append(("candidate", "At 0.1x scale — 50 million DAU — everything simplifies considerably. A single CDN provider handles the traffic. Transcoding can run on a few dozen GPU instances. The metadata database might not even need sharding — a large PostgreSQL instance with read replicas could handle it. The processing DAG could be a simple task queue rather than a full workflow engine. But the core architecture — pre-signed uploads, transcoding to HLS, CDN serving with ABR — stays the same. The fundamental design is correct at any scale; it's the capacity planning and operational complexity that changes."))

    lines.append(("interviewer", "Let me give you feedback. Positives: excellent requirements clarification — you surfaced live streaming, adaptive bitrate, content moderation, and view counter deduplication unprompted. The CDN tiered caching strategy with prefetching for popular creators was strong. The segment-level parallel transcoding insight showed practical understanding. Your ABR algorithm explanation went beyond surface level, especially the buffer-based approach and the trade-off between quality oscillation and rebuffering. For improvement: you didn't address storage tiering in much detail — the move from hot to cold storage is a major cost lever, and you could have quantified the savings. Also, when discussing the processing DAG, you didn't mention how the manifest is assembled after parallel transcoding of segments — that's a non-trivial coordination problem. Overall, very strong performance. Thanks."))

    lines.append(("candidate", "Thanks for the feedback. You're right about storage tiering — I should have quantified the cost difference between S3 Standard and S3 Glacier or equivalent, and defined the policy for moving videos between tiers based on access patterns. And manifest assembly after parallel segment transcoding does need explicit coordination — the workflow engine has to wait for all segments of a given rendition to complete, then concatenate the segment URLs into the rendition's M3U8 playlist, and finally assemble the master manifest from all rendition playlists. I'll make sure to cover those next time."))

    # SECTION 7: End-to-End Walkthrough (~4 min)
    lines.append(("interviewer", "Before we wrap up, trace a video upload through processing to playback — end to end."))

    lines.append(("candidate", "Sure. Step 1: the uploader opens the app and selects a video to upload. The client calls our Upload API, which creates an upload session in the metadata database with status CREATED and returns a pre-signed URL for the object storage bucket, along with a unique video ID. The pre-signed URL includes the video ID in the object key — something like videos/raw/{video_id}/original.mp4 — and is valid for 24 hours. The client begins a multipart upload directly to S3, splitting the video into 100 MB chunks."))

    lines.append(("candidate", "Step 2: the upload completes. S3 sends a notification — via S3 Event Notifications to an SNS topic, which fans out to an SQS queue — that the object has been created. Our Video Processing Service picks up the message from the queue, verifies the video ID exists and the upload session status is CREATED, then updates the status to PROCESSING and starts the processing DAG."))

    lines.append(("candidate", "Step 3: the processing DAG kicks off. First, the video is validated — FFprobe checks the container format, codec, resolution, and duration. If the video is 10 minutes long at 1080p, the DAG schedules the following parallel tasks: segment splitting — the original video is split into 1-minute chunks; thumbnail extraction — keyframes are extracted at 5 time points; audio extraction — the audio track is demuxed; and content moderation — keyframes are run through the classification model. The segment splitting must complete before transcoding can begin, since each segment is transcoded independently."))

    lines.append(("candidate", "Step 4: transcoding. Each segment is transcoded into 7 renditions. With 10 segments, that's 70 transcoding tasks running in parallel across the GPU worker pool. As each task completes, the output segment is stored in S3 at a path like videos/processed/{video_id}/1080p_8m/segment_005.ts. When all segments for a given rendition are complete, the manifest assembler creates the rendition's M3U8 playlist. When all renditions are complete, the master manifest is created, listing all renditions with their bandwidth and resolution."))

    lines.append(("candidate", "Step 5: the DAG completes. The metadata service is updated with the final video metadata — title, description, duration, all rendition URLs, master manifest URL, thumbnail URLs, and the content moderation result. The video status moves to AVAILABLE. The video is indexed in the search service, and a notification is sent to the uploader. If the uploader has subscribers, a notification event is published for the notification service."))

    lines.append(("candidate", "Step 6: a viewer opens the video. The client requests the video metadata from the Streaming API, which returns the master manifest URL, thumbnails, and other display information. The client fetches the master manifest from the CDN. Since this is a newly uploaded video, it's unlikely to be cached at the edge — the CDN fetches it from origin on the first request and caches it. The client's ABR algorithm selects an initial rendition — probably 480p for fast startup — and begins requesting segments."))

    lines.append(("candidate", "Step 7: segment fetching with ABR. The first few segments are cache misses on the CDN edge — they're fetched from the mid-tier or origin and cached. After the initial buffering period, the client has enough buffer to assess throughput. If the connection is good — say, 15 Mbps — the ABR algorithm switches up to 1080p. The client starts requesting 1080p segments instead. These are also initially cache misses, but they get cached on the way back. Subsequent viewers in the same region get cache hits."))

    lines.append(("candidate", "Step 8: the view is counted. When playback starts, the client sends a playback-started event to the View Counter Service. The service checks the Bloom filter for this user-video pair in Redis. If the user hasn't viewed this video recently, the view count is incremented in Redis and the user's hash is added to the Bloom filter. The displayed count on the video page is served from Redis. Periodically — every 30 seconds — a batch job aggregates the Redis counters and writes them to the metadata database, which is the source of truth for analytics. And that's the full lifecycle — from the uploader selecting a file to a viewer watching it on the other side of the world."))

    # SECTION 8: Thinking Process & Beats (~3 min) — interviewer monologue
    lines.append(("interviewer", "Let me share the thinking framework behind this interview. The mental model for a video streaming design has five layers, and I evaluate candidates on how they navigate between them. Layer 1 is the data plane — how bits move from uploader to viewer. The key insight is that video is fundamentally different from other content because of its size. A 10-minute 4K video is 3 to 5 GB, while a tweet is 280 bytes. This size difference cascades into every decision — pre-signed URLs instead of direct upload, segment-based formats instead of monolithic files, CDN as the primary serving mechanism rather than a caching afterthought. Candidates who don't internalize this size difference tend to propose web-scale architectures that don't work for video-scale problems."))

    lines.append(("interviewer", "Layer 2 is the processing plane — the DAG that transforms raw uploads into streamable content. The critical beat here is parallelism. A candidate who proposes transcoding a video as a single sequential FFmpeg job hasn't thought about the latency implication — at 500 hours per minute of upload, sequential processing creates an ever-growing backlog. The segment-level parallelism insight — split first, then transcode segments in parallel — is a key differentiator between junior and senior candidates. The manifest assembly coordination after parallel transcoding is the follow-up trap — many candidates forget that someone has to collect the outputs and produce the final playlist."))

    lines.append(("interviewer", "Layer 3 is the serving plane — CDN architecture and ABR. The common trap here is treating CDN as a black box that magically makes things fast. Strong candidates reason about cache hierarchy, hit rates, eviction policies, and the cold-start problem for new content. The prefetching insight — proactively pushing new content from popular creators to edge caches — shows that the candidate understands that CDN performance is about what's in the cache, not just about proximity. On the ABR side, the trap is thinking throughput estimation is sufficient. Buffer-based ABR is the industry standard because throughput varies wildly, and rebuffering is worse than quality drops."))

    lines.append(("interviewer", "Layer 4 is the metadata and discovery plane — search, recommendation, and the view counter. The view counter is a classic interview topic because it's deceptively simple. The trap is proposing a simple increment on a database row — that fails at 57K writes per second. The correct approach involves write buffering, eventual consistency, and deduplication, and the Bloom filter for dedup is a nice touch that shows systems thinking. For recommendations, collaborative filtering is the expected baseline answer — candidates who go deeper into matrix factorization or real-time model serving show extra depth, but it's not required."))

    lines.append(("interviewer", "Layer 5 is the cost plane — and this is where I assess seniority. Video streaming is a low-margin business where bandwidth is 50 to 70 percent of total cost. Candidates who don't quantify bandwidth, don't discuss storage tiering from hot to cold, and don't mention spot instances for transcoding are missing the economic dimension. The best candidates think about cost optimization as a first-class design constraint, not an afterthought. Storage tiering alone — moving videos with no views in the last 30 days from S3 Standard to Glacier — can save 50 to 70 percent on storage costs, which at 24 exabytes is a massive amount of money."))

    lines.append(("interviewer", "The key traps to avoid in this problem are: first, treating video like any other blob storage problem — it's not, because of the transcoding and ABR requirements. Second, underestimating the processing pipeline — 500 hours per minute of upload is an enormous computing challenge that needs explicit attention. Third, ignoring the CDN cold-start problem — new content isn't cached, and if you don't prefetch, your CDN hit rate for new content is zero. Fourth, proposing synchronous or single-threaded transcoding without considering parallelism. And fifth, forgetting about content moderation — at 500 hours per minute, you can't have humans review everything, so automated classification must be part of the processing DAG from the start."))

    return lines