"""Mock Interview: Web Crawler — Two-voice dialogue."""


def build():
    lines = []

    # SECTION 1: Requirements (~5 min)
    lines.append(("interviewer", "Hi, thanks for coming in. Today I'd like you to design a web crawler — a system that systematically browses the internet, downloads pages, and makes them available for indexing or analysis. Before you jump in, tell me what questions you'd ask to clarify the scope."))

    lines.append(("candidate", "Sure. Web crawler can mean a lot of things — from a simple script that scrapes one site to Google's infrastructure that indexes the entire web. So the first thing I need to understand is scale. Are we crawling the entire web, or are we focused on a specific domain or a set of domains? That completely changes the design."))

    lines.append(("interviewer", "Let's say we're building a general-purpose crawler that handles billions of pages across the entire web. Something in the ballpark of a large search engine's crawler."))

    lines.append(("candidate", "OK, that's the hard version. Good. Next question: what's the primary use case? Is this for search indexing, archival, data mining, or something else? Because the freshness requirements are very different — a search engine needs to re-crawl frequently to catch updates, while an archive might crawl less often but needs to store every version."))

    lines.append(("interviewer", "Search indexing. We need to keep our index fresh, but we also need broad coverage — we can't miss major pages."))

    lines.append(("candidate", "Got it. So freshness and coverage are both important. Let me ask about politeness constraints. Different websites have different crawling preferences — robots.txt, crawl delays, and some sites are more sensitive to aggressive crawling than others. Are we required to respect robots.txt? And do we have any contractual relationships with websites that give us special crawling privileges?"))

    lines.append(("interviewer", "We must respect robots.txt — that's non-negotiable. No special relationships. We're a polite crawler. And we need to handle the fact that some sites serve different content to crawlers than to real users — we should try to get the same content a user would see, but we won't run JavaScript for now."))

    lines.append(("candidate", "No JavaScript rendering simplifies things significantly — we're doing pure HTTP GETs and parsing static HTML. Let me also ask about content handling. Do we need to handle non-HTML content — PDFs, images, videos? And do we need to extract links only from HTML, or also from sitemaps and RSS feeds?"))

    lines.append(("interviewer", "We extract links from HTML, sitemaps, and RSS. For non-HTML content, we store the metadata — content type, content length, last-modified — but we only parse HTML for links. We don't index the actual content here, that's a separate indexing pipeline. Our job is to fetch and store the raw content plus metadata."))

    lines.append(("candidate", "One more question about deduplication. The web is full of duplicate content — mirrored sites, URL aliases, boilerplate templates. Do we need to detect near-duplicates, or just exact duplicates? And at the URL level or the content level?"))

    lines.append(("interviewer", "We need URL-level deduplication for sure — never crawl the same URL twice. Content-level deduplication is nice to have but not a hard requirement for the initial design. You can mention it as an extension."))

    lines.append(("candidate", "Let me summarize the requirements. We're building a large-scale web crawler for search indexing that handles billions of pages, respects robots.txt and politeness policies, extracts links from HTML, sitemaps, and RSS, stores raw content and metadata, deduplicates at the URL level, and needs to balance freshness with broad coverage. No JavaScript rendering. Let's move to estimation."))

    # SECTION 2: Estimation (~5 min)
    lines.append(("interviewer", "Give me the back-of-envelope numbers."))

    lines.append(("candidate", "Let's start with the total number of pages. The indexed web is roughly 50 to 100 billion pages, depending on how you count. Let's say 50 billion as our target. Not all of these need frequent re-crawling — important sites might be re-crawled daily, while obscure pages might be visited once a month or less. Let's assume an average re-crawl interval of 10 days, which means we need to crawl about 5 billion pages per day. That's roughly 60,000 pages per second."))

    lines.append(("candidate", "Wait, let me double-check that. 50 billion pages, re-crawled every 10 days on average. 50 billion divided by 10 is 5 billion per day. 5 billion divided by 86,400 seconds is about 58,000 pages per second. Let's call it 60K QPS as our sustained rate. Peak might be 2x, so 120K QPS. But we also need headroom for discovering new URLs, so let's say our design target is 100K pages per second."))

    lines.append(("interviewer", "What about the per-page size and the resulting storage and bandwidth?"))

    lines.append(("candidate", "Average HTML page size is about 200 KB, but that includes images and scripts which we're not downloading. For pure HTML, it's more like 30 to 50 KB. Let's say 50 KB per page including HTTP headers. At 100K pages per second, that's 5 GB per second of raw download bandwidth — about 40 Gbps. For storage, we're keeping the raw HTML plus metadata. If we compress at a 5:1 ratio, which is typical for HTML, each page is about 10 KB compressed. At 5 billion pages per day, that's 50 TB per day. Over a year, that's about 18 PB. We'd want to keep recent content in hot storage — say, the last 30 days — which is about 1.5 PB. Older content goes to cold storage. The metadata index — URL, content hash, crawl timestamp, HTTP status — is much smaller, maybe 200 bytes per page. At 50 billion pages, that's about 10 TB, which fits in a distributed key-value store."))

    lines.append(("interviewer", "What about the URL frontier — how many URLs do we need to track?"))

    lines.append(("candidate", "Good question. The URL frontier holds both URLs we've discovered but not yet crawled, and metadata about URLs we've already crawled for deduplication. The number of discovered URLs is much larger than the number of crawlable pages — many URLs point to the same content, some are dead, some are infinite URL spaces. A realistic estimate is 200 to 300 billion unique URLs discovered. Each URL entry in the frontier might be 200 bytes — the URL itself, priority score, last-crawled timestamp, and some metadata. That's about 50 TB for the full frontier. This is too large for memory, so we'd keep the hot portion — recently discovered and high-priority URLs — in memory and the rest on disk or in a distributed store."))

    lines.append(("candidate", "Actually, let me reconsider the bandwidth estimate. We also need to account for DNS resolution. At 100K QPS, if we need to resolve a new hostname every 100 requests, that's 1,000 DNS queries per second. With DNS caching, the actual number is lower, but DNS can become a bottleneck if every crawler node is hitting DNS servers independently."))

    # SECTION 3: High-Level Architecture (~5 min)
    lines.append(("interviewer", "Walk me through the high-level architecture."))

    lines.append(("candidate", "At a high level, the crawler has five main components. First, the URL Frontier — this is the heart of the crawler. It manages the queue of URLs to be crawled, prioritizes them, enforces politeness policies, and ensures we don't crawl the same URL twice. Second, the Fetcher — this takes URLs from the frontier and performs the actual HTTP GET requests. Third, the Parser — this extracts links from the downloaded HTML, processes sitemaps and RSS feeds, and normalizes URLs. Fourth, the Storage layer — this stores the raw HTML content and metadata. Fifth, the Scheduler — this coordinates re-crawl frequency based on page change rates and importance."))

    lines.append(("candidate", "The flow is straightforward. Seed URLs go into the frontier. The frontier serves URLs to the fetcher. The fetcher downloads the content and passes it to the parser and storage. The parser extracts new URLs and feeds them back into the frontier. The scheduler periodically promotes URLs for re-crawling based on their freshness policy. It's a continuous loop — crawl, parse, discover, repeat."))

    lines.append(("interviewer", "Why do you call it a URL frontier instead of just a queue?"))

    lines.append(("candidate", "The term comes from the original Google paper. It's called a frontier because it represents the boundary between the crawled and uncrawled web. It's not just a simple FIFO queue because URLs have different priorities — a page with high PageRank should be crawled before a random blog post. And we can't just pull URLs in arbitrary order because we need to respect per-domain politeness — we can't hit the same server twice in rapid succession. So the frontier is really a collection of per-domain FIFO queues with a priority selector on top. Each domain has its own queue with its own crawl delay timer. The frontier selects which domain's queue to pull from next based on priority and politeness readiness."))

    lines.append(("interviewer", "How do you distribute this across multiple machines?"))

    lines.append(("candidate", "The key challenge in distributed crawling is partitioning the URL frontier. If we partition randomly, we might have two machines crawling the same domain simultaneously, which violates politeness. The standard approach is to partition by domain — or more precisely, by the registered domain. We hash the domain name and assign it to a specific crawler node. That node owns all URLs for that domain, so it can enforce per-domain rate limiting correctly. If a node goes down, its domains are reassigned to other nodes. This also helps with DNS caching — since all requests to a given domain come from the same node, the DNS cache is naturally warm."))

    lines.append(("candidate", "Hmm, but this can lead to load imbalance. Some domains have millions of pages — think wikipedia.org or blogspot.com — while most have a handful. A naive hash partitioning might assign a mega-domain to one node and overload it. We can mitigate this by using consistent hashing with virtual nodes, or by splitting very large domains into sub-domain shards. For example, blogspot.com could be split by sub-domain — each blogspot subdomain is treated as a separate domain for partitioning purposes. This is reasonable because each subdomain is effectively a separate site with its own crawl rate."))

    lines.append(("interviewer", "What about the fetcher component? Any special considerations there?"))

    lines.append(("candidate", "The fetcher needs to handle a lot of concurrent connections — at 100K QPS across, say, 100 crawler nodes, each node is fetching about 1,000 pages per second. With an average fetch time of 200 milliseconds, that means each node needs about 200 concurrent connections. This is manageable with async I/O — something like epoll or kqueue. Each fetcher node would run a connection pool with a few hundred concurrent HTTP connections. We also need to handle connection timeouts, read timeouts, and malformed HTTP responses. And we need to follow redirects — up to a reasonable limit, maybe 10 hops, to avoid redirect loops."))

    # SECTION 4: Deep Dive — URL Dedup, Politeness, and Ranking (~10 min)
    lines.append(("interviewer", "Let's go deeper into the hard parts. How do you handle URL deduplication at web scale?"))

    lines.append(("candidate", "URL deduplication is one of the most critical and tricky parts of the crawler. The naive approach is to store every URL we've ever seen in a set and check new URLs against it. But with 200 to 300 billion unique URLs, a simple set in memory is impossible. Even on disk, the lookup time would be prohibitive at 100K QPS. The standard solution is a Bloom filter. A Bloom filter is a probabilistic data structure that can tell you if a URL is definitely not in the set or probably in the set. It has false positives but no false negatives. If the Bloom filter says a URL is new, it might actually be a duplicate — but if it says it's a duplicate, it's definitely a duplicate."))

    lines.append(("candidate", "The false positive rate depends on the size of the filter and the number of hash functions. For 300 billion URLs with a 1% false positive rate, we'd need about 360 GB of memory. That's feasible across a cluster of machines, but not cheap. If we can tolerate a higher false positive rate — say 5% — the memory drops to about 150 GB. The tradeoff is that we'd skip about 5% of new URLs because we'd incorrectly think they're duplicates. For a search engine, missing 5% of URLs might be acceptable — we'd still get most of the web. But if we need to be more precise, we can use a two-level approach: a Bloom filter as the first check, and if it says duplicate, we confirm with a disk-based lookup. This way, only the false positives hit disk, which is a small fraction of the total lookups."))

    lines.append(("interviewer", "What about URL normalization? Two URLs that look different can point to the same page."))

    lines.append(("candidate", "Right, that's crucial. Before we check the Bloom filter, we need to normalize URLs. Normalization includes: converting the scheme and host to lowercase, removing the default port — 80 for HTTP, 443 for HTTPS — removing trailing slashes, collapsing dot segments — /a/../b becomes /b — removing duplicate slashes, sorting query parameters alphabetically, and removing session IDs and other tracking parameters. Some of these are straightforward, but tracking parameters are tricky — different sites use different parameter names for sessions. We'd need a configurable list of parameter names to strip, and we'd need to update it over time. There are also edge cases like fragment identifiers — the part after the hash — which typically don't affect server-side content, so we'd strip those too. But for single-page applications, the fragment might determine the content. Since we're not running JavaScript, we strip fragments."))

    lines.append(("interviewer", "Let's talk about politeness in more detail. How do you ensure we don't overwhelm any single server?"))

    lines.append(("candidate", "Politeness has multiple layers. The first and most important is per-domain rate limiting. We maintain a minimum crawl delay between consecutive requests to the same domain — typically 1 to 5 seconds. We also respect the Crawl-delay directive in robots.txt if the site specifies one. Some sites don't specify a crawl delay, so we use a default. The per-domain queue in the URL frontier naturally enforces this — each domain's queue has a timer, and we only pull from it when the timer expires."))

    lines.append(("candidate", "Wait, actually, let me reconsider. Per-domain rate limiting isn't quite enough. A single domain might be served by a single server with limited capacity, and even one request per second might be too aggressive for a small personal blog. We should also consider the server's response time as a signal. If a server starts responding slowly, we should back off. We can implement adaptive politeness — if the average response time for a domain increases, we increase the crawl delay proportionally. And if we start getting 429 Too Many Requests responses, we should back off immediately and increase the delay for that domain."))

    lines.append(("interviewer", "What about robots.txt specifically? How do you handle it?"))

    lines.append(("candidate", "We fetch and cache robots.txt for each domain before we start crawling it. We parse the robots.txt file to extract the disallowed paths for our user-agent. We store the parsed rules in a cache with a TTL — typically 24 hours — so we don't need to re-fetch it for every URL. When we add a URL to the frontier, we check it against the cached robots.txt rules for its domain. If it's disallowed, we discard it. This pre-filtering avoids wasting fetcher resources on disallowed URLs."))

    lines.append(("candidate", "Hmm, but what about this edge case: what if a domain's robots.txt changes while we're crawling it? Maybe the site owner adds new disallow rules. Our cached version would be stale. We need to periodically re-fetch robots.txt — the 24-hour TTL handles this. But there's a subtler issue: what if the site owner is blocking us because we're crawling too aggressively, and they add a crawl-delay or disallow rule specifically for our user-agent? We should detect when we start getting 403 Forbidden responses and immediately re-fetch robots.txt rather than waiting for the TTL to expire."))

    lines.append(("interviewer", "Good point. Now tell me about URL prioritization in the frontier. How do you decide which URLs to crawl first?"))

    lines.append(("candidate", "URL prioritization is important because we can't crawl everything instantly — we have limited bandwidth and we need to be polite. So we need to crawl the most important pages first. Priority is determined by several factors. First, the PageRank or importance of the linking page — if a high-authority page links to a URL, that URL is probably important. Second, the number of inbound links — a URL linked from many pages is likely important. Third, the freshness of the page — if we've never crawled a URL, it gets higher priority than a URL we've crawled recently. Fourth, historical change frequency — if a page changes often, it should be re-crawled sooner."))

    lines.append(("candidate", "Actually, that's not quite right. Prioritizing high-change-frequency pages for re-crawling makes sense for freshness, but it doesn't mean they should always be higher priority than new URLs. There's a tension between exploration — discovering new content — and exploitation — keeping existing content fresh. We might use a weighted scoring function that balances both: priority equals some combination of page importance, change probability, and time since last crawl. The exact weights would be tuned based on search quality metrics."))

    lines.append(("interviewer", "How would you implement this priority queue efficiently?"))

    lines.append(("candidate", "A simple approach is to use multiple FIFO queues at different priority levels — say, 10 levels. High-priority URLs go into the top queues, low-priority into the bottom. We pull from higher-priority queues more frequently — for example, for every 10 URLs, we take 5 from the highest non-empty queue, 3 from the next, and 2 from the next. This gives preference to important URLs while still making progress on lower-priority ones. It's not perfectly fair, but it works well in practice. For per-domain politeness, each priority level contains per-domain sub-queues. The frontier selector picks the domain whose crawl delay timer has expired and whose priority is highest."))

    lines.append(("candidate", "For persistence and recovery, the URL frontier needs to be durable. If a crawler node crashes, we don't want to lose the URLs in its frontier. We'd write frontier state to a persistent log — similar to a write-ahead log in a database. Every URL addition and removal is logged, so we can rebuild the frontier after a crash. We'd also checkpoint the full frontier state to disk periodically — say, every hour — to limit recovery time."))

    # SECTION 5: Failure Modes (~4 min)
    lines.append(("interviewer", "What are the main failure modes and edge cases you'd worry about?"))

    lines.append(("candidate", "Crawler traps are probably the most insidious. These are URL patterns that generate an infinite number of unique URLs, all pointing to the same or similar content. The classic example is a calendar script — you visit /calendar/2024/01, and it has a link to /calendar/2024/02, which links to /calendar/2024/03, and so on infinitely. Each URL is unique, each returns valid HTML with links to the next month, so the crawler just keeps going forever. Another example is session IDs in URLs — every visit generates a new session ID, creating a new unique URL for the same page."))

    lines.append(("candidate", "Detecting crawler traps is hard because there's no single pattern. We can use several heuristics. First, URL depth limit — if a URL path has more than, say, 10 segments, we flag it as suspicious. Second, duplicate content detection — if we've crawled N URLs from the same domain and they all have nearly identical content, something's wrong. Third, URL pattern analysis — if we see URLs following a numeric sequence like /page/1, /page/2, /page/3, and the count exceeds a threshold, we cap it. Fourth, page count per domain — if a single domain has more than, say, a million URLs in the frontier, we investigate. None of these heuristics are perfect, but together they catch most traps."))

    lines.append(("interviewer", "What about DNS failures?"))

    lines.append(("candidate", "DNS failures are more common than you'd think, especially for smaller domains. A DNS lookup failure means we can't fetch the page, but it doesn't necessarily mean the page is gone — the DNS server might just be temporarily down. We need to distinguish between NXDOMAIN — the domain truly doesn't exist — and a timeout or server failure. NXDOMAIN means we can remove all URLs for that domain from the frontier. A timeout means we should retry later with exponential backoff. We'd cache DNS results with a TTL — positive results cached for the TTL from the DNS record, negative results cached for a shorter period, maybe 5 minutes. This is where partitioning by domain helps — since all requests to a domain come from the same node, we get natural DNS caching without a separate distributed cache."))

    lines.append(("candidate", "Actually, let me think about this more carefully. At 100K QPS across 100 nodes, each node is resolving maybe 1,000 new hostnames per second. We'd want a local DNS cache on each node — something like dnsmasq or unbound — with a generous cache size. For DNS server failures, we could use a fallback to a secondary resolver like Google's 8.8.8.8 or Cloudflare's 1.1.1.1. We'd also use DNSSEC validation where available, though it adds latency."))

    lines.append(("interviewer", "What about robots.txt edge cases? You mentioned some earlier."))

    lines.append(("candidate", "There are several tricky edge cases. First, what if robots.txt returns a 4xx status — like 401 or 403? The RFC says that if robots.txt is inaccessible, we should treat the entire site as disallowed, because the site owner might have intentionally blocked it. But in practice, many sites have misconfigured servers that return 401 for robots.txt while serving content normally. This is a policy decision — do we follow the strict RFC interpretation or the pragmatic approach? Most large crawlers take a pragmatic approach: if robots.txt returns 401 or 403, we proceed with caution but don't skip the entire site. But if robots.txt returns 5xx, we treat it as a temporary failure and retry later."))

    lines.append(("candidate", "Second edge case: what if robots.txt is huge — like, megabytes in size? Some sites accidentally expose their entire URL structure in robots.txt with thousands of Disallow rules. Parsing and storing all of these is wasteful. We'd set a size limit — say, 500 KB — and truncate anything larger. Third edge case: conflicting rules. What if there are multiple user-agent sections that match our crawler? We should use the most specific match — if there's a section for our specific user-agent, we use that; otherwise, we fall back to the wildcard section. And if there are conflicting Allow and Disallow rules for the same path, the more specific path wins — /disallow/this/path overrides /disallow/."))

    lines.append(("interviewer", "One more failure mode — what happens when we download a page and it's garbage? Malformed HTML, binary content pretending to be HTML, or just spam?"))

    lines.append(("candidate", "Content validation is important. After fetching, we check the Content-Type header — if it's not HTML, we store the metadata but don't parse it for links. If the Content-Type claims HTML but the content is actually binary or gibberish, we detect this by looking at the byte distribution — valid HTML should be mostly ASCII printable characters with a reasonable distribution. If more than, say, 30% of bytes are non-printable, it's probably not real HTML. We'd also check for obvious spam signals — pages with thousands of links, pages with very little text content relative to HTML markup, pages with suspicious redirect chains. These don't go into the main index, and we might penalize the linking pages' priority scores."))

    # SECTION 6: Scale & Debrief (~3 min)
    lines.append(("interviewer", "How does this design change at 10x scale — a trillion pages?"))

    lines.append(("candidate", "At a trillion pages, the URL deduplication Bloom filter becomes the biggest challenge. For a trillion URLs at 1% false positive rate, we'd need over a terabyte of memory — still feasible across a cluster but expensive. We might use a partitioned Bloom filter or a counting Bloom filter that lets us remove entries for dead URLs. The frontier storage would grow to maybe 500 TB, needing distributed storage like HDFS or a custom key-value store."))

    lines.append(("candidate", "The fetcher fleet scales from 100 nodes to maybe 500 to 1,000. Network bandwidth goes from 40 Gbps to 400 Gbps, requiring multiple 100 Gbps links. Content storage goes from 18 PB per year to 180 PB, so we'd need more aggressive compression and expiration policies. DNS resolution at this scale needs a dedicated caching layer. At a trillion pages, we'd also want to optimize for fewer, more valuable fetches rather than trying to crawl everything."))

    lines.append(("candidate", "At 0.1x scale — 5 billion pages — a single rack of machines handles the crawl. The Bloom filter fits in 15 to 20 GB of memory on one machine. The URL frontier uses a simple disk-based queue with an in-memory cache. No distributed coordination needed. A single PostgreSQL instance handles the metadata. The crawler is a single process with async I/O — more like a Scrapy or Nutch setup, good for focused crawls but not the full web."))

    lines.append(("interviewer", "Let me give you feedback. Positives: you asked great clarifying questions up front — scale, use case, politeness, JavaScript rendering, deduplication granularity. Your high-level architecture was clear and well-organized. The URL frontier explanation was solid — you clearly understood why it's not just a queue. The deep dive on URL normalization, Bloom filter sizing, and the politeness discussion with adaptive rate limiting were all strong. The crawler trap heuristics were practical and well-reasoned. For improvement: you could have discussed content deduplication more, even though I said it was nice to have — simhash or shingling for near-duplicate detection is a common interview topic and worth mentioning. You also didn't say much about freshness policies — how exactly do you decide when to re-crawl a page? You mentioned it briefly but didn't go deep. And the HTTP ETag and If-Modified-Since mechanisms for conditional requests would have been worth bringing up — they save bandwidth on re-crawls. Overall, very solid performance."))

    lines.append(("candidate", "Thanks for the feedback. You're right — I should have covered freshness policies more explicitly. The basic idea is to estimate a page's change rate from historical crawl data and schedule re-crawls accordingly. If a page hasn't changed in the last 5 crawls, we double the re-crawl interval. If it changed on the last 3 crawls, we crawl it more frequently. And conditional requests with ETag and If-Modified-Since are a simple optimization that I should have mentioned — if the server supports them, we avoid re-downloading unchanged content, which saves bandwidth and is also more polite since we're lighter on the server. I'll make sure to cover those next time."))

    # SECTION 7: End-to-End Walkthrough (~4 min)
    lines.append(("interviewer", "Walk me through what happens step by step when the crawler encounters a specific URL. Let's say we discover a link to https://tech.example.com/articles/2024/ai-progress on a page we just crawled. Start from the moment the parser extracts this URL and go all the way to stored content."))

    lines.append(("candidate", "Sure. Let's trace it. Step 1: the parser extracts the URL from an anchor tag on the page we just crawled. Before doing anything else, we normalize the URL. We convert the scheme to lowercase — it's already https, good. We convert the host to lowercase — tech.example.com stays the same. We check for a default port — there's no explicit port, so nothing to strip. We check for a trailing slash — nope. We check for a fragment — no fragment. We remove any tracking parameters — none present. The normalized URL is the same as the original in this case: https://tech.example.com/articles/2024/ai-progress."))

    lines.append(("candidate", "Step 2: we check the URL against the robots.txt cache for tech.example.com. If we've crawled this domain before, we have a cached robots.txt. We check if /articles/2024/ai-progress is disallowed for our user-agent. Let's say it's not disallowed — articles are typically allowed. If we don't have a cached robots.txt for this domain, we add a special priority task to the frontier to fetch robots.txt before any other URLs from this domain."))

    lines.append(("candidate", "Step 3: we check URL deduplication. We compute the Bloom filter hashes for the normalized URL and check the Bloom filter. If any of the bits are not set, the URL is definitely new — we proceed. If all bits are set, the URL might be a duplicate, so we do a disk-based lookup to confirm. Let's say it's new — the Bloom filter says it's not in the set. We add the URL to the Bloom filter immediately so that if another page links to it before we crawl it, we don't add it to the frontier twice."))

    lines.append(("candidate", "Step 4: we add the URL to the frontier. We compute the domain — tech.example.com — and hash it to determine which crawler node owns this domain. Let's say it hashes to node 17. We send the URL to node 17's frontier manager over the internal network. The frontier manager on node 17 determines the URL's priority. Since it's linked from a page with decent PageRank, and it's a new URL that we've never crawled, it gets a relatively high priority — maybe priority level 3 out of 10. The URL is placed into tech.example.com's per-domain sub-queue within priority level 3."))

    lines.append(("candidate", "Step 5: the frontier selector on node 17 is constantly checking which domains are ready — meaning their crawl delay timer has expired. When tech.example.com's timer expires, the selector picks this domain if it's the highest-priority ready domain. It dequeues the URL from the per-domain queue and passes it to the fetcher. The fetcher first resolves the IP address for tech.example.com using the local DNS cache. If it's not cached, it performs a DNS lookup. Let's say the IP is 203.0.113.50. The fetcher then opens an HTTP connection to 203.0.113.50:443 with TLS, sends a GET request for /articles/2024/ai-progress, and waits for the response."))

    lines.append(("candidate", "Step 6: the server responds with a 200 OK, Content-Type: text/html, and the HTML body. The fetcher measures the response time — let's say 180 milliseconds — and updates the adaptive politeness tracker for tech.example.com. It resets the domain's crawl delay timer to, say, 2 seconds — our minimum crawl delay for this domain. If the server responded slowly, we'd increase the delay."))

    lines.append(("candidate", "Step 7: the fetcher passes the response to two places in parallel. It sends the raw HTML and metadata to storage, and it sends the HTML to the parser. The storage layer compresses the HTML — maybe from 45 KB down to 9 KB using gzip or zstd — and writes it to the content store, keyed by a content hash. The metadata — URL, content hash, HTTP status code, Content-Type, Content-Length, Last-Modified header, ETag header, crawl timestamp, response time — is written to the metadata index. This metadata is what the scheduler will use later to decide when to re-crawl this page."))

    lines.append(("candidate", "Step 8: the parser processes the HTML. It extracts all anchor tags, normalizes the linked URLs, and for each one, goes through the same process — robots.txt check, Bloom filter check, and frontier insertion. It also extracts any sitemap links from the HTML head or robots.txt. Let's say this article has 15 outbound links, 3 of which are to new domains. Those 3 new domains trigger robots.txt fetches. The other 12 links go through dedup and are added to the frontier if they're new. And finally, the parser marks this URL as successfully crawled in the frontier — it moves from the pending set to the crawled set."))

    lines.append(("interviewer", "What if the server returned a 301 redirect instead of a 200?"))

    lines.append(("candidate", "Good question. If we get a 301, we note the redirect — we store the mapping from the original URL to the target URL in the redirect table. Then we normalize the target URL and go through the same process: robots.txt check, dedup check, and frontier insertion. The original URL stays in the crawled set so we don't re-fetch it. For future link discovery, when we encounter the original URL again, we can immediately resolve it to the target without fetching. We'd also update the page's canonical URL in the metadata to help the indexing pipeline with duplicate content detection. The key thing is that we don't want to waste fetches on redirecting URLs — after we've seen a redirect once, we resolve it locally."))

    # SECTION 8: Thinking Process & Beats (~3 min)
    lines.append(("interviewer", "Before we wrap up, let me share how I think about this problem as an interviewer — the mental framework, the key beats you need to hit, and the common traps I see candidates fall into."))

    lines.append(("interviewer", "The mental framework for a crawler design is really about managing three fundamental tensions. The first tension is coverage versus freshness — you want to crawl as much of the web as possible, but you also want to keep your existing index up to date. You can't do both perfectly with limited resources, so you need a principled way to allocate crawl budget between new URLs and re-crawls. The second tension is thoroughness versus politeness — the crawler that fetches the most pages is the one that gets banned by webmasters. You need to be aggressive enough to get the data you need but respectful enough to not get blocked. The third tension is efficiency versus simplicity — a crawler can be endlessly optimized with predictive re-crawl scheduling, machine-learned priorities, and incremental Bloom filter tuning, but at some point the complexity stops paying off. Knowing where to draw that line is what separates a good design from an overengineered one."))

    lines.append(("interviewer", "The key beats you must hit in a crawler interview, in order. First, clarify requirements — scale, use case, content type, and politeness constraints. If you don't ask about robots.txt and crawl delay, I notice. Second, do the math — pages per second, bandwidth, storage. This grounds the rest of the design. Third, draw the high-level architecture with the URL frontier at the center. If you don't use the term URL frontier or don't explain per-domain queuing, that's a red flag. Fourth, go deep on deduplication — Bloom filters, URL normalization, and the tradeoffs around false positive rates. This is where most interviews are won or lost. Fifth, explain politeness — per-domain rate limiting, adaptive backoff, and robots.txt handling including edge cases. Sixth, discuss crawler traps and how to detect them. If you don't mention traps, it suggests you haven't thought about what can go wrong at scale."))

    lines.append(("interviewer", "The common traps I see — pun intended. First, treating the URL queue as a simple FIFO. It's not. It's a multi-level priority queue with per-domain sub-queues and politeness timers. If you design it as a basic queue, you'll violate politeness and your crawler will be blocked everywhere. Second, ignoring URL normalization. Two URLs that look different can point to the same page, and without normalization your deduplication is broken before it starts. Third, forgetting about DNS. At web scale, DNS resolution is a real bottleneck, and you need a caching strategy. Fourth, not handling crawler traps. They're real, they're common, and they'll burn your entire crawl budget on garbage if you don't detect them. Fifth, over-indexing on one component and running out of time. I'd rather see you cover all the key beats at a moderate depth than go incredibly deep on Bloom filter math but never mention politeness or traps."))

    lines.append(("interviewer", "Finally, the strongest candidates connect the crawler design to the broader system. They mention how the stored content feeds into an indexing pipeline, how crawl metadata like PageRank and change frequency are computed, and how search quality feedback loops back into crawl priority. You don't need to design the index, but showing that you understand the crawler's role in the larger system demonstrates systems thinking. And if you can bring up content deduplication with simhash or shingling as an extension, even though it wasn't required, that's a bonus — it shows you've thought about the next layer of the problem."))

    return lines