#!/usr/bin/env python3
"""generate_estimation.py — Back-of-envelope estimation practice episodes.

Voice: en-US-EmmaNeural (cheerful, clear, good for numbers)
Duration: ~30 min per episode (~4750 words at 159 WPM)
5-6 estimation problems per episode
Each: setup context → assumption reasoning → step-by-step with false starts → sanity checks → design implications → interview tips
Style: flowing prose, no bullet points or structural markers
"""

import json, os, sys, subprocess, shutil, tempfile
from datetime import datetime, timezone

from tts import synthesize, get_duration_str

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = os.path.join(os.path.dirname(SCRIPT_DIR), "data")

ESTIMATION_EPISODES = [
    {
        "id": 44, "theme": "estimation-1",
        "title": "Estimation Practice I",
        "subtitle": "Twitter QPS, Google storage, WhatsApp bandwidth, YouTube storage, Amazon orders QPS, Spotify bandwidth",
        "playlist_id": "sd-estimation",
        "problems": [
            {
                "name": "Twitter QPS and Storage",
                "prompt": "Estimate the queries per second and storage for Twitter.",
                "prose": (
                    "OK so let's think about this. I'm in an interview and the interviewer asks me to estimate Twitter's queries per second and storage. The first thing I'd do is nail down the user base, because everything flows from that. "
                    "So I'm assuming about 1.5 billion total registered users. Twitter reported crossing 1.5 billion registrations a while back, though many of those are inactive or bots. The number that really matters is daily active users. "
                    "I'm going to assume 300 million DAU. Twitter's last public number was about 250 million monetizable DAU back in their quarterly reports before the acquisition, and it's been fluctuating, but 300 million seems like a reasonable working number for a global platform of this scale. If the interviewer pushes back, I'd say somewhere between 250 and 350 million, and 300 is my midpoint. "
                    "Now, how many tweets does each user post per day? This is tricky because most users are lurkers — they read but don't post. The 90-9-1 rule of internet culture says 90 percent lurk, 9 percent contribute occasionally, and 1 percent are power users. So if the 1 percent post like 20 tweets a day, and the 9 percent post maybe 1, and the 90 percent post close to zero, the average works out to roughly 2 tweets per DAU per day. That feels right to me. Some studies have put it at 1 to 3, so 2 is a solid estimate. "
                    "What about tweet size? A text-only tweet is at most 280 characters, which is 280 bytes in UTF-8 for English text, but with URLs and mentions, let's call it 200 bytes on average. Then there are images. Not every tweet has an image — I'd say maybe 20 percent do. When someone does attach media, it's typically compressed to around 500 kilobytes by Twitter's image pipeline. So that's our media assumption. "
                    "And the read-to-write ratio — this is super important for sizing our read infrastructure. For social media platforms, reads vastly outnumber writes. People scroll their timeline for minutes but tweet maybe once or twice. Twitter is probably at least 10 to 1, maybe higher. I'll use 10 to 1. Facebook has reported ratios as high as 100 to 1 for some workloads, but Twitter's engagement pattern is a bit different, so 10 to 1 feels safe. "
                    "OK let me work through the math out loud now. First, write QPS. 300 million DAU times 2 tweets per day gives us 600 million tweets per day. There are 86,400 seconds in a day, so 600 million divided by 86,400 is approximately 7,000 tweets per second on average. But traffic isn't flat — there are peaks during big events, breaking news, that kind of thing. A common rule of thumb is to assume peak is 2 to 3 times average. I'll use 2x. So peak write QPS is about 14,000 per second. "
                    "Now for read QPS. With our 10 to 1 read-to-write ratio, average read QPS is 70,000 per second, and peak is 140,000. That's a lot of reads. "
                    "Wait, actually I want to double-check something here. The read-to-write ratio of 10 to 1 — does that account for the fact that a single tweet from someone like Elon Musk gets read by millions of people? That's actually why the ratio is so high. A normal user's tweet might get 10 reads, but a celebrity tweet gets millions. The average really does skew high. So 10 to 1 is probably conservative, but I'll stick with it since I'd rather underestimate than overestimate in an interview. "
                    "Alright, let me calculate storage now. Text storage first. 600 million tweets times 200 bytes is 120 gigabytes of text per day. That's actually quite small. Now for images. 20 percent of 600 million tweets have images, so that's 120 million images. At 500KB each, that's 60 terabytes per day. So the total daily storage is dominated by images — about 60 terabytes per day, with text being negligible in comparison. And annually, 60 terabytes times 365 is roughly 22 petabytes per year. "
                    "Hmm, let me sanity check this against a few different reference points. First, YouTube uploads about 500 hours of video per minute. Even at modest compression, that's many times more data than Twitter handles. So Twitter at 60 terabytes per day being much less than YouTube makes sense. Second, Google processes about 8.5 billion searches per day, which at average is about 100,000 QPS. Our Twitter read QPS estimate of 70,000 is in the same order of magnitude, which feels right — Twitter and Google Search are both top-10 websites with massive read traffic. Third, Instagram has about 500 million DAU and they handle roughly 100 million photo uploads per day. Twitter with 300 million DAU and 120 million images per day — that's a similar ratio, maybe a touch high, but remember 20 percent was our guess and it could be lower. So I'd say the numbers are in the right ballpark. "
                    "So what does all this mean for system design? At 70,000 read QPS, a single database instance absolutely cannot handle the load. Even a read replica cluster would struggle. We need a caching layer — probably Redis or Memcached in front of the database, and probably a CDN for images. At 60 terabytes per day of image storage, relational databases are the wrong tool entirely. We'd use object storage like S3 for the images, with metadata in a database. And at 14,000 peak write QPS, we'd need to shard the tweet database, most likely by user ID so that all of one user's tweets live on the same shard, making timeline generation easier. We'd probably also use a fan-out on write approach for the home timeline — when you tweet, we push it to the Redis timelines of all your followers. "
                    "Here's a tip for interviews: when you sanity check, always compare to a system you already know. If you don't know the exact number, give a range and explain why. The interviewer cares about your reasoning process, not whether you got exactly 7,000 QPS. Also, always mention peak versus average — that's something interviewers specifically look for. A system designed only for average load will fall over during the first traffic spike."
                ),
            },
            {
                "name": "Google Storage for Web Index",
                "prompt": "How much storage does Google need to index the web?",
                "prose": (
                    "Alright, moving on to our next problem. So the interviewer now asks: how much storage does Google need to index the web? This one's interesting because it's all about scale and compression. "
                    "Let me think about the number of web pages first. There's no official number from Google, but common estimates put the indexed web at around 50 billion pages. Some sources say it could be as high as 100 billion, but a lot of pages are duplicates, spam, or very low quality, so 50 billion unique indexable pages is a reasonable working assumption. The web is estimated to have over a trillion unique URLs, but Google doesn't index all of them — it skips duplicates, thin content, and pages behind paywalls. So 50 billion is my number. "
                    "Now, how big is the average web page? The HTTP Archive tracks this — the average web page, including HTML, CSS, JavaScript, and images, is about 2 megabytes for transfer. But we're not storing the full rendered page — Google stores a compressed snapshot. The HTML itself is typically around 50 to 100 kilobytes after minification, and Google's compression is really aggressive. I'll assume about 100 kilobytes per page for the cached content. "
                    "On top of the cached content, there's the index metadata — the inverted index entries, page rank scores, anchors, and so on. This is hard to estimate precisely, but it's probably in the same ballpark as the content. Let's say 50 kilobytes of metadata per page. "
                    "And of course, Google doesn't store just one copy. For redundancy and geographic distribution, they'd have at least 3 copies, probably more. I'll use 3 for this estimate. "
                    "OK so let me calculate. 50 billion pages times 100 kilobytes per page for content — that's 5 petabytes of compressed content. Then the index metadata: 50 billion times 50 kilobytes is 2.5 petabytes. So total per copy is 7.5 petabytes. With 3 copies, that's 22.5 petabytes. "
                    "Wait, actually, I should think about this differently. Google doesn't just store the current snapshot — they also store historical versions of pages for cache and for their time-travel features. But that's a separate concern. For the basic index, 22.5 petabytes is my answer. "
                    "Let me sanity check this. Amazon S3 is estimated to store over 100 trillion objects. If the average object is 100 kilobytes, that's 10 exabytes — orders of magnitude larger than our Google index estimate. That makes sense because S3 stores all kinds of data, not just web pages. The Wayback Machine, which archives historical snapshots, is estimated at about 45 petabytes for hundreds of billions of captures. Google's index at 7.5 petabytes per copy for just current snapshots seems very reasonable compared to that. And Google's total storage infrastructure is commonly estimated in the exabyte range — but that includes YouTube, Gmail, Drive, Photos, and everything else. The web index is just one component. "
                    "For the design implications — this much data means we absolutely need distributed storage across thousands of machines. No single machine, no single rack, can hold even a fraction of the full index. We'd shard the index across a distributed file system like GFS or Colossus, Google's internal successors to the original Google File System. The index itself would be segmented by URL hash or by topic domains, with each segment assigned to a cluster of index servers. Search queries get routed to the relevant segments, and results are merged at a root server. This is exactly how Google's architecture works — the original MapReduce and BigTable papers describe this pattern. "
                    "One more thing — the index isn't static. Google re-crawls the web continuously. The freshness requirement means we need a pipeline that can update the index incrementally without rebuilding it from scratch. That's why they have the Percolator system for incremental index updates. "
                    "Interview tip: when you estimate storage for a search engine, always mention both the content storage and the index overhead separately. The index is often as large as or larger than the content itself, and forgetting it is a common mistake. Also, mention redundancy — any production system has multiple copies, and that multiplies your storage requirement."
                ),
            },
            {
                "name": "WhatsApp Bandwidth",
                "prompt": "Estimate the daily bandwidth for WhatsApp.",
                "prose": (
                    "So here's the thing — now the interviewer pivots to bandwidth. They want to know how much bandwidth WhatsApp uses per day. This is a great question because bandwidth is one of the biggest operational costs for messaging platforms, and the numbers get huge fast. "
                    "Let me start with the user base. WhatsApp has about 2 billion monthly active users. That's publicly reported. For daily active users, I'd estimate about half of monthly — so 1 billion DAU. This ratio varies by region, but for a messaging app that people use every day, 50 percent is a reasonable assumption. In some markets like India and Brazil, the ratio might be even higher because WhatsApp is essentially the internet for many people. "
                    "Now, how many messages does each person send? This varies wildly. Some people send 5 messages a day, some send 200. I've seen estimates averaging around 50 messages per DAU per day, including both sent and received messages in groups. But for bandwidth, I only care about sent messages, because each sent message generates outbound bandwidth to recipients. So 50 messages per user per day. "
                    "Text messages are tiny — about 100 bytes on average, including overhead. That's negligible. The real bandwidth comes from media. I'd estimate about 50 percent of messages include media — photos, videos, voice messages, documents. That might sound high, but in many markets, WhatsApp has replaced SMS and MMS entirely, and people share photos constantly. The average media attachment after WhatsApp's compression is about 3 megabytes. Photos compress to a few hundred kilobytes, but videos average much larger, so 3 megs is a blended average. "
                    "And here's the crucial factor — group chats. Each message isn't delivered to one person, it's delivered to all members of the group. The average message is delivered to about 2 recipients. Small groups and one-on-one chats bring this average down from what you'd expect with large broadcast lists. "
                    "OK let me run the numbers. 1 billion DAU times 50 messages per day is 50 billion messages per day. The text portion is 50 billion times 100 bytes, that's 5 gigabytes. Honestly, that's rounding error — text bandwidth is nothing. "
                    "Now for media. 50 percent of 50 billion messages have media, so 25 billion media messages. At 3 megabytes each, that's 75 petabytes of media per day. But each message is delivered to 2 recipients on average, so we multiply by 2 for outbound delivery. That gives us 150 petabytes of outbound bandwidth per day. "
                    "Wait actually, I need to be more careful here. Not every recipient downloads the media immediately, and WhatsApp uses end-to-end encryption, so they can't cache decrypted versions at the edge. But for bandwidth estimation purposes, let's assume most media is viewed relatively quickly — within a day — so the download bandwidth approaches the upload bandwidth times the fan-out factor. I'll keep my 150 petabytes estimate. "
                    "To convert to throughput, 150 petabytes divided by 86,400 seconds is about 1.7 terabytes per second of outbound bandwidth. That's massive. "
                    "Let me sanity check against multiple references. Netflix streams about 1 petabyte per hour during peak, which is about 0.28 terabytes per second. WhatsApp at 1.7 terabytes per second is about 6 times Netflix's peak. Hmm, that seems high. But wait — WhatsApp has 2 billion users versus Netflix's 250 million, so roughly 8 times more users. And messaging frequency is much higher than watching a show. But Netflix streams video at much higher bitrate per session. So the ratio being 6 to 1 is probably too high. The issue is my 3 megabyte average for media might be too large, and my 50 percent media ratio might be too high. In reality, many messages are just text, and the media ratio could be closer to 20 percent. If I use 20 percent, the bandwidth drops to 60 petabytes per day, or about 0.7 terabytes per second, which is 2.5 times Netflix. That feels more reasonable. I'd present both estimates to the interviewer and explain my uncertainty about the media ratio. "
                    "For design, at even 0.7 terabytes per second outbound, we absolutely need edge distribution or a CDN. Delivering all media from a central data center would be too expensive and too slow, especially for users in regions far from our data centers. But here's the real design tension — WhatsApp uses end-to-end encryption, which means media is encrypted on the device and we can't cache the decrypted version at the edge. We can cache the encrypted blob, but each recipient has a different encryption key for the same media item. So the CDN efficiency is lower than for something like Netflix, where one copy of a video serves millions of users. This is a fundamental architectural constraint that comes directly from the privacy model. We'd likely use a combination of regional data centers and direct peer-to-peer delivery for media where possible. "
                    "Interview tip: bandwidth estimation is where your assumptions really matter. The media attachment ratio and average media size are the key levers. If you're unsure, present a range — say, 0.7 to 1.7 terabytes per second — and explain which assumptions drive the uncertainty. Interviewers love seeing you identify which variables matter most."
                ),
            },
            {
                "name": "YouTube Storage",
                "prompt": "How much storage does YouTube need for its video library, assuming 500 hours uploaded per minute, average video 100 megabytes after compression, and 5-year retention?",
                "prose": (
                    "OK, next up — and this one's a big one. The interviewer asks how much storage YouTube needs for its entire video library. They give me some parameters to work with: 500 hours of video uploaded per minute, average video is 100 megabytes after compression, and they retain videos for 5 years. So some of the assumptions are given, which is nice, but I still need to reason through the details. "
                    "Let me start with the upload rate. 500 hours per minute — that's a number YouTube has publicly confirmed, by the way. They hit 500 hours per minute a few years ago and it's probably even higher now. But let's work with 500. "
                    "So 500 hours per minute. Let me convert that to a daily figure. 500 hours per minute times 60 minutes per hour is 30,000 hours per hour of upload. And 30,000 hours per hour times 24 hours per day is 720,000 hours of video uploaded per day. That's an insane amount of content — 720,000 hours every single day. "
                    "Now, how many individual videos is that? The problem states the average video is 100 megabytes after compression. But I need to know the average video length to convert hours to number of videos. Hmm, this isn't given. Let me make an assumption. YouTube has everything from 15-second Shorts to 2-hour livestreams. The average is probably somewhere around 10 minutes. Most YouTube videos are short-form content, and Shorts have been growing explosively. So 10 minutes per video on average, which is one-sixth of an hour. "
                    "Wait actually, let me reconsider. If Shorts are 15 seconds and there are billions of them, and regular videos average 10 to 15 minutes, the true average might be even shorter — maybe 5 minutes. But let me stick with 10 minutes for now and note that this is a key uncertainty. "
                    "So 720,000 hours uploaded per day, and each video is one-sixth of an hour on average, that gives us 720,000 times 6, which is 4.32 million videos uploaded per day. Each at 100 megabytes, so daily storage is 4.32 million times 100 megabytes, which is 432 terabytes per day. "
                    "But hold on — YouTube doesn't store just one encoding of each video. They transcode into multiple resolutions. The 100 megabytes the problem mentions — is that the total across all encodings, or just one? I think the problem means 100 megabytes per video on average after compression, and that probably refers to the storage footprint including all transcoded variants. YouTube typically encodes in maybe 8 to 12 different bitrate and resolution combinations. A 10-minute video at 1080p might be 150 megabytes, at 720p maybe 80 megabytes, at 480p maybe 40 megabytes, plus the audio tracks. The total across all variants could easily be 300 to 400 megabytes per 10-minute video. But the problem says 100 megabytes average, so maybe they're accounting for the huge volume of very short Shorts that are tiny. I'll go with the given assumption of 100 megabytes per video on average. "
                    "Actually, wait. Let me try another approach to verify. If 500 hours of video are uploaded per minute, and the average video is 100 megabytes, I can work from hours to storage directly. 500 hours per minute is 500 times 60 times 24 equals 720,000 hours per day. At 100 megabytes per video and 6 videos per hour (if 10-minute average), that's 600 megabytes per hour of upload content. So 720,000 hours times 600 megabytes per hour is 432 terabytes. Same answer. Good, it's consistent. "
                    "Now for 5-year retention. 432 terabytes per day times 365 days per year is about 158 petabytes per year. And over 5 years, that's roughly 790 petabytes, or about 0.8 exabytes. "
                    "But I should account for the fact that not every video stays for 5 years. Some are deleted by users, some are removed for policy violations. Maybe 10 to 20 percent get deleted before 5 years. But that's a small correction, and I'm estimating, so I'll say roughly 0.8 exabytes for the full 5-year library, maybe 0.6 to 0.7 after deletions. "
                    "Let me sanity check. Backblaze, a cloud storage provider, has reported storing about 2 exabytes total across all their customers. YouTube alone at 0.8 exabytes seems high but not unreasonable for the world's largest video platform. Facebook has reported storing over 100 petabytes just for photo storage, and video is much larger than photos. And the Internet Archive's Wayback Machine is about 45 petabytes. YouTube is orders of magnitude larger because video files are orders of magnitude larger than web pages. So 0.8 exabytes over 5 years feels plausible, possibly even conservative if the 100 megabyte average is on the low side. "
                    "For design implications, storing nearly an exabyte of video means object storage is the only viable option — something like Google's own Colossus file system or a S3-like object store. Each video and its transcoded variants would be stored as separate objects. We'd use erasure coding rather than simple replication to reduce the storage overhead for redundancy — instead of 3x replication, erasure coding can provide the same durability at about 1.3 to 1.5x overhead. That saves hundreds of petabytes. The transcoding pipeline itself needs to be massively parallel — ingesting 500 hours per minute and producing multiple encodings requires a huge compute cluster, probably running on preemptible VMs to keep costs down. And for serving, we'd use YouTube's own CDN with edge caches in ISP data centers worldwide, similar to what Netflix does with their Open Connect appliances. "
                    "Tip here: when you estimate storage for media platforms, always ask about retention period and whether the given size per item includes all transcoded variants. These are the two biggest sources of confusion. And mention erasure coding — it's a real cost saver at exabyte scale, and showing you know about it demonstrates systems knowledge."
                ),
            },
            {
                "name": "Amazon Orders QPS",
                "prompt": "Estimate Amazon's order processing rate, given 300 million customers, average 2 orders per week, and Prime Day peak traffic.",
                "prose": (
                    "Alright, here's a fun one. The interviewer wants me to estimate Amazon's order processing rate. They mention 300 million customers and an average of 2 orders per week. They also want me to think about Prime Day peaks. This is a classic e-commerce estimation problem, and it's really relevant because order processing is the core transactional workload for Amazon. "
                    "So let's think about this. 300 million customers — that's roughly Amazon's customer base. They reported over 200 million Prime subscribers, and not all customers are Prime members, so 300 million total customers is very reasonable. Some estimates put it even higher at 400 million, but let's work with 300. "
                    "2 orders per week per customer on average. Hmm, is that right? Some customers order daily, some order once a month. Prime members probably order more — maybe 3 to 4 times per week, while non-Prime members might order once every couple of weeks. The weighted average of 2 per week seems reasonable if we consider that Prime members are a large fraction of the active customer base and they order frequently. "
                    "OK so let me calculate the average orders per second first. 300 million customers times 2 orders per week is 600 million orders per week. Divide by 7 days, that's about 85.7 million orders per day. And 85.7 million divided by 86,400 seconds per day gives us about 990 orders per second on average. Let's round to 1,000 orders per second. "
                    "But wait, I made an implicit assumption that all 300 million customers are equally active. That's definitely not true. Many accounts are dormant, some are occasional gift shoppers. The 2 orders per week might already account for this if it's an average across all customers, including inactive ones. But if 2 orders per week is the average for active customers only, and only say 50 percent of the 300 million are active in any given week, then the real number would be lower. Let me keep it as stated — 300 million customers averaging 2 orders per week — and note this ambiguity to the interviewer. "
                    "Now the interesting part — peak. The problem specifically asks about Prime Day. Amazon's Prime Day is their biggest sales event, and the peak is insane. On a normal day, there's a diurnal pattern — orders peak around 8 to 10 PM local time, and the peak-to-average ratio is maybe 2 to 3x. But on Prime Day, it's a whole different story. Amazon has reported that Prime Day generates more sales than the entire Black Friday weekend. I'd estimate the Prime Day peak is at least 5x the average daily rate, and the peak hour might be 10x average. During the flash sales that drop at specific times, the spike could be even higher, maybe 20x for brief periods. "
                    "So our average is 1,000 orders per second. Normal peak at 2 to 3x would be 2,000 to 3,000 per second. Prime Day peak at 5x average is 5,000 per second sustained, with flash sale spikes potentially hitting 10,000 to 20,000 per second for a few minutes. "
                    "Let me sanity check this. Alibaba reported over 540,000 transactions per second at peak during Singles' Day. That's the highest publicly reported e-commerce TPS. Amazon is comparable in scale to Alibaba, and Prime Day is comparable to Singles' Day, so our estimate of 10,000 to 20,000 for flash sale peaks is actually conservative compared to Alibaba's number. But Alibaba's number includes all their marketplace sellers and payment transactions, not just orders. Still, it suggests that large e-commerce platforms handle tens of thousands of TPS during peak events. Our average of 1,000 TPS and peak of 5,000 TPS seem very reasonable. "
                    "Another reference — Visa processes about 65,000 transactions per second at their global peak. Amazon orders at 5,000 per second is about 8 percent of Visa's peak, which makes sense since Amazon is one merchant (albeit the largest) in the global payments network. "
                    "For design implications, order processing at 1,000 TPS average with 5x peaks requires careful capacity planning. The order database must be ACID-compliant — you absolutely cannot lose an order or double-charge a customer. We'd use a sharded relational database, probably sharded by customer ID or order ID, with each shard using a single-leader setup for strong consistency. Amazon famously uses a lot of custom infrastructure — their Dynamo paper came from the need for high availability, but for orders, they'd use something more consistent than Dynamo. Their Aurora database service likely powers the order pipeline. "
                    "For Prime Day, we need to handle the traffic spike. This means auto-scaling the order processing fleet, but also pre-provisioning database capacity since you can't just add shards on the fly. We'd over-provision by 2x for the event. And the flash sales need a queuing system — when 20,000 orders per second hit for a limited-stock item, you need to throttle and queue rather than process everything instantly, or you risk overselling. A system like Kafka would buffer the incoming orders, and the processing pipeline would consume from the queue at its maximum sustainable rate. "
                    "Interview tip: for e-commerce problems, always distinguish between average load and peak load, and always ask about flash sales or promotional events. The difference between average and peak determines whether you need auto-scaling or pre-provisioned capacity. Also, always mention idempotency — if a customer clicks buy twice because the page is slow, you need to ensure they don't get charged twice. That's a real production concern at Amazon's scale."
                ),
            },
            {
                "name": "Spotify Bandwidth",
                "prompt": "How much bandwidth does Spotify use? Given 500 million MAU, average 2 hours listening per day, and 320kbps streaming.",
                "prose": (
                    "OK so let me move on to our last problem for this session, and it's a bandwidth estimation for Spotify. The parameters are 500 million monthly active users, average 2 hours of listening per day, and streaming at 320 kilobits per second. I like this problem because it's a pure bandwidth calculation with some interesting nuances around caching and variable bitrate. "
                    "So 500 million MAU — that's Spotify's publicly reported number. They crossed 500 million a while back and have been growing since. But MAU is monthly, and we need daily numbers for bandwidth estimation. The MAU to DAU ratio for a music app is pretty high because people who use a music app tend to use it daily — it becomes a habit. I'd estimate about 60 to 70 percent of monthly users are daily users. Let's say 65 percent, which gives us about 325 million DAU. But the problem says average 2 hours listening per day — is that per MAU or per DAU? I think it's per DAU, since it wouldn't make sense for someone who only opens the app once a month to listen for 2 hours per day. So let's use 325 million DAU, each listening 2 hours per day. "
                    "Actually, hold on. Some people listen to Spotify for 6 hours a day — at work, commuting, working out — and some listen for just 30 minutes. The average of 2 hours seems reasonable. Spotify has reported that their users stream over 100 million hours of content per day. Let me check that against our numbers. 325 million DAU times 2 hours equals 650 million hours per day. That's 6.5 times the reported number, which suggests my DAU estimate might be too high, or the 2 hours might be per MAU rather than per DAU. Let me recalculate. If it's 500 million MAU times 2 hours, that's a billion hours per day — even higher. Hmm. Maybe the actual listening average is closer to 20 to 30 minutes per day across all MAU. Let me just use the problem's given assumptions and note that the 2 hours is probably for active daily listeners, not all monthly users. I'll use 300 million DAU listening 2 hours each per day, which gives 600 million hours per day. Still seems high, but the problem gives us these numbers, so let me work with them. "
                    "Now, 320 kilobits per second — that's Spotify's highest quality tier, called Very High quality. Most users actually stream at lower bitrates. Spotify has three quality levels: Normal at about 96kbps, High at about 160kbps, and Very High at 320kbps. Mobile users on cellular often use Normal or High to save data. So the average bitrate across all users is probably closer to 150 to 200kbps. But the problem says 320kbps, so I'll use that, and then note that the real number is likely lower. "
                    "OK let me calculate the bandwidth. 300 million DAU times 2 hours per day times 3,600 seconds per hour gives us 2.16 trillion seconds of audio streamed per day. At 320 kilobits per second, that's 2.16 trillion times 320, which is 691.2 trillion kilobits per day. Divide by 8 to get kilobytes, that's 86.4 trillion kilobytes, or about 86.4 petabytes per day of outbound bandwidth. "
                    "Let me double-check with a simpler approach. Average concurrent listeners — 300 million DAU times 2 hours per day divided by 24 hours per day is 25 million concurrent listeners on average. At 320kbps each, that's 25 million times 320 kilobits per second equals 8 trillion kilobits per second, which is 8 terabits per second. Divide by 8 to get terabytes, that's 1 terabyte per second sustained. Times 86,400 seconds per day is 86.4 petabytes. Same answer, good. "
                    "But wait, there's caching! Spotify caches aggressively. When you listen to a playlist, the next few songs are pre-downloaded to your device. And the Spotify app itself caches songs you've played before. So not every second of listening results in a network request. I'd estimate that caching reduces the actual bandwidth by maybe 30 to 50 percent, depending on repeat listening rates. Music has a much higher repeat rate than video — people listen to the same songs over and over. So real bandwidth might be closer to 40 to 60 petabytes per day. "
                    "Let me sanity check against known numbers. Netflix streams about 1 petabyte per hour at peak, which is about 24 petabytes per day at peak. Spotify at 86 petabytes per day before caching is about 3.5 times Netflix's daily peak. Netflix has about 250 million subscribers and streams at much higher bitrates per user — 5 to 25 megabits per second versus Spotify's 0.32 megabits. But Spotify has more concurrent users. 25 million concurrent Spotify listeners versus maybe 10 million concurrent Netflix watchers at peak. So Spotify having higher total data volume seems possible but a bit high. With caching bringing it down to 40 to 60 petabytes, that's 1.5 to 2.5 times Netflix, which feels more reasonable. "
                    "Another check — internet backbone traffic. Global internet traffic is estimated at about 5 exabytes per day. Spotify at 86 petabytes would be about 1.7 percent of all internet traffic. Sandvine reports that Spotify accounts for about 2 to 3 percent of downstream traffic in some regions. So our estimate is actually right in line with observed data. Nice. "
                    "For design, at 1 terabyte per second of outbound bandwidth before caching, we need a serious CDN. Spotify uses their own CDN with caching nodes deployed in ISP data centers, similar to Netflix's Open Connect. The key insight is that music files are small — a 3-minute song at 320kbps is about 7.2 megabytes. This means we can cache a lot on the client side and on edge nodes. A single edge server with a few terabytes of SSD can cache hundreds of thousands of the most popular songs, serving the vast majority of requests locally. For the database side, we need metadata storage for 100 million tracks, user libraries, playlists, and listening history — that's a more modest data problem, probably in the low petabyte range. The real engineering challenge is the recommendation engine, which processes petabytes of listening data daily, but that's a compute problem, not a bandwidth problem. "
                    "Interview tip: for bandwidth problems, always calculate in two ways — total daily volume and average concurrent throughput — and verify they're consistent. Also, always mention caching for media streaming problems. Caching can reduce bandwidth by 30 to 70 percent depending on content repeat rates, and ignoring it will give you an overestimate that shows you haven't thought about real-world optimization."
                ),
            },
        ]
    },
    {
        "id": 45, "theme": "estimation-2",
        "title": "Estimation Practice II",
        "subtitle": "Payment TPS, Netflix CDN, Uber location writes, Google search QPS, Slack message QPS, Zoom bandwidth",
        "playlist_id": "sd-estimation",
        "problems": [
            {
                "name": "Payment System TPS",
                "prompt": "Estimate transactions per second for a global payment processor like Stripe.",
                "prose": (
                    "OK so let's dive into this one. The interviewer asks me to estimate the transactions per second for a global payment processor like Stripe. This is a great real-world problem because payment processing is the backbone of e-commerce, and the throughput requirements directly determine your database architecture and consistency model. "
                    "So first, let me figure out the scale of Stripe's customer base. Stripe processes payments for over 1 million businesses globally. That's a publicly known number — they announced passing a million merchants a while back. These range from tiny indie developers selling a five-dollar app to giant companies like Amazon and Shopify merchants. "
                    "Now, how many transactions does the average business process per day? This is where the distribution really matters. The vast majority of Stripe's million businesses are small — they might process 10 or 50 transactions per day. But the top 1 percent — the big e-commerce platforms and SaaS companies — might process millions of transactions each. The long tail dominates by count but the head dominates by volume. For a working average, I'd say about 1,000 transactions per business per day. This accounts for the fact that most are small, but the big players pull the average up significantly. "
                    "One more thing before I calculate — the peak-to-average ratio. Payment traffic is spikey. Black Friday, Cyber Monday, end-of-month subscription billing runs, flash sales — all of these create huge spikes. I'd estimate the peak is about 3 times the average. Visa has reported peak-to-average ratios of 2 to 4x depending on the season, so 3x is a solid middle ground. "
                    "And for storage, each transaction record includes the amount, currency, merchant ID, customer token, timestamps, risk scores, and so on. I'd estimate about 500 bytes per transaction record. And for compliance, payment records need to be retained for 7 years in most jurisdictions. "
                    "OK let's do the math. 1 million businesses times 1,000 transactions per day equals 1 billion transactions per day. Average TPS: 1 billion divided by 86,400 seconds is about 11,600 transactions per second. Let me round to 12,000 for easy math. Peak TPS at 3x is 36,000 per second. "
                    "For daily storage: 1 billion times 500 bytes is 500 gigabytes per day. Over 7 years: 500 gigabytes times 365 days times 7 years is about 1.28 petabytes. That's very manageable for modern distributed storage. "
                    "Hmm, wait. Let me reconsider the 1,000 transactions per business per day. That might be too high for the median business. If I think about it differently — Stripe processes something like 250 billion dollars per year. If the average transaction is 50 dollars, that's 5 billion transactions per year, or about 14 million per day. That's way lower than my 1 billion per day estimate! Something's off. "
                    "Oh, I see the issue. My 1 million businesses times 1,000 transactions per day assumes every business is active every day. Many businesses on Stripe are seasonal or occasional. And the 50-dollar average might be too high — micro-transactions and subscription fees are often 10 to 30 dollars. Let me try with a 30-dollar average. 250 billion divided by 30 is about 8.3 billion transactions per year, which is about 23 million per day. That's still way below 1 billion. "
                    "So my original estimate was off by a factor of 40. The average transactions per business per day is closer to 23, not 1,000. That's a huge difference. Let me redo this with the corrected number. 23 million transactions per day divided by 86,400 seconds gives about 270 TPS on average. With 3x peak, that's about 800 TPS at peak. "
                    "But wait — this is based on total dollar volume, and it assumes I know Stripe's total volume. If I'm in an interview, I might not know that number. The point is, I should sanity check my assumptions and catch errors like this. My original approach of 1,000 transactions per business was wrong because I didn't account for inactive businesses and small volumes. "
                    "So here's the thing — let me present both approaches to the interviewer. The top-down approach using total dollar volume gives about 270 TPS average and 800 TPS peak. The bottom-up approach with corrected assumptions — maybe 100 transactions per active business per day, with 30 percent of businesses active on any given day — gives 1 million times 0.3 times 100, which is 30 million per day, or about 350 TPS. Those two estimates are in the same order of magnitude, which gives me confidence. I'll go with about 300 to 400 TPS average and 1,000 TPS peak. "
                    "Let me sanity check one more time. Visa processes about 65,000 TPS at peak globally. Stripe is a much smaller network than Visa — Stripe handles online payments while Visa handles all card-present transactions too. 1,000 TPS peak for Stripe is about 1.5 percent of Visa's peak, which seems right for an online-only payment processor. Amazon Prime Day processes about 100,000 orders per second, but those go through multiple payment processors, and Stripe would handle a fraction. So 1,000 TPS peak for Stripe is very reasonable. "
                    "For design, even at 1,000 TPS peak, the payment system needs strong consistency. You cannot risk double-charging or losing a transaction. We'd use a sharded relational database, probably sharded by merchant ID, with each shard running a single-leader database with synchronous replication. The ledger must be append-only and ACID-compliant. We'd also need an idempotency key on every transaction request so that retries don't create duplicate charges. And for the peak handling, we'd have a message queue like Kafka to absorb spikes — orders come in, they get queued, and the processing pipeline consumes them at a sustainable rate. "
                    "Interview tip: always sanity check your average-per-entity assumptions. The most common estimation mistake is assuming every entity contributes equally, when in reality there's almost always a power-law distribution where a few big players dominate. If you can, validate your bottom-up estimate with a top-down approach using a known total, and vice versa. The interviewer will be impressed if you catch your own error and correct it."
                ),
            },
            {
                "name": "Netflix CDN Storage",
                "prompt": "How much storage does Netflix need for its content library on CDN?",
                "prose": (
                    "Alright, so now the interviewer asks about Netflix's CDN storage. This is a fun one because Netflix has one of the most well-documented CDN architectures in the industry — they even published a paper about it. But let me work through the estimation from first principles. "
                    "So how many titles are in Netflix's library? Netflix has reported having around 15,000 titles, though this varies by country due to licensing. Some estimates put the US catalog at around 6,000 titles, and the global catalog across all regions at 15,000 to 17,000. I'll use 15,000 as my working number. "
                    "The average title length — a TV episode is about 40 to 60 minutes, and a movie is about 90 to 120 minutes. Netflix has a mix of both, plus documentaries, stand-up specials, and shorts. Let's say the average title is about 2 hours long. That accounts for the fact that many titles are actually multi-episode seasons, where each season counts as one title entry but is really 8 to 13 hours of content. Wait, actually, that complicates things. If we're counting by title and each title is 2 hours on average, that might undercount if we're including full seasons. Let me just clarify with the interviewer that we're treating each catalog entry as a single title, and 2 hours is the average duration. "
                    "Now, the encoding. Netflix encodes each title in multiple resolutions and bitrates to support adaptive bitrate streaming. The standard encoding ladder includes 4K at about 20 megabits per second, 1080p at 8 megabits per second, 720p at 5 megabits per second, 480p at 2 megabits per second, and 360p at 1 megabit per second. Plus audio tracks in multiple languages — maybe 128 to 256 kilobits per second per track, and there could be 10 to 20 audio tracks per title for different languages. But for simplicity, let's focus on video. The total bitrate across all encoding levels is 20 plus 8 plus 5 plus 2 plus 1, which is 36 megabits per second for video alone. "
                    "Let me calculate storage per title. 2 hours is 7,200 seconds. 7,200 seconds times 36 megabits per second equals 259,200 megabits. Divide by 8 to convert to megabytes, and that's about 32,400 megabytes, or roughly 32 gigabytes per title for all video encodings combined. "
                    "Total library: 15,000 titles times 32 gigabytes per title is 480 terabytes. That's the complete Netflix library in all encoding variants. "
                    "Now for the CDN. Netflix deploys their own CDN called Open Connect, with cache appliances in about 200 edge locations worldwide — typically inside ISP data centers. If every edge location cached the entire library, that would be 480 terabytes times 200, which is 96 petabytes of total CDN storage. "
                    "But here's the thing — not every edge caches every title. Netflix uses a popularity-based caching strategy. The top 20 percent of titles probably account for 80 percent of views. So a small edge location in a regional ISP might cache only the most popular 1,000 titles, which would be about 32 terabytes. A larger hub might cache everything. Let me estimate that on average, each edge caches about 40 percent of the library. So 480 terabytes times 40 percent is 192 terabytes per edge, times 200 edges is about 38 petabytes of total CDN storage. But honestly, the exact number depends heavily on the caching policy, and I'd present both the full-cache and partial-cache scenarios to the interviewer. "
                    "Let me sanity check. Netflix has publicly stated they deliver over 1 petabyte of data per hour during peak evening hours. If the entire library is 480 terabytes and they stream 1 petabyte per hour, that means the entire library is streamed roughly twice per hour during peak. With 250 million subscribers, if even 10 percent are watching at peak, that's 25 million concurrent viewers. 25 million viewers streaming at an average of 5 megabits per second is 125 million megabits per second, which is 125 gigabits per second, or about 15.6 gigabytes per second, which is 56 terabytes per hour. Hmm, that's way lower than the 1 petabyte per hour they reported. Oh wait, 5 megabits per second is too low for the average — many viewers watch in 1080p or 4K. If the average is closer to 10 megabits per second, and there are more like 50 million concurrent viewers at peak, we get closer to their reported number. The point is, my library size of 480 terabytes is consistent with the streaming volume — the library gets served multiple times per hour at peak, which makes sense for a popular streaming service. "
                    "Another reference — a single Netflix Open Connect appliance can store about 100 terabytes. If there are 200 locations with maybe 2 to 5 appliances each, that's 40 to 100 petabytes of CDN capacity, which aligns with my estimate. "
                    "For design, the key insight is intelligent caching. We'd use a popularity-based caching policy where new releases are pushed to every edge, while catalog content is stored only at regional hubs. This is called a hierarchical CDN. Adaptive bitrate streaming requires chunked encoding — each title is split into 2 to 10 second chunks at each bitrate, and the player switches between bitrate chunks based on network conditions. This means the CDN needs to serve small chunks efficiently, which is where HTTP range requests and CDN prefetching come in. "
                    "Interview tip: for CDN problems, always discuss the caching policy, not just the total storage. The difference between caching everything and caching smartly can be a factor of 3 to 5 in storage cost. Also, mention that Netflix builds their own CDN rather than using a commercial one like Akamai — at their scale, the cost savings from owning the infrastructure outweigh the engineering investment."
                ),
            },
            {
                "name": "Uber Location Writes",
                "prompt": "Estimate the write QPS for Uber's real-time location tracking.",
                "prose": (
                    "OK so let's tackle this one. The interviewer wants me to estimate the write QPS for Uber's real-time location tracking system. This is a really interesting problem because it's fundamentally different from the previous ones — we're dealing with high-frequency, small writes, which is a very different workload than large media storage or transaction processing. "
                    "Let me start by thinking about the user base. Uber operates in about 70 countries and has roughly 25 million daily active riders. That's a number that's been reported in various news articles. And on the driver side, there are about 5 million drivers globally, though not all are active at the same time. "
                    "So the question is: how many drivers are actively driving at any given moment? I'd say about 60 percent of registered drivers are active during peak hours in their local market. But it varies by time of day — late at night there are fewer drivers, during rush hour there are more. 60 percent as a time-averaged figure seems reasonable. So 5 million drivers times 60 percent gives us 3 million active drivers at any given time. "
                    "Now, how often does each driver report their location? This is a critical assumption. For real-time dispatch to work well, the driver's location needs to be accurate to within a few hundred meters. If a driver is moving at 30 miles per hour, that's about 13 meters per second. To keep the location accurate to within 200 meters, you'd need updates roughly every 15 seconds. But for efficiency, Uber probably uses something like every 4 to 5 seconds when the driver is on a trip or heading to a pickup, and maybe every 30 seconds when they're just waiting. I'll use 5 seconds as the reporting interval for active drivers. "
                    "So driver location writes: 3 million drivers, each reporting once every 5 seconds. That's 3 million divided by 5, which is 600,000 writes per second. That's already a huge number. "
                    "But we also have riders. When a rider is on a trip, the Uber app also reports their location for features like share-my-trip and ETA calculation. How many riders are in a trip at any given time? If there are 25 million daily active riders, and each takes maybe 2 to 3 rides per day with an average duration of 15 minutes, then at any given moment, roughly 25 million times 2.5 rides times 15 minutes divided by 24 hours times 60 minutes is about 43,000 riders in a trip at any moment. Wait, that seems low. Let me recalculate. 25 million riders, each taking 2.5 rides of 15 minutes, that's 25 million times 2.5 times 15 minutes equals 937.5 million rider-minutes per day. Divided by 1,440 minutes per day, that's about 650,000 riders in a trip at any moment. That's more like it. "
                    "Riders report their location every 30 seconds while in a trip. So 650,000 riders divided by 30 is about 22,000 rider location writes per second. That's small compared to driver writes. "
                    "So total location write QPS is 600,000 plus 22,000, which is about 622,000 writes per second. Let me round to 620,000. "
                    "Actually wait, I should also account for the Uber Eats delivery drivers. Uber Eats has become a huge part of their business, and delivery drivers also report their location frequently. There are probably another 2 to 3 million Uber Eats couriers globally, with maybe 40 percent active at any time. That's about 1 million additional active couriers, reporting every 5 seconds, adding another 200,000 writes per second. So the total might be closer to 820,000 writes per second. "
                    "Let me sanity check. 820,000 writes per second sounds enormous, but remember, these are incredibly simple writes — just updating a key with a latitude, longitude, and timestamp. No complex queries, no joins, no transactions. Redis can handle over 100,000 simple writes per second per instance on modern hardware. So we'd need about 8 to 10 Redis shards, which is very doable. Compare this to a social media platform like Twitter at 7,000 write QPS — Uber's location writes are two orders of magnitude higher in QPS, but each write is much simpler. "
                    "For daily storage, 820,000 writes per second times 86,400 seconds times 50 bytes per write is about 3.5 terabytes per day of raw location data. Over a year, that's about 1.3 petabytes. Not huge by modern standards. "
                    "For design implications, the real-time location system would use an in-memory store like Redis for the current location of each driver, with TTL-based expiration — if a driver hasn't reported in 30 seconds, their entry expires and they're considered offline. For historical location data, we'd batch-write to a time-series database like InfluxDB or Cassandra, because querying historical trajectories is a different access pattern. And for the matching algorithm — finding the nearest available driver for a ride request — we'd use a geospatial index, either Redis's built-in GEO commands or a dedicated system like Google's S2 geometry library for efficient proximity queries. "
                    "Interview tip: for location-based systems, always clarify the reporting frequency — it's the single biggest factor in write QPS. And always distinguish between the real-time serving path, which needs low-latency key-value access, and the historical analytics path, which needs time-series storage. These are two very different workloads that should be served by different systems."
                ),
            },
            {
                "name": "Google Search QPS",
                "prompt": "Estimate Google's search queries per second, given 8.5 billion searches per day and peak is 2x average.",
                "prose": (
                    "OK, next problem. The interviewer wants me to estimate Google's search queries per second. They give me a key number — 8.5 billion searches per day — and say that peak is 2 times average. This one seems straightforward mathematically, but there's a lot of interesting infrastructure discussion that follows from the numbers. "
                    "So 8.5 billion searches per day. That's a number that's been widely reported and comes from various analytics firms. Google themselves have said they process billions of searches daily, and 8.5 billion is a commonly cited estimate. Some sources put it higher at 10 to 12 billion, but let's work with 8.5 billion as given. "
                    "Average QPS is simple. 8.5 billion divided by 86,400 seconds per day. Let me do the math. 8.5 billion divided by 86,400 is approximately 98,400 queries per second. Let me round to about 100,000 QPS on average. "
                    "Now, the problem says peak is 2x average, so peak QPS is about 200,000 per second. But I want to think about when peak actually occurs. Google search traffic follows a diurnal pattern — it peaks during weekday business hours in each timezone. So the US East Coast morning rush, 8 to 10 AM Eastern, is one peak. Then Europe peaks a few hours later, then Asia. The global peak is probably during the overlap of US and European business hours, around 2 to 3 PM UTC. And on top of that, there are event-driven spikes — during breaking news, major sports events, elections, the QPS can spike even higher. The 2x peak might be conservative for those situations. "
                    "Wait, actually, I should question whether 2x is the right multiplier. For most web services, the peak-to-average ratio is 2 to 3x for normal diurnal variation. Google search is a mature, global service with traffic from every timezone, which actually smooths out the curve compared to a single-country service. A service only in the US might have a 4x peak-to-average ratio because all traffic is in one timezone. But Google being global means when the US is sleeping, Asia and Europe are active, which reduces the peak-to-average ratio. So 2x for the global peak is actually quite reasonable. "
                    "Let me sanity check this against other known numbers. We estimated Twitter at about 70,000 read QPS earlier. Google at 100,000 QPS is about 40 percent higher than Twitter's reads, which makes sense — Google is the most visited website in the world. But here's a more direct comparison: Google themselves have said that over 1 billion people use Search every day. If each person does an average of 8.5 searches per day, that's 8.5 billion, which matches. And 8.5 searches per day per person seems high, but remember, many searches are quick — did you know, weather, spell check, unit conversion. I probably do 20 to 30 searches a day without thinking about it. "
                    "Another angle — Google's AdWords revenue. They make about 150 billion dollars per year from search ads. If the average cost per click is about 1 dollar, that's about 150 billion clicks per year, or about 400 million ad clicks per day. Not every search results in an ad click — the click-through rate for search ads is about 3 to 5 percent. So 400 million clicks divided by 4 percent CTR gives about 10 billion search ad impressions per day. That's in the same ballpark as 8.5 billion total searches, which checks out since not every search has ads. "
                    "For design implications, 100,000 QPS average with 200,000 peak is a massive read-heavy workload. The architecture for Google Search is one of the most sophisticated in the world. The index is sharded across thousands of index servers, with each server responsible for a subset of the web. A single search query gets fanned out to hundreds of index servers in parallel, each returning their top results, and a root server merges and ranks the final results. This whole process needs to complete in under 200 milliseconds, which is Google's famous latency target. "
                    "At 200,000 QPS peak, even with thousands of index servers, each server handles maybe 50 to 100 queries per second. The index itself is kept in RAM on each server for low latency — Google was one of the first companies to make the economic case for putting entire indexes in memory. And they have multiple data centers worldwide, with DNS-level routing sending your query to the nearest data center. "
                    "The write side is interesting too. The web is constantly changing, and Google needs to update its index in near-real-time for breaking news. They use a two-tier index — a main index that's updated in bulk every few days, and a real-time index for recent content that's updated continuously. The real-time index is much smaller but handles fresh content, while the main index handles the bulk of queries. "
                    "Interview tip: for search engines, always discuss the fan-out architecture and the latency constraint. A 100,000 QPS system where each query touches hundreds of servers is very different from a 100,000 QPS system where each query is a simple key lookup. The QPS number alone doesn't tell the whole story — you need to think about the fan-out factor and the per-query cost. Also, mentioning the two-tier index for freshness shows you understand that search has both a completeness requirement and a freshness requirement."
                ),
            },
            {
                "name": "Slack Message QPS",
                "prompt": "Estimate Slack's message throughput, given 20 million DAU, 200 messages per user per day, and 5-person average channel size.",
                "prose": (
                    "So here's another interesting one — Slack's message throughput. The parameters are 20 million DAU, 200 messages per user per day, and a 5-person average channel size. This problem is cool because the fan-out from group channels makes the write-to-read multiplication non-trivial. "
                    "Let me think about these assumptions. 20 million DAU for Slack — that seems reasonable. Slack has reported over 30 million daily active users across all organizations, and 20 million for the core messaging product feels like a good working number. Salesforce, which acquired Slack, has mentioned even higher numbers in earnings calls. "
                    "200 messages per user per day. Hmm, that's actually a lot when you think about it. 200 messages means if you're online for 8 hours, that's 25 messages per hour, or roughly one message every 2.5 minutes. That's... actually pretty typical for an active Slack user. You have channels with constant chatter, bot notifications, automated alerts from CI/CD pipelines, and then your direct messages. I can easily see how it adds up to 200 if you count every notification and every automated message. Some power users in active channels probably see 500 to 1,000 messages a day. And then there are lurkers who read but rarely post. So 200 as an average across all DAU, including both senders and receivers seeing messages, is reasonable. But wait — does 200 mean the user sends 200 messages, or they see 200 messages in their feed? That's an important distinction for QPS estimation. If 200 is messages seen, then the actual send rate is much lower, since one message to a channel is seen by all members. I think the problem means 200 messages sent per user per day — that's the write rate. Let me use that interpretation. "
                    "Actually, hold on. 200 messages sent per user per day seems too high. Let me reconsider. In a typical company, maybe 10 to 20 percent of users are active posters, and they might send 50 to 100 messages a day. The rest are mostly readers. If only 20 percent of 20 million DAU are active posters sending 100 messages each, the average drops to about 20 messages per user per day. But the problem says 200, so maybe they're using a broader definition that includes bot messages, reactions, thread replies, and other interactions. Or maybe it's a different kind of average. I'll work with 200 as given, but I'd clarify this with the interviewer in a real session. "
                    "OK so the write QPS — messages being posted. 20 million DAU times 200 messages per day equals 4 billion messages per day. Divided by 86,400 seconds, that's about 46,300 messages per second on average. Let me call it 46,000. "
                    "Now for the fan-out. The problem says the average channel has 5 people. So each message needs to be delivered to 5 people — the sender plus 4 others. But wait, does that mean we need 5 writes per message? It depends on the architecture. In a fan-out on write system, when you post a message, we push it to the read buffer of every channel member. So one message write triggers 5 buffer writes. In a fan-out on read system, we just write the message once to the channel, and when each user loads their feed, we query all their channels for recent messages. "
                    "Slack probably uses a hybrid approach — fan-out on write for online users, and fan-out on read for offline users. But for bandwidth estimation, I need to think about the read traffic. Each of those 4 billion messages is read by 5 people, so total reads per day are 20 billion. Read QPS: 20 billion divided by 86,400 is about 231,000 reads per second. "
                    "Hmm, but that's assuming every message is read by every channel member, which isn't true. People skim, they ignore channels, they're offline. Maybe 60 percent of messages are actually read. So real read QPS might be closer to 140,000 per second. "
                    "And for peak, Slack traffic follows a very clear pattern — it peaks during business hours, especially Monday through Friday, 9 AM to 5 PM in each timezone. The peak-to-average ratio for a business communication tool is probably 3 to 4x, because usage drops to nearly zero outside business hours. So peak write QPS might be 46,000 times 3.5, which is about 160,000 messages per second. And peak read QPS could be 140,000 times 3.5, which is about 490,000 per second. "
                    "Let me sanity check. Twitter had about 7,000 write QPS and 70,000 read QPS in our earlier estimate. Slack's 46,000 write QPS is about 6.5 times Twitter's, which seems high. But Slack users are in active conversations all day, while Twitter users mostly scroll and read. The write-to-read ratio for Slack is closer to 1 to 3, versus Twitter's 1 to 10. That tracks — Slack is a conversation tool, Twitter is a broadcast tool. "
                    "Compare to Discord, which has reported handling over 4 billion messages per day. That's similar to our Slack estimate of 4 billion, and Discord has a larger user base. So 4 billion messages per day for Slack seems in the right ballpark, maybe slightly high. "
                    "For design, 46,000 message writes per second is significant. We'd need a message store that can handle high write throughput — Cassandra or a similar log-structured database would be a good fit, since messages are append-only and rarely updated. Each message write also needs to fan out to channel members' read buffers. We'd use a publish-subscribe system — when a message is posted to a channel, we publish it to a message queue, and subscribers (the WebSocket connections of channel members) receive it in near-real-time. "
                    "For the 140,000 read QPS, we'd cache each user's feed in Redis, updated whenever a message is posted to one of their channels. The key challenge is the per-user fan-out — each user might be in 50 to 100 channels, and their feed cache needs to be updated whenever any of those channels has a new message. That's a lot of cache invalidation. We'd use a sorted set in Redis, with messages scored by timestamp, and just prepend new messages. "
                    "Interview tip: for messaging systems, the key design decision is fan-out on write versus fan-out on read, and the choice depends on the read-to-write ratio and the group size. For small groups like Slack channels, fan-out on write is usually better because it keeps reads fast. For large groups like Twitter with millions of followers, fan-out on read becomes necessary. Always discuss this trade-off in the interview."
                ),
            },
            {
                "name": "Zoom Bandwidth",
                "prompt": "Estimate Zoom's bandwidth during peak, given 300 million daily meeting participants, average 2 hours per participant, and 2 megabits per second per participant.",
                "prose": (
                    "Alright, let's tackle our final problem for this session. Zoom's peak bandwidth. The parameters are 300 million daily meeting participants, average 2 hours of meeting time per participant, and 2 megabits per second per participant. This is a bandwidth estimation problem, but with a twist — video conferencing has both upload and download bandwidth, and the traffic pattern is symmetric, unlike streaming which is download-only. "
                    "So 300 million daily meeting participants. Zoom reported over 300 million daily meeting participants at the peak of the pandemic, and while it's come down since then, the number is still massive for a working day. I'll use 300 million as given. "
                    "Average 2 hours per participant. That seems right for remote and hybrid workers. Some people are in meetings all day, others just have a couple of standups. 2 hours as a weighted average across all participants is reasonable. "
                    "2 megabits per second per participant. This is where I need to think carefully. What does 2 Mbps represent? Zoom's bandwidth usage depends on the number of participants in the meeting and whether video is on. A one-on-one call with video uses about 1 to 1.5 Mbps up and down. A group call where you're receiving video from multiple participants uses more download bandwidth. Gallery view with 25 videos could use 3 to 4 Mbps download, while your upload stays at about 1 Mbps since you're only sending one video stream. Screen sharing adds more upload bandwidth. So 2 Mbps as an average across all scenarios — some one-on-one calls, some large meetings, some screen shares, some audio-only — seems like a reasonable blended average. "
                    "But I should note that the bandwidth is bidirectional. Each participant uploads their video and audio at about 1 to 2 Mbps, and downloads the video and audio of other participants. For a meeting with N participants, the server receives N video streams and needs to either relay all of them to every participant or do selective forwarding. More on that later. "
                    "OK let me calculate. First, the total data volume per day. 300 million participants times 2 hours each is 600 million participant-hours per day. At 2 Mbps per participant, each participant-hour generates 2 megabits times 3,600 seconds, which is 7,200 megabits, or 900 megabytes per participant-hour. So 600 million participant-hours times 900 megabytes is 540 million gigabytes, which is 540 petabytes of data transferred per day. "
                    "But wait — that's one direction. In a video call, each participant both uploads and downloads. The upload per participant is their own video stream, roughly 1 Mbps. The download is the video from other participants, which varies by meeting size but averages about 1 to 2 Mbps. So the total bidirectional bandwidth is roughly 2 to 3 Mbps per participant. The problem says 2 Mbps per participant, which I think means total, not just download. Let me use 2 Mbps total and stick with 540 petabytes per day. "
                    "Hmm, actually, I think I need to reconsider. The 2 Mbps might refer to download bandwidth only. In a typical meeting, you download more than you upload because you're receiving multiple video streams. Let me think about it differently. The total bandwidth Zoom's infrastructure handles is the sum of all upload and download traffic passing through their servers. Each participant sends one stream up and receives multiple streams down. The infrastructure cost is proportional to the total traffic through Zoom's servers. "
                    "For a rough estimate, let me just use 2 Mbps per participant as the average total throughput through Zoom's servers. That gives us the same 540 petabytes per day, or about 6.25 terabytes per second on average. "
                    "But that's average. The peak is what the problem asks about. Video conferencing has an extremely pronounced peak — it's during business hours, especially 9 to 11 AM and 2 to 4 PM on weekdays. The peak-to-average ratio is probably 4 to 5x, because usage drops to near zero overnight and on weekends. If we take the average throughput over the full 24-hour day, the peak hour might have 4 to 5 times the daily average rate. "
                    "So average throughput is 6.25 terabytes per second over the full day. But most of the 600 million participant-hours are concentrated in an 8-hour window across different timezones. If we consider only the 8 active hours, the average during active hours is 540 petabytes divided by 8 hours, which is 67.5 petabytes per hour, or about 18.75 terabytes per second. And the peak within that active period might be 1.5 to 2x the active-hours average, so 28 to 37 terabytes per second at peak. "
                    "Let me sanity check. Netflix streams about 1 petabyte per hour during their peak. Zoom at 18.75 terabytes per second during active hours is about 67.5 petabytes per hour, which is 67 times Netflix's peak. That seems way too high. Something must be wrong with my calculation. "
                    "Wait, let me reconsider. Netflix's 1 petabyte per hour is during their absolute peak, which is about 250 million subscribers times maybe 30 percent watching at peak, at 5 to 8 Mbps per stream. Zoom has 300 million participants, but not all are active at the same time. 300 million daily participants over, say, 8 active hours means on average 37.5 million concurrent participants during active hours. At 2 Mbps each, that's 75 million Mbps, or 75 Gbps. In terabytes per second, that's about 9.4 terabytes per second. Hmm, still very high. "
                    "Oh wait, I think I made an arithmetic error earlier. Let me redo this more carefully. Average concurrent participants: 300 million times 2 hours per day divided by 24 hours equals 25 million concurrent participants on average. At 2 Mbps each, that's 50 million Mbps, which is 50 Gbps total, or about 6.25 GB/s. In petabytes per day: 6.25 GB/s times 86,400 seconds equals 540,000 GB, which is 540 petabytes per day. That matches my earlier calculation. "
                    "But 50 Gbps — that's 6.25 GB/s — is actually quite reasonable for a global infrastructure. Google's total network capacity is estimated in the hundreds of Gbps for their backbone. Zoom at 50 Gbps average is a significant chunk but not unreasonable. "
                    "The issue with my Netflix comparison was that I was confusing petabytes per hour with terabytes per second. Let me redo: Netflix at 1 PB/hr is about 0.28 TB/s. Zoom at 6.25 GB/s average is 0.00625 TB/s. Wait, that can't be right either. "
                    "OK let me be really careful with units. 50 Gbps. That's 50 times 10 to the 9 bits per second. Divide by 8 for bytes per second: 6.25 times 10 to the 9 bytes per second, which is 6.25 GB/s. That's 0.00625 TB/s. Netflix at 1 PB/hr: 1 times 10 to the 15 bytes divided by 3600 seconds is 2.78 times 10 to the 11 bytes per second, which is 278 GB/s. So Netflix is about 278 GB/s at peak, and Zoom is 6.25 GB/s average. That means Netflix is 44 times Zoom, not the other way around. That makes much more sense — video streaming uses way more bandwidth per user than video conferencing because the video quality is much higher. "
                    "So where did my 540 petabytes per day come from? Let me check. 6.25 GB/s times 86,400 seconds equals 540,000 GB, which is 540 TB, not 540 PB. I had a factor of 1000 error! 540 TB per day. OK that makes way more sense. And during peak, with 4 to 5x the average, we get maybe 25 to 31 GB/s, which is still well below Netflix's 278 GB/s. "
                    "For design implications, Zoom's bandwidth is dominated by the media routing infrastructure. Zoom uses a selective forwarding unit architecture rather than a simple MCU multipoint control unit. In an SFU, each participant sends one video stream to the server, and the server selectively forwards streams to other participants based on their layout and bandwidth. This is much more bandwidth-efficient than an MCU, which decodes and recomposites all streams — the SFU just forwards encoded streams without decoding them. "
                    "At peak, with maybe 40 million concurrent participants, and each sending about 1 Mbps up and receiving about 2 Mbps down, the total server throughput is about 120 Gbps. This requires data centers with massive network capacity, distributed globally to minimize latency. Latency is critical for video conferencing — anything above 150 milliseconds round trip causes noticeable delay in conversation. So Zoom needs servers in every major metro area, not just a few central locations. "
                    "Interview tip: always, always double-check your unit conversions. I just caught myself being off by a factor of 1000, and that kind of error can sink an entire estimation. A good habit is to convert everything to base units — bytes and seconds — and then convert back at the end. Also, always compare your answer to a known reference point. When my initial estimate said Zoom uses 67 times Netflix's bandwidth, that should have been an immediate red flag — streaming HD video to millions of homes always uses more bandwidth than video calls, because the video quality is much higher."
                ),
            },
        ]
    },
]


def build_estimation_script(episode_config):
    """Build a flowing prose think-aloud estimation script."""
    parts = []

    parts.append(
        f"Hey there! Welcome to Estimation Practice. Today we're working through "
        f"{len(episode_config['problems'])} back-of-envelope estimation problems. "
        f"I'm going to think out loud the way I would in an actual interview — "
        f"walking through my reasoning, catching my own mistakes, and double-checking "
        f"everything against numbers I already know. The whole point of estimation isn't "
        f"to get the exact answer — it's to show the interviewer that you can reason "
        f"structuredly about scale. So let's dive in."
    )

    for i, problem in enumerate(episode_config["problems"]):
        if i == 0:
            parts.append(
                f"Let's start with our first problem: {problem['name']}. "
                f"So the question is: {problem['prompt']}"
            )
        else:
            parts.append(
                f"Alright, let's shift gears to our next problem: {problem['name']}. "
                f"So here the question is: {problem['prompt']}"
            )

        parts.append(problem["prose"])

    parts.append(
        "And that wraps up our estimation practice session for today. "
        "If there's one thing I want you to take away, it's this: estimation is a skill you build by practicing out loud. "
        "The pattern is always the same — state your assumptions clearly and explain why they're reasonable, "
        "work through the math step by step, catch your own mistakes, "
        "sanity check against numbers you already know, "
        "and then connect your estimates to real design decisions. "
        "The interviewer doesn't expect exact numbers — they want to see structured, honest reasoning. "
        "And the best way to get better is to practice these problems out loud, just like we did today. "
        "Keep at it, and I'll see you next time!"
    )

    return "\n\n".join(parts)


def main():
    print("=== generate_estimation.py ===")

    os.makedirs(DATA_DIR, exist_ok=True)

    theme = sys.argv[1] if len(sys.argv) > 1 else None
    configs = ESTIMATION_EPISODES
    if theme:
        configs = [c for c in configs if c["theme"] == theme]
        if not configs:
            print(f"ERROR: Unknown theme '{theme}'")
            sys.exit(1)

    results = []
    for config in configs:
        print(f"\n--- #{config['id']}: {config['title']} ---")

        script = build_estimation_script(config)
        word_count = len(script.split())
        est_min = word_count / 159
        print(f"  Script: {word_count} words, ~{est_min:.0f} min estimated")

        script_path = os.path.join(DATA_DIR, f"est-{config['theme']}.txt")
        with open(script_path, "w") as f:
            f.write(script)

        mp3_path = os.path.join(DATA_DIR, f"est-{config['theme']}.mp3")
        print(f"  Generating audio (EmmaNeural)...")
        synthesize(script, mp3_path, voice="estimation")

        size_mb = os.path.getsize(mp3_path) / (1024 * 1024)
        duration = get_duration_str(mp3_path)
        print(f"  MP3: {size_mb:.1f} MB, {duration}")

        results.append({
            "id": config["id"],
            "theme": config["theme"],
            "title": config["title"],
            "subtitle": config["subtitle"],
            "playlist_id": config["playlist_id"],
            "mp3_path": mp3_path,
            "script_path": script_path,
            "file_size_bytes": os.path.getsize(mp3_path),
            "duration": duration,
        })

    print(f"\nDone — {len(results)} estimation episodes generated")


if __name__ == "__main__":
    main()
