#!/usr/bin/env python3
"""tts.py — Minimal TTS: reads script.txt, generates episode.mp3 via edge-tts.
For use with scripts generated by selector.py (system-design, coding-interview).
"""

import os, sys, asyncio
import edge_tts

VOICE = "en-US-ChristopherNeural"
SCRIPT_PATH = os.path.join(os.path.dirname(os.path.dirname(__file__)), "data", "script.txt")
MP3_PATH = os.path.join(os.path.dirname(os.path.dirname(__file__)), "data", "episode.mp3")


async def text_to_speech(text: str, output_path: str):
    """Convert text to MP3 using edge-tts."""
    communicate = edge_tts.Communicate(text, VOICE)
    await communicate.save(output_path)


def main():
    if not os.path.exists(SCRIPT_PATH):
        print(f"ERROR: {SCRIPT_PATH} not found. Run selector.py first.")
        sys.exit(1)

    with open(SCRIPT_PATH) as f:
        text = f.read()

    # Clean up the script for TTS: remove formatting markers, keep spoken text
    lines = []
    for line in text.split("\n"):
        # Skip divider lines and section headers
        if line.startswith("====") or line.startswith("[") and line.endswith("]"):
            continue
        # Remove markdown formatting
        line = line.replace("**", "").replace("###", "").replace("`", "")
        lines.append(line)

    clean_text = "\n".join(lines)
    word_count = len(clean_text.split())
    estimated_minutes = word_count / 130  # ~130 wpm

    print(f"Script: {word_count} words (~{estimated_minutes:.1f} min)")
    print(f"Voice: {VOICE}")
    print(f"Generating MP3...")

    asyncio.run(text_to_speech(clean_text, MP3_PATH))

    size_kb = os.path.getsize(MP3_PATH) / 1024
    print(f"Done: {MP3_PATH} ({size_kb:.0f} KB)")
    print(f"\nNext: python3 scripts/publish.py")


if __name__ == "__main__":
    main()
